#region Summary
// ===========================================================================
// AUTHOR        : BSI Code Generator
// PURPOSE       : VWI_CRM_xts_assessmentferenceDto  class
// SPECIAL NOTES : DNet WebApi Project
// ---------------------
// Copyright  (c) 2018 
// ---------------------
// $History      : $
// Created on 2021-01-04 14:39:00
//
// ===========================================================================	
#endregion

#region Namespace Imports
using System;
#endregion

namespace KTB.DNet.Interface.Model
{
    public class VWI_CRM_xts_assessmentDto : DtoBase
    {
        public string company { get; set; }
        public string businessunitcode { get; set; }
        public Guid xts_vehiclepublicid { get; set; }
        public Guid xts_consumptiontaxid { get; set; }
        public decimal xts_vehiclemainbodyamounttotal_base { get; set; }
        public string xjp_tonnagetaxrefundobject { get; set; }
        public int xjp_tireaddingpoint { get; set; }
        public Guid xts_receivingwarehouseid { get; set; }
        public int xjp_fixtureaddingpoint { get; set; }
        public string xjp_recyclingairbagequipmentname { get; set; }
        public decimal xjp_fluorocarbondepositedamount_base { get; set; }
        public decimal xts_interiorexteriorcorrectiontotal { get; set; }
        public string xts_automaticcreatedname { get; set; }
        public DateTime overriddencreatedon { get; set; }
        public int xts_transmissionadditionandsubtractionpoint { get; set; }
        public string xjp_userphonenumber { get; set; }
        public Guid xts_fuelcategoryid { get; set; }
        public string xts_transmissionname { get; set; }
        public string xjp_lightvehicleflagname { get; set; }
        public string xts_basicpriceidname { get; set; }
        public string xts_numberofdoors { get; set; }
        public int importsequencenumber { get; set; }
        public decimal xts_coefficientofvehicleclass { get; set; }
        public decimal xts_subtractioncorrectiontotal { get; set; }
        public string xjp_owneridname { get; set; }
        public string xjp_roofrackmaterialcolumnname { get; set; }
        public string xjp_ownerpostalcode { get; set; }
        public string xts_shiftposition { get; set; }
        public string xts_address3 { get; set; }
        public decimal xts_width { get; set; }
        public string xjp_stereoequipment { get; set; }
        public string xjp_tireshape { get; set; }
        public Guid modifiedby { get; set; }
        public string xts_vehiclemodelidname { get; set; }
        public bool xts_finalassessmentexsistence { get; set; }
        public string xjp_instructionmanualdeduction { get; set; }
        public string xjp_tvequipment { get; set; }
        public decimal xts_runningkmadditionandsubtractionamount_base { get; set; }
        public Guid xts_assessmentid { get; set; }
        public string xjp_address4 { get; set; }
        public int xjp_compulsoryinsuranceremainingmonth { get; set; }
        public decimal xts_transactionamount { get; set; }
        public string xts_endlifevehiclename { get; set; }
        public string xts_firstyearregistration { get; set; }
        public decimal xts_manualmeasure3_base { get; set; }
        public Guid xts_initialassessmentid { get; set; }
        public string statecodename { get; set; }
        public bool xjp_usersameasclient { get; set; }
        public Guid xts_vehiclespecificationid { get; set; }
        public string xjp_compulsoryinsurancestartdatejapan { get; set; }
        public string xjp_roofrackshapecolumnname { get; set; }
        public Guid owningteam { get; set; }
        public Guid xts_productid { get; set; }
        public string xts_villageandstreetidname { get; set; }
        public string xts_customeridyominame { get; set; }
        public Guid xts_usedvehicleexteriorcolorid { get; set; }
        public string xts_handling { get; set; }
        public decimal xts_seatingcapacity1 { get; set; }
        public int xjp_airbagaddingpoint { get; set; }
        public string xjp_ownernumber { get; set; }
        public decimal xts_remainingfinanceamount { get; set; }
        public string xts_enginevolumeunitname { get; set; }
        public decimal xts_basicpriceamount { get; set; }
        public string xjp_navigationsystemequipment { get; set; }
        public Guid owningbusinessunit { get; set; }
        public string xjp_tireshapename { get; set; }
        public int xjp_outerplatevaluededuction { get; set; }
        public string xts_motortype { get; set; }
        public Guid xts_purchaseordertypeid { get; set; }
        public int xjp_cdmdandstaddingpoint { get; set; }
        public string xjp_ownersameasclientname { get; set; }
        public string xjp_ascdname { get; set; }
        public string xjp_compulsoryinsurancecontractnumber { get; set; }
        public string xjp_carinspectionexpirationdatejapan { get; set; }
        public int xjp_commercialvaluedeductionsubtotal { get; set; }
        public string xjp_registrationdatejapan { get; set; }
        public decimal xts_basicpriceamount_base { get; set; }
        public int xjp_navigationsystemcddvdaddingpoint { get; set; }
        public Guid xjp_ownercountryid { get; set; }
        public Guid xjp_caliremainingadditionandsubtractionid { get; set; }
        public Int64 versionnumber { get; set; }
        public Guid xjp_vehicleregistationcategoryid { get; set; }
        public string xjp_powersteeringequipment { get; set; }
        public string xts_manufactureridname { get; set; }
        public string xjp_recyclingobjectname { get; set; }
        public int xts_mileagebeforeitexchanges { get; set; }
        public string xts_runningmeterexchange { get; set; }
        public string xts_customercountryidname { get; set; }
        public int xjp_repairhistorydeductionabc { get; set; }
        public int xjp_sunroofaddingpoint { get; set; }
        public Guid xts_recognizedmodelid { get; set; }
        public string xts_purchaseusagecategoryname { get; set; }
        public int xjp_powerwindowaddingpoint { get; set; }
        public Guid xts_globalcolorid { get; set; }
        public int xjp_absequipmentaddingpoint { get; set; }
        public string createdbyyominame { get; set; }
        public string xjp_useridname { get; set; }
        public int xts_runningkmadditionandsubtractionpoint { get; set; }
        public string xts_grade { get; set; }
        public string xjp_ownerphonenumber { get; set; }
        public string xts_fuelcategoryidname { get; set; }
        public string xjp_airbagequipmentname { get; set; }
        public string xjp_sunroof { get; set; }
        public Guid xjp_ownerprovinceid { get; set; }
        public string xjp_powerseat { get; set; }
        public Guid xts_vehiclebasicid { get; set; }
        public decimal xts_maximumload2 { get; set; }
        public decimal xts_manualmeasure1 { get; set; }
        public decimal xts_internalpurchasingprice { get; set; }
        public string xjp_writtenguaranteemaintpocketbookdeduction { get; set; }
        public string xts_platenumber { get; set; }
        public string xjp_roofname { get; set; }
        public decimal xjp_compulsoryinsuranceremainderaddingamount_base { get; set; }
        public decimal xts_subtotalabccoefficientofxvehicleclass { get; set; }
        public string xts_globalcoloridname { get; set; }
        public decimal xts_transactionamount_base { get; set; }
        public string xts_customerpostalcode { get; set; }
        public decimal xjp_compulsoryinsuranceremainderaddingamount { get; set; }
        public string xts_transmission { get; set; }
        public string xjp_airsuspensionname { get; set; }
        public string xts_automobilelayoutidname { get; set; }
        public string xts_customernumber { get; set; }
        public int xjp_tvdeduction { get; set; }
        public decimal xts_newcarmeasure { get; set; }
        public int xjp_swandawdeduction { get; set; }
        public decimal xts_priceatnewcar { get; set; }
        public Guid xts_parentbusinessunitid { get; set; }
        public string xjp_fluorocarbonclassificationname { get; set; }
        public decimal xjp_coefficientofyearsa { get; set; }
        public Guid xts_newvehiclesalesorderid { get; set; }
        public string xts_leadidyominame { get; set; }
        public decimal xjp_shredderdustcharge { get; set; }
        public string transactioncurrencyidname { get; set; }
        public string xjp_noxobject { get; set; }
        public int xts_mileage { get; set; }
        public string xjp_useraddress2 { get; set; }
        public string xts_laststatus { get; set; }
        public string xjp_absequipmentname { get; set; }
        public Guid xts_personinchargeid { get; set; }
        public string xts_numberofdoorsname { get; set; }
        public decimal xts_weight { get; set; }
        public string createdonbehalfbyname { get; set; }
        public string xts_productdescription { get; set; }
        public int xjp_commercialvalueaddingpointsubtotal { get; set; }
        public decimal xjp_informationmanagementcharge { get; set; }
        public int xts_usedvehiclesalesorderlookuptype { get; set; }
        public Guid xjp_userid { get; set; }
        public string xts_personinchargeidname { get; set; }
        public bool xts_endlifevehicle { get; set; }
        public decimal xts_length { get; set; }
        public Guid transactioncurrencyid { get; set; }
        public decimal xts_engineandelectricitemcorrectiontotal { get; set; }
        public Guid xts_manufacturerid { get; set; }
        public string xjp_depositedpaymentcategory { get; set; }
        public string owneridname { get; set; }
        public int xjp_coverleatheraddingpoint { get; set; }
        public int xjp_jackandwrenchdeduction { get; set; }
        public int xts_paintcoloradditionandsubtractionpoint { get; set; }
        public string xjp_recyclingobject { get; set; }
        public string xjp_insurancecompanyidname { get; set; }
        public string xjp_roofracklength { get; set; }
        public string xjp_caliremainingadditionandsubtractionidname { get; set; }
        public string xjp_antennadeduction { get; set; }
        public string xts_transactiondetails_json3 { get; set; }
        public string xjp_aeroequipmentname { get; set; }
        public decimal xts_transmissionadditionandsubtractionamount_base { get; set; }
        public string xts_paintcoloradditionandsubtractionidname { get; set; }
        public string xjp_platenumbersegment1idname { get; set; }
        public DateTime xjp_compulsoryinsurancestartdate { get; set; }
        public decimal exchangerate { get; set; }
        public decimal xjp_shredderdustcharge_base { get; set; }
        public decimal xjp_carinspectionperiod { get; set; }
        public decimal xts_manualmeasure2_base { get; set; }
        public string xjp_recyclingticketname { get; set; }
        public DateTime xts_transactiondate { get; set; }
        public Guid owninguser { get; set; }
        public decimal xts_internalpurchasingprice_base { get; set; }
        public int xjp_navigationsystemcddvddeduction { get; set; }
        public string xjp_recyclingticketnumber { get; set; }
        public string xjp_useraddress3 { get; set; }
        public Guid xts_leadid { get; set; }
        public int xjp_swandawaddingpoint { get; set; }
        public string xts_goodsreceiptclassification { get; set; }
        public string xjp_ownercityidname { get; set; }
        public int xjp_otherfixtureaddingpoint { get; set; }
        public string xjp_powerwindow { get; set; }
        public DateTime xts_registrationdate { get; set; }
        public string xts_leadidname { get; set; }
        public string xts_vehicleclassidname { get; set; }
        public int xjp_airconditionerdeduction { get; set; }
        public decimal xjp_subtotadditionalbonuspointitemcorrection { get; set; }
        public int xjp_aeroequipmentaddingpoint { get; set; }
        public string xjp_useraddress1 { get; set; }
        public string xjp_weightcategoryname { get; set; }
        public decimal xjp_informationmanagementcharge_base { get; set; }
        public string xts_customerprovinceidname { get; set; }
        public decimal xjp_thecapitalmgmtchargeconsumingincludingtax { get; set; }
        public Guid xjp_platenumbersegment1id { get; set; }
        public Guid xjp_ownercityid { get; set; }
        public string xjp_useraddress4 { get; set; }
        public string xjp_powerseatname { get; set; }
        public int xjp_fixturedeductionsubtotal { get; set; }
        public Guid xts_businessunitid { get; set; }
        public Guid xts_receivingsiteid { get; set; }
        public string xts_repairhistory { get; set; }
        public Guid xts_villageandstreetid { get; set; }
        public Guid xts_vehicleclassid { get; set; }
        public decimal xts_manualmeasure1_base { get; set; }
        public string xts_assessmentnumber { get; set; }
        public Guid xts_basicpriceid { get; set; }
        public string xjp_platenumbersegment4 { get; set; }
        public string xts_usedvehiclesalesorderlookupname { get; set; }
        public string xjp_owneraddress4 { get; set; }
        public DateTime createdon { get; set; }
        public string xjp_platenumbersegment3 { get; set; }
        public string xjp_platenumbersegment2 { get; set; }
        public string xjp_owneraddress1 { get; set; }
        public string xjp_owneraddress2 { get; set; }
        public string xjp_ownervillageandstreetidname { get; set; }
        public int xjp_fixturededuction { get; set; }
        public string xjp_classificationnumber { get; set; }
        public Guid xts_plannedreceivingstoreid { get; set; }
        public string xts_vehiclebasicidname { get; set; }
        public string xts_motortypename { get; set; }
        public decimal xts_maximumload1 { get; set; }
        public string xts_transactiondetails_json { get; set; }
        public decimal xjp_subtotalengineandelectricitemcorrection { get; set; }
        public string xts_assessmentclassificationname { get; set; }
        public string xts_inventoryusedvehicleidname { get; set; }
        public Guid xts_customercountryid { get; set; }
        public string xjp_airconditionerequipment { get; set; }
        public decimal xts_additionalbonuspointitemcorrectiontotal { get; set; }
        public decimal xts_assessmentpricetotal_base { get; set; }
        public Guid createdby { get; set; }
        public int xjp_cdmdandstdeduction { get; set; }
        public string xts_locking { get; set; }
        public string xts_transmissionadditionandsubtractionidname { get; set; }
        public string xts_goodsreceiptclassificationname { get; set; }
        public string xjp_antennadeductionname { get; set; }
        public Guid xjp_ownerid { get; set; }
        public string xts_purchaseordertypeidname { get; set; }
        public string xjp_recyclingticket { get; set; }
        public string xjp_roofrackmaterialcolumn { get; set; }
        public string xjp_writtenguarantmaintpocketbooksetaddpointname { get; set; }
        public string createdbyname { get; set; }
        public string xts_productidname { get; set; }
        public string xjp_weightcategory { get; set; }
        public string xts_receivingwarehouseidname { get; set; }
        public bool xjp_lightvehicleflag { get; set; }
        public DateTime xts_expectedreceivingdate { get; set; }
        public string xjp_fluorocarbonequipmentname { get; set; }
        public int statecode { get; set; }
        public decimal xts_priceatnewcar_base { get; set; }
        public int statuscode { get; set; }
        public string xjp_airbagequipment { get; set; }
        public Guid xts_inventoryusedvehicleid { get; set; }
        public string xjp_garrageaddress { get; set; }
        public Guid xjp_vhcinspectionremdraddtnandsubtractionid { get; set; }
        public string xjp_recordlist { get; set; }
        public int xjp_carinspectionremainingmonth { get; set; }
        public string xjp_coverleather { get; set; }
        public int xjp_tirededuction { get; set; }
        public decimal xjp_remainingdebtamount { get; set; }
        public int xjp_mileageatcarinspection { get; set; }
        public string xts_vehicleidentificationnumber { get; set; }
        public int timezoneruleversionnumber { get; set; }
        public Guid xjp_ownervillageandstreetid { get; set; }
        public string modifiedonbehalfbyyominame { get; set; }
        public string xts_phonenumber { get; set; }
        public string xts_vehicleage { get; set; }
        public int xjp_fixtureaddingpointsubtotal { get; set; }
        public string statuscodename { get; set; }
        public decimal xjp_subtotalinteriorexteriorcorrection { get; set; }
        public int xjp_sunroofdeduction { get; set; }
        public Guid xts_paintcoloradditionandsubtractionid { get; set; }
        public int xts_registrationelapsedmonth { get; set; }
        public bool xjp_ascd { get; set; }
        public string xts_customeridname { get; set; }
        public Guid xts_customercityid { get; set; }
        public string xjp_vhcinspectionremdraddtnandsubtractionidname { get; set; }
        public string xts_handlingname { get; set; }
        public string xts_runningmeterexchangename { get; set; }
        public string xts_parentbusinessunitidname { get; set; }
        public string xjp_productionyearjapan { get; set; }
        public int xjp_coverleatherdeduction { get; set; }
        public string modifiedbyname { get; set; }
        public string xts_plannedreceivingstoreidname { get; set; }
        public string owneridtype { get; set; }
        public int xjp_airconditioneraddingpoint { get; set; }
        public int xjp_otherfixturededuction { get; set; }
        public string xts_chassisnumber { get; set; }
        public int xjp_aeroequipmentdeduction { get; set; }
        public string xts_vehiclespecificationidname { get; set; }
        public string xjp_owneraddress3 { get; set; }
        public string xjp_roof { get; set; }
        public decimal xts_rate_base { get; set; }
        public decimal xjp_recyclingchargetotal_base { get; set; }
        public decimal xts_additionalcorrectiontotal { get; set; }
        public string xjp_uservillageandstreetidname { get; set; }
        public string xts_motive { get; set; }
        public Guid xjp_modeldivisionid { get; set; }
        public string xts_shiftpositionname { get; set; }
        public DateTime xjp_carinspectionexpirationdate { get; set; }
        public string xjp_stereoequipmentname { get; set; }
        public string xjp_fluorocarbonequipment { get; set; }
        public string xjp_powerwindowname { get; set; }
        public string xts_bodyshapeidname { get; set; }
        public string xts_customercityidname { get; set; }
        public decimal xts_vehiclemainbodyamounttotal { get; set; }
        public string xts_status { get; set; }
        public decimal xts_transmissionadditionandsubtractionamount { get; set; }
        public decimal xts_runningkmadditionandsubtractionamount { get; set; }
        public string xjp_tvequipmentname { get; set; }
        public string xjp_owneridyominame { get; set; }
        public decimal xjp_thecapitalmgmtchargeconsumingincludingtax_base { get; set; }
        public string xts_chassismodel { get; set; }
        public string xjp_airconditionerequipmentname { get; set; }
        public string xts_usedvehicleexteriorcoloridname { get; set; }
        public decimal xjp_recyclingchargetotal { get; set; }
        public decimal xts_baseamount { get; set; }
        public string createdonbehalfbyyominame { get; set; }
        public string xts_transactiondetails_json2 { get; set; }
        public string xjp_firstyearregistrationjapan { get; set; }
        public Guid xts_transmissionadditionandsubtractionid { get; set; }
        public string xts_runningkmadditionandsubtractionidname { get; set; }
        public decimal xjp_fluorocarbondepositedamount { get; set; }
        public Guid ownerid { get; set; }
        public string xts_receivingsiteidname { get; set; }
        public decimal xts_additionalcorrectiontotal_base { get; set; }
        public string xjp_recyclingairbagequipment { get; set; }
        public int xjp_airbagdeduction { get; set; }
        public string traversedpath { get; set; }
        public decimal xts_consumptiontaxamount_base { get; set; }
        public string xjp_cabsectionname { get; set; }
        public string xjp_instructionmanualdeductionname { get; set; }
        public Guid modifiedonbehalfby { get; set; }
        public Guid xts_customerprovinceid { get; set; }
        public Guid xts_automobilelayoutid { get; set; }
        public string xts_recognizedmodelidname { get; set; }
        public string xts_usedvehiclesalesorderidname { get; set; }
        public string xjp_roofracklengthname { get; set; }
        public decimal xts_newcarmeasure_base { get; set; }
        public decimal xjp_remainingdebtamount_base { get; set; }
        public string xjp_absequipment { get; set; }
        public string xts_address1 { get; set; }
        public string xjp_sunroofname { get; set; }
        public string xjp_tonnagetaxrefundobjectname { get; set; }
        public Guid xts_customerid { get; set; }
        public decimal xjp_airbagdepositedamount_base { get; set; }
        public Guid xts_receivingbusinessunitid { get; set; }
        public string xts_finalassessmentexsistencename { get; set; }
        public string xts_motivename { get; set; }
        public string owneridyominame { get; set; }
        public string xjp_useridyominame { get; set; }
        public string xjp_compulsoryinsuranceenddatejapan { get; set; }
        public string xjp_writtenguarantmaintpocketbooksetaddpoint { get; set; }
        public string xts_vehicleagename { get; set; }
        public string xjp_automaticspeedcontroldeviceexistence { get; set; }
        public Guid xjp_ownervendorid { get; set; }
        public decimal xts_enginevolume { get; set; }
        public decimal xts_paintcoloradditionandsubtractionamount { get; set; }
        public Guid xts_vehiclemodelid { get; set; }
        public string xts_receivingbusinessunitidname { get; set; }
        public bool xts_automaticcreated { get; set; }
        public string xts_comment { get; set; }
        public int xjp_absequipmentdeduction { get; set; }
        public string xjp_otherequipment { get; set; }
        public string xts_enginevolumeunit { get; set; }
        public string xjp_roofrackshapecolumn { get; set; }
        public Guid stageid { get; set; }
        public string modifiedonbehalfbyname { get; set; }
        public int xjp_sideviewmirrordeduction { get; set; }
        public decimal xts_manualmeasure3 { get; set; }
        public string xts_newvehiclesalesorderidname { get; set; }
        public bool xjp_airsuspension { get; set; }
        public Guid xjp_insurancecompanyid { get; set; }
        public decimal xts_height { get; set; }
        public int xjp_commercialvaluededuction { get; set; }
        public int xjp_actualexpensesdeduction { get; set; }
        public Guid xts_runningkmadditionandsubtractionid { get; set; }
        public string xjp_aeroequipment { get; set; }
        public string xts_vehiclepublicidname { get; set; }
        public string xjp_writtenguaranteemaintpocketbookdeductionname { get; set; }
        public int xjp_powersteeringaddingpoint { get; set; }
        public decimal xjp_airbagdepositedamount { get; set; }
        public decimal xts_paintcoloradditionandsubtractionamount_base { get; set; }
        public decimal xts_consumptiontaxamount { get; set; }
        public string xts_postalcode { get; set; }
        public string xjp_userpostalcode { get; set; }
        public decimal xts_tradeintotal { get; set; }
        public string xts_numberofgears { get; set; }
        public string xjp_coverleathername { get; set; }
        public decimal xts_rate { get; set; }
        public string xjp_ownercountryidname { get; set; }
        public Guid xts_bodyshapeid { get; set; }
        public int utcconversiontimezonecode { get; set; }
        public bool xjp_ownersameasclient { get; set; }
        public string xts_purchaseusagecategory { get; set; }
        public decimal xts_subtractioncorrectiontotal_base { get; set; }
        public string xts_statusname { get; set; }
        public string xts_interiorcolor { get; set; }
        public string xts_repairhistoryname { get; set; }
        public string xjp_usersameasclientname { get; set; }
        public decimal xts_tradeintotal_base { get; set; }
        public decimal xts_seatingcapacity2 { get; set; }
        public string xjp_modelspecification { get; set; }
        public string xts_numberofgearsname { get; set; }
        public decimal xts_remainingfinanceamount_base { get; set; }
        public string xts_address2 { get; set; }
        public string xjp_automaticspeedcontroldeviceexistencename { get; set; }
        public int xjp_accidentrepairexpense { get; set; }
        public string xts_initialassessmentidname { get; set; }
        public string xts_motormodel { get; set; }
        public decimal xjp_vhcinspectionremainderaddingpointamount { get; set; }
        public decimal xts_baseamount_base { get; set; }
        public string xts_assessmentclassification { get; set; }
        public string xjp_ownervendoridname { get; set; }
        public string xjp_ownerprovinceidname { get; set; }
        public int xjp_powersteeringdeduction { get; set; }
        public string xjp_modeldivisionidname { get; set; }
        public string xts_stocknumber { get; set; }
        public string xjp_powersteeringequipmentname { get; set; }
        public string xjp_usernumber { get; set; }
        public decimal xjp_coefficientofyearsc { get; set; }
        public decimal xjp_coefficientofyearsb { get; set; }
        public Guid xjp_uservillageandstreetid { get; set; }
        public string xjp_cabsection { get; set; }
        public DateTime modifiedon { get; set; }
        public string xjp_vehicleregistationcategoryidname { get; set; }
        public Guid processid { get; set; }
        public string xts_ribbondata { get; set; }
        public Guid xts_usedvehiclesalesorderid { get; set; }
        public string xjp_aluminiumwheelequipment { get; set; }
        public string xts_businessunitidname { get; set; }
        public string xts_consumptiontaxidname { get; set; }
        public string xjp_recordlistname { get; set; }
        public string modifiedbyyominame { get; set; }
        public Guid createdonbehalfby { get; set; }
        public int xjp_commercialvalueaddingpoint { get; set; }
        public decimal xts_manualmeasure2 { get; set; }
        public decimal xts_assessmentpricetotal { get; set; }
        public int xjp_tvaddingpoint { get; set; }
        public string xjp_fluorocarbonclassification { get; set; }
        public string xjp_noxobjectname { get; set; }
        public decimal xjp_vhcinspectionremainderaddingpointamount_base { get; set; }
        public int xjp_powerwindowdeduction { get; set; }
        public string xts_productionyear { get; set; }
        public string xjp_navigationsystemequipmentname { get; set; }
        public DateTime xjp_compulsoryinsuranceenddate { get; set; }
        public string xjp_depositedpaymentcategoryname { get; set; }
        public string xts_laststatusname { get; set; }
        public string xjp_aluminiumwheelequipmentname { get; set; }
        public string msdyn_companycode { get; set; }
    }
}
