#region Summary
// ===========================================================================
// AUTHOR        : BSI Code Generator
// PURPOSE       : VWI_CRM_pricelevelDto  class
// SPECIAL NOTES : DNet WebApi Project
// ---------------------
// Copyright  (c) 2018 
// ---------------------
// $History      : $
// Created on 24/02/2020 18:15:44
//
// ===========================================================================	
#endregion

#region Namespace Imports
using System;
#endregion

namespace KTB.DNet.Interface.Model
{
    public class VWI_CRM_xts_usedvehiclesalesorderDto : DtoBase
    {
        public string company { get; set; }
        public string businessunitcode { get; set; }
        public decimal xts_totalpayment_base { get; set; }
        public DateTime xjp_compulsoryinsurancecoveredperiod { get; set; }
        public decimal xjp_bonuspaymentamount1_base { get; set; }
        public Guid xjp_usercityid { get; set; }
        public Guid xts_financingcompanyid { get; set; }
        public string xjp_actualsalesrecognitionname { get; set; }
        public decimal xts_vehiclerelatedproductamount_base { get; set; }
        public string xts_transmissionname { get; set; }
        public string xjp_acquisitiontaxreductionidname { get; set; }
        public DateTime xjp_automobiletaxfirstpaymentperiod { get; set; }
        public string xjp_guarantoraddress3 { get; set; }
        public decimal xts_weights { get; set; }
        public decimal xjp_automobiletaxremainingamount_base { get; set; }
        public string xjp_firstyearregistration { get; set; }
        public decimal xts_extrachargesamount { get; set; }
        public DateTime overriddencreatedon { get; set; }
        public string xts_salesquoteidname { get; set; }
        public string x01_usercountryidname { get; set; }
        public decimal xts_miscellaneouschargecost { get; set; }
        public Int32 importsequencenumber { get; set; }
        public string x01_payercountryidname { get; set; }
        public decimal xts_miscellaneouschargeconsumptiontaxamount_base { get; set; }
        public string xjp_compulsoryinsuranceidname { get; set; }
        public Int32 xts_potentiallookuptype { get; set; }
        public string xjp_usagecategory { get; set; }
        public decimal xts_totaltradeinconsumptiontaxamount_base { get; set; }
        public decimal xts_enginevolume { get; set; }
        public string xjp_actualsalesrecognition { get; set; }
        public Guid xts_stockid { get; set; }
        public bool x01_registrationfeeispaid { get; set; }
        public DateTime xjp_garagecertificateacquisitiondate { get; set; }
        public string xts_virtualaccountname { get; set; }
        public decimal xts_servicemaintenancetaxamount_base { get; set; }
        public Guid xjp_lastregistrationrequestid { get; set; }
        public Guid modifiedby { get; set; }
        public string xts_owneridyominame { get; set; }
        public decimal xts_miscellaneouschargesalesprice_base { get; set; }
        public string xjp_firstregistrationjapan { get; set; }
        public decimal xts_vehiclecost_base { get; set; }
        public Guid x01_ownercountryid { get; set; }
        public string xjp_insurancecompanycode { get; set; }
        public DateTime xts_birthdate { get; set; }
        public string xts_handling { get; set; }
        public decimal xts_miscellaneouschargegrossmargin { get; set; }
        public string xts_siteidname { get; set; }
        public string statecodename { get; set; }
        public decimal xts_serviceaddandmaintenancenetsalesprice_base { get; set; }
        public decimal xts_serviceaddandmaintenancegrossmargin { get; set; }
        public string xjp_registrationpurposename { get; set; }
        public Int32 xjp_effectivebillperioddays { get; set; }
        public decimal xts_ttlvehiclerelatedproducttransactionamount { get; set; }
        public Guid xjp_payerprovinceid { get; set; }
        public Guid owningteam { get; set; }
        public decimal xts_vehiclerelatedproductcost { get; set; }
        public Guid xts_productid { get; set; }
        public decimal xjp_storecost { get; set; }
        public string xts_intercompanysalesname { get; set; }
        public DateTime xjp_automobiletaxunelapsedtime { get; set; }
        public bool xts_vehicledeliveryplace { get; set; }
        public decimal xjp_automobiletaxamount { get; set; }
        public Guid xts_usedvehicleexteriorcolorid { get; set; }
        public string xjp_owneraddress3 { get; set; }
        public Guid xjp_weightedtaxid { get; set; }
        public string xjp_compulsoryinsvehicleclassificationidname { get; set; }
        public string xts_cardeliveryname { get; set; }
        public decimal xts_totaltradeinamount { get; set; }
        public decimal xjp_serviceacquisitiontaxamount { get; set; }
        public decimal xjp_airbagcharge { get; set; }
        public decimal xts_otherdiscountsubtotal_base { get; set; }
        public Guid owningbusinessunit { get; set; }
        public decimal xjp_autmbltaxremainingamountconsumptiontax { get; set; }
        public string xjp_weightedtaxreductionidname { get; set; }
        public decimal xjp_compulsoryinsuranceamount { get; set; }
        public string xts_landtransportationdestinationdistrictidname { get; set; }
        public string x01_ordertypeidname { get; set; }
        public string xjp_payeridname { get; set; }
        public decimal xts_totaltradeinremainderbondamount_base { get; set; }
        public string xjp_vehiclemanagementidname { get; set; }
        public string xjp_guarantoraddress1 { get; set; }
        public Guid xts_miscellaneouschargetemplateid { get; set; }
        public decimal xts_vehiclegrossmarginsubtotal_base { get; set; }
        public string xts_bcmidname { get; set; }
        public string xjp_payeraddress2 { get; set; }
        public string xjp_ownerpostalcode { get; set; }
        public Int64 versionnumber { get; set; }
        public string xts_userphone { get; set; }
        public string xjp_guarantoraddress4 { get; set; }
        public decimal xts_totaltradeinremainderbondamount { get; set; }
        public DateTime xts_paymentendingperiod { get; set; }
        public decimal xjp_automobiletaxremainingamount { get; set; }
        public string xts_owneridname { get; set; }
        public string xts_customeraddress { get; set; }
        public decimal xts_estimatedprofitandlosssalesprice_base { get; set; }
        public Guid xts_potentialcustomerid { get; set; }
        public string xts_manufactureridname { get; set; }
        public decimal xts_miscellaneouschargegrossmargin_base { get; set; }
        public Guid xjp_userprovinceid { get; set; }
        public Guid xts_landtransportationorigindistrictid { get; set; }
        public decimal xts_vehiclegrossmargin_base { get; set; }
        public decimal xjp_tradeinautomobiletaxcashbackamount_base { get; set; }
        public decimal xts_estimatedprofitandlosscost_base { get; set; }
        public decimal xts_totalreceiptamount_base { get; set; }
        public decimal xjp_shredderresiduecharge_base { get; set; }
        public decimal xts_monthlypayment_base { get; set; }
        public string xts_landtransportationorigindistrictidname { get; set; }
        public string xjp_payeridyominame { get; set; }
        public Guid xts_userid { get; set; }
        public string createdbyyominame { get; set; }
        public DateTime xts_expectedtradeindate { get; set; }
        public Int32 xts_load { get; set; }
        public decimal xts_miscellaneouschargediscount_base { get; set; }
        public string xts_useridyominame { get; set; }
        public decimal xts_totalvehicletransactionamount { get; set; }
        public decimal xts_totalmiscellaneoustransactionamount_base { get; set; }
        public decimal xjp_weighttaxamount_base { get; set; }
        public string x01_ownercountryidname { get; set; }
        public decimal xts_miscellaneouschargebaseamount_base { get; set; }
        public decimal xjp_shredderresiduecharge { get; set; }
        public decimal xjp_elvvariouscosttaxation { get; set; }
        public decimal xts_vehiclerelatedproducttaxamount { get; set; }
        public Guid xjp_guarantorprovinceid { get; set; }
        public decimal xjp_bonuspaymentamount2 { get; set; }
        public decimal xts_salescampaigncost { get; set; }
        public string xjp_recyclingfeedepositclassificationname { get; set; }
        public decimal xts_balance_base { get; set; }
        public DateTime xjp_vehicleinspectionexpirationdate { get; set; }
        public string xts_locationidname { get; set; }
        public decimal xts_serviceaddandmaintenancediscount_base { get; set; }
        public decimal xts_totalpaymentamount_base { get; set; }
        public string xts_consumptiontaxidname { get; set; }
        public bool x01_downpaymentispaid { get; set; }
        public Guid x01_payercountryid { get; set; }
        public decimal xjp_fluorocarboncharge { get; set; }
        public string xts_wholesalesorderidname { get; set; }
        public decimal xjp_bonuspaymentamount2_base { get; set; }
        public string xts_ownername { get; set; }
        public string xjp_payeraliasname { get; set; }
        public string xts_transmission { get; set; }
        public decimal xts_othergrossmarginsubtotal_base { get; set; }
        public decimal xts_consumptiontaxamount { get; set; }
        public string xts_warrantytypeidname { get; set; }
        public string xts_owneraddress { get; set; }
        public decimal xts_totalservicemaintenancetransactionamount { get; set; }
        public string xjp_guarantorvillageandaddressidname { get; set; }
        public DateTime xts_paymentstartingperiod { get; set; }
        public decimal xts_vehiclediscountsubtotal_base { get; set; }
        public decimal xts_vehiclediscount { get; set; }
        public string xts_salespersonname { get; set; }
        public decimal xts_totaltradeinprice_base { get; set; }
        public Int32 xts_numberofpayment { get; set; }
        public string xjp_guarantorprovinceidname { get; set; }
        public decimal xts_vehiclerelatedproductbaseamount_base { get; set; }
        public decimal xts_interestrateamount { get; set; }
        public string transactioncurrencyidname { get; set; }
        public string xjp_useraddress2 { get; set; }
        public string xts_laststatus { get; set; }
        public DateTime xts_effectiveto { get; set; }
        public decimal xts_totaladvancepayment_base { get; set; }
        public string xts_status { get; set; }
        public string xjp_vehiclemanagementaddress { get; set; }
        public decimal xts_referralcommissioncost_base { get; set; }
        public string xjp_payerphone { get; set; }
        public Int32 xts_weight { get; set; }
        public string xjp_payercityidname { get; set; }
        public string xts_owneraliasname { get; set; }
        public string xts_productdescription { get; set; }
        public decimal xts_referralgrossmargin_base { get; set; }
        public decimal xjp_informationmanagementcharge { get; set; }
        public decimal xts_variouscostconsumptiontaxamount_base { get; set; }
        public decimal xts_salescampaigncost_base { get; set; }
        public Guid transactioncurrencyid { get; set; }
        public DateTime xjp_automobileweighttaxcarinspectionperiod { get; set; }
        public decimal xts_subtotal { get; set; }
        public Guid xts_manufacturerid { get; set; }
        public string owneridname { get; set; }
        public string xts_potentialcontactidname { get; set; }
        public string xts_vehicledeliveryplacename { get; set; }
        public DateTime xts_actualvehicledeliverydate { get; set; }
        public decimal xts_downpayment_base { get; set; }
        public decimal xts_vehiclerelatedproducttaxamount_base { get; set; }
        public DateTime xts_expectedvehicledeliverydate { get; set; }
        public string xts_ribbonsource { get; set; }
        public Guid processid { get; set; }
        public string xts_virtualaccountidname { get; set; }
        public string xts_salescategory { get; set; }
        public Guid xjp_uservillageandaddressid { get; set; }
        public decimal xts_monthlypayment { get; set; }
        public string traversedpath { get; set; }
        public decimal xts_interestrateamount_base { get; set; }
        public decimal exchangerate { get; set; }
        public decimal xts_balance { get; set; }
        public decimal xts_estimatedprofitandlossdiscount_base { get; set; }
        public Guid x01_guarantorcountryid { get; set; }
        public Guid xts_locationid { get; set; }
        public string xjp_grade { get; set; }
        public DateTime xts_transactiondate { get; set; }
        public string xjp_recyclingticketnumber { get; set; }
        public string xts_ownerphone { get; set; }
        public Guid xjp_ownervillageandaddressid { get; set; }
        public string xts_currentplatenumber { get; set; }
        public string xjp_uservillageandaddressidname { get; set; }
        public Guid xjp_guarantorcityid { get; set; }
        public Guid xts_warehouseid { get; set; }
        public string xjp_ownercityidname { get; set; }
        public string xjp_guarantoridname { get; set; }
        public Guid xjp_payervillageandaddressid { get; set; }
        public decimal xts_othercostsubtotal_base { get; set; }
        public decimal xts_salescampaignmargin_base { get; set; }
        public Guid xts_salespersonid { get; set; }
        public decimal xjp_capitalmanagementcharge { get; set; }
        public Guid x01_usercountryid { get; set; }
        public string xjp_userpostalcode { get; set; }
        public string xts_username { get; set; }
        public string xjp_payerpostalcode { get; set; }
        public string x01_nvacquisitiontaxidname { get; set; }
        public string xjp_useraddress1 { get; set; }
        public decimal xts_downpayment { get; set; }
        public decimal xjp_informationmanagementcharge_base { get; set; }
        public decimal xts_extrachargesamount_base { get; set; }
        public decimal xjp_tradeinautomobiletaxcashbackamount { get; set; }
        public decimal xjp_subtotaltaxandinsuranceremainingamount_base { get; set; }
        public decimal xts_accessorytaxamount { get; set; }
        public string xjp_useraddress4 { get; set; }
        public decimal xts_othersalessubtotal_base { get; set; }
        public string xjp_consumptiontaxcategoryname { get; set; }
        public string xjp_recyclingfeedepositclassification { get; set; }
        public decimal xts_totalpayment { get; set; }
        public decimal xjp_storecost_base { get; set; }
        public string xjp_usagecategoryname { get; set; }
        public decimal xts_totaltradeinconsumptiontaxamount { get; set; }
        public string xjp_guarantorpostalcode { get; set; }
        public decimal xts_billamount_base { get; set; }
        public string xts_potentialcustomeridname { get; set; }
        public Guid xts_landtransportationdestinationdistrictid { get; set; }
        public string createdonbehalfbyname { get; set; }
        public string xts_useraliasname { get; set; }
        public DateTime createdon { get; set; }
        public decimal xts_vehiclerelatedproductgrossmargin_base { get; set; }
        public string xjp_owneraddress1 { get; set; }
        public decimal xts_interestratecost { get; set; }
        public string xjp_garagecertificatepolicestationname { get; set; }
        public string xjp_modelspecificationnumber { get; set; }
        public decimal xts_estimatedprofitandlossdiscount { get; set; }
        public Guid xts_salesquoteid { get; set; }
        public decimal xjp_totalrecyclingcharge { get; set; }
        public string xjp_classificationnumber { get; set; }
        public decimal xts_vehicletaxamount_base { get; set; }
        public Guid xts_virtualaccountid { get; set; }
        public Guid xjp_compulsoryinsvehicleclassificationid { get; set; }
        public string xts_customername { get; set; }
        public string xjp_guarantoraliasname { get; set; }
        public string xts_landtransportationdestinationprovinceidname { get; set; }
        public decimal xjp_elfrecyclingdepositedmoney_base { get; set; }
        public Guid xjp_guarantorvillageandaddressid { get; set; }
        public string xjp_useraddress3 { get; set; }
        public string x01_vehiclespecificationidname { get; set; }
        public DateTime xts_registrationdesireddate { get; set; }
        public string xts_claimstatusname { get; set; }
        public decimal xjp_elvtotalamount_base { get; set; }
        public string xjp_consumptiontaxcategory { get; set; }
        public decimal xts_othersalessubtotal { get; set; }
        public Guid xts_vehiclemodelid { get; set; }
        public Guid createdby { get; set; }
        public Int32 xts_currentmileage { get; set; }
        public string xts_locking { get; set; }
        public decimal xts_totaltradeinrecyclingdepositamount_base { get; set; }
        public decimal xjp_compulsoryinsurancerefundamount_base { get; set; }
        public Guid xjp_acquisitiontaxreductionid { get; set; }
        public string xjp_ownervillageandaddressidname { get; set; }
        public decimal xts_interestgrossmargin { get; set; }
        public decimal xts_serviceaddandmaintenancediscount { get; set; }
        public string xts_statusname { get; set; }
        public string xjp_automobiletaxremainingcategoryname { get; set; }
        public decimal xts_vehiclerelatedproductcost_base { get; set; }
        public string xts_temporary { get; set; }
        public string xts_stockidname { get; set; }
        public decimal xts_accessorytaxrate { get; set; }
        public string createdbyname { get; set; }
        public string xts_productidname { get; set; }
        public string xts_claimstatus { get; set; }
        public Guid xjp_acquisitiontaxid { get; set; }
        public decimal xts_vehiclecostsubtotal { get; set; }
        public string xts_potentiallookupname { get; set; }
        public bool xts_virtualaccountuse { get; set; }
        public Int32 statecode { get; set; }
        public decimal xts_totalremainingamount { get; set; }
        public Int32 statuscode { get; set; }
        public decimal xts_totaltradeinamount_base { get; set; }
        public string x01_registrationfeeispaidname { get; set; }
        public decimal xts_estimatedprofitandlossgrossmargin_base { get; set; }
        public decimal xts_miscellaneouschargenetsalesprice { get; set; }
        public decimal xts_totalremainingamount_base { get; set; }
        public DateTime xts_warrantyexpirationdate { get; set; }
        public decimal xjp_acquisitiontaxamount_base { get; set; }
        public string xjp_acquisitiontaxidname { get; set; }
        public string xjp_lastregistrationrequestidname { get; set; }
        public decimal xts_vehiclesalessubtotal { get; set; }
        public decimal xjp_remainingvaluetaxamount { get; set; }
        public decimal xjp_elvconsumptiontax_base { get; set; }
        public string xjp_vehicleinspectionexpirationdatejapan { get; set; }
        public string xjp_compulsoryinsuranceremainingamount { get; set; }
        public decimal xjp_voluntaryinsurance_base { get; set; }
        public decimal xts_vehiclegrossmarginsubtotal { get; set; }
        public decimal xts_variouscostconsumptiontaxamount { get; set; }
        public Int32 timezoneruleversionnumber { get; set; }
        public Guid x01_ordertypeid { get; set; }
        public string modifiedonbehalfbyyominame { get; set; }
        public Guid xts_potentialcontactid { get; set; }
        public string xjp_guarantoridyominame { get; set; }
        public decimal xts_miscellaneouschargeconsumptiontaxamount { get; set; }
        public string statuscodename { get; set; }
        public decimal xts_vehicletaxrate { get; set; }
        public string xjp_registrationpurpose { get; set; }
        public decimal xts_vehiclebaseamount_base { get; set; }
        public Guid xts_siteid { get; set; }
        public Guid xjp_ownerprovinceid { get; set; }
        public string xts_usedvehicleexteriorcoloridname { get; set; }
        public string xts_parentbusinessunitidname { get; set; }
        public decimal xts_loads { get; set; }
        public decimal xts_totalmiscellaneoustransactionamount { get; set; }
        public string modifiedbyname { get; set; }
        public string xjp_owneraddress2 { get; set; }
        public string owneridtype { get; set; }
        public Guid xts_landtransportationoriginprovinceid { get; set; }
        public string xts_cardelivery { get; set; }
        public Guid xts_businessunitid { get; set; }
        public string xjp_guarantorcityidname { get; set; }
        public decimal xts_grandtotal { get; set; }
        public decimal xts_othergrossmarginsubtotal { get; set; }
        public string xjp_owneraddress4 { get; set; }
        public decimal xts_vehiclenetsalesprice_base { get; set; }
        public decimal xts_serviceaddandmaintenancecost { get; set; }
        public decimal xts_discountbaseamount { get; set; }
        public decimal xjp_fluorocarboncharge_base { get; set; }
        public decimal xts_interestratecost_base { get; set; }
        public Guid xts_consumptiontaxid { get; set; }
        public decimal xts_totaltradeinprice { get; set; }
        public decimal xts_vehiclerelatedproductdiscountamount_base { get; set; }
        public string xjp_ownershipcategoryname { get; set; }
        public decimal xts_referralgrossmargin { get; set; }
        public string xjp_vehiclemanagementphone { get; set; }
        public string xts_potentialcontactidyominame { get; set; }
        public Guid x01_vehiclespecificationid { get; set; }
        public decimal xts_otherdiscountsubtotal { get; set; }
        public decimal xjp_elvvariouscosttaxation_base { get; set; }
        public decimal xts_billamount { get; set; }
        public Guid xts_bcmid { get; set; }
        public string xts_potentialcustomeridyominame { get; set; }
        public Guid xjp_automobiletaxid { get; set; }
        public decimal xjp_elvtotalamount { get; set; }
        public decimal xts_vehiclegrossmargin { get; set; }
        public decimal xjp_elvvariouscosttaxfree_base { get; set; }
        public decimal xjp_elvvariouscosttaxfree { get; set; }
        public string xjp_recognizedmodelidname { get; set; }
        public decimal xjp_subtotaltaxandinsuranceremainingamount { get; set; }
        public string xjp_payeraddress { get; set; }
        public Guid xjp_vehiclemanagementid { get; set; }
        public decimal xts_miscellaneouschargesalesprice { get; set; }
        public Guid xts_wholesalesorderid { get; set; }
        public string xjp_usercityidname { get; set; }
        public string createdonbehalfbyyominame { get; set; }
        public decimal xts_serviceaddandmaintenancenetsalesprice { get; set; }
        public decimal xts_referralcommissioncost { get; set; }
        public decimal xjp_voluntaryinsurance { get; set; }
        public decimal xjp_elfrecyclingdepositedmoney { get; set; }
        public Guid xjp_compulsoryinsuranceid { get; set; }
        public Guid ownerid { get; set; }
        public Int32 xjp_bonuspaymentmonth1 { get; set; }
        public DateTime xjp_compulsoryinsuranceunelapsedtime { get; set; }
        public decimal xts_miscellaneouschargebaseamount { get; set; }
        public bool xts_requestplatenumber { get; set; }
        public Guid modifiedonbehalfby { get; set; }
        public decimal xts_totalreceiptamount { get; set; }
        public string xts_requestplatenumbername { get; set; }
        public decimal xts_vehiclebaseamount { get; set; }
        public Int32 xts_warrantymileage { get; set; }
        public string xjp_automobiletaxidname { get; set; }
        public Guid xts_parentbusinessunitid { get; set; }
        public string x01_downpaymentispaidname { get; set; }
        public string xts_enginevolumeunitname { get; set; }
        public string xts_laststatusname { get; set; }
        public decimal xts_vehiclesalessubtotal_base { get; set; }
        public string xts_requestedplatenumber { get; set; }
        public DateTime xts_actualtradeinreceivingdate { get; set; }
        public string xjp_payeraddress4 { get; set; }
        public Guid xts_methodofpaymentid { get; set; }
        public string xjp_guarantoraddress2 { get; set; }
        public string xts_customeraliasname { get; set; }
        public decimal xjp_compulsoryinsuranceremainingamount_base { get; set; }
        public string owneridyominame { get; set; }
        public string xjp_payeraddress3 { get; set; }
        public decimal xjp_acquisitiontaxamount { get; set; }
        public string xjp_weightedtaxidname { get; set; }
        public string xts_enginevolumeunit { get; set; }
        public string xjp_guarantorname { get; set; }
        public decimal xts_vehiclerelatedproductbaseamount { get; set; }
        public decimal xts_vehiclerelatedproductnetsalesprice_base { get; set; }
        public string xjp_automobiletaxreductionidname { get; set; }
        public Guid xjp_payercityid { get; set; }
        public string xts_salescategoryname { get; set; }
        public decimal xjp_weighttaxamount { get; set; }
        public decimal xjp_compulsoryinsurancerefundamount { get; set; }
        public string xjp_lightcharacterplatetypename { get; set; }
        public string xts_useridname { get; set; }
        public Guid xjp_automobiletaxreductionid { get; set; }
        public string xjp_vehiclemanagementidyominame { get; set; }
        public decimal xts_servicemaintenancetaxamount { get; set; }
        public decimal xts_vehiclerelatedproducttaxrate { get; set; }
        public string x01_guarantorcountryidname { get; set; }
        public decimal xts_serviceaddandmaintenancecost_base { get; set; }
        public string xjp_idempotentmessage { get; set; }
        public decimal xts_vehiclediscountsubtotal { get; set; }
        public decimal xts_totalvehicletransactionamount_base { get; set; }
        public Guid stageid { get; set; }
        public string modifiedonbehalfbyname { get; set; }
        public decimal xjp_subtotaltaxandinsurance_base { get; set; }
        public string xjp_payervillageandaddressidname { get; set; }
        public decimal xts_grandtotal_base { get; set; }
        public decimal xts_vehiclerelatedproductdiscountamount { get; set; }
        public string xjp_payername { get; set; }
        public decimal xts_annualcreditrate { get; set; }
        public Guid x01_nvacquisitiontaxid { get; set; }
        public decimal xts_miscellaneouschargediscount { get; set; }
        public decimal xjp_remainingvaluetaxamount_base { get; set; }
        public string xjp_payeraddress1 { get; set; }
        public string xts_productionyear { get; set; }
        public DateTime xts_invoiceddate { get; set; }
        public bool xts_intercompanysales { get; set; }
        public Guid xts_landtransportationdestinationprovinceid { get; set; }
        public Int32 xjp_usefullife { get; set; }
        public string xjp_guarantoraddress { get; set; }
        public decimal xts_ttlvehiclerelatedproducttransactionamount_base { get; set; }
        public string xts_financingcompanyidyominame { get; set; }
        public Guid owninguser { get; set; }
        public string xjp_automobiletaxremainingcategory { get; set; }
        public decimal xts_vehiclerelatedproductnetsalesprice { get; set; }
        public decimal xts_consumptiontaxamount_base { get; set; }
        public decimal xjp_capitalmanagementcharge_base { get; set; }
        public string xts_usedvehiclesalesordernumber { get; set; }
        public string xts_warehouseidname { get; set; }
        public string xjp_numberofyearselapsed { get; set; }
        public decimal xts_serviceaddandmaintenanceamount_base { get; set; }
        public decimal xts_totaltradeinrecyclingdepositamount { get; set; }
        public Guid createdonbehalfby { get; set; }
        public decimal xts_servicemaintenancebaseamount_base { get; set; }
        public decimal xjp_serviceacquisitiontaxamount_base { get; set; }
        public decimal xts_miscellaneouschargenetsalesprice_base { get; set; }
        public string xjp_vehiclemanagementnumber { get; set; }
        public string xjp_ownershipcategory { get; set; }
        public decimal xjp_totalrecyclingcharge_base { get; set; }
        public decimal xts_servicemaintenancetaxrate { get; set; }
        public decimal xjp_bonuspaymentamount1 { get; set; }
        public Int32 utcconversiontimezonecode { get; set; }
        public string xjp_guarantorphone { get; set; }
        public string xts_salespersonidname { get; set; }
        public Guid xjp_guarantorid { get; set; }
        public decimal xts_vehiclediscount_base { get; set; }
        public decimal xts_discountbaseamount_base { get; set; }
        public decimal xjp_airbagcharge_base { get; set; }
        public decimal xts_vehiclerelatedproductgrossmargin { get; set; }
        public string xjp_vehiclemanagementname { get; set; }
        public string xjp_userprovinceidname { get; set; }
        public decimal xts_totalservicemaintenancetransactionamount_base { get; set; }
        public decimal xjp_compulsoryinsremainamountconsumptiontax_base { get; set; }
        public string xts_methodofpaymentidname { get; set; }
        public decimal xts_serviceaddandmaintenancegrossmargin_base { get; set; }
        public decimal xts_interestgrossmargin_base { get; set; }
        public decimal xts_estimatedprofitandlosssalesprice { get; set; }
        public string xjp_ownerprovinceidname { get; set; }
        public string xjp_payerprovinceidname { get; set; }
        public decimal xjp_automobiletaxamount_base { get; set; }
        public bool xjp_lightcharacterplatetype { get; set; }
        public string xts_vehiclemodelidname { get; set; }
        public Guid xjp_recognizedmodelid { get; set; }
        public decimal xjp_elvconsumptiontax { get; set; }
        public decimal xts_vehiclerelatedproductamount { get; set; }
        public decimal xts_serviceaddandmaintenanceamount { get; set; }
        public decimal xts_totalpaymentamount { get; set; }
        public decimal xjp_autmbltaxremainingamountconsumptiontax_base { get; set; }
        public Guid xjp_ownercityid { get; set; }
        public decimal xts_subtotal_base { get; set; }
        public decimal xts_salescampaignmargin { get; set; }
        public string xts_handlingname { get; set; }
        public DateTime modifiedon { get; set; }
        public Guid xts_usedvehiclesalesorderid { get; set; }
        public decimal xts_othercostsubtotal { get; set; }
        public Guid xts_warrantytypeid { get; set; }
        public string xts_businessunitidname { get; set; }
        public decimal xts_totaladvancepayment { get; set; }
        public decimal xts_vehiclenetsalesprice { get; set; }
        public decimal xts_vehiclecostsubtotal_base { get; set; }
        public decimal xjp_compulsoryinsremainamountconsumptiontax { get; set; }
        public string modifiedbyyominame { get; set; }
        public decimal xts_accessorytaxamount_base { get; set; }
        public string xts_landtransportationoriginprovinceidname { get; set; }
        public decimal xts_vehicletaxamount { get; set; }
        public string xts_virtualaccountusename { get; set; }
        public Guid xjp_payerid { get; set; }
        public decimal xts_servicemaintenancebaseamount { get; set; }
        public decimal xts_vehicleamount_base { get; set; }
        public decimal xjp_compulsoryinsuranceamount_base { get; set; }
        public decimal xjp_subtotaltaxandinsurance { get; set; }
        public decimal xts_miscellaneouschargecost_base { get; set; }
        public decimal xts_vehiclecost { get; set; }
        public decimal xts_estimatedprofitandlossgrossmargin { get; set; }
        public decimal xts_vehicleamount { get; set; }
        public string xts_miscellaneouschargetemplateidname { get; set; }
        public decimal xts_estimatedprofitandlosscost { get; set; }
        public Guid xjp_weightedtaxreductionid { get; set; }
        public string xts_useraddress { get; set; }
        public string xjp_contractnumber { get; set; }
        public Guid xts_ownerid { get; set; }
        public string xts_financingcompanyidname { get; set; }
        public Int32 xjp_bonuspaymentmonth2 { get; set; }
        public string msdyn_companycode { get; set; }

    }
}
