#region Summary
// ===========================================================================
// AUTHOR        : BSI Code Generator
// PURPOSE       : VWI_CRM_xts_registrationdocumentferenceDto  class
// SPECIAL NOTES : DNet WebApi Project
// ---------------------
// Copyright  (c) 2018 
// ---------------------
// $History      : $
// Created on 12/24/2020 14:38:00
//
// ===========================================================================	
#endregion

#region Namespace Imports
using System;
#endregion

namespace KTB.DNet.Interface.Model
{
    public class VWI_CRM_xjp_registrationrequestDto : DtoBase
    {
        public string company { get; set; }
        public string businessunitcode { get; set; }
        public string xjp_requestingbusinessunitidname { get; set; }
        public bool xjp_endoflifevehicle { get; set; }
        public string xjp_parkingspacecertificationcollectedby { get; set; }
        public string xjp_stockstoreidname { get; set; }
        public string xjp_garageaddresssamewithusername { get; set; }
        public string xjp_agencyautomobiletaxpaymentname { get; set; }
        public string xjp_othercarkatakana { get; set; }
        public Guid xjp_garagecityid { get; set; }
        public DateTime xjp_cardeliverydesireddate { get; set; }
        public string xjp_lightcharacterplatetypename { get; set; }
        public DateTime overriddencreatedon { get; set; }
        public string xjp_usertype { get; set; }
        public Guid xjp_stockinventorynewvehicleid { get; set; }
        public string xjp_parentbusinessunitdescription { get; set; }
        public Guid xjp_usercityid { get; set; }
        public string xjp_pattern { get; set; }
        public decimal xjp_actualautomobileacquisitiontaxamount_base { get; set; }
        public int importsequencenumber { get; set; }
        public string xjp_owneridname { get; set; }
        public string xjp_productionyear { get; set; }
        public string xjp_registrationtaxcategory { get; set; }
        public string xjp_registrationcategoryname { get; set; }
        public Guid xjp_stockstoreid { get; set; }
        public string xjp_userdescription { get; set; }
        public string xjp_whereaboutsproof { get; set; }
        public string xjp_taxdeclarationbook { get; set; }
        public DateTime xjp_compulsoryinsuranceapplicationdate { get; set; }
        public Guid xjp_receivingbusinessunitid { get; set; }
        public string xjp_vehiclespecificationidname { get; set; }
        public string xjp_garageaddress2 { get; set; }
        public string xjp_leasedocument { get; set; }
        public string statecodename { get; set; }
        public string xjp_othercarnumber { get; set; }
        public string xjp_businessunitidname { get; set; }
        public string xjp_customeridyominame { get; set; }
        public string xjp_registrationpurposename { get; set; }
        public string xjp_completeinspectionexpiredname { get; set; }
        public string xjp_agencyacquisitiontaxpaymentname { get; set; }
        public string xjp_applicationregistrationofficeidname { get; set; }
        public string xjp_endoflifevehiclename { get; set; }
        public string xjp_garageapplicationsamewithusername { get; set; }
        public string xjp_ownerzipcode { get; set; }
        public decimal xjp_taxablemisccharge_base { get; set; }
        public string xjp_ownercityidname { get; set; }
        public string xjp_garageapplicationvillageandstreetidname { get; set; }
        public decimal xjp_automobiletaxamount { get; set; }
        public string xjp_othercarclassification { get; set; }
        public Guid xjp_garageapplicationvillageandstreetid { get; set; }
        public Guid xjp_vehiclespecificationid { get; set; }
        public string xjp_ownernumber { get; set; }
        public string xjp_garageprovinceidname { get; set; }
        public string xjp_vehiclemodelidname { get; set; }
        public string xjp_otherpartyregistrationtypename { get; set; }
        public Guid xjp_registrationresultofficeid { get; set; }
        public string xjp_handlingname { get; set; }
        public string xjp_otherpartyregistrationtype { get; set; }
        public string xjp_patternname { get; set; }
        public string xjp_garageapplicationsamewithuser { get; set; }
        public Guid xjp_vehiclemodelid { get; set; }
        public Guid xjp_creditcompanyid { get; set; }
        public string xjp_currentplatenumber { get; set; }
        public decimal xjp_miscellaneouschargeconsumptiontax_base { get; set; }
        public decimal xjp_vehicleconsumptiontax { get; set; }
        public DateTime xjp_documentcompletiondate { get; set; }
        public string xjp_requiredservice { get; set; }
        public string xjp_remodelingname { get; set; }
        public Guid xjp_customerid { get; set; }
        public bool xjp_peoplewithdisabilities { get; set; }
        public Guid xjp_personinchargeid { get; set; }
        public Guid xjp_paymentmethodid { get; set; }
        public bool xjp_requestplatenumber { get; set; }
        public Int64 versionnumber { get; set; }
        public bool xjp_garageapplicationrequired { get; set; }
        public string xjp_salesordernumber { get; set; }
        public decimal xjp_vehicleconsumptiontax_base { get; set; }
        public string xjp_residentscard { get; set; }
        public Guid xjp_othercarregistrationofficeid { get; set; }
        public string xjp_parentbusinessunitidname { get; set; }
        public decimal xjp_grandtotal { get; set; }
        public string xjp_stocknumberlookupname { get; set; }
        public string modifiedonbehalfbyname { get; set; }
        public string xjp_userrepresentative { get; set; }
        public DateTime xjp_documentexpireddate { get; set; }
        public string xjp_stockinventorynewvehicleidname { get; set; }
        public string createdbyyominame { get; set; }
        public string xjp_garageaddress1 { get; set; }
        public string xjp_ownerdescription { get; set; }
        public string xjp_insurancecompanyidname { get; set; }
        public Guid xjp_uservillageandaddressid { get; set; }
        public decimal xjp_weighttaxamount_base { get; set; }
        public Guid xjp_ownerprovinceid { get; set; }
        public DateTime xjp_registrationreceiptdate { get; set; }
        public string xjp_insurancecompanycode { get; set; }
        public Guid owningbusinessunit { get; set; }
        public string xjp_garageaddress3 { get; set; }
        public string xjp_userproxydocumentcollectedbyname { get; set; }
        public string xjp_ownershipcategoryname { get; set; }
        public DateTime xjp_vehicleinspectionexpirationdate { get; set; }
        public string xjp_uservillageandaddressidname { get; set; }
        public string xjp_usedvehicletaxreductioncategoryname { get; set; }
        public string xjp_compulsoryinsuranceapplymethod { get; set; }
        public Guid xjp_productid { get; set; }
        public decimal xjp_caliamount_base { get; set; }
        public string xjp_requestedclassification { get; set; }
        public Guid xjp_ownervillageandaddressid { get; set; }
        public decimal xjp_accessoriesacquisitiontaxamount { get; set; }
        public bool xjp_agencyautomobiletaxpayment { get; set; }
        public string xjp_registrationmethodname { get; set; }
        public string xjp_taxpayercategory { get; set; }
        public decimal xjp_actualautomobileacquisitiontaxamount { get; set; }
        public string transactioncurrencyidname { get; set; }
        public string xjp_requestedplatenumber { get; set; }
        public string xjp_useraddress2 { get; set; }
        public DateTime xjp_registrationscheduleddate { get; set; }
        public int xjp_validperiod { get; set; }
        public bool xjp_governmentoffice { get; set; }
        public string xjp_referencenumber { get; set; }
        public string xjp_customeridname { get; set; }
        public string createdonbehalfbyname { get; set; }
        public bool xjp_parkingplaceownersamewithuser { get; set; }
        public string xjp_vehiclespecificnumber { get; set; }
        public string xjp_garageaddresssamewithuser { get; set; }
        public Guid xjp_userid { get; set; }
        public string xjp_taxpayercategoryname { get; set; }
        public string xjp_agencycalipaymentname { get; set; }
        public Guid transactioncurrencyid { get; set; }
        public string xjp_registrationtype { get; set; }
        public string xjp_agencyhandlingname { get; set; }
        public decimal xjp_nontaxablemiscellaneouscharge { get; set; }
        public string xjp_requestedpersonincharge { get; set; }
        public string owneridname { get; set; }
        public string xjp_requestedbusinessunitidname { get; set; }
        public DateTime xjp_vehicleinspectionexpireddate { get; set; }
        public decimal xjp_miscellaneouschargetotal_base { get; set; }
        public string xjp_parkingplaceownersamewithusername { get; set; }
        public string xjp_height { get; set; }
        public string xjp_companyvehiclename { get; set; }
        public string xjp_userproxydocumentcollectedby { get; set; }
        public bool xjp_companyvehicle { get; set; }
        public string xjp_agencyweighttaxpaymentname { get; set; }
        public decimal xjp_acquisitiontaxtotalamount_base { get; set; }
        public string xjp_osscoloridname { get; set; }
        public string xjp_lightvehiclename { get; set; }
        public string xjp_platenumbersegment1idname { get; set; }
        public decimal exchangerate { get; set; }
        public string xjp_garageapplicationrequiredname { get; set; }
        public decimal xjp_miscellaneouschargeconsumptiontax { get; set; }
        public decimal xjp_accessoriesconsumptiontax_base { get; set; }
        public Guid xjp_parkingplaceprovinceid { get; set; }
        public DateTime xjp_registrationdesireddate { get; set; }
        public bool xjp_agencyacquisitiontaxpayment { get; set; }
        public string xjp_registrationcategory { get; set; }
        public string xjp_registrationcardeliveryagencyname { get; set; }
        public string xjp_others { get; set; }
        public string xjp_garageaddress { get; set; }
        public decimal xjp_actualweighttaxamount { get; set; }
        public int xjp_insuranceperiod { get; set; }
        public string xjp_compulsoryinsurancecertificatenumber { get; set; }
        public string xjp_physicallyhandicappedpersonpocketbook { get; set; }
        public string xjp_registrationdocumentnumber { get; set; }
        public decimal xjp_accessoriesacquisitiontaxamount_base { get; set; }
        public string xjp_currentplatenumbersegment4 { get; set; }
        public string xjp_userphone { get; set; }
        public string xjp_ownershippatternname { get; set; }
        public decimal xjp_taxablemisccharge { get; set; }
        public string xjp_receivingbusinessunitidname { get; set; }
        public string xjp_ownershipcategory { get; set; }
        public string xjp_locking { get; set; }
        public decimal xjp_nontaxablemiscellaneouscharge_base { get; set; }
        public string xjp_ossregistrationstatus { get; set; }
        public string xjp_useraddress4 { get; set; }
        public decimal xjp_grandtotal_base { get; set; }
        public string xjp_useraddress1 { get; set; }
        public string xjp_parkingspacecertificationcollectedbyname { get; set; }
        public Guid xjp_osscolorid { get; set; }
        public string xjp_parkingplaceprovinceidname { get; set; }
        public string xjp_platenumbersegment4 { get; set; }
        public string xjp_owneraddress4 { get; set; }
        public DateTime createdon { get; set; }
        public string xjp_parkingplaceaddress { get; set; }
        public string xjp_platenumbersegment2 { get; set; }
        public string xjp_owneraddress1 { get; set; }
        public string xjp_owneraddress2 { get; set; }
        public string xjp_owneraddress3 { get; set; }
        public string xjp_garageaddress4 { get; set; }
        public string xjp_usertypename { get; set; }
        public Guid xjp_businessunitid { get; set; }
        public string xjp_classificationnumber { get; set; }
        public Guid xjp_registrationdocumentrefid { get; set; }
        public string xjp_ownertype { get; set; }
        public string xjp_ownershippattern { get; set; }
        public string xjp_usagecategory { get; set; }
        public string xjp_customernumber { get; set; }
        public int xjp_round { get; set; }
        public Guid xjp_currentplatenumbersegment1id { get; set; }
        public string xjp_registrationresultofficeidname { get; set; }
        public string xjp_compulsoryautomobileliabilityinsurance { get; set; }
        public string xjp_premisesvehiclename { get; set; }
        public string xjp_creditcompanyidyominame { get; set; }
        public string xjp_registrationrequestnumber { get; set; }
        public string xjp_certificationofparkingspace { get; set; }
        public string xjp_width { get; set; }
        public decimal xjp_actualautomobiletaxamount { get; set; }
        public string xjp_governmentofficename { get; set; }
        public Guid xjp_ownerid { get; set; }
        public string xjp_recyclingticket { get; set; }
        public string xjp_registrationtypename { get; set; }
        public decimal xjp_actualautomobiletaxamount_base { get; set; }
        public string createdbyname { get; set; }
        public DateTime xjp_registrationresultsdate { get; set; }
        public string xjp_garageapplicationcityidname { get; set; }
        public Guid xjp_parentbusinessunitid { get; set; }
        public DateTime xjp_scheduleddeliverydate { get; set; }
        public int statecode { get; set; }
        public string xjp_productidname { get; set; }
        public int statuscode { get; set; }
        public string xjp_ownerrepresentativedescription { get; set; }
        public DateTime xjp_bringingindate { get; set; }
        public string xjp_vehicleidentificationnumber { get; set; }
        public bool xjp_remodeling { get; set; }
        public decimal xjp_vehicleacquisitiontaxamount { get; set; }
        public Guid xjp_productconfigurationid { get; set; }
        public string xjp_peoplewithdisabilitiesname { get; set; }
        public int timezoneruleversionnumber { get; set; }
        public string modifiedonbehalfbyyominame { get; set; }
        public string xjp_creditcompanyidname { get; set; }
        public string xjp_writtenreportmodel { get; set; }
        public string xjp_productinteriorcoloridname { get; set; }
        public string statuscodename { get; set; }
        public Guid owninguser { get; set; }
        public string xjp_requestplatenumbername { get; set; }
        public string xjp_parkingplacecertificatenumber { get; set; }
        public Guid xjp_stockinventoryusedvehicleid { get; set; }
        public decimal xjp_consumptiontaxamount_base { get; set; }
        public string xjp_registrationreferencenumber { get; set; }
        public string xjp_productionyearjapan { get; set; }
        public string modifiedbyname { get; set; }
        public string xjp_requiredservicename { get; set; }
        public string owneridtype { get; set; }
        public string xjp_registrationmethod { get; set; }
        public string xjp_garageapplicationprovinceidname { get; set; }
        public DateTime xjp_miscellaneouschargecollectiondate { get; set; }
        public string xjp_spaceforcorrespondence { get; set; }
        public bool xjp_documentcompletion { get; set; }
        public string xjp_officiallyregisteredseal { get; set; }
        public Guid xjp_requestingbusinessunitid { get; set; }
        public DateTime xjp_transactiondate { get; set; }
        public decimal xjp_accessoriesconsumptiontax { get; set; }
        public string xjp_productexteriorcoloridname { get; set; }
        public string xjp_registrationdocumentrefidname { get; set; }
        public string xjp_ownerphone { get; set; }
        public bool xjp_premisesvehicle { get; set; }
        public bool xjp_taxreductioncategory { get; set; }
        public bool xjp_agencyweighttaxpayment { get; set; }
        public Guid xjp_ownercityid { get; set; }
        public bool xjp_completeinspectionexpired { get; set; }
        public string xjp_recognizedmodelidname { get; set; }
        public string xjp_owneridyominame { get; set; }
        public string xjp_personinchargeidname { get; set; }
        public Guid xjp_lastregistrationpaymentid { get; set; }
        public Guid xjp_requestedbusinessunitid { get; set; }
        public string xjp_compulsoryinsuranceholder { get; set; }
        public string xjp_usercityidname { get; set; }
        public string xjp_documentcompletionname { get; set; }
        public string createdonbehalfbyyominame { get; set; }
        public string xjp_lastregistrationpaymentidname { get; set; }
        public string xjp_agencyhandling { get; set; }
        public Guid ownerid { get; set; }
        public DateTime xjp_scheduleshipmentdate { get; set; }
        public string xjp_currentplatenumbersegment3 { get; set; }
        public string xjp_requestednumber { get; set; }
        public string xjp_agencyregistrationstatusname { get; set; }
        public Guid modifiedonbehalfby { get; set; }
        public string xjp_productconfigurationidname { get; set; }
        public Guid owningteam { get; set; }
        public string xjp_registrationresultplatenumber { get; set; }
        public Guid xjp_applicationregistrationofficeid { get; set; }
        public string xjp_lightcharacter { get; set; }
        public string xjp_useridname { get; set; }
        public string xjp_button { get; set; }
        public string xjp_taxreductioncategoryname { get; set; }
        public Guid xjp_userprovinceid { get; set; }
        public string xjp_garagevillageandstreetidname { get; set; }
        public string owneridyominame { get; set; }
        public string xjp_useridyominame { get; set; }
        public string xjp_requestedrequestedbusinessunitincharge { get; set; }
        public Guid xjp_garageapplicationcityid { get; set; }
        public string xjp_customerdescription { get; set; }
        public DateTime xjp_registrationsendingdate { get; set; }
        public string xjp_othercarplatenumber { get; set; }
        public decimal xjp_weighttaxamount { get; set; }
        public string xjp_productstyleidname { get; set; }
        public string xjp_parkingplaceownersamewiththeusername { get; set; }
        public string xjp_proxydocumentcollectedby { get; set; }
        public string xjp_currentplatenumbersegment2 { get; set; }
        public string xjp_length { get; set; }
        public decimal xjp_consumptiontaxamount { get; set; }
        public bool xjp_reject { get; set; }
        public DateTime xjp_receivingdate { get; set; }
        public string xjp_userrepresentativedescription { get; set; }
        public string xjp_useraddress3 { get; set; }
        public Guid modifiedby { get; set; }
        public Guid xjp_insurancecompanyid { get; set; }
        public string xjp_currentplatenumbersegment1idname { get; set; }
        public string xjp_requestedkatakana { get; set; }
        public string xjp_proxydocumentcollectedbyname { get; set; }
        public Guid xjp_garagevillageandstreetid { get; set; }
        public string xjp_tempotherids { get; set; }
        public string xjp_usagecategoryname { get; set; }
        public decimal xjp_acquisitiontaxtotalamount { get; set; }
        public string xjp_compulsoryinsuranceapplymethodname { get; set; }
        public decimal xjp_vehicleacquisitiontaxamount_base { get; set; }
        public string xjp_rentalvehiclename { get; set; }
        public string xjp_userpostalcode { get; set; }
        public string xjp_theletterofattorney { get; set; }
        public Guid xjp_productexteriorcolorid { get; set; }
        public string xjp_agencyregistrationstatus { get; set; }
        public bool xjp_usedvehicletaxreductioncategory { get; set; }
        public bool xjp_ownerhaveothercar { get; set; }
        public DateTime xjp_documentreturndate { get; set; }
        public string xjp_othercarregistrationofficeidname { get; set; }
        public string xjp_ownerrepresentative { get; set; }
        public int utcconversiontimezonecode { get; set; }
        public Guid xjp_garageapplicationprovinceid { get; set; }
        public string xjp_compulsoryinsuranceholdername { get; set; }
        public string xjp_ossregistrationstatusname { get; set; }
        public DateTime xjp_documentreceiptdate { get; set; }
        public Guid xjp_productinteriorcolorid { get; set; }
        public string xjp_modelspecification { get; set; }
        public DateTime xjp_invoiceddate { get; set; }
        public Guid xjp_registrationrequestid { get; set; }
        public decimal xjp_caliamount { get; set; }
        public string xjp_registrationresultperiod { get; set; }
        public string xjp_platenumbersegment3 { get; set; }
        public string xjp_userprovinceidname { get; set; }
        public decimal xjp_miscellaneouschargetotal { get; set; }
        public bool xjp_rentalvehicle { get; set; }
        public string xjp_ownervillageandaddressidname { get; set; }
        public bool xjp_registrationcardeliveryagency { get; set; }
        public string xjp_ownerprovinceidname { get; set; }
        public bool xjp_agencycalipayment { get; set; }
        public decimal xjp_automobiletaxamount_base { get; set; }
        public string xjp_registrationpurpose { get; set; }
        public bool xjp_lightcharacterplatetype { get; set; }
        public string xjp_handling { get; set; }
        public Guid xjp_recognizedmodelid { get; set; }
        public string xjp_ownerhaveothercarname { get; set; }
        public string xjp_rejectname { get; set; }
        public string xjp_statusname { get; set; }
        public bool xjp_lightvehicle { get; set; }
        public string xjp_paymentmethodidname { get; set; }
        public decimal xjp_actualweighttaxamount_base { get; set; }
        public Guid xjp_garageprovinceid { get; set; }
        public int xjp_stocknumberlookuptype { get; set; }
        public DateTime modifiedon { get; set; }
        public string modifiedbyyominame { get; set; }
        public Guid createdonbehalfby { get; set; }
        public string xjp_requestedplatenumberproof { get; set; }
        public string xjp_status { get; set; }
        public Guid xjp_platenumbersegment1id { get; set; }
        public string xjp_garagecityidname { get; set; }
        public Guid createdby { get; set; }
        public string xjp_ownertypename { get; set; }
        public string xjp_ribbonsource { get; set; }
        public string xjp_stockinventoryusedvehicleidname { get; set; }
        public string xjp_parkingplaceownersamewiththeuser { get; set; }
        public Guid xjp_productstyleid { get; set; }
        public string msdyn_companycode { get; set; }
    }
}
