#region Summary
// ===========================================================================
// AUTHOR        : BSI Code Generator
// PURPOSE       : VWI_CRM_xts_goodsreceiptferenceDto  class
// SPECIAL NOTES : DNet WebApi Project
// ---------------------
// Copyright  (c) 2018 
// ---------------------
// $History      : $
// Created on 2021-01-05 08:26:00
//
// ===========================================================================	
#endregion

#region Namespace Imports
using System;
#endregion

namespace KTB.DNet.Interface.Model
{
    public class VWI_CRM_xts_goodsreceiptDto : DtoBase
    {
        public string company { get; set; }
        public string businessunitcode { get; set; }
        public Guid xts_goodsreceiptid { get; set; }
        public Guid xjp_weighttaxid { get; set; }
        public decimal xjp_standardmarketsellingprice { get; set; }
        public string owneridname { get; set; }
        public Guid xjp_initialassessmentbusinessunitid { get; set; }
        public string modifiedonbehalfbyname { get; set; }
        public DateTime overriddencreatedon { get; set; }
        public decimal xts_purchasepricebaseamount_base { get; set; }
        public decimal xjp_finaltotaldeposit { get; set; }
        public decimal xjp_initialassessmenttradeinamount { get; set; }
        public decimal xjp_initialthecapitalmanagementcharge_base { get; set; }
        public string xjp_initialairbagequipmentname { get; set; }
        public int xjp_finalassessmentmileage { get; set; }
        public string xjp_finalairbagequipment { get; set; }
        public string xjp_initialassessmentpicidname { get; set; }
        public string transactioncurrencyidname { get; set; }
        public string xjp_useridyominame { get; set; }
        public decimal xts_purchaseprice_base { get; set; }
        public string xjp_taxpaymentcertificatename { get; set; }
        public string xts_vehiclemodelidname { get; set; }
        public string xts_parentbusinessunitidname { get; set; }
        public Guid xts_siteid { get; set; }
        public string xjp_finalrecyclingobjectsname { get; set; }
        public decimal xjp_automobiletaxamount { get; set; }
        public Guid processid { get; set; }
        public string xts_hasapvoucher { get; set; }
        public decimal xjp_initialassessmenttradeinamount_base { get; set; }
        public Guid createdonbehalfby { get; set; }
        public decimal xts_purchasepricebaseamount { get; set; }
        public string xts_goodsreceiptclassification { get; set; }
        public string xjp_initialfluorocarbonequipmentname { get; set; }
        public decimal xjp_initialshredderdustfee { get; set; }
        public decimal xjp_finalassessmenttradeinamount_base { get; set; }
        public string xjp_initialfluorocarbonclassificationname { get; set; }
        public string xjp_initialairbagequipment { get; set; }
        public Guid xts_consumptiontaxid { get; set; }
        public string xjp_comment { get; set; }
        public bool xjp_transferbook { get; set; }
        public string xjp_recyclingticketname { get; set; }
        public string owneridtype { get; set; }
        public decimal xjp_finalassessmentpricemeter { get; set; }
        public decimal xjp_initialpurchaseprice_base { get; set; }
        public bool xjp_calichangeapprovalbill { get; set; }
        public Guid owninguser { get; set; }
        public string createdonbehalfbyname { get; set; }
        public decimal xjp_finaltotalnondeposit_base { get; set; }
        public string xts_assessmentcompletionstatusname { get; set; }
        public string xjp_theletterofattorneyname { get; set; }
        public DateTime xts_transactiondate { get; set; }
        public decimal xjp_standardmarketsellingprice_base { get; set; }
        public string xts_supplieridyominame { get; set; }
        public string xjp_finalfluorocarbonclassificationname { get; set; }
        public string xjp_finalassessmentbusinessunitidname { get; set; }
        public decimal xjp_initialshredderdustfee_base { get; set; }
        public string xts_usedvehiclesalesorderlookupname { get; set; }
        public string xjp_officiallyregisteredsealname { get; set; }
        public string xts_consumptiontax { get; set; }
        public bool xjp_finalendoflifevehicle { get; set; }
        public decimal xjp_vehicleschedulecost_base { get; set; }
        public string xts_personinchargeidname { get; set; }
        public decimal xjp_initialassessmentmanualmeasure3_base { get; set; }
        public decimal xjp_storecost { get; set; }
        public Guid xjp_antiqueledgerid { get; set; }
        public string xjp_weighttaxidname { get; set; }
        public decimal xjp_initialtotaldeposit { get; set; }
        public string xts_hasapvouchername { get; set; }
        public decimal xjp_initialairbagdepositedamount { get; set; }
        public string xjp_useridname { get; set; }
        public string xjp_finaldepositedpaymentcategoryname { get; set; }
        public int timezoneruleversionnumber { get; set; }
        public Guid modifiedby { get; set; }
        public decimal xjp_finalfluorocarbondepositedamount { get; set; }
        public Guid xts_vehicletransactionhistoryid { get; set; }
        public decimal xjp_initialassessmentmanualmeasure1_base { get; set; }
        public Guid modifiedonbehalfby { get; set; }
        public string owneridyominame { get; set; }
        public decimal xjp_vehicleschedulecost { get; set; }
        public DateTime xjp_documentcompleteddate { get; set; }
        public string xts_handlingname { get; set; }
        public bool xjp_initialendoflifevehicle { get; set; }
        public string xjp_antiqueledgeridname { get; set; }
        public Guid owningteam { get; set; }
        public Guid xjp_ownerid { get; set; }
        public string xts_goodsreceiptnumber { get; set; }
        public string xjp_initialassessmentgoodsreceiptclassify { get; set; }
        public Guid xts_businessunitid { get; set; }
        public DateTime xjp_documenteffectivedate { get; set; }
        public string xjp_consumptiontaxcategory { get; set; }
        public string xjp_finalairbagequipmentname { get; set; }
        public string xts_newvehiclesalesorderidname { get; set; }
        public string xjp_selection { get; set; }
        public decimal xts_sellingprice_base { get; set; }
        public bool xjp_theletterofattorney { get; set; }
        public decimal xjp_initialassessmentnewcarmeasure_base { get; set; }
        public decimal xjp_finalpurchaseprice { get; set; }
        public string xjp_initialassessmentgoodsreceiptclassifyname { get; set; }
        public string createdbyyominame { get; set; }
        public string xjp_carinspectioninstruction { get; set; }
        public string xjp_documentcompletionstatusname { get; set; }
        public DateTime createdon { get; set; }
        public decimal xjp_finalassessmenttradeinamount { get; set; }
        public string xts_locking { get; set; }
        public string xts_firstyearregistration { get; set; }
        public string xts_stockidname { get; set; }
        public decimal xjp_finalinformationmanagementcharge_base { get; set; }
        public string xjp_consumptiontaxcategoryname { get; set; }
        public string xjp_automobiletaxidname { get; set; }
        public int xts_guaranteemileage { get; set; }
        public string xjp_finalfluorocarbonequipmentname { get; set; }
        public int xjp_initialassessmentmileagebeforeexchanges { get; set; }
        public decimal xjp_finalassessmentnewcarmeasure { get; set; }
        public string xjp_redeemname { get; set; }
        public decimal exchangerate { get; set; }
        public decimal xjp_initialassessmentmanualmeasure1 { get; set; }
        public decimal xjp_initialassessmentmanualmeasure2 { get; set; }
        public decimal xjp_initialassessmentmanualmeasure3 { get; set; }
        public decimal xts_wholesaleprice_base { get; set; }
        public decimal xjp_initialassessmentnewcarmeasure { get; set; }
        public Guid xts_stockid { get; set; }
        public decimal xjp_finalassessmentnewcarmeasure_base { get; set; }
        public decimal xjp_finalairbagdepositedamount { get; set; }
        public decimal xjp_finalassessmentmanualmeasure1_base { get; set; }
        public string xjp_owneridyominame { get; set; }
        public Guid xts_newvehiclesalesorderid { get; set; }
        public DateTime xts_warrantyperiod { get; set; }
        public string xts_goodsreceiptclassificationname { get; set; }
        public string xjp_idempotentmessage { get; set; }
        public decimal xjp_initialfluorocarbondepositedamount_base { get; set; }
        public string xjp_initialdepositedpaymentcategory { get; set; }
        public DateTime xjp_finalassessmentdate { get; set; }
        public string xjp_finalassessmentgoodsreceiptclassification { get; set; }
        public string xjp_newcarguaranteesuccession { get; set; }
        public decimal xjp_finalshredderdustfee { get; set; }
        public string xjp_firstyearregistrationjapan { get; set; }
        public DateTime xts_carinspectionexpirationdate { get; set; }
        public decimal xjp_storecost_base { get; set; }
        public Guid xjp_automobiletaxid { get; set; }
        public int statuscode { get; set; }
        public Guid xts_supplierid { get; set; }
        public decimal xts_consumptiontaxamount { get; set; }
        public int xjp_initialassessmentmileage { get; set; }
        public string xjp_initialrecyclingobjectsname { get; set; }
        public Guid xts_locationid { get; set; }
        public string xjp_initialrecyclingobject { get; set; }
        public Guid xts_warrantytypeid { get; set; }
        public Guid xts_initialassessmentid { get; set; }
        public string xjp_finalfluorocarbonclassification { get; set; }
        public Guid xts_salesorderid { get; set; }
        public Guid xts_finalassessmentid { get; set; }
        public string xts_initialassessmentidname { get; set; }
        public string xjp_carinspectionexpirationdatejapan { get; set; }
        public DateTime xts_suppliervendorinvoicedate { get; set; }
        public Guid owningbusinessunit { get; set; }
        public Guid xts_personinchargeid { get; set; }
        public string xjp_transferbookname { get; set; }
        public Guid xjp_finalassessmentbusinessunitid { get; set; }
        public int xjp_laststatus { get; set; }
        public decimal xjp_finalassessmentmanualmeasure1 { get; set; }
        public Guid xjp_userid { get; set; }
        public decimal xjp_finalassessmentmanualmeasure3 { get; set; }
        public decimal xjp_finalassessmentmanualmeasure2 { get; set; }
        public string xjp_newcarguaranteesuccessionname { get; set; }
        public string xjp_initialdepositedpaymentcategoryname { get; set; }
        public string xjp_specificproductionyearforuvmireport { get; set; }
        public decimal xjp_finalassessmentmanualmeasure2_base { get; set; }
        public string xts_supplierdescription { get; set; }
        public decimal xjp_finalassessmentpricemeter_base { get; set; }
        public decimal xjp_initialassessmentpricemeter { get; set; }
        public string xjp_initialassessmentrunningmeterexchangename { get; set; }
        public decimal xts_purchasepricetotal_base { get; set; }
        public decimal xjp_finaltotalnondeposit { get; set; }
        public int xts_usedvehiclesalesorderlookuptype { get; set; }
        public string xjp_residentscardname { get; set; }
        public decimal xts_sellingprice { get; set; }
        public string xts_consumptiontaxname { get; set; }
        public decimal xjp_initialassessmentmanualmeasure2_base { get; set; }
        public string xjp_grade { get; set; }
        public bool xjp_compulsoryinsurancecertificate { get; set; }
        public Guid xts_vehiclemodelid { get; set; }
        public Guid xts_parentbusinessunitid { get; set; }
        public int xjp_finalassessmentmileagebeforeexchanges { get; set; }
        public string xjp_salepricecompletionstatusname { get; set; }
        public string xts_handling { get; set; }
        public Guid transactioncurrencyid { get; set; }
        public decimal xjp_finalinformationmanagementcharge { get; set; }
        public string statuscodename { get; set; }
        public bool xjp_automobileinspectioncertificate { get; set; }
        public decimal xts_internalsalesprice_base { get; set; }
        public bool xjp_residentscard { get; set; }
        public string xjp_finalassessmentstatusname { get; set; }
        public decimal xjp_finalairbagdepositedamount_base { get; set; }
        public DateTime modifiedon { get; set; }
        public decimal xts_purchasepricetotal { get; set; }
        public decimal xjp_initialinformationmanagementcharge { get; set; }
        public DateTime xjp_initialassessmentdate { get; set; }
        public string xjp_initialassessmentbusinessunitidname { get; set; }
        public decimal xjp_initialassessmentpricemeter_base { get; set; }
        public decimal xjp_finalpurchaseprice_base { get; set; }
        public Guid xts_exteriorcolorid { get; set; }
        public bool xjp_officiallyregisteredseal { get; set; }
        public string xjp_owneridname { get; set; }
        public string xjp_selectionname { get; set; }
        public string traversedpath { get; set; }
        public string xts_supplieridname { get; set; }
        public string xjp_newvehicleguaranteesuccessionname { get; set; }
        public decimal xjp_finaltotaldeposit_base { get; set; }
        public Guid xjp_initialassessmentpicid { get; set; }
        public string xjp_finalrecyclingobjectname { get; set; }
        public string createdonbehalfbyyominame { get; set; }
        public string statecodename { get; set; }
        public bool xjp_taxpaymentcertificate { get; set; }
        public Guid xjp_nonsalesdeliveryid { get; set; }
        public decimal xts_consumptiontaxamount_base { get; set; }
        public string xjp_incompletedocument1 { get; set; }
        public string xjp_documentcompletionstatus { get; set; }
        public string xjp_incompletedocument2 { get; set; }
        public string xjp_recognizedmodelforuvmireport { get; set; }
        public Guid xjp_finalassessmentpicid { get; set; }
        public Guid ownerid { get; set; }
        public decimal xjp_finalshredderdustfee_base { get; set; }
        public string xts_exteriorcoloridname { get; set; }
        public Guid stageid { get; set; }
        public decimal xjp_finalassessmentmanualmeasure3_base { get; set; }
        public string xjp_finalassessmentrunningmeterexchange { get; set; }
        public string xjp_finaldepositedpaymentcategory { get; set; }
        public string xts_suppliervendorinvoicenumber { get; set; }
        public string xts_warrantytypeidname { get; set; }
        public string xjp_compulsoryinsurancecertificatename { get; set; }
        public decimal xjp_initialtotalnondeposit { get; set; }
        public decimal xjp_automobiletaxamount_base { get; set; }
        public string xjp_initialfluorocarbonequipment { get; set; }
        public Guid xts_warehouseid { get; set; }
        public string xjp_initialassessmentrunningmeterexchange { get; set; }
        public decimal xjp_initialairbagdepositedamount_base { get; set; }
        public string xts_vendoridname { get; set; }
        public string createdbyname { get; set; }
        public string xts_businessunitidname { get; set; }
        public decimal xjp_initialinformationmanagementcharge_base { get; set; }
        public string modifiedbyyominame { get; set; }
        public string xts_siteidname { get; set; }
        public string xts_locationidname { get; set; }
        public string modifiedonbehalfbyyominame { get; set; }
        public Guid createdby { get; set; }
        public string xts_platenumber { get; set; }
        public string xjp_calichangeapprovalbillname { get; set; }
        public decimal xjp_finalthecapitalmanagementcharge { get; set; }
        public string xjp_initialfluorocarbonclassification { get; set; }
        public string xts_vehicletransactionhistoryidname { get; set; }
        public string xjp_newvehicleguaranteesuccession { get; set; }
        public string xjp_finalassessmentstatus { get; set; }
        public string xjp_initialrecyclingobjectname { get; set; }
        public int importsequencenumber { get; set; }
        public string xjp_finalrecyclingobject { get; set; }
        public decimal xts_wholesaleprice { get; set; }
        public int utcconversiontimezonecode { get; set; }
        public string xjp_carinspectioninstructionname { get; set; }
        public string xjp_nonsalesdeliveryidname { get; set; }
        public Guid xts_vendorid { get; set; }
        public string xjp_finalassessmentpicidname { get; set; }
        public string xts_finalassessmentidname { get; set; }
        public decimal xjp_finalthecapitalmanagementcharge_base { get; set; }
        public decimal xts_minimumsalespriceforretail_base { get; set; }
        public bool xjp_recyclingticket { get; set; }
        public decimal xts_internalsalesprice { get; set; }
        public decimal xjp_weighttaxamount { get; set; }
        public decimal xjp_initialfluorocarbondepositedamount { get; set; }
        public string xjp_finalassessmentgoodsreceiptclassificationname { get; set; }
        public Int64 versionnumber { get; set; }
        public bool xjp_redeem { get; set; }
        public string xts_warehouseidname { get; set; }
        public decimal xjp_initialtotalnondeposit_base { get; set; }
        public string xts_salesorderidname { get; set; }
        public decimal xts_minimumsalespriceforretail { get; set; }
        public string xts_status { get; set; }
        public string xjp_finalfluorocarbonequipment { get; set; }
        public string xjp_initialrecyclingobjects { get; set; }
        public string xts_statusname { get; set; }
        public string modifiedbyname { get; set; }
        public decimal xjp_initialthecapitalmanagementcharge { get; set; }
        public string xjp_finalrecyclingobjects { get; set; }
        public string xjp_finalendoflifevehiclename { get; set; }
        public string xts_assessmentcompletionstatus { get; set; }
        public decimal xjp_weighttaxamount_base { get; set; }
        public string xjp_automobileinspectioncertificatename { get; set; }
        public string xjp_initialendoflifevehiclename { get; set; }
        public decimal xts_purchaseprice { get; set; }
        public decimal xjp_finalfluorocarbondepositedamount_base { get; set; }
        public string xjp_salepricecompletionstatus { get; set; }
        public decimal xjp_initialtotaldeposit_base { get; set; }
        public string xjp_finalassessmentrunningmeterexchangename { get; set; }
        public string xts_consumptiontaxidname { get; set; }
        public decimal xjp_initialpurchaseprice { get; set; }
        public string xts_vehicleidentificationnumber { get; set; }
        public int statecode { get; set; }
        public string msdyn_companycode { get; set; }
    }
}
