#region Summary
/*
 ===========================================================================
 AUTHOR        : BSI Code Generator Interface 
 PURPOSE       : CRM_xts_warehouseinquiry class
 SPECIAL NOTES : Generated from database BSIDMS_MMKSI_IF_ACC_DEV
 GENERATED BY  : Ivan
 ---------------------
 Copyright  (c) 2020 
 ---------------------
 $History      : $
 Created on 19 Jan 2021 09:10:04
 ===========================================================================
*/
#endregion


using KTB.DNet.Interface.Model;
using KTB.DNet.Interface.Domain;
using System.Collections.Generic;

namespace KTB.DNet.Interface.BusinessLogic.Interface
{
    public interface ICRM_xts_warehouseinquiryBL : IBaseInterface<CRM_xts_warehouseinquiryParameterDto, CRM_xts_warehouseinquiryFilterDto, CRM_xts_warehouseinquiryDto>
    {
        ResponseBase<List<CRM_xts_warehouseinquiryDto>> ReadList(CRM_xts_warehouseinquiryFilterDto filterDto, int pageSize);
        ResponseBaseCustom<CRM_xts_warehouseinquiryDto> Create(CRM_xts_warehouseinquiryCreateParameterDto paramCreate);
        ResponseBase<List<CRM_xts_warehouseinquiryDto>> BulkCreate(List<CRM_xts_warehouseinquiryCreateParameterDto> lstObjCreate);
        ResponseBaseCustom<CRM_xts_warehouseinquiryDto> Update(CRM_xts_warehouseinquiryUpdateParameterDto paramUpdate);
        ResponseBaseCustom<CRM_xts_warehouseinquiryDto> Delete(CRM_xts_warehouseinquiryDeleteParameterDto paramDelete);
    }
}
