#region Summary
/*
 ===========================================================================
 AUTHOR        : BSI Code Generator Interface 
 PURPOSE       : CRM_xts_newvehiclesalesquote class
 SPECIAL NOTES : Generated from database BSIDMS_MMKSI_IF_ACC_DEV
 GENERATED BY  : Gugun (version : v.1.08)
 ---------------------
 Copyright  (c) 2020 
 ---------------------
 $History      : $
 Created on 02 Sep 2020 19:08:00
 ===========================================================================
*/
#endregion


using KTB.DNet.Interface.Model;
using KTB.DNet.Interface.Domain;
using System.Collections.Generic;

namespace KTB.DNet.Interface.BusinessLogic.Interface
{
    public interface ICRM_xts_newvehiclesalesquoteBL : IBaseInterface<CRM_xts_newvehiclesalesquoteParameterDto, CRM_xts_newvehiclesalesquoteFilterDto, CRM_xts_newvehiclesalesquoteDto>
    {
        ResponseBase<List<CRM_xts_newvehiclesalesquoteDto>> ReadList(CRM_xts_newvehiclesalesquoteFilterDto filterDto, int pageSize);
        ResponseBaseCustom<CRM_xts_newvehiclesalesquoteDto> Create(CRM_xts_newvehiclesalesquoteCreateParameterDto paramCreate);
        ResponseBase<List<CRM_xts_newvehiclesalesquoteDto>> BulkCreate(List<CRM_xts_newvehiclesalesquoteCreateParameterDto> lstObjCreate);
        ResponseBaseCustom<CRM_xts_newvehiclesalesquoteDto> Update(CRM_xts_newvehiclesalesquoteUpdateParameterDto paramUpdate);
        ResponseBaseCustom<CRM_xts_newvehiclesalesquoteDto> Delete(CRM_xts_newvehiclesalesquoteDeleteParameterDto paramDelete);
    }
}
