#region Summary
/*
 ===========================================================================
 AUTHOR        : BSI Code Generator Interface 
 PURPOSE       : CRM_xts_product class
 SPECIAL NOTES : Generated from database BSIDMS_MMKSI_IF_ACC_DEV
 GENERATED BY  : Ivan
 ---------------------
 Copyright  (c) 2020 
 ---------------------
 $History      : $
 Created on 18 Jan 2021 15:54:16
 ===========================================================================
*/
#endregion


using KTB.DNet.Interface.Model;
using KTB.DNet.Interface.Domain;
using System.Collections.Generic;

namespace KTB.DNet.Interface.BusinessLogic.Interface
{
    public interface ICRM_xts_productBL : IBaseInterface<CRM_xts_productParameterDto, CRM_xts_productFilterDto, CRM_xts_productDto>
    {
        ResponseBase<List<CRM_xts_productDto>> ReadList(CRM_xts_productFilterDto filterDto, int pageSize);
        ResponseBaseCustom<CRM_xts_productDto> Create(CRM_xts_productCreateParameterDto paramCreate);
        ResponseBase<List<CRM_xts_productDto>> BulkCreate(List<CRM_xts_productCreateParameterDto> lstObjCreate);
        ResponseBaseCustom<CRM_xts_productDto> Update(CRM_xts_productUpdateParameterDto paramUpdate);
        ResponseBaseCustom<CRM_xts_productDto> Delete(CRM_xts_productDeleteParameterDto paramDelete);
    }
}
