#region Summary
/*
 ===========================================================================
 AUTHOR        : BSI Code Generator Interface 
 PURPOSE       : CRM_xts_workorder class
 SPECIAL NOTES : Generated from database BSIDMS_MMKSI_IF_ACC_DEV
 GENERATED BY  : Fika
 ---------------------
 Copyright  (c) 2020 
 ---------------------
 $History      : $
 Created on 01 Sep 2020 19:46:39
 ===========================================================================
*/
#endregion


using KTB.DNet.Interface.Model;
using KTB.DNet.Interface.Domain;
using System.Collections.Generic;

namespace KTB.DNet.Interface.BusinessLogic.Interface
{
    public interface ICRM_xts_workorderBL : IBaseInterface<CRM_xts_workorderParameterDto, CRM_xts_workorderFilterDto, CRM_xts_workorderDto>
    {
        ResponseBase<List<CRM_xts_workorderDto>> ReadList(CRM_xts_workorderFilterDto filterDto, int pageSize);
        ResponseBaseCustom<CRM_xts_workorderDto> Create(CRM_xts_workorderCreateParameterDto paramCreate);
        ResponseBase<List<CRM_xts_workorderDto>> BulkCreate(List<CRM_xts_workorderCreateParameterDto> lstObjCreate);
        ResponseBaseCustom<CRM_xts_workorderDto> Update(CRM_xts_workorderUpdateParameterDto paramUpdate);
        ResponseBaseCustom<CRM_xts_workorderDto> Delete(CRM_xts_workorderDeleteParameterDto paramDelete);
    }
}
