#region Summary
/*
 ===========================================================================
 AUTHOR        : BSI Code Generator Interface 
 PURPOSE       : CRM_xts_purchaseorder class
 SPECIAL NOTES : Generated from database BSIDMS_MMKSI_IF_ACC_DEV
 GENERATED BY  : Khalil
 ---------------------
 Copyright  (c) 2020 
 ---------------------
 $History      : $
 Created on 01 Sep 2020 15:23:00
 ===========================================================================
*/
#endregion


using KTB.DNet.Interface.Model;
using KTB.DNet.Interface.Domain;
using System.Collections.Generic;

namespace KTB.DNet.Interface.BusinessLogic.Interface
{
    public interface ICRM_xts_purchaseorderBL : IBaseInterface<CRM_xts_purchaseorderParameterDto, CRM_xts_purchaseorderFilterDto, CRM_xts_purchaseorderDto>
    {
        ResponseBase<List<CRM_xts_purchaseorderDto>> ReadList(CRM_xts_purchaseorderFilterDto filterDto, int pageSize);
        ResponseBaseCustom<CRM_xts_purchaseorderDto> Create(CRM_xts_purchaseorderCreateParameterDto paramCreate);
        ResponseBase<List<CRM_xts_purchaseorderDto>> BulkCreate(List<CRM_xts_purchaseorderCreateParameterDto> lstObjCreate);
        ResponseBaseCustom<CRM_xts_purchaseorderDto> Update(CRM_xts_purchaseorderUpdateParameterDto paramUpdate);
        ResponseBaseCustom<CRM_xts_purchaseorderDto> Delete(CRM_xts_purchaseorderDeleteParameterDto paramDelete);
    }
}
