INSERT INTO [APIUser]
           ([FirstName]
           ,[LastName]
           ,[Street1]
           ,[Street2]
           ,[Street3]
           ,[City]
           ,[State]
           ,[PostalCode]
           ,[Country]
           ,[Company]
           ,[Status]
           ,[IsActive]
           ,[DealerId]
           ,[CreatedBy]
           ,[CreatedTime]
           ,[UpdatedBy]
           ,[UpdatedTime]
           ,[Email]
           ,[EmailConfirmed]
           ,[PasswordHash]
           ,[SecurityStamp]
           ,[PhoneNumber]
           ,[PhoneNumberConfirmed]
           ,[TwoFactorEnabled]
           ,[LockoutEndDateUtc]
           ,[LockoutEnabled]
           ,[AccessFailedCount]
           ,[UserName])
OUTPUT INSERTED.ID
     VALUES
           (@FirstName
           ,@LastName
           ,@Street1
           ,@Street2
           ,@Street3
           ,@City
           ,@State
           ,@PostalCode
           ,@Country
           ,@Company
           ,@Status
           ,@IsActive
           ,@DealerId
           ,@CreatedBy
           ,@CreatedTime
           ,@UpdatedBy
           ,@UpdatedTime
           ,@Email
           ,@EmailConfirmed
           ,@PasswordHash
           ,@SecurityStamp
           ,@PhoneNumber
           ,@PhoneNumberConfirmed
           ,@TwoFactorEnabled
           ,@LockoutEndDateUtc
           ,@LockoutEnabled
           ,@AccessFailedCount
           ,@UserName);