SELECT [Id]
      ,[ClientUserId]
      ,[PermissionId]
      ,[IsCustomPermission]
      ,[IsDismantledPermission]
      ,[CreatedBy]
      ,[CreatedTime]
      ,[UpdatedBy]
      ,[UpdatedTime]
FROM [APIUserPermission]
WHERE Id = @Id