SELECT [AppId]
      ,[Name]
      ,[DeploymentJenkinsJobName]
      ,[DeploymentBackupFolder]
      ,[CreatedBy]
      ,[CreatedTime]
      ,[UpdatedBy]
      ,[UpdatedTime]
  FROM [MsApplication]
WHERE AppId = @Id