SELECT [Id]
    ,[Username]
    ,[Endpoint]
    ,[Activity]
    ,[ActivityTime]
    ,[ActivityDesc]
    ,[DealerCode]
    ,[AppId]
    ,[CreatedBy]
    ,[CreatedTime]
    ,[UpdatedBy]
    ,[UpdatedTime]
FROM [UserActivity]
WHERE Id = @Id