/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [ID]
      ,[MainDealerID]
      ,[DealerCode]
      ,[DealerName]
      ,[Status]
      ,[Title]
      ,[SearchTerm1]
      ,[SearchTerm2]
      ,[DealerGroupID]
      ,[Address]
      ,[CityID]
      ,[ZipCode]
      ,[ProvinceID]
      ,[Phone]
      ,[Fax]
      ,[Website]
      ,[Email]
      ,[SalesUnitFlag]
      ,[ServiceFlag]
      ,[SparepartFlag]
      ,[Area1ID]
      ,[Area2ID]
      ,[SPANumber]
      ,[SPADate]
      ,[FreePPh22Indicator]
      ,[FreePPh22From]
      ,[FreePPh22To]
      ,[LegalStatus]
      ,[DueDate]
      ,[AgreementNo]
      ,[AgreementDate]
      ,[CreditAccount]
      ,[MainAreaID]
      ,[RowStatus]
      ,[CreatedBy]
      ,[CreatedTime]
      ,[LastUpdateBy]
      ,[LastUpdateTime]
  FROM [Dealer]
  WHERE RowStatus = 0