#region Summary
/*
 ===========================================================================
 AUTHOR        : BSI Code Generator Interface 
 PURPOSE       : CRM_xts_workorder class
 SPECIAL NOTES : Generated from database BSIDMS_MMKSI_IF_ACC_GOLIVE
 GENERATED BY  : Admin
 ---------------------
 Copyright  (c) 2020 
 ---------------------
 $History      : $
 Created on 12 Apr 2021 22:04:42
 ===========================================================================
*/
#endregion

using System;

namespace KTB.DNet.Interface.Domain
{
    public class CRM_xts_workorder
    {
        
		public Guid xts_servicetemplatevehiclepriceclassid { get; set; }

		public DateTime? ktb_tanggalterbitspk { get; set; }

		public decimal? xts_exchangerate { get; set; }

		public decimal? xts_paymentreceivedamount { get; set; }

		public string xts_originalcustomeridname { get; set; }

		public decimal? xts_esttotalmiscchargetaxamount_base { get; set; }

		public string xts_arrivalpatternname { get; set; }

		public string ktb_statusinterface { get; set; }

		public DateTime? xts_transactiondate { get; set; }

		public string statuscodename { get; set; }

		public decimal? xts_totalothersalestaxnotallocated { get; set; }

		public Guid owninguser { get; set; }

		public decimal? xts_totalothersalesbasenotallocated { get; set; }

		public decimal? ktb_totalsubmaterialamount_base { get; set; }

		public string ktb_interfacehandlingname { get; set; }

		public string xts_customeridname { get; set; }

		public string xts_checkstockagainstname { get; set; }

		public string xts_handlingname { get; set; }

		public string xts_modelspecificationnumber { get; set; }

		public string xts_checkstockagainst { get; set; }

		public string xts_parentbusinessunitidname { get; set; }

		public Guid xts_dimension4id { get; set; }

		public string xts_dslinternalnumber { get; set; }

		public string xts_servicetemplatevehiclepriceclassidname { get; set; }

		public string modifiedbyname { get; set; }

		public decimal? xts_totalothersalestaxallocated_base { get; set; }

		public string owneridtype { get; set; }

		public Guid xts_dimension9id { get; set; }

		public decimal? xts_totalworkallocated_base { get; set; }

		public Guid xts_businessunitid { get; set; }

		public string xts_pickupaddress2 { get; set; }

		public decimal? xts_totalwithholdingtaxnotallocated_base { get; set; }

		public string ktb_vehiclestate { get; set; }

		public bool? ktb_isfreebilltocustomer { get; set; }

		public decimal? xts_totalmiscchargetaxnotallocated_base { get; set; }

		public int? ktb_panel { get; set; }

		public decimal? xts_esttotalbaseamount_base { get; set; }

		public decimal? xts_totalpartsamount_base { get; set; }

		public string xts_downpaymentispaidname { get; set; }

		public string ktb_contactmobilephonenumber { get; set; }

		public Guid xts_dimension10id { get; set; }

		public string xts_deliveryaddress2 { get; set; }

		public Guid xts_vehicleidentificationid { get; set; }

		public Guid xts_incomingoutsourcereferenceid { get; set; }

		public DateTime? ktb_fullpaymentdate { get; set; }

		public decimal? xts_totalpartsnotallocated_base { get; set; }

		public decimal? xts_totalmiscchargetaxnotallocated { get; set; }

		public decimal? xts_totalpartstaxallocated { get; set; }

		public decimal? xts_esttotalbaseamount { get; set; }

		public Guid xts_servicecategoryid { get; set; }

		public Guid xts_exchangeratetypeid { get; set; }

		public string xjp_originaloutsorcereferencepdiidname { get; set; }

		public string ktb_statusinterfaceassistpartsalesdnetname { get; set; }

		public string xts_dimension3idname { get; set; }

		public string ktb_statusinterfacefreeservicednetname { get; set; }

		public int? xts_meterexchangemileage { get; set; }

		public string ktb_cogsupdatedname { get; set; }

		public string ktb_methodofpaymentidname { get; set; }

		public string xts_ordertypeidname { get; set; }

		public DateTime? xts_scheduledservicefinishdateandtime { get; set; }

		public string xts_chassismodel { get; set; }

		public string ktb_workorderdescription { get; set; }

		public Guid xts_reservationid { get; set; }

		public int? timezoneruleversionnumber { get; set; }

		public string createdonbehalfbyyominame { get; set; }

		public decimal? xts_esttotalothersalesamount { get; set; }

		public string xts_registrationmodel { get; set; }

		public decimal? xts_totalpartsallocated { get; set; }

		public decimal? xts_totalworkallocated { get; set; }

		public decimal? xts_downpaymentamountreceived_base { get; set; }

		public string xts_mainpartcauseidname { get; set; }

		public Guid ownerid { get; set; }

		public string ktb_mechanicalleaderemployeeidname { get; set; }

		public Guid xts_dimension8id { get; set; }

		public decimal? xts_totalworkbaseamount { get; set; }

		public decimal? xts_esttotalmiscchargebaseamount_base { get; set; }

		public bool? xts_warrantycontractavailable { get; set; }

		public Guid modifiedonbehalfby { get; set; }

		public string xts_servicepackagecontractavailablename { get; set; }

		public Guid xts_dimension6id { get; set; }

		public Guid owningteam { get; set; }

		public string ktb_isinsurancename { get; set; }

		public string ktb_statusinterfacednetname { get; set; }

		public decimal? xts_totalothersalesbaseamount_base { get; set; }

		public decimal? xts_totalwithholdingtaxallocated { get; set; }

		public string xts_vehicleincludedintherecallname { get; set; }

		public decimal? xts_totalpartsbaseamount_base { get; set; }

		public string xts_readytobeinvoiced { get; set; }

		public decimal? xts_esttotalothersalesbaseamount { get; set; }

		public decimal? xts_totalwithholdingtaxamount { get; set; }

		public string xts_vehicleidentificationidname { get; set; }

		public Guid xts_customerid { get; set; }

		public string xts_pickupaddress3 { get; set; }

		public string xts_manufacturername { get; set; }

		public string owneridyominame { get; set; }

		public decimal? ktb_totalsubmaterialamount { get; set; }

		public Guid xts_parentbusinessunitid { get; set; }

		public string xts_billallocationmethodname { get; set; }

		public decimal? xts_grandtotalallocated_base { get; set; }

		public string xts_serviceadvisoridname { get; set; }

		public string createdbyyominame { get; set; }

		public Guid stageid { get; set; }

		public string xts_deliveryaddress3 { get; set; }

		public bool? xts_overcreditlimitonhold { get; set; }

		public string xts_vehiclesizeclassidname { get; set; }

		public Guid xts_ordertypeid { get; set; }

		public decimal? xts_totalwithholdingtax2notallocated_base { get; set; }

		public string ktb_formsprosurveyinvitationidname { get; set; }

		public decimal? ktb_grandtotalinformationdetail { get; set; }

		public decimal? ktb_grandtotalinformationdetail_base { get; set; }

		public decimal? xts_totalworktaxnotallocated_base { get; set; }

		public string xts_workorder { get; set; }

		public string xts_workgroupidname { get; set; }

		public decimal? xts_totalworktaxallocated_base { get; set; }

		public string ktb_workordermemo { get; set; }

		public string ktb_svcincominginterfacestatus { get; set; }

		public string xts_pickuppostalcode { get; set; }

		public string xts_vehiclemodelname { get; set; }

		public Guid owningbusinessunit { get; set; }

		public Guid xts_globalserviceid { get; set; }

		public string xts_productsegment3idname { get; set; }

		public DateTime? xts_scheduledservicestartdateandtime { get; set; }

		public int? ktb_countprintinvoice { get; set; }

		public bool? xts_vehicleincludedintherecall { get; set; }

		public Guid ktb_servicetypeid { get; set; }

		public string xts_warrantycontractavailablename { get; set; }

		public decimal? xts_totalmiscchargebaseamount { get; set; }

		public string ktb_contactidname { get; set; }

		public bool? ktb_isprintgatepassreadytobeinvoice { get; set; }

		public decimal? xts_totalworkbaseallocated { get; set; }

		public string xts_servicecategorydescription { get; set; }

		public string xts_originaloutsorcereferenceoutsourcewoidname { get; set; }

		public decimal? xts_estgrandtotalamount_base { get; set; }

		public Guid xts_loadinggroupid { get; set; }

		public string xts_handling { get; set; }

		public string ktb_statusinterfaceregcheckdnetname { get; set; }

		public int? xts_originaloutsorcereferencelookuptype { get; set; }

		public Guid xts_productsegment2id { get; set; }

		public decimal? xts_totalothersalesnotallocated_base { get; set; }

		public Guid xts_incomingoutsourcebusinessunitid { get; set; }

		public long? versionnumber { get; set; }

		public Guid xts_originalcustomerid { get; set; }

		public decimal? xts_grandtotalnotallocated { get; set; }

		public string xts_queuestatus { get; set; }

		public Guid xjp_originaloutsorcereferencepdiid { get; set; }

		public string ktb_saleschannelidname { get; set; }

		public string xts_reservationidname { get; set; }

		public decimal? ktb_totalpartamount_base { get; set; }

		public decimal? xts_reservationmanhour { get; set; }

		public string xts_referencenumberlookupname { get; set; }

		public string xts_symptomcauseidname { get; set; }

		public decimal? xts_esttotalpartstaxamount_base { get; set; }

		public string xts_productidname { get; set; }

		public Guid xts_productsegment3id { get; set; }

		public decimal? xts_esttotalwithholdingtaxamount_base { get; set; }

		public decimal? xts_totalothersalesamount { get; set; }

		public DateTime? ktb_wodate { get; set; }

		public string xts_originaloutsorcereferencelookupname { get; set; }

		public string ktb_panelcategoryname { get; set; }

		public decimal? xts_downpaymentamountreceived { get; set; }

		public Guid xts_servicetemplateid { get; set; }

		public Guid xts_billtocustomerid { get; set; }

		public string xts_platenumber { get; set; }

		public decimal? xts_totalpaymentamount_base { get; set; }

		public string xts_billtocustomeridname { get; set; }

		public decimal? xts_totalworkamount_base { get; set; }

		public string xts_isworkorderformname { get; set; }

		public decimal? xjp_caliamount_base { get; set; }

		public decimal? xts_totalothersalesamount_base { get; set; }

		public decimal? xjp_calinotallocated_base { get; set; }

		public string xts_customernumber { get; set; }

		public decimal? xts_totalmiscchargenotallocated_base { get; set; }

		public string ktb_eventdata { get; set; }

		public decimal? xts_esttotalpartstaxamount { get; set; }

		public DateTime? xjp_caliexpirationdate { get; set; }

		public Guid xts_productsegment1id { get; set; }

		public string ktb_liststatusinterface { get; set; }

		public string transactioncurrencyidname { get; set; }

		public string xts_manufactureridname { get; set; }

		public string ktb_ordertypetranstype { get; set; }

		public string xts_workorderstatus { get; set; }

		public decimal? ktb_totalpartamount { get; set; }

		public DateTime? xts_actualservicefinishdateandtime { get; set; }

		public string xts_dimension6idname { get; set; }

		public string ktb_interfacehandlingdnet { get; set; }

		public string createdonbehalfbyname { get; set; }

		public string xts_productdescription { get; set; }

		public string xts_arrivalpattern { get; set; }

		public decimal? xts_totalothersalesallocated_base { get; set; }

		public decimal? xts_totalmiscchargeallocated { get; set; }

		public string xts_technicaladvisoridname { get; set; }

		public string ktb_contactidyominame { get; set; }

		public decimal? xts_totalworktaxallocated { get; set; }

		public string xts_overcreditlimitonholdname { get; set; }

		public decimal? ktb_totalsuborderamount_base { get; set; }

		public string xts_maintenancemodelidname { get; set; }

		public Guid transactioncurrencyid { get; set; }

		public decimal? xts_totalbaseamount_base { get; set; }

		public decimal? xts_esttotaltaxamount { get; set; }

		public Guid xts_originaloutsorcereferenceoutsourcewoid { get; set; }

		public decimal? xts_totalmiscchargebasenotallocated { get; set; }

		public string owneridname { get; set; }

		public decimal? xts_totalmiscchargetaxamount_base { get; set; }

		public decimal? xts_esttotalwithholdingtaxamount { get; set; }

		public string xts_dimension7idname { get; set; }

		public decimal? xts_esttotalworkamount_base { get; set; }

		public string ktb_interfacehandling { get; set; }

		public decimal? xts_totalothersalesbaseallocated { get; set; }

		public bool? xts_isworkorderform { get; set; }

		public decimal? ktb_totalserviceamount_base { get; set; }

		public DateTime? xts_actualarrivaldateandtime { get; set; }

		public decimal? xts_totalwithholdingtaxallocated_base { get; set; }

		public decimal? xts_totalworknotallocated_base { get; set; }

		public decimal? xts_esttotalpartsamount { get; set; }

		public decimal? xts_esttotalpartsbaseamount_base { get; set; }

		public decimal? xts_totalwithholdingtaxnotallocated { get; set; }

		public string xts_dimension10idname { get; set; }

		public Guid xts_salespersonid { get; set; }

		public string xts_finishpattern { get; set; }

		public Guid xts_symptomid { get; set; }

		public decimal? xts_balance_base { get; set; }

		public decimal? xts_esttotalworkbaseamount { get; set; }

		public string xts_deliveryaddress1 { get; set; }

		public Guid xts_maintenancemodelid { get; set; }

		public string xjp_idempotentmessage { get; set; }

		public string ktb_isvalidationfromdnet { get; set; }

		public string xts_classificationnumber { get; set; }

		public decimal? xts_esttotalworktaxamount { get; set; }

		public string xts_contactpersonidname { get; set; }

		public Guid xts_dimension3id { get; set; }

		public decimal? xts_totalmiscchargetaxallocated_base { get; set; }

		public Guid modifiedby { get; set; }

		public decimal? xts_totalworknotallocated { get; set; }

		public decimal? xts_esttotalpartsbaseamount { get; set; }

		public DateTime? xts_actualfinishdateandtime { get; set; }

		public decimal? xts_totalothersalesnotallocated { get; set; }

		public decimal? xts_totaltaxamount_base { get; set; }

		public decimal? xts_totalpartsnotallocated { get; set; }

		public string xts_referralname { get; set; }

		public decimal? xts_totalcostamount { get; set; }

		public Guid xts_manufacturerid { get; set; }

		public bool? xts_servicepackagecontractavailable { get; set; }

		public decimal? xts_totalworkbasenotallocated { get; set; }

		public Guid xts_termofpaymentid { get; set; }

		public decimal? xjp_calinotallocated { get; set; }

		public string xts_readytobeinvoicedname { get; set; }

		public string xts_leaseapprovalnumber { get; set; }

		public string xts_behavior { get; set; }

		public Guid xts_servicecampaignid { get; set; }

		public decimal? ktb_totaloilamount { get; set; }

		public decimal? xts_totalmiscchargeamount_base { get; set; }

		public string ktb_interfacehandlingdnetname { get; set; }

		public string xts_productsegment1idname { get; set; }

		public decimal? xts_totalworkbaseallocated_base { get; set; }

		public string xts_billallocationmethod { get; set; }

		public decimal? xts_grandtotalallocated { get; set; }

		public int? utcconversiontimezonecode { get; set; }

		public string xts_salespersonidname { get; set; }

		public decimal? xjp_caliamount { get; set; }

		public string ktb_ordertypetranstypename { get; set; }

		public decimal? xts_totalpartsbasenotallocated_base { get; set; }

		public decimal? xts_esttotalmiscchargeamount_base { get; set; }

		public Guid ktb_contactid { get; set; }

		public decimal? xts_totalmiscchargebaseallocated_base { get; set; }

		public string ktb_interfacemessage { get; set; }

		public decimal? xts_totalwithholdingtaxamount_base { get; set; }

		public Guid xts_dimension7id { get; set; }

		public string xts_workorderstatusname { get; set; }

		public Guid xts_dimension1id { get; set; }

		public decimal? xts_totalmiscchargebasenotallocated_base { get; set; }

		public string xts_servicetemplateidname { get; set; }

		public string xts_vehiclemodelidname { get; set; }

		public Guid ktb_mechanicalleaderemployeeid { get; set; }

		public bool? xts_autocreateoutsourceworkorderreceipt { get; set; }

		public decimal? xjp_estcaliamount { get; set; }

		public decimal? xts_totalpaymentamount { get; set; }

		public Guid processid { get; set; }

		public string xts_termofpaymentidname { get; set; }

		public bool? xts_downpaymentispaid { get; set; }

		public decimal? xts_esttotalmiscchargeamount { get; set; }

		public DateTime? modifiedon { get; set; }

		public decimal? xts_totalothersalesbasenotallocated_base { get; set; }

		public decimal? xts_esttotalmiscchargebaseamount { get; set; }

		public string xts_productsegment2idname { get; set; }

		public string xts_productsegment4idname { get; set; }

		public string xts_businessunitidname { get; set; }

		public string ktb_panelcategory { get; set; }

		public DateTime? xts_scheduledfinishdateandtime { get; set; }

		public Guid xts_dimension2id { get; set; }

		public string modifiedbyyominame { get; set; }

		public Guid createdonbehalfby { get; set; }

		public Guid xts_originalworkorderreferencenumberid { get; set; }

		public decimal? xts_totalbaseamount { get; set; }

		public DateTime? ktb_estimationfinishdatebysa { get; set; }

		public string ktb_dnetidwotype { get; set; }

		public decimal? xts_totalothersalestaxallocated { get; set; }

		public string xts_originaloutsorcereferencesvcinstructionidname { get; set; }

		public Guid xts_technicaladvisorid { get; set; }

		public Guid ktb_servicelocationid { get; set; }

		public Guid createdby { get; set; }

		public string xts_loadinggroupidname { get; set; }

		public decimal? xts_esttotalothersalesamount_base { get; set; }

		public decimal? xts_esttotalpartsamount_base { get; set; }

		public Guid xts_workgroupid { get; set; }

		public string RowStatus { get; set; }

		public decimal? xts_totalmiscchargeamount { get; set; }

		public Guid xts_contactpersonid { get; set; }

		public string ktb_statusinterfaceassistpartsalesdnet { get; set; }

		public decimal? xts_totalmiscchargebaseallocated { get; set; }

		public Guid xts_vehiclesizeclassid { get; set; }

		public string ktb_isinterfacedname { get; set; }

		public decimal? xts_esttotalothersalesbaseamount_base { get; set; }

		public string modifiedonbehalfbyname { get; set; }

		public int? ktb_countedprint { get; set; }

		public DateTime? overriddencreatedon { get; set; }

		public DateTime? xts_actualservicestartdateandtime { get; set; }

		public string xts_invoicedname { get; set; }

		public Guid xts_dimension5id { get; set; }

		public decimal? xts_totalothersalesbaseallocated_base { get; set; }

		public string ktb_isprintgatepassreadytobeinvoicename { get; set; }

		public Guid xts_symptomcauseid { get; set; }

		public string ktb_isfreebilltocustomername { get; set; }

		public int? importsequencenumber { get; set; }

		public string xts_claimstatusname { get; set; }

		public string xts_pickupaddress4 { get; set; }

		public string xts_queuestatusname { get; set; }

		public string xts_workordermemo { get; set; }

		public string ktb_statusinterfacefreeservicednet { get; set; }

		public decimal? xjp_estcaliamount_base { get; set; }

		public decimal? xts_totalpartsamount { get; set; }

		public decimal? xts_esttotaltaxamount_base { get; set; }

		public string ktb_vehiclestatename { get; set; }

		public decimal? xts_esttotalothersalestaxamount_base { get; set; }

		public decimal? xts_grandtotalamount_base { get; set; }

		public string ktb_say { get; set; }

		public decimal? xts_esttotalworktaxamount_base { get; set; }

		public decimal? xts_totalmiscchargebaseamount_base { get; set; }

		public decimal? xts_totalpartsallocated_base { get; set; }

		public string xts_woinsurancereceiptnumber { get; set; }

		public decimal? xts_esttotalothersalestaxamount { get; set; }

		public string xts_incomingoutsourcebusinessunitidname { get; set; }

		public string xts_siteidname { get; set; }

		public string statecodename { get; set; }

		public decimal? xts_paymentreceivedamount_base { get; set; }

		public decimal? xts_estgrandtotalamount { get; set; }

		public int? xts_lastmileage { get; set; }

		public string ktb_svcincominginterfacestatusname { get; set; }

		public string xts_billtocustomeridyominame { get; set; }

		public string ktb_origworkordernumber { get; set; }

		public string xts_dimension5idname { get; set; }

		public Guid xts_originaloutsorcereferencesvcinstructionid { get; set; }

		public string xts_araccountidname { get; set; }

		public bool? xts_invoiced { get; set; }

		public string xts_deliverypostalcode { get; set; }

		public string xts_originalworkorderreferencenumberidname { get; set; }

		public Guid ktb_paneltypeid { get; set; }

		public Guid xts_productid { get; set; }

		public decimal? xts_totalpartstaxamount_base { get; set; }

		public string traversedpath { get; set; }

		public decimal? xts_totalcostamount_base { get; set; }

		public decimal? xjp_caliallocated { get; set; }

		public decimal? xts_totalmiscchargenotallocated { get; set; }

		public string xts_customeridyominame { get; set; }

		public decimal? xts_totalpartsbaseallocated_base { get; set; }

		public string xts_servicepersoninchargeidname { get; set; }

		public decimal? ktb_totalmiscchargeamount { get; set; }

		public decimal? ktb_ownriskamount_base { get; set; }

		public decimal? ktb_totalmiscchargeamount_base { get; set; }

		public string ktb_spknumber { get; set; }

		public decimal? ktb_ownriskamount { get; set; }

		public string xts_servicecampaignidname { get; set; }

		public string xts_incomingoutsourcereferenceidname { get; set; }

		public decimal? xts_totaltaxamount { get; set; }

		public Guid xts_mainpartcauseid { get; set; }

		public decimal? exchangerate { get; set; }

		public decimal? xts_balance { get; set; }

		public string modifiedonbehalfbyyominame { get; set; }

		public string xts_pickupaddress1 { get; set; }

		public DateTime? xts_vehicleinspectionexpirationdate { get; set; }

		public Guid xts_productsegment4id { get; set; }

		public string xts_servicetemplatecalculationmethod { get; set; }

		public string xts_dimension4idname { get; set; }

		public decimal? xts_totalpartsbaseallocated { get; set; }

		public string xts_exchangeratetypeidname { get; set; }

		public decimal? xts_totalworktaxamount_base { get; set; }

		public string ktb_statusinterfacednet { get; set; }

		public Guid xts_workorderreferenceid { get; set; }

		public Guid xts_workorderid { get; set; }

		public string xts_behaviorname { get; set; }

		public string xts_servicetemplatecalculationmethodname { get; set; }

		public string ktb_paneltypeidname { get; set; }

		public Guid ktb_saleschannelid { get; set; }

		public Guid xts_reservationclassid { get; set; }

		public decimal? xts_totalworkbaseamount_base { get; set; }

		public DateTime? xts_insuranceinspectiondate { get; set; }

		public decimal? xts_exchangerateamount { get; set; }

		public string xts_cancelreason { get; set; }

		public DateTime? xts_exchangeratedate { get; set; }

		public string xts_finishpatternname { get; set; }

		public decimal? xts_totalpartstaxnotallocated_base { get; set; }

		public decimal? xts_totalmiscchargeallocated_base { get; set; }

		public string xts_claimapprovalnumber { get; set; }

		public decimal? xjp_caliallocated_base { get; set; }

		public decimal? xts_totalothersalestaxamount_base { get; set; }

		public decimal? xts_totalpartsbaseamount { get; set; }

		public decimal? xts_grandtotalnotallocated_base { get; set; }

		public string ktb_paneldescription { get; set; }

		public decimal? xts_downpaymentamount { get; set; }

		public Guid xts_serviceadvisorid { get; set; }

		public int? xjp_estcaliperiodmonths { get; set; }

		public Guid xts_siteid { get; set; }

		public decimal? xts_esttotalmiscchargetaxamount { get; set; }

		public string xts_dimension9idname { get; set; }

		public string xts_globalserviceidname { get; set; }

		public string ktb_servicelocationidname { get; set; }

		public bool? ktb_validatorhandling { get; set; }

		public decimal? xts_totalmiscchargetaxamount { get; set; }

		public string ktb_servicetypeidname { get; set; }

		public string xts_log { get; set; }

		public string xts_contactpersonphone { get; set; }

		public decimal? ktb_totaloilamount_base { get; set; }

		public string xts_dimension8idname { get; set; }

		public Guid ktb_methodofpaymentid { get; set; }

		public string xts_reservationclassidname { get; set; }

		public string ktb_paneldeskripsi { get; set; }

		public bool? ktb_isinsurance { get; set; }

		public string xjp_firstregistration { get; set; }

		public DateTime? createdon { get; set; }

		public DateTime? xts_invoicepostingdate { get; set; }

		public decimal? xts_totalworktaxamount { get; set; }

		public decimal? xts_totalpartstaxallocated_base { get; set; }

		public decimal? xts_totalothersalesallocated { get; set; }

		public decimal? ktb_totalserviceamount { get; set; }

		public string xts_autocreateoutsourceworkorderreceiptname { get; set; }

		public string xts_aliasname { get; set; }

		public decimal? xts_totalmiscchargetaxallocated { get; set; }

		public string ktb_validatorhandlingname { get; set; }

		public string ktb_statusinterfaceregcheckdnet { get; set; }

		public decimal? ktb_totalsuborderamount { get; set; }

		public string xts_deliveryaddress4 { get; set; }

		public Guid xts_servicepersoninchargeid { get; set; }

		public string ktb_notificationvalidatorservice { get; set; }

		public decimal? xts_esttotalworkbaseamount_base { get; set; }

		public string ktb_dnetidserviceincoming { get; set; }

		public Guid xts_vehiclemodelid { get; set; }

		public string xts_servicecategoryidname { get; set; }

		public int? xts_currentmileage { get; set; }

		public string xts_locking { get; set; }

		public string xts_claimstatus { get; set; }

		public string xts_workorderreferenceidname { get; set; }

		public decimal? xts_totalpartsbasenotallocated { get; set; }

		public string xts_chassisnumber { get; set; }

		public decimal? xts_totalothersalestaxamount { get; set; }

		public string xts_symptomidname { get; set; }

		public bool? ktb_cogsupdated { get; set; }

		public decimal? xts_totalpartstaxnotallocated { get; set; }

		public bool? ktb_isinterfaced { get; set; }

		public int? xts_historymileage { get; set; }

		public string createdbyname { get; set; }

		public decimal? xts_totalworkbasenotallocated_base { get; set; }

		public DateTime? ktb_tanggalinputmerimen { get; set; }

		public string xts_dimension1idname { get; set; }

		public decimal? xts_grandtotalamount { get; set; }

		public decimal? xts_downpaymentamount_base { get; set; }

		public int? statecode { get; set; }

		public Guid xts_araccountid { get; set; }

		public int? statuscode { get; set; }

		public string ktb_notificationvalidatormessage { get; set; }

		public decimal? xts_totalothersalesbaseamount { get; set; }

		public decimal? xts_totalworktaxnotallocated { get; set; }

		public decimal? xts_esttotalworkamount { get; set; }

		public int? xjp_caliperiodmonths { get; set; }

		public decimal? xts_totalpartstaxamount { get; set; }

		public decimal? xts_totalothersalestaxnotallocated_base { get; set; }

		public decimal? xts_totalworkamount { get; set; }

		public DateTime? xts_scheduledarrivaldateandtime { get; set; }

		public string xts_dimension2idname { get; set; }

		public string xts_originalcustomeridyominame { get; set; }

		public string xts_contactpersonidyominame { get; set; }

		public DateTime? xts_accidentdate { get; set; }

		public decimal? xts_totalwithholdingtax2allocated_base { get; set; }

		public Guid ktb_formsprosurveyinvitationid { get; set; }

		public string ktb_approvedcreditlimitreason { get; set; }

		public string ktb_approvedcreditlimitbyname { get; set; }

		public string ktb_approvedcreditlimitbyyominame { get; set; }

		public decimal? xts_totalwithholdingtax2notallocated { get; set; }

		public Guid ktb_approvedcreditlimitby { get; set; }

		public decimal? xts_totalwithholdingtax2allocated { get; set; }

		public string DealerCode { get; set; }

		public string SourceType { get; set; }

		public string ktb_externalcode { get; set; }

		public bool ktb_isinbound { get; set; }
		public Guid ktb_mechanic { get; set; }

	}
}
