#region Summary
/*
 ===========================================================================
 AUTHOR        : BSI Code Generator Interface 
 PURPOSE       : CRM_xts_purchaserequisitiondetail class
 SPECIAL NOTES : Generated from database BSIDMS_MMKSI_IF_ACC_GOLIVE
 GENERATED BY  : Admin
 ---------------------
 Copyright  (c) 2020 
 ---------------------
 $History      : $
 Created on 12 Apr 2021 21:53:50
 ===========================================================================
*/
#endregion

using System;

namespace KTB.DNet.Interface.Domain
{
    public class CRM_xts_purchaserequisitiondetail
    {
        
		public string modifiedonbehalfbyname { get; set; }

		public string xts_productexteriorcoloridname { get; set; }

		public string xts_productconfigurationidname { get; set; }

		public decimal? xts_discountamount_base { get; set; }

		public bool? xts_closeline { get; set; }

		public decimal? xts_discountpercentage { get; set; }

		public Guid xts_productid { get; set; }

		public Guid transactioncurrencyid { get; set; }

		public Guid createdby { get; set; }

		public Guid modifiedby { get; set; }

		public string ktb_productname { get; set; }

		public Guid xts_purchaseunitid { get; set; }

		public string xts_parentbusinessunitidname { get; set; }

		public string createdbyyominame { get; set; }

		public Guid owninguser { get; set; }

		public string transactioncurrencyidname { get; set; }

		public bool? ktb_isconversion { get; set; }

		public Guid xts_requestedbyid { get; set; }

		public decimal? xts_basequantityorder { get; set; }

		public Guid owningbusinessunit { get; set; }

		public string modifiedbyyominame { get; set; }

		public decimal? xts_consumptiontax1amount { get; set; }

		public decimal? xts_consumptiontax2amount_base { get; set; }

		public decimal? xts_transactionamount { get; set; }

		public DateTime? xts_requireddate { get; set; }

		public decimal? xts_totalamount { get; set; }

		public int? statuscode { get; set; }

		public string modifiedonbehalfbyyominame { get; set; }

		public string xts_siteidname { get; set; }

		public Guid xts_purchaseorderdetailid { get; set; }

		public decimal? xts_totalamountbeforediscount_base { get; set; }

		public decimal? xts_basequantityonpurchaseorder { get; set; }

		public Guid xts_baseunitid { get; set; }

		public string ktb_isapprovedname { get; set; }

		public int? ktb_qtyforecast { get; set; }

		public string xts_productdescription { get; set; }

		public string statecodename { get; set; }

		public string xts_businessunitidname { get; set; }

		public string xts_productstyleidname { get; set; }

		public string RowStatus { get; set; }

		public string xts_productinteriorcoloridname { get; set; }

		public Guid xts_parentbusinessunitid { get; set; }

		public long? versionnumber { get; set; }

		public DateTime? createdon { get; set; }

		public string xts_closelinename { get; set; }

		public Guid ktb_purchaserequisitionid { get; set; }

		public Guid xts_purchaserequisitionid { get; set; }

		public Guid xts_productconfigurationid { get; set; }

		public string xts_requestedbyidname { get; set; }

		public Guid xts_consumptiontax1id { get; set; }

		public string xts_eventdata { get; set; }

		public string statuscodename { get; set; }

		public Guid xts_productinteriorcolorid { get; set; }

		public decimal? xts_quantityonpurchaseorder { get; set; }

		public string xts_description { get; set; }

		public string xts_purchaserequisitiondetail { get; set; }

		public decimal? xts_quantityorder { get; set; }

		public string owneridtype { get; set; }

		public decimal? xts_totalbaseamount_base { get; set; }

		public int? ktb_qty { get; set; }

		public Guid createdonbehalfby { get; set; }

		public string xts_departmentidname { get; set; }

		public string modifiedbyname { get; set; }

		public Guid xts_departmentid { get; set; }

		public DateTime? xts_promisedate { get; set; }

		public string xts_consumptiontax1idname { get; set; }

		public string ktb_isconversionname { get; set; }

		public string owneridname { get; set; }

		public Guid xts_purchaserequisitiondetailid { get; set; }

		public DateTime? overriddencreatedon { get; set; }

		public string ktb_productsap { get; set; }

		public Guid ktb_product { get; set; }

		public string createdonbehalfbyyominame { get; set; }

		public string xts_purchasefor { get; set; }

		public Guid modifiedonbehalfby { get; set; }

		public decimal? exchangerate { get; set; }

		public decimal? xts_totalconsumptiontaxamount_base { get; set; }

		public decimal? xts_transactionamount_base { get; set; }

		public Guid xts_consumptiontax2id { get; set; }

		public Guid owningteam { get; set; }

		public decimal? xts_totalbaseamount { get; set; }

		public string xts_productidname { get; set; }

		public int? statecode { get; set; }

		public decimal? xts_unitcost { get; set; }

		public decimal? xts_consumptiontax1amount_base { get; set; }

		public int? timezoneruleversionnumber { get; set; }

		public string ktb_purchaserequisitionidname { get; set; }

		public Guid xts_productstyleid { get; set; }

		public decimal? xts_totalconsumptiontaxamount { get; set; }

		public string xts_locking { get; set; }

		public decimal? xts_totalamountbeforediscount { get; set; }

		public string xts_purchaseforname { get; set; }

		public decimal? xts_totalamount_base { get; set; }

		public string xts_purchaseorderdetailidname { get; set; }

		public string createdonbehalfbyname { get; set; }

		public string xts_consumptiontax2idname { get; set; }

		public Guid xts_productexteriorcolorid { get; set; }

		public int? utcconversiontimezonecode { get; set; }

		public string xts_baseunitidname { get; set; }

		public decimal? xts_discountamount { get; set; }

		public decimal? xts_unitcost_base { get; set; }

		public Guid ownerid { get; set; }

		public DateTime? modifiedon { get; set; }

		public int? importsequencenumber { get; set; }

		public string owneridyominame { get; set; }

		public bool? ktb_isapproved { get; set; }

		public string xts_closereason { get; set; }

		public string xts_purchaseunitidname { get; set; }

		public string xts_purchaserequisitionidname { get; set; }

		public DateTime? xts_transactiondate { get; set; }

		public Guid xts_siteid { get; set; }

		public string createdbyname { get; set; }

		public decimal? xts_consumptiontax2amount { get; set; }

		public Guid xts_businessunitid { get; set; }

		public string DealerCode { get; set; }

		public string SourceType { get; set; }

    }
}
