SELECT [Id]
      ,[ClientId]
      ,[UserId]
      ,[Token]
      ,[TokenExpired]
      ,[LastActivity]
      ,[LastLogin]
      ,[CreatedBy]
      ,[CreatedTime]
      ,[UpdatedBy]
      ,[UpdatedTime]
FROM [APIClientUser]

