#region Summary
/*
 ===========================================================================
 AUTHOR        : BSI Code Generator Interface 
 PURPOSE       : CRM_xts_inventserial class
 SPECIAL NOTES : Generated from database BSIDMS_MMKSI_IF_ACC_DEV
 GENERATED BY  : Ivan
 ---------------------
 Copyright  (c) 2020 
 ---------------------
 $History      : $
 Created on 05 Feb 2021 13:49:19
 ===========================================================================
*/
#endregion

#region Namespace Imports
using Dapper;
using KTB.DNet.Interface.Domain;
using KTB.DNet.Interface.Framework;
using KTB.DNet.Interface.Repository.Dapper.NonDMS.SqlQuery.CRM_xts_inventserial;
using KTB.DNet.Interface.Repository.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using System.Data.SqlClient;
using System.Reflection;
#endregion

namespace KTB.DNet.Interface.Repository.Dapper.NonDMS
{
    public class CRM_xts_inventserialRepository : BaseDNetRepository<CRM_xts_inventserial>, ICRM_xts_inventserialRepository<CRM_xts_inventserial, int>
    {
        #region Constructor
        public CRM_xts_inventserialRepository(string connectionString)
            : base(connectionString)
        { }
        #endregion

		
        #region Create CRM_xts_inventserial
        public ResponseMessage Create(CRM_xts_inventserial entity)
        {
			
            ResponseMessage responseMessage = new ResponseMessage() { Success = false };

            try
            {
                //SetCreatedLog(entity);
                ExecuteTransaction(Connection, (connection, transaction) =>
                {
                    return connection.Execute(CRM_xts_inventserialQuery.InsertCRM_xts_inventserial, entity, transaction);
                });

                responseMessage.Success = true;
                responseMessage.Status = ResponseStatus.Success;
                responseMessage.Message = string.Format("Inventserial {0} has been successfully created", entity.xts_inventserialid);
                responseMessage.Data = entity;
            }
            catch (Exception ex)
            {
                responseMessage.Status = ResponseStatus.Error;
                responseMessage.Message = "Failed to create Inventserial. " + GetInnerException(ex).Message;
            }

            return responseMessage;
			
        }
        #endregion
		
		
        public bool BulkInsert(List<CRM_xts_inventserial> data)
        {	
            bool result = false;
            try
            {
                DataTable dataTableData = new DataTable("CRM_xts_inventserial");
                dataTableData = data.ToDataTableForCreate();
                dataTableData = UpdateEmptyGuid(dataTableData);
                int batchSize = AppConfigs.GetInt(Constants.DBInsertBatchSizeConfigName);

                ExecuteTransaction(Connection, (connection, transaction) =>
                {
                    using (SqlBulkCopy insert = new SqlBulkCopy((SqlConnection)connection, SqlBulkCopyOptions.Default, (SqlTransaction)transaction))
                    {
                        if (batchSize > 0)
                        {
                            insert.BatchSize = batchSize;
                        }
                        insert.DestinationTableName = "CRM_xts_inventserial";

                        insert.WriteToServer(dataTableData);

                        result = true;
                        return true;
                    }
                });

                return result;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
		

        #region Update CRM_xts_inventserial
        public ResponseMessage Update(CRM_xts_inventserial entity)
        {
			
            ResponseMessage responseMessage = new ResponseMessage() { Success = false };

            try
            {
                if (entity != null)
                {
                    //SetLastModifiedLog(entity);
                    ExecuteTransaction(Connection, (connection, transaction) =>
                    {
                        return connection.Execute(CRM_xts_inventserialQuery.UpdateCRM_xts_inventserial, entity, transaction);
                    });

                    responseMessage.Success = true;
                    responseMessage.Status = ResponseStatus.Success;
                    responseMessage.Message = string.Format("Inventserial{0} has been successfully updated", entity.xts_inventserialid);
                    responseMessage.Data = entity;
                }
                else
                {
                    responseMessage.Status = ResponseStatus.Warning;
                    responseMessage.Message = "Inventserial does not exist";
                }
            }
            catch (Exception ex)
            {
                responseMessage.Status = ResponseStatus.Error;
                responseMessage.Message = "Failed to update Inventserial. " + GetInnerException(ex).Message;
            }

            return responseMessage;
			
        }
        #endregion
		

        #region Delete CRM_xts_inventserial
        public ResponseMessage Delete(int id)
        {
            return null;
        }
        #endregion

		#region Get CRM_xts_inventserial By Id
        public CRM_xts_inventserial Get(Guid xts_inventserialid)
        {
            try
            {
                using (var cn = Connection)
                {
                    return cn.Query<CRM_xts_inventserial>(
                        CRM_xts_inventserialQuery.GetCRM_xts_inventserialByID, new { xts_inventserialid = xts_inventserialid }
                        ).SingleOrDefault();
                }
            }
            catch (Exception)
            {
                return null;
            }
        }

        public CRM_xts_inventserial Get(int id)
        {
            return null;
        }
        #endregion

        #region Get All CRM_xts_inventserial
        public List<CRM_xts_inventserial> GetAll()
        {
            return null;
        }
        #endregion

        #region Search CRM_xts_inventserial
        public List<CRM_xts_inventserial> Search(DataTablePostModel model, out int filteredResultsCount, out int totalResultsCount)
        {
            filteredResultsCount = 0;
            totalResultsCount = 0;
            return new List<CRM_xts_inventserial>();
        }
        #endregion

		#region Search CRM_xts_inventserial        
        public new List<CRM_xts_inventserial> Search(string strCriteria, string strInnerCriteria, string sortColumns, int page, int pageSize, out int filteredResultsCount, out int totalResultsCount)
        {
            try
            {
                string orderBy = sortColumns != string.Empty ? sortColumns.ToString() : null;
                filteredResultsCount = 0;

                List<CRM_xts_inventserial> result = SearchFetchPaging<CRM_xts_inventserial>((connection, query, sqlParams) =>
                {
                    return connection.Query<CRM_xts_inventserial>(query, sqlParams, null, true, Timeout, null).ToList();
                }, Connection, string.Format(CRM_xts_inventserialQuery.SelectQuery,
                                                strCriteria,
                                                strInnerCriteria)
                , "CRM_xts_inventserial.xts_inventserialid", null, orderBy, out filteredResultsCount, page, pageSize,
                string.Format(CRM_xts_inventserialQuery.GetTotalQuery,
                                                strCriteria,
                                                strInnerCriteria), "xts_inventserialid");

                totalResultsCount = filteredResultsCount;

                return result;

            }
            catch (Exception ex)
            {
                filteredResultsCount = 0;
                totalResultsCount = 0;
                return new List<CRM_xts_inventserial>();
            }
        }
        #endregion

        public void SetCreatedLog(CRM_xts_inventserial CRM_xts_inventserial)
        {
            CRM_xts_inventserial.createdbyname = UserLogin;
            CRM_xts_inventserial.createdon = DateTime.Now;
            CRM_xts_inventserial.RowStatus = "0";
            SetLastModifiedLog(CRM_xts_inventserial);
        }

        public void SetLastModifiedLog(CRM_xts_inventserial CRM_xts_inventserial)
        {
            CRM_xts_inventserial.modifiedbyname = UserLogin;
            CRM_xts_inventserial.modifiedon = DateTime.Now;
        }

		
        private DataTable UpdateEmptyGuid(DataTable dt)
        {
            foreach (DataColumn col in dt.Columns)
            {
                if (col.DataType.Name.ToString() == "Guid")
                {
                    foreach (DataRow row in dt.Rows)
                    {
                        if (row[col.ColumnName].ToString() == Guid.Empty.ToString())
                        {
                            row[col.ColumnName] = DBNull.Value;
                        }
                    }
                }
            }
            return dt;
        }
		

    }
}
