#region Summary
/*
 ===========================================================================
 AUTHOR        : BSI Code Generator Interface 
 PURPOSE       : CRM_xts_outsourceworkshopconfiguration class
 SPECIAL NOTES : Generated from database BSIDMS_MMKSI_IF_ACC_DEV
 GENERATED BY  : Ivan
 ---------------------
 Copyright  (c) 2020 
 ---------------------
 $History      : $
 Created on 19 Jan 2021 09:25:04
 ===========================================================================
*/
#endregion

#region Namespace Imports
using Dapper;
using KTB.DNet.Interface.Domain;
using KTB.DNet.Interface.Framework;
using KTB.DNet.Interface.Repository.Dapper.NonDMS.SqlQuery.CRM_xts_outsourceworkshopconfiguration;
using KTB.DNet.Interface.Repository.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using System.Data.SqlClient;
using System.Reflection;
#endregion

namespace KTB.DNet.Interface.Repository.Dapper.NonDMS
{
    public class CRM_xts_outsourceworkshopconfigurationRepository : BaseDNetRepository<CRM_xts_outsourceworkshopconfiguration>, ICRM_xts_outsourceworkshopconfigurationRepository<CRM_xts_outsourceworkshopconfiguration, int>
    {
        #region Constructor
        public CRM_xts_outsourceworkshopconfigurationRepository(string connectionString)
            : base(connectionString)
        { }
        #endregion

		
        #region Create CRM_xts_outsourceworkshopconfiguration
        public ResponseMessage Create(CRM_xts_outsourceworkshopconfiguration entity)
        {
			
            ResponseMessage responseMessage = new ResponseMessage() { Success = false };

            try
            {
                //SetCreatedLog(entity);
                ExecuteTransaction(Connection, (connection, transaction) =>
                {
                    return connection.Execute(CRM_xts_outsourceworkshopconfigurationQuery.InsertCRM_xts_outsourceworkshopconfiguration, entity, transaction);
                });

                responseMessage.Success = true;
                responseMessage.Status = ResponseStatus.Success;
                responseMessage.Message = string.Format("Outsourceworkshopconfiguration {0} has been successfully created", entity.xts_outsourceworkshopconfigurationid);
                responseMessage.Data = entity;
            }
            catch (Exception ex)
            {
                responseMessage.Status = ResponseStatus.Error;
                responseMessage.Message = "Failed to create Outsourceworkshopconfiguration. " + GetInnerException(ex).Message;
            }

            return responseMessage;
			
        }
        #endregion
		
		
        public bool BulkInsert(List<CRM_xts_outsourceworkshopconfiguration> data)
        {	
            bool result = false;
            try
            {
                DataTable dataTableData = new DataTable("CRM_xts_outsourceworkshopconfiguration");
                dataTableData = data.ToDataTableForCreate();
                dataTableData = UpdateEmptyGuid(dataTableData);
                int batchSize = AppConfigs.GetInt(Constants.DBInsertBatchSizeConfigName);

                ExecuteTransaction(Connection, (connection, transaction) =>
                {
                    using (SqlBulkCopy insert = new SqlBulkCopy((SqlConnection)connection, SqlBulkCopyOptions.Default, (SqlTransaction)transaction))
                    {
                        if (batchSize > 0)
                        {
                            insert.BatchSize = batchSize;
                        }
                        insert.DestinationTableName = "CRM_xts_outsourceworkshopconfiguration";

                        insert.WriteToServer(dataTableData);

                        result = true;
                        return true;
                    }
                });

                return result;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
		

        #region Update CRM_xts_outsourceworkshopconfiguration
        public ResponseMessage Update(CRM_xts_outsourceworkshopconfiguration entity)
        {
			
            ResponseMessage responseMessage = new ResponseMessage() { Success = false };

            try
            {
                if (entity != null)
                {
                    //SetLastModifiedLog(entity);
                    ExecuteTransaction(Connection, (connection, transaction) =>
                    {
                        return connection.Execute(CRM_xts_outsourceworkshopconfigurationQuery.UpdateCRM_xts_outsourceworkshopconfiguration, entity, transaction);
                    });

                    responseMessage.Success = true;
                    responseMessage.Status = ResponseStatus.Success;
                    responseMessage.Message = string.Format("Outsourceworkshopconfiguration{0} has been successfully updated", entity.xts_outsourceworkshopconfigurationid);
                    responseMessage.Data = entity;
                }
                else
                {
                    responseMessage.Status = ResponseStatus.Warning;
                    responseMessage.Message = "Outsourceworkshopconfiguration does not exist";
                }
            }
            catch (Exception ex)
            {
                responseMessage.Status = ResponseStatus.Error;
                responseMessage.Message = "Failed to update Outsourceworkshopconfiguration. " + GetInnerException(ex).Message;
            }

            return responseMessage;
			
        }
        #endregion
		

        #region Delete CRM_xts_outsourceworkshopconfiguration
        public ResponseMessage Delete(int id)
        {
            return null;
        }
        #endregion

		#region Get CRM_xts_outsourceworkshopconfiguration By Id
        public CRM_xts_outsourceworkshopconfiguration Get(Guid xts_outsourceworkshopconfigurationid)
        {
            try
            {
                using (var cn = Connection)
                {
                    return cn.Query<CRM_xts_outsourceworkshopconfiguration>(
                        CRM_xts_outsourceworkshopconfigurationQuery.GetCRM_xts_outsourceworkshopconfigurationByID, new { xts_outsourceworkshopconfigurationid = xts_outsourceworkshopconfigurationid }
                        ).SingleOrDefault();
                }
            }
            catch (Exception)
            {
                return null;
            }
        }

        public CRM_xts_outsourceworkshopconfiguration Get(int id)
        {
            return null;
        }
        #endregion

        #region Get All CRM_xts_outsourceworkshopconfiguration
        public List<CRM_xts_outsourceworkshopconfiguration> GetAll()
        {
            return null;
        }
        #endregion

        #region Search CRM_xts_outsourceworkshopconfiguration
        public List<CRM_xts_outsourceworkshopconfiguration> Search(DataTablePostModel model, out int filteredResultsCount, out int totalResultsCount)
        {
            filteredResultsCount = 0;
            totalResultsCount = 0;
            return new List<CRM_xts_outsourceworkshopconfiguration>();
        }
        #endregion

		#region Search CRM_xts_outsourceworkshopconfiguration        
        public new List<CRM_xts_outsourceworkshopconfiguration> Search(string strCriteria, string strInnerCriteria, string sortColumns, int page, int pageSize, out int filteredResultsCount, out int totalResultsCount)
        {
            try
            {
                string orderBy = sortColumns != string.Empty ? sortColumns.ToString() : null;
                filteredResultsCount = 0;

                List<CRM_xts_outsourceworkshopconfiguration> result = SearchFetchPaging<CRM_xts_outsourceworkshopconfiguration>((connection, query, sqlParams) =>
                {
                    return connection.Query<CRM_xts_outsourceworkshopconfiguration>(query, sqlParams, null, true, Timeout, null).ToList();
                }, Connection, string.Format(CRM_xts_outsourceworkshopconfigurationQuery.SelectQuery,
                                                strCriteria,
                                                strInnerCriteria)
                , "CRM_xts_outsourceworkshopconfiguration.xts_outsourceworkshopconfigurationid", null, orderBy, out filteredResultsCount, page, pageSize,
                string.Format(CRM_xts_outsourceworkshopconfigurationQuery.GetTotalQuery,
                                                strCriteria,
                                                strInnerCriteria), "xts_outsourceworkshopconfigurationid");

                totalResultsCount = filteredResultsCount;

                return result;

            }
            catch (Exception ex)
            {
                filteredResultsCount = 0;
                totalResultsCount = 0;
                return new List<CRM_xts_outsourceworkshopconfiguration>();
            }
        }
        #endregion

        public void SetCreatedLog(CRM_xts_outsourceworkshopconfiguration CRM_xts_outsourceworkshopconfiguration)
        {
            CRM_xts_outsourceworkshopconfiguration.createdbyname = UserLogin;
            CRM_xts_outsourceworkshopconfiguration.createdon = DateTime.Now;
            CRM_xts_outsourceworkshopconfiguration.RowStatus = 0;
            SetLastModifiedLog(CRM_xts_outsourceworkshopconfiguration);
        }

        public void SetLastModifiedLog(CRM_xts_outsourceworkshopconfiguration CRM_xts_outsourceworkshopconfiguration)
        {
            CRM_xts_outsourceworkshopconfiguration.modifiedbyname = UserLogin;
            CRM_xts_outsourceworkshopconfiguration.modifiedon = DateTime.Now;
        }

		
        private DataTable UpdateEmptyGuid(DataTable dt)
        {
            foreach (DataColumn col in dt.Columns)
            {
                if (col.DataType.Name.ToString() == "Guid")
                {
                    foreach (DataRow row in dt.Rows)
                    {
                        if (row[col.ColumnName].ToString() == Guid.Empty.ToString())
                        {
                            row[col.ColumnName] = DBNull.Value;
                        }
                    }
                }
            }
            return dt;
        }
		

    }
}
