#region Summary
/*
 ===========================================================================
 AUTHOR        : BSI Code Generator Interface 
 PURPOSE       : CRM_xts_purchasereceiptdetaillandedcost class
 SPECIAL NOTES : Generated from database BSIDMS_MMKSI_IF_ACC_DEV
 GENERATED BY  : Fika
 ---------------------
 Copyright  (c) 2020 
 ---------------------
 $History      : $
 Created on 31 Aug 2020 16:19:08
 ===========================================================================
*/
#endregion

using Swashbuckle.Examples;

namespace KTB.DNet.Interface.WebApi.Models.Examples
{
    public class APICreateCRM_xts_purchasereceiptdetaillandedcostExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var obj = new
            {
				modifiedon = "modifiedon value",
				ownerid = "ownerid value",
				statecode = "statecode value",
				transactioncurrencyid = "transactioncurrencyid value",
				xts_amount = "xts_amount value",
				xts_apvouchernumberid = "xts_apvouchernumberid value",
				xts_businessunitid = "xts_businessunitid value",
				xts_calculationmethod = "xts_calculationmethod value",
				xts_documentdate = "xts_documentdate value",
				xts_invoicenumber = "xts_invoicenumber value",
				xts_landedcostid = "xts_landedcostid value",
				xts_landedcostnumber = "xts_landedcostnumber value",
				xts_parentbusinessunitid = "xts_parentbusinessunitid value",
				xts_purchasereceiptdetailid = "xts_purchasereceiptdetailid value",
				xts_purchasereceiptid = "xts_purchasereceiptid value",
				xts_recognitioncategory = "xts_recognitioncategory value",
				xts_taxamount = "xts_taxamount value",
				xts_totalamount = "xts_totalamount value",
				xts_vendorid = "xts_vendorid value",
				UpdatedBy = "UpdatedBy value"
            };

            return obj;
        }
    }
}