#region Summary
/*
 ===========================================================================
 AUTHOR        : BSI Code Generator Interface 
 PURPOSE       : CRM_xts_vehicleprice class
 SPECIAL NOTES : Generated from database BSIDMS_MMKSI_IF_ACC_DEV
 GENERATED BY  : Ivan
 ---------------------
 Copyright  (c) 2020 
 ---------------------
 $History      : $
 Created on 05 Feb 2021 13:44:53
 ===========================================================================
*/
#endregion

using Swashbuckle.Examples;

namespace KTB.DNet.Interface.WebApi.Models.Examples
{
    public class APICreateCRM_xts_vehiclepriceExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var obj = new
            {
				createdby = "createdby value",
				createdbyname = "createdbyname value",
				createdbyyominame = "createdbyyominame value",
				createdon = "createdon value",
				createdonbehalfby = "createdonbehalfby value",
				createdonbehalfbyname = "createdonbehalfbyname value",
				createdonbehalfbyyominame = "createdonbehalfbyyominame value",
				DealerCode = "DealerCode value",
				importsequencenumber = "importsequencenumber value",
				ktb_isinterfaced = "ktb_isinterfaced value",
				ktb_isinterfacedname = "ktb_isinterfacedname value",
				modifiedby = "modifiedby value",
				modifiedbyname = "modifiedbyname value",
				modifiedbyyominame = "modifiedbyyominame value",
				modifiedon = "modifiedon value",
				modifiedonbehalfby = "modifiedonbehalfby value",
				modifiedonbehalfbyname = "modifiedonbehalfbyname value",
				modifiedonbehalfbyyominame = "modifiedonbehalfbyyominame value",
				overriddencreatedon = "overriddencreatedon value",
				ownerid = "ownerid value",
				owneridname = "owneridname value",
				owneridtype = "owneridtype value",
				owneridyominame = "owneridyominame value",
				owningbusinessunit = "owningbusinessunit value",
				owningteam = "owningteam value",
				owninguser = "owninguser value",
				RowStatus = "RowStatus value",
				SourceType = "SourceType value",
				statecode = "statecode value",
				statecodename = "statecodename value",
				statuscode = "statuscode value",
				statuscodename = "statuscodename value",
				timezoneruleversionnumber = "timezoneruleversionnumber value",
				utcconversiontimezonecode = "utcconversiontimezonecode value",
				versionnumber = "versionnumber value",
				xts_businessunitid = "xts_businessunitid value",
				xts_businessunitidname = "xts_businessunitidname value",
				xts_currencyid = "xts_currencyid value",
				xts_currencyidname = "xts_currencyidname value",
				xts_customerclassid = "xts_customerclassid value",
				xts_customerclassidname = "xts_customerclassidname value",
				xts_effectivestartdate = "xts_effectivestartdate value",
				xts_locking = "xts_locking value",
				xts_pkcombinationkey = "xts_pkcombinationkey value",
				xts_vehicleprice = "xts_vehicleprice value",
				xts_vehiclepriceid = "xts_vehiclepriceid value",
				UpdatedBy = "UpdatedBy value"
            };

            return obj;
        }
    }
}