#region Summary
/*
 ===========================================================================
 AUTHOR        : BSI Code Generator Interface 
 PURPOSE       : CRM_xts_newvehicleaccessories class
 SPECIAL NOTES : Generated from database BSIDMS_MMKSI_IF_ACC_DEV
 GENERATED BY  : Fika
 ---------------------
 Copyright  (c) 2020 
 ---------------------
 $History      : $
 Created on 01 Sep 2020 20:01:32
 ===========================================================================
*/
#endregion

using Swashbuckle.Examples;

namespace KTB.DNet.Interface.WebApi.Models.Examples
{
    public class APICreateCRM_xts_newvehicleaccessoriesExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var obj = new
            {
				modifiedon = "modifiedon value",
				ownerid = "ownerid value",
				statecode = "statecode value",
				xts_accessorieskitgroupid = "xts_accessorieskitgroupid value",
				xts_businessunitid = "xts_businessunitid value",
				xts_exteriorcolorlookupname = "xts_exteriorcolorlookupname value",
				xts_exteriorcolorlookuptype = "xts_exteriorcolorlookuptype value",
				xts_exteriorcolornewvehicleexteriorcolorid = "xts_exteriorcolornewvehicleexteriorcolorid value",
				xts_exteriorcolorproductexteriorcolorid = "xts_exteriorcolorproductexteriorcolorid value",
				xts_gradeid = "xts_gradeid value",
				xts_gradename = "xts_gradename value",
				xts_interiorcolorlookupname = "xts_interiorcolorlookupname value",
				xts_interiorcolorlookuptype = "xts_interiorcolorlookuptype value",
				xts_interiorcolornewvehicleinteriorcolorid = "xts_interiorcolornewvehicleinteriorcolorid value",
				xts_interiorcolorproductinteriorcolorid = "xts_interiorcolorproductinteriorcolorid value",
				xts_newvehicleaccessories = "xts_newvehicleaccessories value",
				xts_productdescription = "xts_productdescription value",
				xts_productid = "xts_productid value",
				xts_stylelookupname = "xts_stylelookupname value",
				xts_stylelookuptype = "xts_stylelookuptype value",
				xts_styleproductstyleid = "xts_styleproductstyleid value",
				xts_stylestyleid = "xts_stylestyleid value",
				UpdatedBy = "UpdatedBy value"
            };

            return obj;
        }
    }
}