#region Summary
/*
 ===========================================================================
 AUTHOR        : BSI Code Generator Interface 
 PURPOSE       : CRM_xid_documentregistration class
 SPECIAL NOTES : Generated from database BSIDMS_MMKSI_IF_ACC_DEV
 GENERATED BY  : Khalil (version : v.1.08)
 ---------------------
 Copyright  (c) 2020 
 ---------------------
 $History      : $
 Created on 04 Sep 2020 14:12:48
 ===========================================================================
*/
#endregion

using Swashbuckle.Examples;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KTB.DNet.Interface.WebApi.Models.Examples
{
    public class APIDeleteCRM_xid_documentregistrationExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var obj = new
            {
                xid_documentregistrationid = "00000000-0000-0000-0000-000000000000"
            };

            return obj;
        }
    }
}