#region Summary
/*
 ===========================================================================
 AUTHOR        : BSI Code Generator Interface 
 PURPOSE       : CRM_serviceappointment class
 SPECIAL NOTES : Generated from database BSIDMS_MMKSI_IF_ACC_DEV
 GENERATED BY  : Ivan
 ---------------------
 Copyright  (c) 2020 
 ---------------------
 $History      : $
 Created on 19 Jan 2021 09:35:16
 ===========================================================================
*/
#endregion


using Swashbuckle.Examples;

namespace KTB.DNet.Interface.WebApi.Models.Examples
{
    public class APIUpdateCRM_serviceappointmentExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var obj = new
            {
				activityid = "activityid value",
				activityadditionalparams = "activityadditionalparams value",
				activitytypecode = "activitytypecode value",
				activitytypecodename = "activitytypecodename value",
				actualdurationminutes = "actualdurationminutes value",
				actualend = "actualend value",
				actualstart = "actualstart value",
				bcc = "bcc value",
				category = "category value",
				cc = "cc value",
				community = "community value",
				communityname = "communityname value",
				createdby = "createdby value",
				createdbyname = "createdbyname value",
				createdbyyominame = "createdbyyominame value",
				createdon = "createdon value",
				createdonbehalfby = "createdonbehalfby value",
				createdonbehalfbyname = "createdonbehalfbyname value",
				createdonbehalfbyyominame = "createdonbehalfbyyominame value",
				customers = "customers value",
				DealerCode = "DealerCode value",
				deliverylastattemptedon = "deliverylastattemptedon value",
				deliveryprioritycode = "deliveryprioritycode value",
				deliveryprioritycodename = "deliveryprioritycodename value",
				description = "description value",
				exchangeitemid = "exchangeitemid value",
				exchangerate = "exchangerate value",
				exchangeweblink = "exchangeweblink value",
				from = "from value",
				importsequencenumber = "importsequencenumber value",
				instancetypecode = "instancetypecode value",
				instancetypecodename = "instancetypecodename value",
				isalldayevent = "isalldayevent value",
				isalldayeventname = "isalldayeventname value",
				isbilled = "isbilled value",
				isbilledname = "isbilledname value",
				ismapiprivate = "ismapiprivate value",
				ismapiprivatename = "ismapiprivatename value",
				isregularactivity = "isregularactivity value",
				isregularactivityname = "isregularactivityname value",
				isworkflowcreated = "isworkflowcreated value",
				isworkflowcreatedname = "isworkflowcreatedname value",
				lastonholdtime = "lastonholdtime value",
				leftvoicemail = "leftvoicemail value",
				leftvoicemailname = "leftvoicemailname value",
				location = "location value",
				modifiedby = "modifiedby value",
				modifiedbyname = "modifiedbyname value",
				modifiedbyyominame = "modifiedbyyominame value",
				modifiedon = "modifiedon value",
				modifiedonbehalfby = "modifiedonbehalfby value",
				modifiedonbehalfbyname = "modifiedonbehalfbyname value",
				modifiedonbehalfbyyominame = "modifiedonbehalfbyyominame value",
				msdyn_organizationalunitid = "msdyn_organizationalunitid value",
				msdyn_organizationalunitidname = "msdyn_organizationalunitidname value",
				onholdtime = "onholdtime value",
				optionalattendees = "optionalattendees value",
				organizer = "organizer value",
				overriddencreatedon = "overriddencreatedon value",
				ownerid = "ownerid value",
				owneridname = "owneridname value",
				owneridtype = "owneridtype value",
				owneridyominame = "owneridyominame value",
				owningbusinessunit = "owningbusinessunit value",
				owningteam = "owningteam value",
				owninguser = "owninguser value",
				partners = "partners value",
				postponeactivityprocessinguntil = "postponeactivityprocessinguntil value",
				prioritycode = "prioritycode value",
				prioritycodename = "prioritycodename value",
				processid = "processid value",
				regardingobjectid = "regardingobjectid value",
				regardingobjectidname = "regardingobjectidname value",
				regardingobjectidyominame = "regardingobjectidyominame value",
				regardingobjecttypecode = "regardingobjecttypecode value",
				requiredattendees = "requiredattendees value",
				resources = "resources value",
				RowStatus = "RowStatus value",
				scheduleddurationminutes = "scheduleddurationminutes value",
				scheduledend = "scheduledend value",
				scheduledstart = "scheduledstart value",
				sendermailboxid = "sendermailboxid value",
				sendermailboxidname = "sendermailboxidname value",
				senton = "senton value",
				seriesid = "seriesid value",
				serviceid = "serviceid value",
				serviceidname = "serviceidname value",
				siteid = "siteid value",
				siteidname = "siteidname value",
				slaid = "slaid value",
				slainvokedid = "slainvokedid value",
				slainvokedidname = "slainvokedidname value",
				slaname = "slaname value",
				sortdate = "sortdate value",
				SourceType = "SourceType value",
				stageid = "stageid value",
				statecode = "statecode value",
				statecodename = "statecodename value",
				statuscode = "statuscode value",
				statuscodename = "statuscodename value",
				subcategory = "subcategory value",
				subject = "subject value",
				subscriptionid = "subscriptionid value",
				timezoneruleversionnumber = "timezoneruleversionnumber value",
				to = "to value",
				transactioncurrencyid = "transactioncurrencyid value",
				transactioncurrencyidname = "transactioncurrencyidname value",
				traversedpath = "traversedpath value",
				utcconversiontimezonecode = "utcconversiontimezonecode value",
				versionnumber = "versionnumber value",
				xts_billable = "xts_billable value",
				xts_billablename = "xts_billablename value",
				xts_billabletype = "xts_billabletype value",
				xts_billabletypename = "xts_billabletypename value",
				xts_businessunitid = "xts_businessunitid value",
				xts_businessunitidname = "xts_businessunitidname value",
				xts_costcenterid = "xts_costcenterid value",
				xts_costcenteridname = "xts_costcenteridname value",
				xts_freecouponnumber = "xts_freecouponnumber value",
				xts_isfromwoquote = "xts_isfromwoquote value",
				xts_isfromwoquotename = "xts_isfromwoquotename value",
				xts_locationid = "xts_locationid value",
				xts_locationidname = "xts_locationidname value",
				xts_locking = "xts_locking value",
				xts_maindealerinvoicegroup = "xts_maindealerinvoicegroup value",
				xts_maindealerinvoicegroupname = "xts_maindealerinvoicegroupname value",
				xts_nonbillabletype = "xts_nonbillabletype value",
				xts_nonbillabletypename = "xts_nonbillabletypename value",
				xts_reasonid = "xts_reasonid value",
				xts_reasonidname = "xts_reasonidname value",
				xts_servicetype = "xts_servicetype value",
				xts_servicetypename = "xts_servicetypename value",
				xts_totallaborcost = "xts_totallaborcost value",
				xts_totallaborcost_base = "xts_totallaborcost_base value",
				UpdatedBy = "UpdatedBy value"
            };

            return obj;
        }
    }
}