#region Summary
/*
 ===========================================================================
 AUTHOR        : BSI Code Generator Interface 
 PURPOSE       : CRM_xts_workorder class
 SPECIAL NOTES : Generated from database BSIDMS_MMKSI_IF_ACC_DEV
 GENERATED BY  : Fika
 ---------------------
 Copyright  (c) 2020 
 ---------------------
 $History      : $
 Created on 01 Sep 2020 19:46:39
 ===========================================================================
*/
#endregion

#region Namespace Imports
using System;
#endregion

namespace KTB.DNet.Interface.Model
{
    public class CRM_xts_workorderDto : DtoBase
    {
        public Guid xts_workorderid { get; set; }

		public string ktb_dnetidserviceincoming { get; set; }

		public string ktb_dnetidwotype { get; set; }

		public DateTime? ktb_estimationfinishdatebysa { get; set; }

		public string ktb_interfacehandlingdnet { get; set; }

		public string ktb_interfacemessage { get; set; }

		public bool? ktb_isinsurance { get; set; }

		public Guid ktb_methodofpaymentid { get; set; }

		public Guid ktb_saleschannelid { get; set; }

		public Guid ktb_servicelocationid { get; set; }

		public Guid ktb_servicetypeid { get; set; }

		public Guid transactioncurrencyid { get; set; }

		public decimal? xjp_caliallocated { get; set; }

		public decimal? xjp_caliamount { get; set; }

		public DateTime? xjp_caliexpirationdate { get; set; }

		public decimal? xjp_calinotallocated { get; set; }

		public int? xjp_caliperiodmonths { get; set; }

		public decimal? xjp_estcaliamount { get; set; }

		public int? xjp_estcaliperiodmonths { get; set; }

		public Guid xjp_originaloutsorcereferencepdiid { get; set; }

		public DateTime? xts_accidentdate { get; set; }

		public DateTime? xts_actualarrivaldateandtime { get; set; }

		public DateTime? xts_actualfinishdateandtime { get; set; }

		public DateTime? xts_actualservicefinishdateandtime { get; set; }

		public DateTime? xts_actualservicestartdateandtime { get; set; }

		public string xts_billallocationmethod { get; set; }

		public Guid xts_billtocustomerid { get; set; }

		public Guid xts_businessunitid { get; set; }

		public string xts_cancelreason { get; set; }

		public int? xts_currentmileage { get; set; }

		public Guid xts_customerid { get; set; }

		public string xts_customernumber { get; set; }

		public Guid xts_dimension10id { get; set; }

		public Guid xts_dimension1id { get; set; }

		public Guid xts_dimension2id { get; set; }

		public Guid xts_dimension3id { get; set; }

		public Guid xts_dimension4id { get; set; }

		public Guid xts_dimension5id { get; set; }

		public Guid xts_dimension6id { get; set; }

		public Guid xts_dimension7id { get; set; }

		public Guid xts_dimension8id { get; set; }

		public Guid xts_dimension9id { get; set; }

		public decimal? xts_downpaymentamount { get; set; }

		public decimal? xts_downpaymentamountreceived { get; set; }

		public bool? xts_downpaymentispaid { get; set; }

		public decimal? xts_estgrandtotalamount { get; set; }

		public decimal? xts_esttotalbaseamount { get; set; }

		public decimal? xts_esttotalmiscchargeamount { get; set; }

		public decimal? xts_esttotalmiscchargebaseamount { get; set; }

		public decimal? xts_esttotalmiscchargetaxamount { get; set; }

		public decimal? xts_esttotalothersalesamount { get; set; }

		public decimal? xts_esttotalothersalesbaseamount { get; set; }

		public decimal? xts_esttotalothersalestaxamount { get; set; }

		public decimal? xts_esttotalpartsamount { get; set; }

		public decimal? xts_esttotalpartsbaseamount { get; set; }

		public decimal? xts_esttotalpartstaxamount { get; set; }

		public decimal? xts_esttotaltaxamount { get; set; }

		public decimal? xts_esttotalwithholdingtaxamount { get; set; }

		public decimal? xts_esttotalworkamount { get; set; }

		public decimal? xts_esttotalworkbaseamount { get; set; }

		public decimal? xts_esttotalworktaxamount { get; set; }

		public decimal? xts_exchangerate { get; set; }

		public Guid xts_incomingoutsourcebusinessunitid { get; set; }

		public Guid xts_incomingoutsourcereferenceid { get; set; }

		public DateTime? xts_insuranceinspectiondate { get; set; }

		public DateTime? xts_invoicepostingdate { get; set; }

		public int? xts_lastmileage { get; set; }

		public Guid xts_originalcustomerid { get; set; }

		public string xts_originaloutsorcereferencelookupname { get; set; }

		public int? xts_originaloutsorcereferencelookuptype { get; set; }

		public Guid xts_originaloutsorcereferenceoutsourcewoid { get; set; }

		public Guid xts_originaloutsorcereferencesvcinstructionid { get; set; }

		public Guid xts_originalworkorderreferencenumberid { get; set; }

		public bool? xts_overcreditlimitonhold { get; set; }

		public Guid xts_parentbusinessunitid { get; set; }

		public decimal? xts_paymentreceivedamount { get; set; }

		public decimal? xts_paymentreceivedamount_base { get; set; }

		public string xts_platenumber { get; set; }

		public Guid xts_productid { get; set; }

		public Guid xts_productsegment1id { get; set; }

		public Guid xts_productsegment2id { get; set; }

		public Guid xts_productsegment3id { get; set; }

		public Guid xts_productsegment4id { get; set; }

		public Guid xts_reservationclassid { get; set; }

		public Guid xts_reservationid { get; set; }

		public decimal? xts_reservationmanhour { get; set; }

		public Guid xts_salespersonid { get; set; }

		public DateTime? xts_scheduledarrivaldateandtime { get; set; }

		public DateTime? xts_scheduledfinishdateandtime { get; set; }

		public DateTime? xts_scheduledservicefinishdateandtime { get; set; }

		public DateTime? xts_scheduledservicestartdateandtime { get; set; }

		public Guid xts_serviceadvisorid { get; set; }

		public Guid xts_servicecampaignid { get; set; }

		public string xts_servicecategorydescription { get; set; }

		public Guid xts_servicecategoryid { get; set; }

		public Guid xts_servicepersoninchargeid { get; set; }

		public string xts_servicetemplatecalculationmethod { get; set; }

		public Guid xts_symptomcauseid { get; set; }

		public Guid xts_symptomid { get; set; }

		public decimal? xts_totalbaseamount { get; set; }

		public decimal? xts_totalcostamount { get; set; }

		public decimal? xts_totalmiscchargeallocated { get; set; }

		public decimal? xts_totalmiscchargeamount { get; set; }

		public decimal? xts_totalmiscchargebaseallocated { get; set; }

		public decimal? xts_totalmiscchargebaseamount { get; set; }

		public decimal? xts_totalmiscchargebasenotallocated { get; set; }

		public decimal? xts_totalmiscchargenotallocated { get; set; }

		public decimal? xts_totalmiscchargetaxallocated { get; set; }

		public decimal? xts_totalmiscchargetaxamount { get; set; }

		public decimal? xts_totalmiscchargetaxnotallocated { get; set; }

		public decimal? xts_totalothersalesallocated { get; set; }

		public decimal? xts_totalothersalesamount { get; set; }

		public decimal? xts_totalothersalesbaseallocated { get; set; }

		public decimal? xts_totalothersalesbaseamount { get; set; }

		public decimal? xts_totalothersalesbasenotallocated { get; set; }

		public decimal? xts_totalothersalesnotallocated { get; set; }

		public decimal? xts_totalothersalestaxallocated { get; set; }

		public decimal? xts_totalothersalestaxamount { get; set; }

		public decimal? xts_totalothersalestaxnotallocated { get; set; }

		public decimal? xts_totalpartsallocated { get; set; }

		public decimal? xts_totalpartsamount { get; set; }

		public decimal? xts_totalpartsbaseallocated { get; set; }

		public decimal? xts_totalpartsbaseamount { get; set; }

		public decimal? xts_totalpartsbasenotallocated { get; set; }

		public decimal? xts_totalpartsnotallocated { get; set; }

		public decimal? xts_totalpartstaxallocated { get; set; }

		public decimal? xts_totalpartstaxamount { get; set; }

		public decimal? xts_totalpartstaxnotallocated { get; set; }

		public decimal? xts_totalpaymentamount { get; set; }

		public decimal? xts_totaltaxamount { get; set; }

		public decimal? xts_totalwithholdingtaxallocated { get; set; }

		public decimal? xts_totalwithholdingtaxamount { get; set; }

		public decimal? xts_totalwithholdingtaxnotallocated { get; set; }

		public decimal? xts_totalworkallocated { get; set; }

		public decimal? xts_totalworkamount { get; set; }

		public decimal? xts_totalworkbaseallocated { get; set; }

		public decimal? xts_totalworkbaseamount { get; set; }

		public decimal? xts_totalworkbasenotallocated { get; set; }

		public decimal? xts_totalworknotallocated { get; set; }

		public decimal? xts_totalworktaxallocated { get; set; }

		public decimal? xts_totalworktaxamount { get; set; }

		public decimal? xts_totalworktaxnotallocated { get; set; }

		public DateTime? xts_transactiondate { get; set; }

		public Guid xts_vehicleidentificationid { get; set; }

		public Guid xts_vehiclemodelid { get; set; }

		public string xts_vehiclemodelname { get; set; }

		public string xts_woinsurancereceiptnumber { get; set; }

		public string xts_workorder { get; set; }

		public Guid xts_workorderreferenceid { get; set; }

		public string xts_workorderstatus { get; set; }

		public string ktb_externalcode { get; set; }

		public bool ktb_isinbound { get; set; }

	}
}
