#region Summary
/*
 ===========================================================================
 AUTHOR        : BSI Code Generator Interface 
 PURPOSE       : CRM_xts_productlist class
 SPECIAL NOTES : Generated from database BSIDMS_MMKSI_IF_ACC_DEV
 GENERATED BY  : Nando (version : v.1.08)
 ---------------------
 Copyright  (c) 2020 
 ---------------------
 $History      : $
 Created on 03 Sep 2020 10:37:59
 ===========================================================================
*/
#endregion

#region Namespace Imports
using System;
#endregion

namespace KTB.DNet.Interface.Model
{
    public class CRM_xts_productlistDto : DtoBase
    {
        
		public Guid createdby { get; set; }

		public DateTime? createdon { get; set; }

		public Guid createdonbehalfby { get; set; }

		public decimal? exchangerate { get; set; }

		public Guid modifiedby { get; set; }

		public DateTime? modifiedon { get; set; }

		public Guid modifiedonbehalfby { get; set; }

		public DateTime? overriddencreatedon { get; set; }

		public Guid ownerid { get; set; }

		public int? statecode { get; set; }

		public int? statuscode { get; set; }

		public Guid transactioncurrencyid { get; set; }

		public DateTime? xjp_generationdate { get; set; }

		public string xts_company { get; set; }

		public Guid xts_defaultunitid { get; set; }

		public string xts_description { get; set; }

		public string xts_description2 { get; set; }

		public Guid xts_manufacturerid { get; set; }

		public string xts_product { get; set; }

		public Guid xts_productclassid { get; set; }

		public Guid xts_productlistid { get; set; }

		public Guid xts_productsegment1id { get; set; }

		public Guid xts_productsegment2id { get; set; }

		public Guid xts_productsegment3id { get; set; }

		public Guid xts_productsegment4id { get; set; }

		public Guid xts_purchaseunitid { get; set; }

		public Guid xts_salesunitid { get; set; }

		public decimal? xts_stockbaseprice { get; set; }

		public decimal? xts_stockbaseprice_base { get; set; }

    }
}
