#region Summary
// ===========================================================================
// AUTHOR        : BSI Code Generator 
// SPECIAL NOTES : DNet WebApi Project
// ---------------------
// Copyright  (c) 2019 
// ---------------------
// $History      : $
// Created on 14/01/2020 9:03:03]
//
// ===========================================================================	
#endregion

using Swashbuckle.Examples;

namespace KTB.DNet.Interface.WebApi.Models.Examples
{
    public class APICreateVWI_CRM_xts_purchasereceiptdetailExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var obj = new
            {
				UpdatedBy = "DealerUser"
				,company = "company Value"
				,businessunitcode = "businessunitcode Value"
				,xts_discountpercentage = "xts_discountpercentage Value"
				,xts_landedcost = "xts_landedcost Value"
				,bsi_interest_base = "bsi_interest_base Value"
				,xts_consumptiontax2id = "xts_consumptiontax2id Value"
				,xts_returnpurchasereceiptdetailidname = "xts_returnpurchasereceiptdetailidname Value"
				,xts_purchasereceiptdetailid = "xts_purchasereceiptdetailid Value"
				,modifiedon = "modifiedon Value"
				,overriddencreatedon = "overriddencreatedon Value"
				,xts_totalamount = "xts_totalamount Value"
				,statuscodename = "statuscodename Value"
				,ktb_consumptiontax1amountinterface_base = "ktb_consumptiontax1amountinterface_base Value"
				,xts_processedname = "xts_processedname Value"
				,ktb_interest_base = "ktb_interest_base Value"
				,xts_productweight = "xts_productweight Value"
				,xts_returnpurchasereceiptdetailid = "xts_returnpurchasereceiptdetailid Value"
				,ktb_discountreward = "ktb_discountreward Value"
				,ktb_parkingamount = "ktb_parkingamount Value"
				,transactioncurrencyidname = "transactioncurrencyidname Value"
				,xts_chassismodel = "xts_chassismodel Value"
				,xts_unitcost_base = "xts_unitcost_base Value"
				,xts_discountamount_base = "xts_discountamount_base Value"
				,ktb_salesorderno = "ktb_salesorderno Value"
				,ktb_discountdnet = "ktb_discountdnet Value"
				,ktb_materialdescription = "ktb_materialdescription Value"
				,owningbusinessunit = "owningbusinessunit Value"
				,modifiedbyname = "modifiedbyname Value"
				,xts_locationid = "xts_locationid Value"
				,xts_stockid = "xts_stockid Value"
				,statuscode = "statuscode Value"
				,xts_consumptiontax1amount = "xts_consumptiontax1amount Value"
				,ktb_vehiclekinddescription = "ktb_vehiclekinddescription Value"
				,xts_productdescription = "xts_productdescription Value"
				,xts_warehouseidname = "xts_warehouseidname Value"
				,ktb_netpricednet_base = "ktb_netpricednet_base Value"
				,xts_totalvolume = "xts_totalvolume Value"
				,ktb_ppn = "ktb_ppn Value"
				,xts_purchaseorderdetailid = "xts_purchaseorderdetailid Value"
				,xts_consumptiontax1idname = "xts_consumptiontax1idname Value"
				,statecodename = "statecodename Value"
				,xts_batchidname = "xts_batchidname Value"
				,xts_productidname = "xts_productidname Value"
				,exchangerate = "exchangerate Value"
				,xts_totalamount_base = "xts_totalamount_base Value"
				,xts_productexteriorcolorid = "xts_productexteriorcolorid Value"
				,ktb_hargapokok = "ktb_hargapokok Value"
				,xts_purchasereceiptidname = "xts_purchasereceiptidname Value"
				,xts_receivedquantity = "xts_receivedquantity Value"
				,xts_stockidname = "xts_stockidname Value"
				,ktb_updatetosparepartstock = "ktb_updatetosparepartstock Value"
				,xts_reasoncodeid = "xts_reasoncodeid Value"
				,xts_purchaseorderdetailidname = "xts_purchaseorderdetailidname Value"
				,xts_servicepartandmaterialidname = "xts_servicepartandmaterialidname Value"
				,xts_withholdingtaxidname = "xts_withholdingtaxidname Value"
				,xts_landedcost_base = "xts_landedcost_base Value"
				,xts_inventoryunitidname = "xts_inventoryunitidname Value"
				,xts_totalbaseamount_base = "xts_totalbaseamount_base Value"
				,xts_totalconsumptiontaxamount = "xts_totalconsumptiontaxamount Value"
				,bsi_interest = "bsi_interest Value"
				,xts_productvolume = "xts_productvolume Value"
				,owneridyominame = "owneridyominame Value"
				,createdon = "createdon Value"
				,xts_purchaseunitidname = "xts_purchaseunitidname Value"
				,modifiedby = "modifiedby Value"
				,timezoneruleversionnumber = "timezoneruleversionnumber Value"
				,statecode = "statecode Value"
				,xts_productexteriorcoloridname = "xts_productexteriorcoloridname Value"
				,xts_productinteriorcolorid = "xts_productinteriorcolorid Value"
				,modifiedonbehalfby = "modifiedonbehalfby Value"
				,xts_consumptiontax1amount_base = "xts_consumptiontax1amount_base Value"
				,xts_withholdingtaxid = "xts_withholdingtaxid Value"
				,xts_departmentidname = "xts_departmentidname Value"
				,xts_unitcost = "xts_unitcost Value"
				,ktb_hargapokok_base = "ktb_hargapokok_base Value"
				,xts_qtyreturned = "xts_qtyreturned Value"
				,traversedpath = "traversedpath Value"
				,xts_discountamount = "xts_discountamount Value"
				,xts_servicepartandmaterialid = "xts_servicepartandmaterialid Value"
				,ktb_productsap = "ktb_productsap Value"
				,owninguser = "owninguser Value"
				,xts_departmentid = "xts_departmentid Value"
				,xts_totalweight = "xts_totalweight Value"
				,owneridtype = "owneridtype Value"
				,xts_productconfigurationidname = "xts_productconfigurationidname Value"
				,owneridname = "owneridname Value"
				,modifiedonbehalfbyname = "modifiedonbehalfbyname Value"
				,createdonbehalfbyyominame = "createdonbehalfbyyominame Value"
				,xts_totalconsumptiontaxamount_base = "xts_totalconsumptiontaxamount_base Value"
				,xts_basereceivedquantity = "xts_basereceivedquantity Value"
				,owningteam = "owningteam Value"
				,xts_purchasereceiptid = "xts_purchasereceiptid Value"
				,bsi_discountreward_base = "bsi_discountreward_base Value"
				,xts_parentbusinessunitidname = "xts_parentbusinessunitidname Value"
				,xts_siteid = "xts_siteid Value"
				,processid = "processid Value"
				,xts_totalbaseamount = "xts_totalbaseamount Value"
				,createdonbehalfby = "createdonbehalfby Value"
				,xts_parentbusinessunitid = "xts_parentbusinessunitid Value"
				,transactioncurrencyid = "transactioncurrencyid Value"
				,xts_eventdata = "xts_eventdata Value"
				,ktb_discountdnet_base = "ktb_discountdnet_base Value"
				,ktb_discpercentage = "ktb_discpercentage Value"
				,ktb_ppn_base = "ktb_ppn_base Value"
				,bsi_discountreward = "bsi_discountreward Value"
				,ktb_vehiclekindcode = "ktb_vehiclekindcode Value"
				,ktb_parkingamount_base = "ktb_parkingamount_base Value"
				,ktb_materialnumber = "ktb_materialnumber Value"
				,ktb_discountreward_base = "ktb_discountreward_base Value"
				,xts_consumptiontax2amount = "xts_consumptiontax2amount Value"
				,xts_warehouseid = "xts_warehouseid Value"
				,modifiedbyyominame = "modifiedbyyominame Value"
				,ownerid = "ownerid Value"
				,xts_processed = "xts_processed Value"
				,createdonbehalfbyname = "createdonbehalfbyname Value"
				,xts_titleregistrationfee = "xts_titleregistrationfee Value"
				,ktb_endpoint = "ktb_endpoint Value"
				,createdbyname = "createdbyname Value"
				,xts_batchid = "xts_batchid Value"
				,xts_businessunitidname = "xts_businessunitidname Value"
				,ktb_purchaseorderno = "ktb_purchaseorderno Value"
				,xts_siteidname = "xts_siteidname Value"
				,xts_locationidname = "xts_locationidname Value"
				,modifiedonbehalfbyyominame = "modifiedonbehalfbyyominame Value"
				,createdby = "createdby Value"
				,ktb_consumptiontax1amountinterface = "ktb_consumptiontax1amountinterface Value"
				,ktb_updatetosparepartstockname = "ktb_updatetosparepartstockname Value"
				,ktb_gidate = "ktb_gidate Value"
				,xts_productstyleid = "xts_productstyleid Value"
				,ktb_netpricednet = "ktb_netpricednet Value"
				,xts_inventoryunitid = "xts_inventoryunitid Value"
				,xts_productinteriorcoloridname = "xts_productinteriorcoloridname Value"
				,ktb_categoryno = "ktb_categoryno Value"
				,xts_purchasereceiptdetail = "xts_purchasereceiptdetail Value"
				,xts_processgroup = "xts_processgroup Value"
				,ktb_discountpercentage = "ktb_discountpercentage Value"
				,ktb_interest = "ktb_interest Value"
				,stageid = "stageid Value"
				,utcconversiontimezonecode = "utcconversiontimezonecode Value"
				,ktb_deliveryorderno = "ktb_deliveryorderno Value"
				,xts_referencenumber = "xts_referencenumber Value"
				,xts_transactionamount_base = "xts_transactionamount_base Value"
				,importsequencenumber = "importsequencenumber Value"
				,xts_locking = "xts_locking Value"
				,xts_consumptiontax2idname = "xts_consumptiontax2idname Value"
				,xts_baseqtyreturned = "xts_baseqtyreturned Value"
				,xts_productionyear = "xts_productionyear Value"
				,xts_chassisnumberregister = "xts_chassisnumberregister Value"
				,xts_consumptiontax2amount_base = "xts_consumptiontax2amount_base Value"
				,versionnumber = "versionnumber Value"
				,xts_businessunitid = "xts_businessunitid Value"
				,xts_purchaseunitid = "xts_purchaseunitid Value"
				,xts_titleregistrationfee_base = "xts_titleregistrationfee_base Value"
				,xts_productid = "xts_productid Value"
				,xts_productconfigurationid = "xts_productconfigurationid Value"
				,xts_consumptiontax1id = "xts_consumptiontax1id Value"
				,createdbyyominame = "createdbyyominame Value"
				,xts_transactionamount = "xts_transactionamount Value"
				,xts_engineno = "xts_engineno Value"
				,xts_withholdingtaxamount_base = "xts_withholdingtaxamount_base Value"
				,xts_withholdingtaxamount = "xts_withholdingtaxamount Value"
				,xts_keyno = "xts_keyno Value"
				,xts_reasoncodeidname = "xts_reasoncodeidname Value"
				,xts_productstyleidname = "xts_productstyleidname Value"
				,msdyn_companycode = "msdyn_companycode Value"
            };

            return obj;
        }
    }
}