#region Summary
// ===========================================================================
// AUTHOR        : BSI Code Generator 
// SPECIAL NOTES : DNet WebApi Project
// ---------------------
// Copyright  (c) 2019 
// ---------------------
// $History      : $
// Created on 15/01/2020 8:22:46]
//
// ===========================================================================	
#endregion

using Swashbuckle.Examples;

namespace KTB.DNet.Interface.WebApi.Models.Examples
{
    public class APICreateVWI_CRM_xts_purchasereceiptExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var obj = new
            {
				UpdatedBy = "DealerUser"
				,company = "company Value"
				,businessunitcode = "businessunitcode Value"
				,xts_vendordescription = "xts_vendordescription Value"
				,xts_parentbusinessunitid = "xts_parentbusinessunitid Value"
				,versionnumber = "versionnumber Value"
				,createdon = "createdon Value"
				,ktb_updatetosparepartstock = "ktb_updatetosparepartstock Value"
				,ktb_purchaserequisitionid = "ktb_purchaserequisitionid Value"
				,ktb_isfactoringname = "ktb_isfactoringname Value"
				,xts_provinceid = "xts_provinceid Value"
				,ktb_packingdate = "ktb_packingdate Value"
				,statuscodename = "statuscodename Value"
				,xts_status = "xts_status Value"
				,xts_vendorinvoicedate = "xts_vendorinvoicedate Value"
				,modifiedbyyominame = "modifiedbyyominame Value"
				,ktb_interfacehandling = "ktb_interfacehandling Value"
				,owneridtype = "owneridtype Value"
				,xts_vendorinvoicenumber = "xts_vendorinvoicenumber Value"
				,ktb_identificationtypename = "ktb_identificationtypename Value"
				,xts_totalbaseamount_base = "xts_totalbaseamount_base Value"
				,xts_termsofpaymentid = "xts_termsofpaymentid Value"
				,xts_autoinvoiced = "xts_autoinvoiced Value"
				,xts_loaddataname = "xts_loaddataname Value"
				,modifiedbyname = "modifiedbyname Value"
				,xts_totalwithholdingtaxamount = "xts_totalwithholdingtaxamount Value"
				,xts_accountpayablevoucheridname = "xts_accountpayablevoucheridname Value"
				,ktb_interfacestatusname = "ktb_interfacestatusname Value"
				,xts_purchasereceiptreferencerequired = "xts_purchasereceiptreferencerequired Value"
				,owneridname = "owneridname Value"
				,xts_provinceidname = "xts_provinceidname Value"
				,xts_assignlandedcostperdetail = "xts_assignlandedcostperdetail Value"
				,overriddencreatedon = "overriddencreatedon Value"
				,xts_typename = "xts_typename Value"
				,xts_address2 = "xts_address2 Value"
				,xts_type = "xts_type Value"
				,xts_eventdata = "xts_eventdata Value"
				,modifiedonbehalfby = "modifiedonbehalfby Value"
				,exchangerate = "exchangerate Value"
				,xts_totalconsumptiontaxamount_base = "xts_totalconsumptiontaxamount_base Value"
				,xts_address4 = "xts_address4 Value"
				,xts_returnpurchasereceiptid = "xts_returnpurchasereceiptid Value"
				,owningteam = "owningteam Value"
				,xts_totalbaseamount = "xts_totalbaseamount Value"
				,statecode = "statecode Value"
				,xts_totalwithholdingtaxamount_base = "xts_totalwithholdingtaxamount_base Value"
				,ktb_updatetosparepartstockname = "ktb_updatetosparepartstockname Value"
				,xts_termsofpaymentidname = "xts_termsofpaymentidname Value"
				,timezoneruleversionnumber = "timezoneruleversionnumber Value"
				,xts_accountpayablevoucherid = "xts_accountpayablevoucherid Value"
				,xts_deliveryorderdate = "xts_deliveryorderdate Value"
				,ktb_paymentdate = "ktb_paymentdate Value"
				,ktb_goodissuedate = "ktb_goodissuedate Value"
				,ktb_ata = "ktb_ata Value"
				,xts_loaddata = "xts_loaddata Value"
				,xts_totalconsumptiontaxamount = "xts_totalconsumptiontaxamount Value"
				,xts_locking = "xts_locking Value"
				,xts_purchasereceiptnumber = "xts_purchasereceiptnumber Value"
				,ktb_salesorderno = "ktb_salesorderno Value"
				,ktb_pickingdate = "ktb_pickingdate Value"
				,xts_assignlandedcostperdetailname = "xts_assignlandedcostperdetailname Value"
				,xts_totaltitleregistrationfee_base = "xts_totaltitleregistrationfee_base Value"
				,xts_countryid = "xts_countryid Value"
				,ktb_duedate = "ktb_duedate Value"
				,xts_returnpurchasereceiptidname = "xts_returnpurchasereceiptidname Value"
				,traversedpath = "traversedpath Value"
				,createdonbehalfbyname = "createdonbehalfbyname Value"
				,xts_handling = "xts_handling Value"
				,xts_cityid = "xts_cityid Value"
				,createdonbehalfby = "createdonbehalfby Value"
				,xts_autoinvoicedname = "xts_autoinvoicedname Value"
				,utcconversiontimezonecode = "utcconversiontimezonecode Value"
				,xts_deliveryordernumber = "xts_deliveryordernumber Value"
				,xts_statusname = "xts_statusname Value"
				,xts_totaltitleregistrationfee = "xts_totaltitleregistrationfee Value"
				,ownerid = "ownerid Value"
				,modifiedon = "modifiedon Value"
				,importsequencenumber = "importsequencenumber Value"
				,owneridyominame = "owneridyominame Value"
				,xts_workorderidname = "xts_workorderidname Value"
				,xts_countryidname = "xts_countryidname Value"
				,xts_transferorderrequestingid = "xts_transferorderrequestingid Value"
				,xts_totalconsumptiontax1amount = "xts_totalconsumptiontax1amount Value"
				,xts_transactiondate = "xts_transactiondate Value"
				,ktb_isfactoring = "ktb_isfactoring Value"
				,xts_purchaseorderidname = "xts_purchaseorderidname Value"
				,xts_workorderid = "xts_workorderid Value"
				,xts_eventdata2 = "xts_eventdata2 Value"
				,createdbyname = "createdbyname Value"
				,ktb_interfacestatus = "ktb_interfacestatus Value"
				,xts_businessunitid = "xts_businessunitid Value"
				,ktb_deliveryfordeliverydate = "ktb_deliveryfordeliverydate Value"
				,modifiedonbehalfbyname = "modifiedonbehalfbyname Value"
				,xts_address3 = "xts_address3 Value"
				,ktb_invoicedate = "ktb_invoicedate Value"
				,ktb_estimationdeliverydate = "ktb_estimationdeliverydate Value"
				,xts_cityidname = "xts_cityidname Value"
				,xts_purchasereceiptid = "xts_purchasereceiptid Value"
				,xts_bigdata = "xts_bigdata Value"
				,ktb_ribbondataproductwarehouse = "ktb_ribbondataproductwarehouse Value"
				,processid = "processid Value"
				,xts_handlingname = "xts_handlingname Value"
				,xts_grandtotal = "xts_grandtotal Value"
				,xts_grandtotal_base = "xts_grandtotal_base Value"
				,xts_postalcode = "xts_postalcode Value"
				,transactioncurrencyid = "transactioncurrencyid Value"
				,xts_packingslipdate = "xts_packingslipdate Value"
				,xts_businessunitidname = "xts_businessunitidname Value"
				,createdby = "createdby Value"
				,ktb_isinterfaced = "ktb_isinterfaced Value"
				,modifiedby = "modifiedby Value"
				,xts_address1 = "xts_address1 Value"
				,ktb_ribbondata = "ktb_ribbondata Value"
				,stageid = "stageid Value"
				,xts_parentbusinessunitidname = "xts_parentbusinessunitidname Value"
				,ktb_identificationtype = "ktb_identificationtype Value"
				,createdbyyominame = "createdbyyominame Value"
				,owninguser = "owninguser Value"
				,transactioncurrencyidname = "transactioncurrencyidname Value"
				,createdonbehalfbyyominame = "createdonbehalfbyyominame Value"
				,ktb_prpotypeid = "ktb_prpotypeid Value"
				,owningbusinessunit = "owningbusinessunit Value"
				,xts_packingslipnumber = "xts_packingslipnumber Value"
				,xts_purchaseorderid = "xts_purchaseorderid Value"
				,ktb_purchaserequisitionidname = "ktb_purchaserequisitionidname Value"
				,ktb_isinterfacedname = "ktb_isinterfacedname Value"
				,xts_totalconsumptiontax2amount = "xts_totalconsumptiontax2amount Value"
				,ktb_interfacehandlingname = "ktb_interfacehandlingname Value"
				,xts_vendorid = "xts_vendorid Value"
				,xts_bigdataname = "xts_bigdataname Value"
				,ktb_expeditionnumber = "ktb_expeditionnumber Value"
				,statuscode = "statuscode Value"
				,modifiedonbehalfbyyominame = "modifiedonbehalfbyyominame Value"
				,ktb_conversiondays = "ktb_conversiondays Value"
				,xts_purchasereceiptreferencerequiredname = "xts_purchasereceiptreferencerequiredname Value"
				,xts_totalconsumptiontax2amount_base = "xts_totalconsumptiontax2amount_base Value"
				,ktb_discountpercentage = "ktb_discountpercentage Value"
				,xts_transferorderrequestingidname = "xts_transferorderrequestingidname Value"
				,ktb_returnreason = "ktb_returnreason Value"
				,ktb_prpotypeidname = "ktb_prpotypeidname Value"
				,statecodename = "statecodename Value"
				,xts_totalconsumptiontax1amount_base = "xts_totalconsumptiontax1amount_base Value"
				,xts_vendoridname = "xts_vendoridname Value"
				,ktb_eta = "ktb_eta Value"
				,ktb_atd = "ktb_atd Value"
				,ktb_kondisikendaraan = "ktb_kondisikendaraan Value"
				,ktb_endpoint = "ktb_endpoint Value"
				,msdyn_companycode = "msdyn_companycode Value"
            };

            return obj;
        }
    }
}