#region Summary
// ===========================================================================
// AUTHOR        : BSI Code Generator 
// SPECIAL NOTES : DNet WebApi Project
// ---------------------
// Copyright  (c) 2019 
// ---------------------
// $History      : $
// Created on 24/02/2020 18:15:44]
//
// ===========================================================================	
#endregion

using Swashbuckle.Examples;

namespace KTB.DNet.Interface.WebApi.Models.Examples
{
    public class APICreateVWI_CRM_xts_purchaseorderdetailExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var obj = new
            {
				UpdatedBy = "DealerUser"
				,company = "company Value"
				,businessunitcode = "businessunitcode Value"
				,xts_salesorderdetailsid = "xts_salesorderdetailsid Value"
				,xts_shippingdate = "xts_shippingdate Value"
				,xts_discountpercentage = "xts_discountpercentage Value"
				,bsi_discountreward_base = "bsi_discountreward_base Value"
				,bsi_interest_base = "bsi_interest_base Value"
				,xts_consumptiontax2id = "xts_consumptiontax2id Value"
				,xts_salesorderdetailidname = "xts_salesorderdetailidname Value"
				,xts_withholdingtaxidname = "xts_withholdingtaxidname Value"
				,xts_purchaserequisitiondetailid = "xts_purchaserequisitiondetailid Value"
				,xts_originalproductid = "xts_originalproductid Value"
				,modifiedon = "modifiedon Value"
				,xts_purchaseorderidname = "xts_purchaseorderidname Value"
				,overriddencreatedon = "overriddencreatedon Value"
				,xts_totalamount = "xts_totalamount Value"
				,statuscodename = "statuscodename Value"
				,ktb_consumptiontax1amountinterface_base = "ktb_consumptiontax1amountinterface_base Value"
				,ktb_bucompanyname = "ktb_bucompanyname Value"
				,ktb_logisticcost_base = "ktb_logisticcost_base Value"
				,ktb_basepriceamount_base = "ktb_basepriceamount_base Value"
				,ktb_interest_base = "ktb_interest_base Value"
				,xts_productdescription = "xts_productdescription Value"
				,xts_productweight = "xts_productweight Value"
				,xts_quantityorder = "xts_quantityorder Value"
				,xts_inventoryquantityreturn = "xts_inventoryquantityreturn Value"
				,ktb_discountreward = "ktb_discountreward Value"
				,ktb_customeridyominame = "ktb_customeridyominame Value"
				,ktb_discountname = "ktb_discountname Value"
				,transactioncurrencyidname = "transactioncurrencyidname Value"
				,xts_requireddate = "xts_requireddate Value"
				,xts_transactionamount_base = "xts_transactionamount_base Value"
				,xts_salesorderdetailsidname = "xts_salesorderdetailsidname Value"
				,xts_unitcost_base = "xts_unitcost_base Value"
				,xts_discountamount_base = "xts_discountamount_base Value"
				,ktb_interestamount = "ktb_interestamount Value"
				,ktb_materialdecription = "ktb_materialdecription Value"
				,ktb_logisticcost = "ktb_logisticcost Value"
				,ktb_customerid = "ktb_customerid Value"
				,xts_originalproductidname = "xts_originalproductidname Value"
				,xts_purchaseorderdetail = "xts_purchaseorderdetail Value"
				,ktb_materialnumber = "ktb_materialnumber Value"
				,xts_totalamountbeforediscount = "xts_totalamountbeforediscount Value"
				,xts_productcrossreferenceidname = "xts_productcrossreferenceidname Value"
				,xts_quantityreceipt = "xts_quantityreceipt Value"
				,ktb_ppnamount = "ktb_ppnamount Value"
				,modifiedonbehalfby = "modifiedonbehalfby Value"
				,statuscode = "statuscode Value"
				,xts_consumptiontax1amount = "xts_consumptiontax1amount Value"
				,xts_inventoryquantityorder = "xts_inventoryquantityorder Value"
				,xts_warehouseidname = "xts_warehouseidname Value"
				,ktb_netpricednet_base = "ktb_netpricednet_base Value"
				,ktb_orderno = "ktb_orderno Value"
				,ktb_pph22amount = "ktb_pph22amount Value"
				,xts_totalvolume = "xts_totalvolume Value"
				,xts_purchaseorderdetailid = "xts_purchaseorderdetailid Value"
				,xts_consumptiontax1idname = "xts_consumptiontax1idname Value"
				,xts_recallproductname = "xts_recallproductname Value"
				,statecodename = "statecodename Value"
				,xts_stockid = "xts_stockid Value"
				,xts_closereason = "xts_closereason Value"
				,exchangerate = "exchangerate Value"
				,xts_totalamount_base = "xts_totalamount_base Value"
				,xts_productexteriorcolorid = "xts_productexteriorcolorid Value"
				,xts_purchasefor = "xts_purchasefor Value"
				,ktb_totaldepositdnet = "ktb_totaldepositdnet Value"
				,xts_stockidname = "xts_stockidname Value"
				,ktb_pph22amount_base = "ktb_pph22amount_base Value"
				,xts_reasoncodeid = "xts_reasoncodeid Value"
				,createdon = "createdon Value"
				,xts_productvariantidname = "xts_productvariantidname Value"
				,ktb_orderconfirmationno = "ktb_orderconfirmationno Value"
				,owningbusinessunit = "owningbusinessunit Value"
				,xts_totalbaseamount_base = "xts_totalbaseamount_base Value"
				,ktb_bucompany = "ktb_bucompany Value"
				,xts_totalconsumptiontaxamount = "xts_totalconsumptiontaxamount Value"
				,xts_servicepartandmaterialidname = "xts_servicepartandmaterialidname Value"
				,xts_productvariantid = "xts_productvariantid Value"
				,xts_productid = "xts_productid Value"
				,owneridyominame = "owneridyominame Value"
				,xts_purchaseunitidname = "xts_purchaseunitidname Value"
				,modifiedby = "modifiedby Value"
				,timezoneruleversionnumber = "timezoneruleversionnumber Value"
				,xts_productexteriorcoloridname = "xts_productexteriorcoloridname Value"
				,xts_productinteriorcolorid = "xts_productinteriorcolorid Value"
				,xts_nvsoaccessoriesidname = "xts_nvsoaccessoriesidname Value"
				,xts_consumptiontax1amount_base = "xts_consumptiontax1amount_base Value"
				,xts_withholdingtaxid = "xts_withholdingtaxid Value"
				,xts_totalamountbeforediscount_base = "xts_totalamountbeforediscount_base Value"
				,ktb_isapprovedname = "ktb_isapprovedname Value"
				,xts_consumptiontax1id = "xts_consumptiontax1id Value"
				,xts_departmentidname = "xts_departmentidname Value"
				,xts_unitcost = "xts_unitcost Value"
				,ktb_customeridname = "ktb_customeridname Value"
				,xts_productsubstituteidname = "xts_productsubstituteidname Value"
				,xts_productvolume = "xts_productvolume Value"
				,xts_discountamount = "xts_discountamount Value"
				,xts_servicepartandmaterialid = "xts_servicepartandmaterialid Value"
				,ktb_pph23amount = "ktb_pph23amount Value"
				,createdonbehalfbyname = "createdonbehalfbyname Value"
				,owninguser = "owninguser Value"
				,xts_departmentid = "xts_departmentid Value"
				,xts_nvsoaccessoriesid = "xts_nvsoaccessoriesid Value"
				,xts_totalweight = "xts_totalweight Value"
				,owneridtype = "owneridtype Value"
				,xts_purchaseforname = "xts_purchaseforname Value"
				,xts_formsourcename = "xts_formsourcename Value"
				,bsi_discountreward = "bsi_discountreward Value"
				,ktb_interestamount_base = "ktb_interestamount_base Value"
				,xts_productconfigurationidname = "xts_productconfigurationidname Value"
				,xts_withholdingtaxamount = "xts_withholdingtaxamount Value"
				,owneridname = "owneridname Value"
				,ktb_salesorderidname = "ktb_salesorderidname Value"
				,modifiedonbehalfbyname = "modifiedonbehalfbyname Value"
				,createdonbehalfbyyominame = "createdonbehalfbyyominame Value"
				,xts_totalconsumptiontaxamount_base = "xts_totalconsumptiontaxamount_base Value"
				,xts_inventoryunitidname = "xts_inventoryunitidname Value"
				,xts_inventoryquantityreceipt = "xts_inventoryquantityreceipt Value"
				,xts_promiseddate = "xts_promiseddate Value"
				,owningteam = "owningteam Value"
				,ktb_salesorderid = "ktb_salesorderid Value"
				,xts_parentbusinessunitidname = "xts_parentbusinessunitidname Value"
				,xts_siteid = "xts_siteid Value"
				,ktb_nettinterest_base = "ktb_nettinterest_base Value"
				,xts_totalbaseamount = "xts_totalbaseamount Value"
				,createdonbehalfby = "createdonbehalfby Value"
				,xts_parentbusinessunitid = "xts_parentbusinessunitid Value"
				,transactioncurrencyid = "transactioncurrencyid Value"
				,ktb_basepriceamount = "ktb_basepriceamount Value"
				,ktb_discountdnet_base = "ktb_discountdnet_base Value"
				,xts_quantityreturn = "xts_quantityreturn Value"
				,xts_description = "xts_description Value"
				,ktb_pph23amount_base = "ktb_pph23amount_base Value"
				,xts_productidname = "xts_productidname Value"
				,ktb_discountreward_base = "ktb_discountreward_base Value"
				,xts_consumptiontax2amount = "xts_consumptiontax2amount Value"
				,xts_warehouseid = "xts_warehouseid Value"
				,xts_formsource = "xts_formsource Value"
				,modifiedbyyominame = "modifiedbyyominame Value"
				,ownerid = "ownerid Value"
				,ktb_nettinterest = "ktb_nettinterest Value"
				,xts_salesorderdetailid = "xts_salesorderdetailid Value"
				,xts_productsubstituteid = "xts_productsubstituteid Value"
				,xts_titleregistrationfee = "xts_titleregistrationfee Value"
				,ktb_endpoint = "ktb_endpoint Value"
				,createdbyname = "createdbyname Value"
				,xts_businessunitidname = "xts_businessunitidname Value"
				,statecode = "statecode Value"
				,xts_siteidname = "xts_siteidname Value"
				,xts_productinteriorcoloridname = "xts_productinteriorcoloridname Value"
				,modifiedonbehalfbyyominame = "modifiedonbehalfbyyominame Value"
				,createdby = "createdby Value"
				,ktb_consumptiontax1amountinterface = "ktb_consumptiontax1amountinterface Value"
				,xts_purchaseorderid = "xts_purchaseorderid Value"
				,ktb_netpricednet = "ktb_netpricednet Value"
				,xts_inventoryunitid = "xts_inventoryunitid Value"
				,xts_referencenumber = "xts_referencenumber Value"
				,ktb_interest = "ktb_interest Value"
				,utcconversiontimezonecode = "utcconversiontimezonecode Value"
				,xts_completedname = "xts_completedname Value"
				,ktb_discountdnet = "ktb_discountdnet Value"
				,xts_productstyleid = "xts_productstyleid Value"
				,ktb_applicationno = "ktb_applicationno Value"
				,xts_recallproduct = "xts_recallproduct Value"
				,bsi_interest = "bsi_interest Value"
				,xts_completed = "xts_completed Value"
				,importsequencenumber = "importsequencenumber Value"
				,xts_locking = "xts_locking Value"
				,xts_consumptiontax2idname = "xts_consumptiontax2idname Value"
				,ktb_totaldepositdnet_base = "ktb_totaldepositdnet_base Value"
				,xts_productcrossreferenceid = "xts_productcrossreferenceid Value"
				,ktb_depositamount_base = "ktb_depositamount_base Value"
				,xts_consumptiontax2amount_base = "xts_consumptiontax2amount_base Value"
				,versionnumber = "versionnumber Value"
				,xts_businessunitid = "xts_businessunitid Value"
				,xts_purchaseunitid = "xts_purchaseunitid Value"
				,xts_titleregistrationfee_base = "xts_titleregistrationfee_base Value"
				,xts_purchaserequisitiondetailidname = "xts_purchaserequisitiondetailidname Value"
				,xts_closeline = "xts_closeline Value"
				,xts_productconfigurationid = "xts_productconfigurationid Value"
				,ktb_depositamount = "ktb_depositamount Value"
				,modifiedbyname = "modifiedbyname Value"
				,createdbyyominame = "createdbyyominame Value"
				,xts_closelinename = "xts_closelinename Value"
				,xts_transactionamount = "xts_transactionamount Value"
				,xts_withholdingtaxamount_base = "xts_withholdingtaxamount_base Value"
				,ktb_productsap = "ktb_productsap Value"
				,ktb_isapproved = "ktb_isapproved Value"
				,ktb_ppnamount_base = "ktb_ppnamount_base Value"
				,xts_eventdata = "xts_eventdata Value"
				,xts_scheduledshippingdate = "xts_scheduledshippingdate Value"
				,xts_reasoncodeidname = "xts_reasoncodeidname Value"
				,xts_productstyleidname = "xts_productstyleidname Value"
				,msdyn_companycode = "msdyn_companycode Value"
            };

            return obj;
        }
    }
}