#region Summary
// ===========================================================================
// AUTHOR        : BSI Code Generator 
// SPECIAL NOTES : DNet WebApi Project
// ---------------------
// Copyright  (c) 2019 
// ---------------------
// $History      : $
// Created on 24/02/2020 18:15:44]
//
// ===========================================================================	
#endregion

using Swashbuckle.Examples;

namespace KTB.DNet.Interface.WebApi.Models.Examples
{
    public class APICreateVWI_CRM_campaignresponseExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var obj = new
            {
				UpdatedBy = "DealerUser"
				,company = "company Value"
				,businessunitcode = "businessunitcode Value"
				,xts_subject = "xts_subject Value"
				,scheduledend = "scheduledend Value"
				,slaid = "slaid Value"
				,modifiedon = "modifiedon Value"
				,scheduledstart = "scheduledstart Value"
				,overriddencreatedon = "overriddencreatedon Value"
				,statuscodename = "statuscodename Value"
				,senton = "senton Value"
				,activityadditionalparams = "activityadditionalparams Value"
				,xts_mobilephone = "xts_mobilephone Value"
				,subcategory = "subcategory Value"
				,responsecodename = "responsecodename Value"
				,seriesid = "seriesid Value"
				,transactioncurrencyidname = "transactioncurrencyidname Value"
				,requiredattendees = "requiredattendees Value"
				,exchangeweblink = "exchangeweblink Value"
				,xts_postalcode = "xts_postalcode Value"
				,slainvokedid = "slainvokedid Value"
				,customers = "customers Value"
				,isworkflowcreated = "isworkflowcreated Value"
				,postponeactivityprocessinguntil = "postponeactivityprocessinguntil Value"
				,scheduleddurationminutes = "scheduleddurationminutes Value"
				,owningbusinessunit = "owningbusinessunit Value"
				,prioritycodename = "prioritycodename Value"
				,to = "to Value"
				,activitytypecodename = "activitytypecodename Value"
				,community = "community Value"
				,channeltypecodename = "channeltypecodename Value"
				,instancetypecode = "instancetypecode Value"
				,statuscode = "statuscode Value"
				,onholdtime = "onholdtime Value"
				,statecode = "statecode Value"
				,ismapiprivatename = "ismapiprivatename Value"
				,bcc = "bcc Value"
				,versionnumber = "versionnumber Value"
				,statecodename = "statecodename Value"
				,lastonholdtime = "lastonholdtime Value"
				,exchangerate = "exchangerate Value"
				,ownerid = "ownerid Value"
				,xts_productexteriorcolorid = "xts_productexteriorcolorid Value"
				,activityid = "activityid Value"
				,companyname = "companyname Value"
				,communityname = "communityname Value"
				,category = "category Value"
				,isbilled = "isbilled Value"
				,createdon = "createdon Value"
				,isworkflowcreatedname = "isworkflowcreatedname Value"
				,slaname = "slaname Value"
				,isregularactivityname = "isregularactivityname Value"
				,originatingactivityid = "originatingactivityid Value"
				,leftvoicemailname = "leftvoicemailname Value"
				,firstname = "firstname Value"
				,customer = "customer Value"
				,exchangeitemid = "exchangeitemid Value"
				,actualstart = "actualstart Value"
				,xts_salesobjective = "xts_salesobjective Value"
				,xts_productid = "xts_productid Value"
				,owneridyominame = "owneridyominame Value"
				,xts_vehiclemodelid = "xts_vehiclemodelid Value"
				,xts_countryid = "xts_countryid Value"
				,description = "description Value"
				,modifiedby = "modifiedby Value"
				,xts_manufacturerid = "xts_manufacturerid Value"
				,isregularactivity = "isregularactivity Value"
				,xts_productexteriorcoloridname = "xts_productexteriorcoloridname Value"
				,xts_address1 = "xts_address1 Value"
				,modifiedonbehalfby = "modifiedonbehalfby Value"
				,promotioncodename = "promotioncodename Value"
				,xts_customernumber = "xts_customernumber Value"
				,yomilastname = "yomilastname Value"
				,ismapiprivate = "ismapiprivate Value"
				,owningteam = "owningteam Value"
				,partners = "partners Value"
				,traversedpath = "traversedpath Value"
				,isbilledname = "isbilledname Value"
				,xts_aliasname = "xts_aliasname Value"
				,createdonbehalfbyname = "createdonbehalfbyname Value"
				,owninguser = "owninguser Value"
				,optionalattendees = "optionalattendees Value"
				,sortdate = "sortdate Value"
				,owneridtype = "owneridtype Value"
				,instancetypecodename = "instancetypecodename Value"
				,sendermailboxid = "sendermailboxid Value"
				,xts_website = "xts_website Value"
				,regardingobjectid = "regardingobjectid Value"
				,modifiedonbehalfbyname = "modifiedonbehalfbyname Value"
				,createdonbehalfbyyominame = "createdonbehalfbyyominame Value"
				,leftvoicemail = "leftvoicemail Value"
				,timezoneruleversionnumber = "timezoneruleversionnumber Value"
				,actualend = "actualend Value"
				,xts_firstname = "xts_firstname Value"
				,regardingobjectidname = "regardingobjectidname Value"
				,xts_vehiclemodelidname = "xts_vehiclemodelidname Value"
				,deliveryprioritycodename = "deliveryprioritycodename Value"
				,processid = "processid Value"
				,createdonbehalfby = "createdonbehalfby Value"
				,actualdurationminutes = "actualdurationminutes Value"
				,emailaddress = "emailaddress Value"
				,deliveryprioritycode = "deliveryprioritycode Value"
				,transactioncurrencyid = "transactioncurrencyid Value"
				,activitytypecode = "activitytypecode Value"
				,xts_vehiclebrandid = "xts_vehiclebrandid Value"
				,xts_cityid = "xts_cityid Value"
				,resources = "resources Value"
				,responsecode = "responsecode Value"
				,xts_productidname = "xts_productidname Value"
				,slainvokedidname = "slainvokedidname Value"
				,fax = "fax Value"
				,sendermailboxidname = "sendermailboxidname Value"
				,xts_vehiclebrandidname = "xts_vehiclebrandidname Value"
				,deliverylastattemptedon = "deliverylastattemptedon Value"
				,channeltypecode = "channeltypecode Value"
				,xts_provinceidname = "xts_provinceidname Value"
				,subject = "subject Value"
				,xts_manufactureridname = "xts_manufactureridname Value"
				,createdbyname = "createdbyname Value"
				,xts_businessunitidname = "xts_businessunitidname Value"
				,modifiedbyyominame = "modifiedbyyominame Value"
				,from = "from Value"
				,yomifirstname = "yomifirstname Value"
				,createdby = "createdby Value"
				,xts_salesobjectivename = "xts_salesobjectivename Value"
				,originatingactivityname = "originatingactivityname Value"
				,regardingobjectidyominame = "regardingobjectidyominame Value"
				,regardingobjecttypecode = "regardingobjecttypecode Value"
				,xts_homephone = "xts_homephone Value"
				,prioritycode = "prioritycode Value"
				,xts_countryidname = "xts_countryidname Value"
				,stageid = "stageid Value"
				,utcconversiontimezonecode = "utcconversiontimezonecode Value"
				,partner = "partner Value"
				,importsequencenumber = "importsequencenumber Value"
				,xts_locking = "xts_locking Value"
				,originatingactivityidtypecode = "originatingactivityidtypecode Value"
				,xts_address2 = "xts_address2 Value"
				,xts_businessunitid = "xts_businessunitid Value"
				,receivedon = "receivedon Value"
				,cc = "cc Value"
				,yomicompanyname = "yomicompanyname Value"
				,xts_provinceid = "xts_provinceid Value"
				,modifiedbyname = "modifiedbyname Value"
				,createdbyyominame = "createdbyyominame Value"
				,owneridname = "owneridname Value"
				,telephone = "telephone Value"
				,serviceid = "serviceid Value"
				,xts_villageandstreetidname = "xts_villageandstreetidname Value"
				,lastname = "lastname Value"
				,xts_address4 = "xts_address4 Value"
				,xts_cityidname = "xts_cityidname Value"
				,modifiedonbehalfbyyominame = "modifiedonbehalfbyyominame Value"
				,xts_address3 = "xts_address3 Value"
				,organizer = "organizer Value"
				,xts_villageandstreetid = "xts_villageandstreetid Value"
				,xts_otherphone = "xts_otherphone Value"
				,msdyn_companycode = "msdyn_companycode Value"
            };

            return obj;
        }
    }
}