#region Summary
// ===========================================================================
// AUTHOR        : BSI Code Generator 
// SPECIAL NOTES : DNet WebApi Project
// ---------------------
// Copyright  (c) 2019 
// ---------------------
// $History      : $
// Created on 12/18/2019 10:09:30 AM]
//
// ===========================================================================	
#endregion

using Swashbuckle.Examples;

namespace KTB.DNet.Interface.WebApi.Models.Examples
{
    public class APICreateVWI_CRM_xts_sharedproductExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var obj = new
            {
				UpdatedBy = "DealerUser"
				,ktb_nongenuinecategory = "ktb_nongenuinecategory Value"
				,xts_defaultunitidname = "xts_defaultunitidname Value"
				,versionnumber = "versionnumber Value"
				,createdon = "createdon Value"
				,ktb_indicator = "ktb_indicator Value"
				,xts_purchaseprice_base = "xts_purchaseprice_base Value"
				,xts_interiorcolorid = "xts_interiorcolorid Value"
				,xts_stockbaseprice_base = "xts_stockbaseprice_base Value"
				,statuscodename = "statuscodename Value"
				,xts_productvolume = "xts_productvolume Value"
				,xts_description = "xts_description Value"
				,xts_manufacturer = "xts_manufacturer Value"
				,xts_axproducttype = "xts_axproducttype Value"
				,xts_recordtypename = "xts_recordtypename Value"
				,xts_gradenumber = "xts_gradenumber Value"
				,xts_servicefee_base = "xts_servicefee_base Value"
				,modifiedbyname = "modifiedbyname Value"
				,xjp_weighttaxreduction = "xjp_weighttaxreduction Value"
				,xts_servicefee = "xts_servicefee Value"
				,xts_visibilityname = "xts_visibilityname Value"
				,ktb_fixedpricename = "ktb_fixedpricename Value"
				,xts_internalnumber = "xts_internalnumber Value"
				,xts_defaultbrand = "xts_defaultbrand Value"
				,overriddencreatedon = "overriddencreatedon Value"
				,xts_productsegment1id = "xts_productsegment1id Value"
				,xts_partprice_base = "xts_partprice_base Value"
				,xts_salesunitidname = "xts_salesunitidname Value"
				,xts_interiorcoloridname = "xts_interiorcoloridname Value"
				,xts_type = "xts_type Value"
				,xts_gradeid = "xts_gradeid Value"
				,xts_eventdata = "xts_eventdata Value"
				,xts_styleidname = "xts_styleidname Value"
				,xts_product = "xts_product Value"
				,exchangerate = "exchangerate Value"
				,xjp_additionalairbagfee = "xjp_additionalairbagfee Value"
				,xts_exteriorcoloridname = "xts_exteriorcoloridname Value"
				,xts_productsegment3idname = "xts_productsegment3idname Value"
				,xts_taxcategoryname = "xts_taxcategoryname Value"
				,ktb_category = "ktb_category Value"
				,xts_generation = "xts_generation Value"
				,xts_styleid = "xts_styleid Value"
				,xjp_airbagrates_base = "xjp_airbagrates_base Value"
				,statecode = "statecode Value"
				,xjp_additionalairbagfee_base = "xjp_additionalairbagfee_base Value"
				,ktb_categoryname = "ktb_categoryname Value"
				,xts_company = "xts_company Value"
				,xts_sharedproductreferenceimportstring = "xts_sharedproductreferenceimportstring Value"
				,timezoneruleversionnumber = "timezoneruleversionnumber Value"
				,ktb_nongenuinecategoryid = "ktb_nongenuinecategoryid Value"
				,xts_partprice = "xts_partprice Value"
				,xjp_fluorocarbonfee_base = "xjp_fluorocarbonfee_base Value"
				,xts_kittypename = "xts_kittypename Value"
				,xts_productsegment4idname = "xts_productsegment4idname Value"
				,xts_productweight = "xts_productweight Value"
				,xjp_airbagrates = "xjp_airbagrates Value"
				,ktb_indicatorname = "ktb_indicatorname Value"
				,xts_visibility = "xts_visibility Value"
				,xts_purchaseprice = "xts_purchaseprice Value"
				,ktb_nongenuinecategoryname = "ktb_nongenuinecategoryname Value"
				,xts_description2 = "xts_description2 Value"
				,xjp_acquisitiontaxreduction = "xjp_acquisitiontaxreduction Value"
				,xjp_additionalfluorocarbonfee = "xjp_additionalfluorocarbonfee Value"
				,xts_sharedproductid = "xts_sharedproductid Value"
				,xjp_lightcarflagname = "xjp_lightcarflagname Value"
				,createdonbehalfbyname = "createdonbehalfbyname Value"
				,xts_chassismodel = "xts_chassismodel Value"
				,xts_sharedproductreferenceidname = "xts_sharedproductreferenceidname Value"
				,xts_productsegment1idname = "xts_productsegment1idname Value"
				,xts_defaultvehiclebrandid = "xts_defaultvehiclebrandid Value"
				,xts_classificationnumber = "xts_classificationnumber Value"
				,utcconversiontimezonecode = "utcconversiontimezonecode Value"
				,xts_productclassid = "xts_productclassid Value"
				,xts_configurationid = "xts_configurationid Value"
				,xts_typename = "xts_typename Value"
				,xts_additionalvariantprice_base = "xts_additionalvariantprice_base Value"
				,xts_defaultvehiclebrandidname = "xts_defaultvehiclebrandidname Value"
				,modifiedon = "modifiedon Value"
				,importsequencenumber = "importsequencenumber Value"
				,ktb_modelcode = "ktb_modelcode Value"
				,xts_exteriorcolorid = "xts_exteriorcolorid Value"
				,xts_axproducttypename = "xts_axproducttypename Value"
				,xts_additionalvariantpurchaseprice_base = "xts_additionalvariantpurchaseprice_base Value"
				,ktb_typecode = "ktb_typecode Value"
				,createdonbehalfby = "createdonbehalfby Value"
				,ktb_fixedprice = "ktb_fixedprice Value"
				,createdbyname = "createdbyname Value"
				,xts_sharedproductreferenceid = "xts_sharedproductreferenceid Value"
				,modifiedonbehalfbyname = "modifiedonbehalfbyname Value"
				,xts_defaultunitid = "xts_defaultunitid Value"
				,xts_productsegment4id = "xts_productsegment4id Value"
				,xts_additionalvariantprice = "xts_additionalvariantprice Value"
				,xts_stockbaseprice = "xts_stockbaseprice Value"
				,xjp_shredderdustfee_base = "xjp_shredderdustfee_base Value"
				,xts_gradeidname = "xts_gradeidname Value"
				,xts_productclassidname = "xts_productclassidname Value"
				,xts_productsegment2id = "xts_productsegment2id Value"
				,transactioncurrencyid = "transactioncurrencyid Value"
				,createdby = "createdby Value"
				,modifiedby = "modifiedby Value"
				,xjp_productsubsidycategory = "xjp_productsubsidycategory Value"
				,xts_purchaseunitid = "xts_purchaseunitid Value"
				,xts_additionalvariantpurchaseprice = "xts_additionalvariantpurchaseprice Value"
				,xjp_automobiletaxreduction = "xjp_automobiletaxreduction Value"
				,createdbyyominame = "createdbyyominame Value"
				,transactioncurrencyidname = "transactioncurrencyidname Value"
				,xts_entitytag = "xts_entitytag Value"
				,createdonbehalfbyyominame = "createdonbehalfbyyominame Value"
				,modifiedonbehalfby = "modifiedonbehalfby Value"
				,xjp_lightcarflag = "xjp_lightcarflag Value"
				,xts_purchaseunitidname = "xts_purchaseunitidname Value"
				,modifiedbyyominame = "modifiedbyyominame Value"
				,xjp_generationdate = "xjp_generationdate Value"
				,xjp_shredderdustfee = "xjp_shredderdustfee Value"
				,xjp_additionalfluorocarbonfee_base = "xjp_additionalfluorocarbonfee_base Value"
				,xts_productfamily = "xts_productfamily Value"
				,xts_productsegment3id = "xts_productsegment3id Value"
				,statuscode = "statuscode Value"
				,modifiedonbehalfbyyominame = "modifiedonbehalfbyyominame Value"
				,xts_configurationidname = "xts_configurationidname Value"
				,organizationid = "organizationid Value"
				,xts_defaultbrandgeneration = "xts_defaultbrandgeneration Value"
				,xjp_fluorocarbonfee = "xjp_fluorocarbonfee Value"
				,xts_productsegment2idname = "xts_productsegment2idname Value"
				,organizationidname = "organizationidname Value"
				,ktb_nongenuinecategoryidname = "ktb_nongenuinecategoryidname Value"
				,xts_kittype = "xts_kittype Value"
				,xts_taxcategory = "xts_taxcategory Value"
				,statecodename = "statecodename Value"
				,xts_salesunitid = "xts_salesunitid Value"
				,xts_recordtype = "xts_recordtype Value"
				,xts_modelspecification = "xts_modelspecification Value"
            };

            return obj;
        }
    }
}