#region Summary
// ===========================================================================
// AUTHOR        : BSI Code Generator 
// SPECIAL NOTES : DNet WebApi Project
// ---------------------
// Copyright  (c) 2019 
// ---------------------
// $History      : $
// Created on 12/18/2019 10:09:30 AM]
//
// ===========================================================================	
#endregion

using Swashbuckle.Examples;

namespace KTB.DNet.Interface.WebApi.Models.Examples
{
    public class APICreateVWI_CRM_xts_productExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var obj = new
            {
				UpdatedBy = "DealerUser"
				,xts_gradeid = "xts_gradeid Value"
				,xjp_storecostrate = "xjp_storecostrate Value"
				,bsi_productclassroundingname = "bsi_productclassroundingname Value"
				,xts_defaultunitid = "xts_defaultunitid Value"
				,modifiedon = "modifiedon Value"
				,xts_manufacturer = "xts_manufacturer Value"
				,overriddencreatedon = "overriddencreatedon Value"
				,xts_salesunitid = "xts_salesunitid Value"
				,xts_purchaseprice_base = "xts_purchaseprice_base Value"
				,statuscodename = "statuscodename Value"
				,ktb_latestpurchaseprice_base = "ktb_latestpurchaseprice_base Value"
				,xts_servicefee_base = "xts_servicefee_base Value"
				,xjp_weighttaxreduction = "xjp_weighttaxreduction Value"
				,xts_sharedproductid = "xts_sharedproductid Value"
				,xts_productweight = "xts_productweight Value"
				,xts_axproducttype = "xts_axproducttype Value"
				,xjp_hqexpense_base = "xjp_hqexpense_base Value"
				,transactioncurrencyidname = "transactioncurrencyidname Value"
				,xts_chassismodel = "xts_chassismodel Value"
				,xjp_additionalfluorocarbonfee_base = "xjp_additionalfluorocarbonfee_base Value"
				,ktb_indicator = "ktb_indicator Value"
				,xts_type = "xts_type Value"
				,xjp_airbagrates = "xjp_airbagrates Value"
				,xjp_automobiletaxreduction = "xjp_automobiletaxreduction Value"
				,xjp_additionalfluorocarbonfee = "xjp_additionalfluorocarbonfee Value"
				,xts_company = "xts_company Value"
				,xjp_shredderdustfee_base = "xjp_shredderdustfee_base Value"
				,xts_defaultunitidname = "xts_defaultunitidname Value"
				,xjp_additionalairbagfee_base = "xjp_additionalairbagfee_base Value"
				,ktb_isinterfaced = "ktb_isinterfaced Value"
				,xts_methodforsalesordername = "xts_methodforsalesordername Value"
				,xts_productsegment2id = "xts_productsegment2id Value"
				,xts_defaultvehiclebrandidname = "xts_defaultvehiclebrandidname Value"
				,statuscode = "statuscode Value"
				,xts_stoppedforsales = "xts_stoppedforsales Value"
				,xts_stoppedforpurchasename = "xts_stoppedforpurchasename Value"
				,xts_locking = "xts_locking Value"
				,versionnumber = "versionnumber Value"
				,statecodename = "statecodename Value"
				,xjp_acquisitiontaxreduction = "xjp_acquisitiontaxreduction Value"
				,xts_partprice = "xts_partprice Value"
				,xts_stockbaseprice = "xts_stockbaseprice Value"
				,exchangerate = "exchangerate Value"
				,xts_internalnumber = "xts_internalnumber Value"
				,bsi_productclassrounding = "bsi_productclassrounding Value"
				,ktb_fixedpricename = "ktb_fixedpricename Value"
				,xts_entitytag = "xts_entitytag Value"
				,xts_sharedproductidname = "xts_sharedproductidname Value"
				,xts_description2 = "xts_description2 Value"
				,createdon = "createdon Value"
				,xts_classificationnumber = "xts_classificationnumber Value"
				,xts_methodforworkordername = "xts_methodforworkordername Value"
				,xts_productsegment4id = "xts_productsegment4id Value"
				,xjp_airbagrates_base = "xjp_airbagrates_base Value"
				,xts_stoppedforinventory = "xts_stoppedforinventory Value"
				,bsi_producttypeid = "bsi_producttypeid Value"
				,xts_methodforworkorder = "xts_methodforworkorder Value"
				,xts_defaultbrandgeneration = "xts_defaultbrandgeneration Value"
				,xts_gradeidname = "xts_gradeidname Value"
				,ktb_sourcename = "ktb_sourcename Value"
				,ktb_latestpurchasepricedate = "ktb_latestpurchasepricedate Value"
				,xts_productid = "xts_productid Value"
				,xts_productsegment1id = "xts_productsegment1id Value"
				,xts_purchaseunitidname = "xts_purchaseunitidname Value"
				,xjp_shredderdustfee = "xjp_shredderdustfee Value"
				,xts_defaultvehiclebrandid = "xts_defaultvehiclebrandid Value"
				,modifiedby = "modifiedby Value"
				,xts_inventoryprice_base = "xts_inventoryprice_base Value"
				,timezoneruleversionnumber = "timezoneruleversionnumber Value"
				,modifiedonbehalfby = "modifiedonbehalfby Value"
				,xts_kittypename = "xts_kittypename Value"
				,xts_salesunitidname = "xts_salesunitidname Value"
				,ktb_latestpurchaseprice = "ktb_latestpurchaseprice Value"
				,xts_productvolume = "xts_productvolume Value"
				,ktb_categoryname = "ktb_categoryname Value"
				,xjp_lightcarflag = "xjp_lightcarflag Value"
				,createdonbehalfbyname = "createdonbehalfbyname Value"
				,xts_partprice_base = "xts_partprice_base Value"
				,xts_productsegment2idname = "xts_productsegment2idname Value"
				,xjp_fluorocarbonfee = "xjp_fluorocarbonfee Value"
				,xts_productclassidname = "xts_productclassidname Value"
				,xts_stoppedforsalesname = "xts_stoppedforsalesname Value"
				,ktb_vehiclemodelid = "ktb_vehiclemodelid Value"
				,modifiedonbehalfbyname = "modifiedonbehalfbyname Value"
				,createdonbehalfbyyominame = "createdonbehalfbyyominame Value"
				,xts_defaultbrand = "xts_defaultbrand Value"
				,bsi_producttypeidname = "bsi_producttypeidname Value"
				,xts_productsegment3id = "xts_productsegment3id Value"
				,xts_generation = "xts_generation Value"
				,xts_product = "xts_product Value"
				,xts_productclassid = "xts_productclassid Value"
				,xts_servicefee = "xts_servicefee Value"
				,xts_productsegment4idname = "xts_productsegment4idname Value"
				,xts_description = "xts_description Value"
				,ktb_vehicletypecode = "ktb_vehicletypecode Value"
				,xts_recordtype = "xts_recordtype Value"
				,ktb_isinterfacedname = "ktb_isinterfacedname Value"
				,xts_transactiondetails_json = "xts_transactiondetails_json Value"
				,createdonbehalfby = "createdonbehalfby Value"
				,transactioncurrencyid = "transactioncurrencyid Value"
				,xts_eventdata = "xts_eventdata Value"
				,ktb_category = "ktb_category Value"
				,ktb_fixedprice = "ktb_fixedprice Value"
				,ktb_vehiclemodelidname = "ktb_vehiclemodelidname Value"
				,ktb_source = "ktb_source Value"
				,organizationid = "organizationid Value"
				,ktb_typecode = "ktb_typecode Value"
				,xts_stockbaseprice_base = "xts_stockbaseprice_base Value"
				,xts_modelspecification = "xts_modelspecification Value"
				,xts_inventoryprice = "xts_inventoryprice Value"
				,xts_stoppedforpurchase = "xts_stoppedforpurchase Value"
				,xts_gradenumber = "xts_gradenumber Value"
				,xjp_additionalairbagfee = "xjp_additionalairbagfee Value"
				,createdbyname = "createdbyname Value"
				,modifiedbyyominame = "modifiedbyyominame Value"
				,ktb_nongenuinecategory = "ktb_nongenuinecategory Value"
				,modifiedonbehalfbyyominame = "modifiedonbehalfbyyominame Value"
				,createdby = "createdby Value"
				,xts_fixedpricename = "xts_fixedpricename Value"
				,xts_axproducttypename = "xts_axproducttypename Value"
				,xts_productsegment1idname = "xts_productsegment1idname Value"
				,xts_taxcategoryname = "xts_taxcategoryname Value"
				,xts_stoppedforinventoryname = "xts_stoppedforinventoryname Value"
				,ktb_indicatorname = "ktb_indicatorname Value"
				,utcconversiontimezonecode = "utcconversiontimezonecode Value"
				,xjp_lightcarflagname = "xjp_lightcarflagname Value"
				,xts_fixedprice = "xts_fixedprice Value"
				,ktb_nongenuinecategoryname = "ktb_nongenuinecategoryname Value"
				,xts_productsegment3idname = "xts_productsegment3idname Value"
				,new_internalnumber = "new_internalnumber Value"
				,xjp_generationdate = "xjp_generationdate Value"
				,xts_landedcostgroup = "xts_landedcostgroup Value"
				,xjp_productsubsidycategory = "xjp_productsubsidycategory Value"
				,importsequencenumber = "importsequencenumber Value"
				,xts_kittype = "xts_kittype Value"
				,ktb_nongenuinecategoryidname = "ktb_nongenuinecategoryidname Value"
				,organizationidname = "organizationidname Value"
				,ktb_modelcode = "ktb_modelcode Value"
				,xts_purchaseunitid = "xts_purchaseunitid Value"
				,xts_typename = "xts_typename Value"
				,ktb_nongenuinecategoryid = "ktb_nongenuinecategoryid Value"
				,modifiedbyname = "modifiedbyname Value"
				,createdbyyominame = "createdbyyominame Value"
				,xjp_hqexpense = "xjp_hqexpense Value"
				,xts_purchaseprice = "xts_purchaseprice Value"
				,xts_taxcategory = "xts_taxcategory Value"
				,xts_methodforsalesorder = "xts_methodforsalesorder Value"
				,xjp_fluorocarbonfee_base = "xjp_fluorocarbonfee_base Value"
				,xts_recordtypename = "xts_recordtypename Value"
				,statecode = "statecode Value"
            };

            return obj;
        }
    }
}