#region Summary
// ===========================================================================
// AUTHOR        : BSI Code Generator 
// SPECIAL NOTES : DNet WebApi Project
// ---------------------
// Copyright  (c) 2019 
// ---------------------
// $History      : $
// Created on 13/01/2020 9:21:47]
//
// ===========================================================================	
#endregion

using Swashbuckle.Examples;

namespace KTB.DNet.Interface.WebApi.Models.Examples
{
    public class APICreateVWI_CRM_xts_deliveryorderdetailExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var obj = new
            {
				UpdatedBy = "DealerUser"
				,company = "company Value"
				,businessunitcode = "businessunitcode Value"
				,xts_stockidname = "xts_stockidname Value"
				,xts_parentbusinessunitid = "xts_parentbusinessunitid Value"
				,versionnumber = "versionnumber Value"
				,createdon = "createdon Value"
				,xts_amountbeforediscount_base = "xts_amountbeforediscount_base Value"
				,xts_withholdingtaxid = "xts_withholdingtaxid Value"
				,xts_interiorcolorid = "xts_interiorcolorid Value"
				,xts_consumptiontax1id = "xts_consumptiontax1id Value"
				,statuscodename = "statuscodename Value"
				,xts_baseamount_base = "xts_baseamount_base Value"
				,xts_unitprice = "xts_unitprice Value"
				,xts_discountbaseamount_base = "xts_discountbaseamount_base Value"
				,modifiedbyyominame = "modifiedbyyominame Value"
				,xts_quantityorder = "xts_quantityorder Value"
				,xts_productcrossreferenceid = "xts_productcrossreferenceid Value"
				,owneridtype = "owneridtype Value"
				,createdonbehalfby = "createdonbehalfby Value"
				,xts_exteriorcoloridname = "xts_exteriorcoloridname Value"
				,modifiedbyname = "modifiedbyname Value"
				,xts_discountpercentage = "xts_discountpercentage Value"
				,xts_promisedate = "xts_promisedate Value"
				,xts_deliveryorderdetail = "xts_deliveryorderdetail Value"
				,xts_inventoryunitid = "xts_inventoryunitid Value"
				,owneridname = "owneridname Value"
				,overriddencreatedon = "overriddencreatedon Value"
				,xts_deliveryorderid = "xts_deliveryorderid Value"
				,xts_salesunitidname = "xts_salesunitidname Value"
				,xts_interiorcoloridname = "xts_interiorcoloridname Value"
				,xts_quantityreturned = "xts_quantityreturned Value"
				,ktb_cogs_base = "ktb_cogs_base Value"
				,createdonbehalfbyyominame = "createdonbehalfbyyominame Value"
				,modifiedonbehalfby = "modifiedonbehalfby Value"
				,exchangerate = "exchangerate Value"
				,xts_totalconsumptiontaxamount_base = "xts_totalconsumptiontaxamount_base Value"
				,xts_transactionamount_base = "xts_transactionamount_base Value"
				,xts_consumptiontax2id = "xts_consumptiontax2id Value"
				,owningteam = "owningteam Value"
				,xts_stockid = "xts_stockid Value"
				,xts_serialidname = "xts_serialidname Value"
				,xts_productidname = "xts_productidname Value"
				,xts_styleid = "xts_styleid Value"
				,statecode = "statecode Value"
				,xts_serialid = "xts_serialid Value"
				,xts_amountbeforediscount = "xts_amountbeforediscount Value"
				,xts_consumptiontax1amount_base = "xts_consumptiontax1amount_base Value"
				,timezoneruleversionnumber = "timezoneruleversionnumber Value"
				,xts_basequantitydelivered = "xts_basequantitydelivered Value"
				,xts_requestdate = "xts_requestdate Value"
				,xts_basequantityreturned = "xts_basequantityreturned Value"
				,ktb_chassisnumber = "ktb_chassisnumber Value"
				,xts_warehouseidname = "xts_warehouseidname Value"
				,xts_totalconsumptiontaxamount = "xts_totalconsumptiontaxamount Value"
				,xts_locking = "xts_locking Value"
				,xts_salesorderdetailid = "xts_salesorderdetailid Value"
				,xts_siteidname = "xts_siteidname Value"
				,xts_withholdingtaxidname = "xts_withholdingtaxidname Value"
				,xts_totalamount_base = "xts_totalamount_base Value"
				,createdonbehalfbyname = "createdonbehalfbyname Value"
				,xts_consumptiontax2idname = "xts_consumptiontax2idname Value"
				,xts_productid = "xts_productid Value"
				,xts_discountbaseamount = "xts_discountbaseamount Value"
				,utcconversiontimezonecode = "utcconversiontimezonecode Value"
				,xts_configurationid = "xts_configurationid Value"
				,xts_discountamount = "xts_discountamount Value"
				,ownerid = "ownerid Value"
				,modifiedon = "modifiedon Value"
				,importsequencenumber = "importsequencenumber Value"
				,owneridyominame = "owneridyominame Value"
				,ktb_cogs = "ktb_cogs Value"
				,ktb_cogstrx = "ktb_cogstrx Value"
				,xts_exteriorcolorid = "xts_exteriorcolorid Value"
				,xts_styleidname = "xts_styleidname Value"
				,xts_siteid = "xts_siteid Value"
				,createdbyname = "createdbyname Value"
				,xts_deliveryorderdetailreferenceidname = "xts_deliveryorderdetailreferenceidname Value"
				,xts_businessunitid = "xts_businessunitid Value"
				,xts_inventoryunitidname = "xts_inventoryunitidname Value"
				,modifiedonbehalfbyname = "modifiedonbehalfbyname Value"
				,xts_salesorderdetailidname = "xts_salesorderdetailidname Value"
				,xts_batchidname = "xts_batchidname Value"
				,xts_withholdingtaxamount = "xts_withholdingtaxamount Value"
				,xts_discountamount_base = "xts_discountamount_base Value"
				,xts_baseamount = "xts_baseamount Value"
				,xts_consumptiontax2amount = "xts_consumptiontax2amount Value"
				,transactioncurrencyid = "transactioncurrencyid Value"
				,xts_businessunitidname = "xts_businessunitidname Value"
				,createdby = "createdby Value"
				,xts_deliveryorderidname = "xts_deliveryorderidname Value"
				,modifiedby = "modifiedby Value"
				,xts_unitprice_base = "xts_unitprice_base Value"
				,xts_parentbusinessunitidname = "xts_parentbusinessunitidname Value"
				,xts_totalamount = "xts_totalamount Value"
				,xts_productcrossreferenceidname = "xts_productcrossreferenceidname Value"
				,createdbyyominame = "createdbyyominame Value"
				,owninguser = "owninguser Value"
				,transactioncurrencyidname = "transactioncurrencyidname Value"
				,xts_consumptiontax1idname = "xts_consumptiontax1idname Value"
				,xts_basequantityorder = "xts_basequantityorder Value"
				,owningbusinessunit = "owningbusinessunit Value"
				,xts_locationid = "xts_locationid Value"
				,ktb_modelcode = "ktb_modelcode Value"
				,xts_consumptiontax1amount = "xts_consumptiontax1amount Value"
				,xts_consumptiontax2amount_base = "xts_consumptiontax2amount_base Value"
				,xts_transactionamount = "xts_transactionamount Value"
				,xts_quantitydelivered = "xts_quantitydelivered Value"
				,xts_deliveryorderdetailreferenceid = "xts_deliveryorderdetailreferenceid Value"
				,statuscode = "statuscode Value"
				,modifiedonbehalfbyyominame = "modifiedonbehalfbyyominame Value"
				,xts_configurationidname = "xts_configurationidname Value"
				,xts_warehouseid = "xts_warehouseid Value"
				,ktb_cogstrx_base = "ktb_cogstrx_base Value"
				,xts_withholdingtaxamount_base = "xts_withholdingtaxamount_base Value"
				,xts_locationidname = "xts_locationidname Value"
				,xts_runningnumber = "xts_runningnumber Value"
				,xts_productdescription = "xts_productdescription Value"
				,xts_deliveryorderdetailid = "xts_deliveryorderdetailid Value"
				,statecodename = "statecodename Value"
				,xts_salesunitid = "xts_salesunitid Value"
				,xts_batchid = "xts_batchid Value"
				,xts_withholdingtax2amount_base = "xts_withholdingtax2amount_base Value"
				,xts_withholdingtax2id = "xts_withholdingtax2id Value"
				,xts_withholdingtax2idname = "xts_withholdingtax2idname Value"
				,xts_withholdingtax2amount = "xts_withholdingtax2amount Value"
				,msdyn_companycode = "msdyn_companycode Value"
            };

            return obj;
        }
    }
}