#region Summary
// ===========================================================================
// AUTHOR        : BSI Code Generator 
// SPECIAL NOTES : DNet WebApi Project
// ---------------------
// Copyright  (c) 2019 
// ---------------------
// $History      : $
// Created on 24/02/2020 18:15:44]
//
// ===========================================================================	
#endregion

using Swashbuckle.Examples;

namespace KTB.DNet.Interface.WebApi.Models.Examples
{
    public class APICreateVWI_CRM_campaignactivityExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var obj = new
            {
				UpdatedBy = "DealerUser"
				,company = "company Value"
				,businessunitcode = "businessunitcode Value"
				,subcategory = "subcategory Value"
				,prioritycodename = "prioritycodename Value"
				,versionnumber = "versionnumber Value"
				,createdon = "createdon Value"
				,modifiedonbehalfbyyominame = "modifiedonbehalfbyyominame Value"
				,activitytypecodename = "activitytypecodename Value"
				,from = "from Value"
				,resources = "resources Value"
				,statuscodename = "statuscodename Value"
				,isregularactivityname = "isregularactivityname Value"
				,traversedpath = "traversedpath Value"
				,activityid = "activityid Value"
				,xts_salesobjective = "xts_salesobjective Value"
				,owneridtype = "owneridtype Value"
				,xts_manufacturerid = "xts_manufacturerid Value"
				,ismapiprivatename = "ismapiprivatename Value"
				,customers = "customers Value"
				,createdonbehalfby = "createdonbehalfby Value"
				,deliverylastattemptedon = "deliverylastattemptedon Value"
				,postponeactivityprocessinguntil = "postponeactivityprocessinguntil Value"
				,onholdtime = "onholdtime Value"
				,createdbyyominame = "createdbyyominame Value"
				,xts_vehiclemodelidname = "xts_vehiclemodelidname Value"
				,regardingobjectidyominame = "regardingobjectidyominame Value"
				,owneridname = "owneridname Value"
				,prioritycode = "prioritycode Value"
				,overriddencreatedon = "overriddencreatedon Value"
				,xts_vehiclemodelid = "xts_vehiclemodelid Value"
				,exchangeitemid = "exchangeitemid Value"
				,scheduledstart = "scheduledstart Value"
				,createdonbehalfbyyominame = "createdonbehalfbyyominame Value"
				,isbilled = "isbilled Value"
				,exchangerate = "exchangerate Value"
				,deliveryprioritycodename = "deliveryprioritycodename Value"
				,excludeifcontactedinxdays = "excludeifcontactedinxdays Value"
				,budgetedcost_base = "budgetedcost_base Value"
				,owningteam = "owningteam Value"
				,xts_vehiclebrandid = "xts_vehiclebrandid Value"
				,deliveryprioritycode = "deliveryprioritycode Value"
				,sendermailboxid = "sendermailboxid Value"
				,xts_productidname = "xts_productidname Value"
				,regardingobjectid = "regardingobjectid Value"
				,statecode = "statecode Value"
				,exchangeweblink = "exchangeweblink Value"
				,activityadditionalparams = "activityadditionalparams Value"
				,seriesid = "seriesid Value"
				,timezoneruleversionnumber = "timezoneruleversionnumber Value"
				,bcc = "bcc Value"
				,xts_businessunitid = "xts_businessunitid Value"
				,xts_productexteriorcoloridname = "xts_productexteriorcoloridname Value"
				,modifiedonbehalfby = "modifiedonbehalfby Value"
				,xts_locking = "xts_locking Value"
				,community = "community Value"
				,xts_manufactureridname = "xts_manufactureridname Value"
				,actualcost_base = "actualcost_base Value"
				,regardingobjectidname = "regardingobjectidname Value"
				,slainvokedidname = "slainvokedidname Value"
				,ignoreinactivelistmembers = "ignoreinactivelistmembers Value"
				,createdonbehalfbyname = "createdonbehalfbyname Value"
				,ignoreinactivelistmembersname = "ignoreinactivelistmembersname Value"
				,actualstart = "actualstart Value"
				,xts_productexteriorcolorid = "xts_productexteriorcolorid Value"
				,utcconversiontimezonecode = "utcconversiontimezonecode Value"
				,activitytypecode = "activitytypecode Value"
				,instancetypecodename = "instancetypecodename Value"
				,lastonholdtime = "lastonholdtime Value"
				,slaid = "slaid Value"
				,slainvokedid = "slainvokedid Value"
				,sortdate = "sortdate Value"
				,ownerid = "ownerid Value"
				,modifiedon = "modifiedon Value"
				,importsequencenumber = "importsequencenumber Value"
				,owneridyominame = "owneridyominame Value"
				,scheduleddurationminutes = "scheduleddurationminutes Value"
				,category = "category Value"
				,processid = "processid Value"
				,actualcost = "actualcost Value"
				,description = "description Value"
				,slaname = "slaname Value"
				,to = "to Value"
				,createdbyname = "createdbyname Value"
				,regardingobjecttypecode = "regardingobjecttypecode Value"
				,xts_salesobjectivename = "xts_salesobjectivename Value"
				,modifiedonbehalfbyname = "modifiedonbehalfbyname Value"
				,ismapiprivate = "ismapiprivate Value"
				,isworkflowcreatedname = "isworkflowcreatedname Value"
				,requiredattendees = "requiredattendees Value"
				,donotsendonoptout = "donotsendonoptout Value"
				,stageid = "stageid Value"
				,partners = "partners Value"
				,checkfordonotsendmmonlistmembersname = "checkfordonotsendmmonlistmembersname Value"
				,leftvoicemail = "leftvoicemail Value"
				,optionalattendees = "optionalattendees Value"
				,xts_productid = "xts_productid Value"
				,channeltypecode = "channeltypecode Value"
				,instancetypecode = "instancetypecode Value"
				,createdby = "createdby Value"
				,modifiedby = "modifiedby Value"
				,organizer = "organizer Value"
				,serviceid = "serviceid Value"
				,channeltypecodename = "channeltypecodename Value"
				,isworkflowcreated = "isworkflowcreated Value"
				,owninguser = "owninguser Value"
				,transactioncurrencyidname = "transactioncurrencyidname Value"
				,actualend = "actualend Value"
				,owningbusinessunit = "owningbusinessunit Value"
				,xts_vehiclebrandidname = "xts_vehiclebrandidname Value"
				,transactioncurrencyid = "transactioncurrencyid Value"
				,modifiedbyyominame = "modifiedbyyominame Value"
				,typecodename = "typecodename Value"
				,sendermailboxidname = "sendermailboxidname Value"
				,isregularactivity = "isregularactivity Value"
				,cc = "cc Value"
				,isbilledname = "isbilledname Value"
				,senton = "senton Value"
				,scheduledend = "scheduledend Value"
				,statuscode = "statuscode Value"
				,modifiedbyname = "modifiedbyname Value"
				,budgetedcost = "budgetedcost Value"
				,actualdurationminutes = "actualdurationminutes Value"
				,typecode = "typecode Value"
				,subject = "subject Value"
				,leftvoicemailname = "leftvoicemailname Value"
				,statecodename = "statecodename Value"
				,xts_businessunitidname = "xts_businessunitidname Value"
				,communityname = "communityname Value"
				,msdyn_companycode = "msdyn_companycode Value"
            };

            return obj;
        }
    }
}