#region Summary
// ===========================================================================
// AUTHOR        : BSI Code Generator 
// SPECIAL NOTES : DNet WebApi Project
// ---------------------
// Copyright  (c) 2019 
// ---------------------
// $History      : $
// Created on 14/01/2020 9:03:03]
//
// ===========================================================================	
#endregion

using Swashbuckle.Examples;

namespace KTB.DNet.Interface.WebApi.Models.Examples
{
    public class APICreateVWI_CRM_xts_newvehiclewholesaleorderExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var obj = new
            {
				UpdatedBy = "DealerUser"
				,company = "company Value"
				,businessunitcode = "businessunitcode Value"
				,ktb_benefitidname = "ktb_benefitidname Value"
				,traversedpath = "traversedpath Value"
				,xts_vehicleamount_base = "xts_vehicleamount_base Value"
				,ktb_cbu_purcstat = "ktb_cbu_purcstat Value"
				,ktb_karoseriidname = "ktb_karoseriidname Value"
				,xts_vehiclerelatedproductamount_base = "xts_vehiclerelatedproductamount_base Value"
				,ktb_rejectedreasonoptionname = "ktb_rejectedreasonoptionname Value"
				,modifiedon = "modifiedon Value"
				,xts_accessoriesamount_base = "xts_accessoriesamount_base Value"
				,overriddencreatedon = "overriddencreatedon Value"
				,xjp_tradeinrecyclingamount = "xjp_tradeinrecyclingamount Value"
				,statuscodename = "statuscodename Value"
				,xts_potentiallookupname = "xts_potentiallookupname Value"
				,ktb_rejectedreason = "ktb_rejectedreason Value"
				,ktb_begbal = "ktb_begbal Value"
				,xts_netamountaftertax_base = "xts_netamountaftertax_base Value"
				,ktb_cbu_purcstat2name = "ktb_cbu_purcstat2name Value"
				,xts_handling = "xts_handling Value"
				,xts_netamount = "xts_netamount Value"
				,xts_netamount_base = "xts_netamount_base Value"
				,xts_totalreceipt = "xts_totalreceipt Value"
				,xts_othertaxamount_base = "xts_othertaxamount_base Value"
				,ktb_cbu_userage1name = "ktb_cbu_userage1name Value"
				,transactioncurrencyidname = "transactioncurrencyidname Value"
				,ktb_statusinterfacednetname = "ktb_statusinterfacednetname Value"
				,ktb_nvsoregistrationdetailnumberidname = "ktb_nvsoregistrationdetailnumberidname Value"
				,xts_dealerdiscount = "xts_dealerdiscount Value"
				,xts_voluntaryinsuranceamount_base = "xts_voluntaryinsuranceamount_base Value"
				,xjp_billtoidname = "xjp_billtoidname Value"
				,xts_balance_base = "xts_balance_base Value"
				,ktb_qty = "ktb_qty Value"
				,ktb_cbu_purpose2name = "ktb_cbu_purpose2name Value"
				,owningbusinessunit = "owningbusinessunit Value"
				,ktb_productidname = "ktb_productidname Value"
				,ktb_statusinterfacednet = "ktb_statusinterfacednet Value"
				,xts_addressidname = "xts_addressidname Value"
				,xts_potentialcustomerdescription = "xts_potentialcustomerdescription Value"
				,ktb_campaignid = "ktb_campaignid Value"
				,xts_referralamount = "xts_referralamount Value"
				,ktb_categorycode = "ktb_categorycode Value"
				,ktb_interfaceexceptionmessage = "ktb_interfaceexceptionmessage Value"
				,statuscode = "statuscode Value"
				,xts_downpaymentamount_base = "xts_downpaymentamount_base Value"
				,xts_totalreceipt_base = "xts_totalreceipt_base Value"
				,xts_nontaxablemiscellaneouschargeamount_base = "xts_nontaxablemiscellaneouschargeamount_base Value"
				,ktb_namakonsumenspkid = "ktb_namakonsumenspkid Value"
				,ktb_cbu_modelkend = "ktb_cbu_modelkend Value"
				,ktb_cbu_bodytype1name = "ktb_cbu_bodytype1name Value"
				,xts_address3 = "xts_address3 Value"
				,versionnumber = "versionnumber Value"
				,ktb_namakonsumenspkidyominame = "ktb_namakonsumenspkidyominame Value"
				,xts_downpaymentamountreceived_base = "xts_downpaymentamountreceived_base Value"
				,statecodename = "statecodename Value"
				,xts_taxablemiscellaneouschargeamount_base = "xts_taxablemiscellaneouschargeamount_base Value"
				,ktb_lkppno = "ktb_lkppno Value"
				,ktb_address4 = "ktb_address4 Value"
				,xts_couponamount = "xts_couponamount Value"
				,ktb_cbu_purpose1name = "ktb_cbu_purpose1name Value"
				,exchangerate = "exchangerate Value"
				,xts_opportunityidname = "xts_opportunityidname Value"
				,ktb_cbu_jeniskend = "ktb_cbu_jeniskend Value"
				,ktb_cbu_medanoperasi1name = "ktb_cbu_medanoperasi1name Value"
				,xts_compulsoryinsuranceamount_base = "xts_compulsoryinsuranceamount_base Value"
				,xts_accessoriesdiscountamount_base = "xts_accessoriesdiscountamount_base Value"
				,xts_taxablemiscellaneouschargeamount = "xts_taxablemiscellaneouschargeamount Value"
				,ktb_productexteriorcolorid = "ktb_productexteriorcolorid Value"
				,xts_newvehiclewholesaleorderid = "xts_newvehiclewholesaleorderid Value"
				,ktb_begbalname = "ktb_begbalname Value"
				,xjp_billtoidyominame = "xjp_billtoidyominame Value"
				,ktb_cbu_medanoperasi1 = "ktb_cbu_medanoperasi1 Value"
				,xts_potentialcustomeridname = "xts_potentialcustomeridname Value"
				,ktb_dnetid = "ktb_dnetid Value"
				,owneridname = "owneridname Value"
				,createdon = "createdon Value"
				,xjp_billtoid = "xjp_billtoid Value"
				,xts_compulsoryinsuranceamount = "xts_compulsoryinsuranceamount Value"
				,xts_referralamount_base = "xts_referralamount_base Value"
				,xts_statusname = "xts_statusname Value"
				,ktb_nvsoregistrationdetailnumberid = "ktb_nvsoregistrationdetailnumberid Value"
				,ktb_dnetspknumber = "ktb_dnetspknumber Value"
				,ktb_cbu_bodytypelcv1 = "ktb_cbu_bodytypelcv1 Value"
				,ktb_campaignidname = "ktb_campaignidname Value"
				,xts_othertaxamount = "xts_othertaxamount Value"
				,ktb_leasingcompanyid = "ktb_leasingcompanyid Value"
				,xts_vehicleamount = "xts_vehicleamount Value"
				,xts_tradeinamount_base = "xts_tradeinamount_base Value"
				,ktb_cbu_purpose1 = "ktb_cbu_purpose1 Value"
				,ktb_cbu_userage1 = "ktb_cbu_userage1 Value"
				,owneridyominame = "owneridyominame Value"
				,ktb_remarks = "ktb_remarks Value"
				,xts_voluntaryinsuranceamount = "xts_voluntaryinsuranceamount Value"
				,modifiedby = "modifiedby Value"
				,timezoneruleversionnumber = "timezoneruleversionnumber Value"
				,ktb_cbu_purpose2 = "ktb_cbu_purpose2 Value"
				,xts_zipcode = "xts_zipcode Value"
				,xts_address1 = "xts_address1 Value"
				,ktb_cbu_purcstatname = "ktb_cbu_purcstatname Value"
				,modifiedonbehalfby = "modifiedonbehalfby Value"
				,xts_potentialcustomerid = "xts_potentialcustomerid Value"
				,xts_newvehiclewholesaleordernumber = "xts_newvehiclewholesaleordernumber Value"
				,ktb_scheduleddeliverydate = "ktb_scheduleddeliverydate Value"
				,xts_customernumber = "xts_customernumber Value"
				,ktb_spkdnetreference = "ktb_spkdnetreference Value"
				,xts_termofpaymentid = "xts_termofpaymentid Value"
				,xts_outstandingamount_base = "xts_outstandingamount_base Value"
				,xjp_tradeinrecyclingamount_base = "xjp_tradeinrecyclingamount_base Value"
				,ktb_cbu_jeniskendname = "ktb_cbu_jeniskendname Value"
				,createdonbehalfbyname = "createdonbehalfbyname Value"
				,owninguser = "owninguser Value"
				,xts_totalpriceamount = "xts_totalpriceamount Value"
				,ktb_rejectedreasonoption = "ktb_rejectedreasonoption Value"
				,xts_nontaxablemiscellaneouschargeamount = "xts_nontaxablemiscellaneouschargeamount Value"
				,ktb_karoseriid = "ktb_karoseriid Value"
				,xts_salespersonid = "xts_salespersonid Value"
				,owneridtype = "owneridtype Value"
				,xts_transactiondate = "xts_transactiondate Value"
				,ktb_additional = "ktb_additional Value"
				,xts_couponamount_base = "xts_couponamount_base Value"
				,xts_vehiclediscountamount = "xts_vehiclediscountamount Value"
				,modifiedonbehalfbyname = "modifiedonbehalfbyname Value"
				,createdonbehalfbyyominame = "createdonbehalfbyyominame Value"
				,ktb_isinterfaced = "ktb_isinterfaced Value"
				,ktb_handlingname = "ktb_handlingname Value"
				,xts_subsidizeddiscount = "xts_subsidizeddiscount Value"
				,ktb_cbu_bodytypelcv1name = "ktb_cbu_bodytypelcv1name Value"
				,xts_potentiallookuptype = "xts_potentiallookuptype Value"
				,owningteam = "owningteam Value"
				,xts_accessoriesdiscountamount = "xts_accessoriesdiscountamount Value"
				,xts_opportunityid = "xts_opportunityid Value"
				,xjp_billtonumber = "xjp_billtonumber Value"
				,ktb_dnetspkcustomerid = "ktb_dnetspkcustomerid Value"
				,xts_downpaymentamountreceived = "xts_downpaymentamountreceived Value"
				,xts_downpaymentamountispaidname = "xts_downpaymentamountispaidname Value"
				,xts_parentbusinessunitidname = "xts_parentbusinessunitidname Value"
				,xts_bookingfeeamount_base = "xts_bookingfeeamount_base Value"
				,processid = "processid Value"
				,xts_balance = "xts_balance Value"
				,xjp_recyclingamount = "xjp_recyclingamount Value"
				,createdonbehalfby = "createdonbehalfby Value"
				,ktb_cbu_ownership1 = "ktb_cbu_ownership1 Value"
				,ktb_namakonsumenspkidname = "ktb_namakonsumenspkidname Value"
				,xts_parentbusinessunitid = "xts_parentbusinessunitid Value"
				,ktb_cbu_purcstat2 = "ktb_cbu_purcstat2 Value"
				,transactioncurrencyid = "transactioncurrencyid Value"
				,ktb_statusname = "ktb_statusname Value"
				,xts_dealerdiscount_base = "xts_dealerdiscount_base Value"
				,xjp_recyclingamount_base = "xjp_recyclingamount_base Value"
				,ktb_isinterfacedname = "ktb_isinterfacedname Value"
				,xts_addressid = "xts_addressid Value"
				,modifiedbyyominame = "modifiedbyyominame Value"
				,ownerid = "ownerid Value"
				,xts_consumptiontaxtotalamount = "xts_consumptiontaxtotalamount Value"
				,xts_netamountaftertax = "xts_netamountaftertax Value"
				,ktb_dnetsapcustomerid = "ktb_dnetsapcustomerid Value"
				,xts_bookingfeeamount = "xts_bookingfeeamount Value"
				,ktb_cbu_loadprofile1name = "ktb_cbu_loadprofile1name Value"
				,ktb_categorycodename = "ktb_categorycodename Value"
				,xts_titleregistrationfee = "xts_titleregistrationfee Value"
				,xts_consumptiontaxtotalamount_base = "xts_consumptiontaxtotalamount_base Value"
				,xts_salespersonidname = "xts_salespersonidname Value"
				,xts_vehiclerelatedproductamount = "xts_vehiclerelatedproductamount Value"
				,ktb_benefitid = "ktb_benefitid Value"
				,createdbyname = "createdbyname Value"
				,ktb_dnetspkdetailid = "ktb_dnetspkdetailid Value"
				,xts_businessunitidname = "xts_businessunitidname Value"
				,xts_outstandingamount = "xts_outstandingamount Value"
				,xts_phonenumber = "xts_phonenumber Value"
				,xts_accessoriesamount = "xts_accessoriesamount Value"
				,modifiedonbehalfbyyominame = "modifiedonbehalfbyyominame Value"
				,createdby = "createdby Value"
				,ktb_namakonsumenspk = "ktb_namakonsumenspk Value"
				,ktb_cbu_loadprofile1 = "ktb_cbu_loadprofile1 Value"
				,xts_specialcolorpriceamount_base = "xts_specialcolorpriceamount_base Value"
				,ktb_cbu_waypaid1 = "ktb_cbu_waypaid1 Value"
				,ktb_cbu_bodytype1 = "ktb_cbu_bodytype1 Value"
				,ktb_leasingcompanyidname = "ktb_leasingcompanyidname Value"
				,ktb_cbu_modelkendname = "ktb_cbu_modelkendname Value"
				,stageid = "stageid Value"
				,utcconversiontimezonecode = "utcconversiontimezonecode Value"
				,xts_subsidizeddiscount_base = "xts_subsidizeddiscount_base Value"
				,ktb_handling = "ktb_handling Value"
				,xts_potentialcustomeridyominame = "xts_potentialcustomeridyominame Value"
				,ktb_tempdocument = "ktb_tempdocument Value"
				,importsequencenumber = "importsequencenumber Value"
				,xts_locking = "xts_locking Value"
				,ktb_productid = "ktb_productid Value"
				,xts_address2 = "xts_address2 Value"
				,xts_businessunitid = "xts_businessunitid Value"
				,ktb_additionalname = "ktb_additionalname Value"
				,ktb_cbu_waypaid1name = "ktb_cbu_waypaid1name Value"
				,xts_titleregistrationfee_base = "xts_titleregistrationfee_base Value"
				,xts_handlingname = "xts_handlingname Value"
				,xts_potentialcontactidname = "xts_potentialcontactidname Value"
				,ktb_status = "ktb_status Value"
				,xts_status = "xts_status Value"
				,xts_vehiclediscountamount_base = "xts_vehiclediscountamount_base Value"
				,modifiedbyname = "modifiedbyname Value"
				,createdbyyominame = "createdbyyominame Value"
				,xts_specialcolorpriceamount = "xts_specialcolorpriceamount Value"
				,xts_vehiclediscountpercentage = "xts_vehiclediscountpercentage Value"
				,xts_potentialcontactid = "xts_potentialcontactid Value"
				,xts_downpaymentamount = "xts_downpaymentamount Value"
				,xts_termofpaymentidname = "xts_termofpaymentidname Value"
				,ktb_tempdocumentname = "ktb_tempdocumentname Value"
				,xts_potentialcontactidyominame = "xts_potentialcontactidyominame Value"
				,ktb_productexteriorcoloridname = "ktb_productexteriorcoloridname Value"
				,ktb_cbu_ownership1name = "ktb_cbu_ownership1name Value"
				,xts_downpaymentamountispaid = "xts_downpaymentamountispaid Value"
				,xts_tradeinamount = "xts_tradeinamount Value"
				,xts_totalpriceamount_base = "xts_totalpriceamount_base Value"
				,statecode = "statecode Value"
				,msdyn_companycode = "msdyn_companycode Value"
            };

            return obj;
        }
    }
}