#region Summary
// ===========================================================================
// AUTHOR        : BSI Code Generator 
// SPECIAL NOTES : DNet WebApi Project
// ---------------------
// Copyright  (c) 2019 
// ---------------------
// $History      : $
// Created on 24/02/2020 18:15:44]
//
// ===========================================================================	
#endregion

using Swashbuckle.Examples;

namespace KTB.DNet.Interface.WebApi.Models.Examples
{
    public class APICreateVWI_CRM_xts_accountreceivablereceiptExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var obj = new
            {
				UpdatedBy = "DealerUser"
				,company = "company Value"
				,businessunitcode = "businessunitcode Value"
				,xts_customerid = "xts_customerid Value"
				,ktb_untukpembayaran = "ktb_untukpembayaran Value"
				,modifiedon = "modifiedon Value"
				,xts_cancelled = "xts_cancelled Value"
				,overriddencreatedon = "overriddencreatedon Value"
				,xts_totalamount = "xts_totalamount Value"
				,statuscodename = "statuscodename Value"
				,xts_totaloutstandingbalance = "xts_totaloutstandingbalance Value"
				,xts_handling = "xts_handling Value"
				,xts_cancelledname = "xts_cancelledname Value"
				,xts_cashandbankdimension3id = "xts_cashandbankdimension3id Value"
				,transactioncurrencyidname = "transactioncurrencyidname Value"
				,xts_customeridyominame = "xts_customeridyominame Value"
				,xts_cashandbankdimension5idname = "xts_cashandbankdimension5idname Value"
				,xts_insuranceamount_base = "xts_insuranceamount_base Value"
				,xts_type = "xts_type Value"
				,ktb_colordescription = "ktb_colordescription Value"
				,ktb_giroduedate = "ktb_giroduedate Value"
				,ktb_bankgiro = "ktb_bankgiro Value"
				,ktb_productionyear = "ktb_productionyear Value"
				,xts_cashandbankdimension2id = "xts_cashandbankdimension2id Value"
				,xts_contractid = "xts_contractid Value"
				,owningbusinessunit = "owningbusinessunit Value"
				,xts_receivabledimension2id = "xts_receivabledimension2id Value"
				,ktb_productidname = "ktb_productidname Value"
				,xts_receivabledimension1id = "xts_receivabledimension1id Value"
				,xts_customernumber = "xts_customernumber Value"
				,xts_cashandbankdimension4idname = "xts_cashandbankdimension4idname Value"
				,xts_customeridname = "xts_customeridname Value"
				,ktb_referencekwitansi = "ktb_referencekwitansi Value"
				,statuscode = "statuscode Value"
				,statecode = "statecode Value"
				,xts_accountreceivableinvoicereferenceid = "xts_accountreceivableinvoicereferenceid Value"
				,xts_locking = "xts_locking Value"
				,xts_cashandbankdimension5id = "xts_cashandbankdimension5id Value"
				,xts_receivabledimension2idname = "xts_receivabledimension2idname Value"
				,xts_methodofpaymentidname = "xts_methodofpaymentidname Value"
				,xts_newvehiclewholesaleorderidname = "xts_newvehiclewholesaleorderidname Value"
				,xts_receivabledimension1idname = "xts_receivabledimension1idname Value"
				,xts_accountreceivablereceiptreferenceid = "xts_accountreceivablereceiptreferenceid Value"
				,xts_paymentsettlement_base = "xts_paymentsettlement_base Value"
				,statecodename = "statecodename Value"
				,xts_totalremainingbalance_base = "xts_totalremainingbalance_base Value"
				,xts_receivabledimension5idname = "xts_receivabledimension5idname Value"
				,exchangerate = "exchangerate Value"
				,ownerid = "ownerid Value"
				,xts_totalamount_base = "xts_totalamount_base Value"
				,ktb_spkidname = "ktb_spkidname Value"
				,xts_newvehiclewholesaleorderid = "xts_newvehiclewholesaleorderid Value"
				,ktb_description2 = "ktb_description2 Value"
				,modifiedbyyominame = "modifiedbyyominame Value"
				,xts_paymentsettlement = "xts_paymentsettlement Value"
				,xts_exchangerateamount = "xts_exchangerateamount Value"
				,xts_totalchangeamount_base = "xts_totalchangeamount_base Value"
				,xts_statusname = "xts_statusname Value"
				,ktb_description1 = "ktb_description1 Value"
				,xts_arreceipttype = "xts_arreceipttype Value"
				,xts_postinglayername = "xts_postinglayername Value"
				,owneridyominame = "owneridyominame Value"
				,xts_endorderdate = "xts_endorderdate Value"
				,createdon = "createdon Value"
				,ktb_description4 = "ktb_description4 Value"
				,xts_receivabledimension6idname = "xts_receivabledimension6idname Value"
				,xts_cashandbankdimension1idname = "xts_cashandbankdimension1idname Value"
				,modifiedby = "modifiedby Value"
				,timezoneruleversionnumber = "timezoneruleversionnumber Value"
				,xts_handlingname = "xts_handlingname Value"
				,modifiedonbehalfby = "modifiedonbehalfby Value"
				,xts_totalreceiptamount_base = "xts_totalreceiptamount_base Value"
				,xts_typename = "xts_typename Value"
				,xts_accountreceivableinvoicereferenceidname = "xts_accountreceivableinvoicereferenceidname Value"
				,xts_totalotherexpenses_base = "xts_totalotherexpenses_base Value"
				,xts_insuranceamount = "xts_insuranceamount Value"
				,owningteam = "owningteam Value"
				,xts_exchangeratetype = "xts_exchangeratetype Value"
				,xts_accountreceivablereceiptid = "xts_accountreceivablereceiptid Value"
				,xts_postinglayer = "xts_postinglayer Value"
				,createdonbehalfbyname = "createdonbehalfbyname Value"
				,owninguser = "owninguser Value"
				,xts_idempotentmessage = "xts_idempotentmessage Value"
				,ktb_spkid = "ktb_spkid Value"
				,xts_cashandbankdimension1id = "xts_cashandbankdimension1id Value"
				,xts_receivabledimension6id = "xts_receivabledimension6id Value"
				,xts_transactiondate = "xts_transactiondate Value"
				,xts_receivabledimension5id = "xts_receivabledimension5id Value"
				,xts_cashandbankdimension3idname = "xts_cashandbankdimension3idname Value"
				,xts_receivabledimension4id = "xts_receivabledimension4id Value"
				,xts_accountreceivablereceiptreferenceidname = "xts_accountreceivablereceiptreferenceidname Value"
				,owneridname = "owneridname Value"
				,modifiedonbehalfbyname = "modifiedonbehalfbyname Value"
				,createdonbehalfbyyominame = "createdonbehalfbyyominame Value"
				,ktb_description3 = "ktb_description3 Value"
				,xts_receiptnumber = "xts_receiptnumber Value"
				,xts_receivabledimension4idname = "xts_receivabledimension4idname Value"
				,xts_parentbusinessunitidname = "xts_parentbusinessunitidname Value"
				,createdonbehalfby = "createdonbehalfby Value"
				,xts_parentbusinessunitid = "xts_parentbusinessunitid Value"
				,ktb_chassisnumber = "ktb_chassisnumber Value"
				,transactioncurrencyid = "transactioncurrencyid Value"
				,xts_eventdata = "xts_eventdata Value"
				,xts_exchangeratetypename = "xts_exchangeratetypename Value"
				,xts_accountreceivablereceiptnumber = "xts_accountreceivablereceiptnumber Value"
				,xts_receivabledimension3id = "xts_receivabledimension3id Value"
				,ktb_say = "ktb_say Value"
				,xts_exchangeratedate = "xts_exchangeratedate Value"
				,xts_cashandbankaccountidname = "xts_cashandbankaccountidname Value"
				,xts_totaloutstandingbalance_base = "xts_totaloutstandingbalance_base Value"
				,xts_totalchangeamount = "xts_totalchangeamount Value"
				,xts_totalreceiptamount = "xts_totalreceiptamount Value"
				,xts_contractidname = "xts_contractidname Value"
				,xts_cashandbankdimension4id = "xts_cashandbankdimension4id Value"
				,xjp_generatedtoken = "xjp_generatedtoken Value"
				,xts_cashandbankid = "xts_cashandbankid Value"
				,ktb_girono = "ktb_girono Value"
				,xts_totalotherexpenses = "xts_totalotherexpenses Value"
				,createdbyname = "createdbyname Value"
				,xts_businessunitidname = "xts_businessunitidname Value"
				,xts_sourcetypename = "xts_sourcetypename Value"
				,modifiedonbehalfbyyominame = "modifiedonbehalfbyyominame Value"
				,createdby = "createdby Value"
				,xts_startorderdate = "xts_startorderdate Value"
				,importsequencenumber = "importsequencenumber Value"
				,utcconversiontimezonecode = "utcconversiontimezonecode Value"
				,xts_cashandbankdimension6id = "xts_cashandbankdimension6id Value"
				,xts_cashandbankaccountid = "xts_cashandbankaccountid Value"
				,xts_arreceipttypename = "xts_arreceipttypename Value"
				,xts_cashandbankdimension6idname = "xts_cashandbankdimension6idname Value"
				,xts_cashandbankdimension2idname = "xts_cashandbankdimension2idname Value"
				,xts_cashandbankidname = "xts_cashandbankidname Value"
				,xts_bookingfee = "xts_bookingfee Value"
				,ktb_productid = "ktb_productid Value"
				,versionnumber = "versionnumber Value"
				,xts_businessunitid = "xts_businessunitid Value"
				,xts_status = "xts_status Value"
				,owneridtype = "owneridtype Value"
				,ktb_customerdescription = "ktb_customerdescription Value"
				,modifiedbyname = "modifiedbyname Value"
				,xts_methodofpaymentid = "xts_methodofpaymentid Value"
				,createdbyyominame = "createdbyyominame Value"
				,xts_sourcetype = "xts_sourcetype Value"
				,xts_bookingfeename = "xts_bookingfeename Value"
				,xts_totalremainingbalance = "xts_totalremainingbalance Value"
				,xts_receivabledimension3idname = "xts_receivabledimension3idname Value"
				,ktb_enginenumber = "ktb_enginenumber Value"
				,msdyn_companycode = "msdyn_companycode Value"
            };

            return obj;
        }
    }
}