#region Summary
// ===========================================================================
// AUTHOR        : BSI Code Generator 
// SPECIAL NOTES : DNet WebApi Project
// ---------------------
// Copyright  (c) 2019 
// ---------------------
// $History      : $
// Created on 15/01/2020 8:22:46]
//
// ===========================================================================	
#endregion

using Swashbuckle.Examples;

namespace KTB.DNet.Interface.WebApi.Models.Examples
{
    public class APICreateVWI_CRM_xts_ordertypeExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var obj = new
            {
				UpdatedBy = "DealerUser"
				,company = "company Value"
				,businessunitcode = "businessunitcode Value"
				,xts_discountdimension6fromname = "xts_discountdimension6fromname Value"
				,xts_cogsdimension7id = "xts_cogsdimension7id Value"
				,ktb_defaultlocationwoname = "ktb_defaultlocationwoname Value"
				,xts_cogsdimension4id = "xts_cogsdimension4id Value"
				,xts_discdimension10id = "xts_discdimension10id Value"
				,overriddencreatedon = "overriddencreatedon Value"
				,xts_downpaymentdimension4id = "xts_downpaymentdimension4id Value"
				,statuscodename = "statuscodename Value"
				,xts_ardimension2idname = "xts_ardimension2idname Value"
				,xts_salesdimension3id = "xts_salesdimension3id Value"
				,modifiedbyyominame = "modifiedbyyominame Value"
				,xts_salesdimension10idname = "xts_salesdimension10idname Value"
				,ktb_ordertypetointerface = "ktb_ordertypetointerface Value"
				,xts_discountaccountfromname = "xts_discountaccountfromname Value"
				,xts_salesaccountfromname = "xts_salesaccountfromname Value"
				,xts_discdimension9idname = "xts_discdimension9idname Value"
				,xts_cogsdimension5idname = "xts_cogsdimension5idname Value"
				,xts_salesdimension4idname = "xts_salesdimension4idname Value"
				,xts_salesaccountfrom = "xts_salesaccountfrom Value"
				,xts_behaviour = "xts_behaviour Value"
				,ktb_isnoprice = "ktb_isnoprice Value"
				,xts_discdimension4id = "xts_discdimension4id Value"
				,ktb_isbilltoatpm = "ktb_isbilltoatpm Value"
				,xts_salesdimension4fromname = "xts_salesdimension4fromname Value"
				,xts_discountdimension6from = "xts_discountdimension6from Value"
				,ktb_isfreeservice = "ktb_isfreeservice Value"
				,owningbusinessunit = "owningbusinessunit Value"
				,xts_partspricecalculationmethod = "xts_partspricecalculationmethod Value"
				,xts_cogsdimension10id = "xts_cogsdimension10id Value"
				,xts_ardimension1id = "xts_ardimension1id Value"
				,xts_downpaymentdimension4idname = "xts_downpaymentdimension4idname Value"
				,ktb_transtype = "ktb_transtype Value"
				,xts_ardimension2id = "xts_ardimension2id Value"
				,xts_discdimension2id = "xts_discdimension2id Value"
				,xts_salesdimension4from = "xts_salesdimension4from Value"
				,xts_salesdimension3from = "xts_salesdimension3from Value"
				,statuscode = "statuscode Value"
				,xts_servicetemplateparentgroupidname = "xts_servicetemplateparentgroupidname Value"
				,xts_ordertypeid = "xts_ordertypeid Value"
				,xts_salesdimension6fromname = "xts_salesdimension6fromname Value"
				,xts_discountdimension1from = "xts_discountdimension1from Value"
				,xts_salesdimension3idname = "xts_salesdimension3idname Value"
				,xts_cogsdimension9id = "xts_cogsdimension9id Value"
				,xts_salesdimension4id = "xts_salesdimension4id Value"
				,xts_partspricecalculationmethodname = "xts_partspricecalculationmethodname Value"
				,ktb_interfacedtoexternalsystem = "ktb_interfacedtoexternalsystem Value"
				,xts_salesdimension2fromname = "xts_salesdimension2fromname Value"
				,xts_discdimension3idname = "xts_discdimension3idname Value"
				,xts_salesdimension7idname = "xts_salesdimension7idname Value"
				,statecodename = "statecodename Value"
				,xts_discountdimension5fromname = "xts_discountdimension5fromname Value"
				,xts_cogsdimension1idname = "xts_cogsdimension1idname Value"
				,xts_salesdimension1id = "xts_salesdimension1id Value"
				,xts_downpaymentdimension6idname = "xts_downpaymentdimension6idname Value"
				,xts_discdimension7id = "xts_discdimension7id Value"
				,ownerid = "ownerid Value"
				,modifiedon = "modifiedon Value"
				,xts_ardimension3idname = "xts_ardimension3idname Value"
				,ktb_ordertypetointerfacename = "ktb_ordertypetointerfacename Value"
				,xts_ardimension5id = "xts_ardimension5id Value"
				,xts_salesdimension5id = "xts_salesdimension5id Value"
				,xts_cogsdimension6id = "xts_cogsdimension6id Value"
				,ktb_defaultwarehouseid = "ktb_defaultwarehouseid Value"
				,ktb_bodypaint = "ktb_bodypaint Value"
				,createdon = "createdon Value"
				,ktb_isonlyshownongenuineproductinwopmsname = "ktb_isonlyshownongenuineproductinwopmsname Value"
				,xts_ordertype = "xts_ordertype Value"
				,ktb_isonlyshownongenuineproductinwopms = "ktb_isonlyshownongenuineproductinwopms Value"
				,xts_cogsdimension3idname = "xts_cogsdimension3idname Value"
				,createdonbehalfby = "createdonbehalfby Value"
				,xts_salesdimension10id = "xts_salesdimension10id Value"
				,xts_discdimension10idname = "xts_discdimension10idname Value"
				,xts_ordervehiclename = "xts_ordervehiclename Value"
				,xts_cogsdimension9idname = "xts_cogsdimension9idname Value"
				,xts_discountdimension1fromname = "xts_discountdimension1fromname Value"
				,xts_cogsdimension6idname = "xts_cogsdimension6idname Value"
				,xts_discountdimension4fromname = "xts_discountdimension4fromname Value"
				,owneridyominame = "owneridyominame Value"
				,xts_ardimension6id = "xts_ardimension6id Value"
				,xts_downpaymentdimension2id = "xts_downpaymentdimension2id Value"
				,xts_discountaccountfrom = "xts_discountaccountfrom Value"
				,xts_salesaccountidname = "xts_salesaccountidname Value"
				,ktb_issmartpackagename = "ktb_issmartpackagename Value"
				,modifiedby = "modifiedby Value"
				,xts_salesdimension5idname = "xts_salesdimension5idname Value"
				,timezoneruleversionnumber = "timezoneruleversionnumber Value"
				,ktb_isfreeservicename = "ktb_isfreeservicename Value"
				,xts_aftervso = "xts_aftervso Value"
				,xts_discdimension7idname = "xts_discdimension7idname Value"
				,ktb_bodypaintname = "ktb_bodypaintname Value"
				,modifiedonbehalfby = "modifiedonbehalfby Value"
				,xts_discdimension9id = "xts_discdimension9id Value"
				,xts_ardimension5idname = "xts_ardimension5idname Value"
				,ktb_isnopricename = "ktb_isnopricename Value"
				,xts_cogsdimension7idname = "xts_cogsdimension7idname Value"
				,xts_downpaymentdimension5id = "xts_downpaymentdimension5id Value"
				,xts_cogsdimension4idname = "xts_cogsdimension4idname Value"
				,xts_cogsdimension5id = "xts_cogsdimension5id Value"
				,createdonbehalfbyname = "createdonbehalfbyname Value"
				,owninguser = "owninguser Value"
				,ktb_description = "ktb_description Value"
				,xts_cogsaccountid = "xts_cogsaccountid Value"
				,xts_cogsdimension8idname = "xts_cogsdimension8idname Value"
				,ktb_ordertypetranstypename = "ktb_ordertypetranstypename Value"
				,owneridtype = "owneridtype Value"
				,xts_discountaccountid = "xts_discountaccountid Value"
				,xts_behaviourname = "xts_behaviourname Value"
				,owneridname = "owneridname Value"
				,modifiedonbehalfbyname = "modifiedonbehalfbyname Value"
				,xts_salesdimension5from = "xts_salesdimension5from Value"
				,ktb_interfacedtoexternalsystemname = "ktb_interfacedtoexternalsystemname Value"
				,xts_cogsdimension2idname = "xts_cogsdimension2idname Value"
				,xts_servicetemplategroupid = "xts_servicetemplategroupid Value"
				,xts_salesdimension6idname = "xts_salesdimension6idname Value"
				,xts_servicetemplategroupidname = "xts_servicetemplategroupidname Value"
				,xts_downpaymentdimension6id = "xts_downpaymentdimension6id Value"
				,xts_discdimension3id = "xts_discdimension3id Value"
				,owningteam = "owningteam Value"
				,xts_aftervsoname = "xts_aftervsoname Value"
				,xts_discountdimension3from = "xts_discountdimension3from Value"
				,ktb_validatorwotruename = "ktb_validatorwotruename Value"
				,versionnumber = "versionnumber Value"
				,ktb_isprintgatepassreadytobeinvoicename = "ktb_isprintgatepassreadytobeinvoicename Value"
				,ktb_issmartpackage = "ktb_issmartpackage Value"
				,xts_salesdimension5fromname = "xts_salesdimension5fromname Value"
				,xts_discdimension8idname = "xts_discdimension8idname Value"
				,xts_discountdimension2from = "xts_discountdimension2from Value"
				,xts_aftersales = "xts_aftersales Value"
				,xts_salesdimension1from = "xts_salesdimension1from Value"
				,xts_discdimension1idname = "xts_discdimension1idname Value"
				,xts_ardimension3id = "xts_ardimension3id Value"
				,xts_discdimension2idname = "xts_discdimension2idname Value"
				,xts_salesdimension1fromname = "xts_salesdimension1fromname Value"
				,createdonbehalfbyyominame = "createdonbehalfbyyominame Value"
				,xts_downpaymentdimension1id = "xts_downpaymentdimension1id Value"
				,ktb_isbilltoatpmname = "ktb_isbilltoatpmname Value"
				,xts_salesdimension6id = "xts_salesdimension6id Value"
				,xts_cogsdimension2id = "xts_cogsdimension2id Value"
				,xts_cogsdimension3id = "xts_cogsdimension3id Value"
				,ktb_defaultwarehouseidname = "ktb_defaultwarehouseidname Value"
				,xts_salesdimension9idname = "xts_salesdimension9idname Value"
				,xts_discountdimension5from = "xts_discountdimension5from Value"
				,xts_salesdimension6from = "xts_salesdimension6from Value"
				,xts_discdimension4idname = "xts_discdimension4idname Value"
				,xts_aftersalesname = "xts_aftersalesname Value"
				,xts_cogsdimension8id = "xts_cogsdimension8id Value"
				,createdbyname = "createdbyname Value"
				,xts_discdimension1id = "xts_discdimension1id Value"
				,xts_salesdimension1idname = "xts_salesdimension1idname Value"
				,xts_salesdimension3fromname = "xts_salesdimension3fromname Value"
				,xts_businessunitidname = "xts_businessunitidname Value"
				,statecode = "statecode Value"
				,xts_ardimension4idname = "xts_ardimension4idname Value"
				,modifiedonbehalfbyyominame = "modifiedonbehalfbyyominame Value"
				,createdby = "createdby Value"
				,xts_discdimension8id = "xts_discdimension8id Value"
				,xts_discdimension5id = "xts_discdimension5id Value"
				,xts_discdimension6id = "xts_discdimension6id Value"
				,xts_salesdimension8idname = "xts_salesdimension8idname Value"
				,xts_ordervehicle = "xts_ordervehicle Value"
				,xts_downpaymentdimension3id = "xts_downpaymentdimension3id Value"
				,xts_salesdimension2from = "xts_salesdimension2from Value"
				,utcconversiontimezonecode = "utcconversiontimezonecode Value"
				,xts_discdimension5idname = "xts_discdimension5idname Value"
				,xts_downpaymentdimension5idname = "xts_downpaymentdimension5idname Value"
				,xts_discdimension6idname = "xts_discdimension6idname Value"
				,xts_ardimension4id = "xts_ardimension4id Value"
				,importsequencenumber = "importsequencenumber Value"
				,xts_locking = "xts_locking Value"
				,xts_cogsdimension1id = "xts_cogsdimension1id Value"
				,xts_discountdimension2fromname = "xts_discountdimension2fromname Value"
				,xts_ardimension6idname = "xts_ardimension6idname Value"
				,xts_downpaymentdimension3idname = "xts_downpaymentdimension3idname Value"
				,xts_salesdimension7id = "xts_salesdimension7id Value"
				,xts_cogsaccountidname = "xts_cogsaccountidname Value"
				,xts_salesaccountid = "xts_salesaccountid Value"
				,xts_businessunitid = "xts_businessunitid Value"
				,xts_downpaymentdimension1idname = "xts_downpaymentdimension1idname Value"
				,ktb_defaultlocationwo = "ktb_defaultlocationwo Value"
				,xts_salesdimension2idname = "xts_salesdimension2idname Value"
				,ktb_isprintgatepassreadytobeinvoice = "ktb_isprintgatepassreadytobeinvoice Value"
				,xts_discountdimension4from = "xts_discountdimension4from Value"
				,xts_salesdimension8id = "xts_salesdimension8id Value"
				,xts_discountdimension3fromname = "xts_discountdimension3fromname Value"
				,xts_servicetemplateparentgroupid = "xts_servicetemplateparentgroupid Value"
				,modifiedbyname = "modifiedbyname Value"
				,createdbyyominame = "createdbyyominame Value"
				,ktb_ordertypetranstype = "ktb_ordertypetranstype Value"
				,xts_ardimension1idname = "xts_ardimension1idname Value"
				,xts_discountaccountidname = "xts_discountaccountidname Value"
				,xts_downpaymentdimension2idname = "xts_downpaymentdimension2idname Value"
				,ktb_validatorwotrue = "ktb_validatorwotrue Value"
				,xts_salesdimension2id = "xts_salesdimension2id Value"
				,xts_cogsdimension10idname = "xts_cogsdimension10idname Value"
				,xts_salesdimension9id = "xts_salesdimension9id Value"
				,xts_pkcombinationkey = "xts_pkcombinationkey Value"
				,xts_regularservicename = "xts_regularservicename Value"
				,xts_regularservice = "xts_regularservice Value"
				,msdyn_companycode = "msdyn_companycode Value"
            };

            return obj;
        }
    }
}