#region Summary
// ===========================================================================
// AUTHOR        : BSI Code Generator 
// SPECIAL NOTES : DNet WebApi Project
// ---------------------
// Copyright  (c) 2019 
// ---------------------
// $History      : $
// Created on 10/01/2020 7:00:32]
//
// ===========================================================================	
#endregion

using Swashbuckle.Examples;

namespace KTB.DNet.Interface.WebApi.Models.Examples
{
    public class APIUpdateVWI_CRM_xts_deliveryorderExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var obj = new
            {
                UpdatedBy = "DealerUser"
				,company = "company Value"
				,businessunitcode = "businessunitcode Value"
				,xts_totaltaxamount_base = "xts_totaltaxamount_base Value"
				,xts_parentbusinessunitid = "xts_parentbusinessunitid Value"
				,versionnumber = "versionnumber Value"
				,createdon = "createdon Value"
				,xts_billtocustomeridyominame = "xts_billtocustomeridyominame Value"
				,xts_villageandstreetid = "xts_villageandstreetid Value"
				,xts_methodofpaymentidname = "xts_methodofpaymentidname Value"
				,xts_provinceid = "xts_provinceid Value"
				,xts_referenceid = "xts_referenceid Value"
				,xts_referencenumberlookuptype = "xts_referencenumberlookuptype Value"
				,ktb_arinvoicenoname = "ktb_arinvoicenoname Value"
				,statuscodename = "statuscodename Value"
				,xts_status = "xts_status Value"
				,xts_customerid = "xts_customerid Value"
				,xts_referencenumbersalesorderidname = "xts_referencenumbersalesorderidname Value"
				,modifiedbyyominame = "modifiedbyyominame Value"
				,owneridtype = "owneridtype Value"
				,xts_log = "xts_log Value"
				,xts_totalbaseamount_base = "xts_totalbaseamount_base Value"
				,createdonbehalfby = "createdonbehalfby Value"
				,modifiedbyname = "modifiedbyname Value"
				,xts_totalwithholdingtaxamount = "xts_totalwithholdingtaxamount Value"
				,xjp_idempotentmessage = "xjp_idempotentmessage Value"
				,xts_deliveryaddressidname = "xts_deliveryaddressidname Value"
				,xts_billtocustomeridname = "xts_billtocustomeridname Value"
				,owneridname = "owneridname Value"
				,xts_totalmiscchargebaseamount = "xts_totalmiscchargebaseamount Value"
				,overriddencreatedon = "overriddencreatedon Value"
				,xts_billtocustomerid = "xts_billtocustomerid Value"
				,xts_deliveryorderid = "xts_deliveryorderid Value"
				,xts_ordertypeid = "xts_ordertypeid Value"
				,xts_villageandstreetidname = "xts_villageandstreetidname Value"
				,ktb_statusinterfacedesc = "ktb_statusinterfacedesc Value"
				,xts_eventdata = "xts_eventdata Value"
				,modifiedonbehalfby = "modifiedonbehalfby Value"
				,exchangerate = "exchangerate Value"
				,ktb_cogsupdated = "ktb_cogsupdated Value"
				,xts_address4 = "xts_address4 Value"
				,owningteam = "owningteam Value"
				,xts_totalbaseamount = "xts_totalbaseamount Value"
				,xts_deliveryaddressid = "xts_deliveryaddressid Value"
				,xts_totalreceipt = "xts_totalreceipt Value"
				,statecode = "statecode Value"
				,xts_totaldiscountamount_base = "xts_totaldiscountamount_base Value"
				,xts_salespersonid = "xts_salespersonid Value"
				,xts_totalmiscchargebaseamount_base = "xts_totalmiscchargebaseamount_base Value"
				,timezoneruleversionnumber = "timezoneruleversionnumber Value"
				,xts_referencenumbersalesorderid = "xts_referencenumbersalesorderid Value"
				,xts_deliverytypename = "xts_deliverytypename Value"
				,xts_totaltaxamount = "xts_totaltaxamount Value"
				,xts_totalwithholdingtaxamount_base = "xts_totalwithholdingtaxamount_base Value"
				,xts_referencenumberdeliveryorderid = "xts_referencenumberdeliveryorderid Value"
				,ktb_statusinterface = "ktb_statusinterface Value"
				,xts_salespersonidname = "xts_salespersonidname Value"
				,xts_referencenumberlookupname = "xts_referencenumberlookupname Value"
				,xts_locking = "xts_locking Value"
				,xts_customercontactid = "xts_customercontactid Value"
				,xts_termofpaymentidname = "xts_termofpaymentidname Value"
				,xts_totalamountbeforediscount = "xts_totalamountbeforediscount Value"
				,xts_customernumber = "xts_customernumber Value"
				,ktb_handlinginterface = "ktb_handlinginterface Value"
				,xts_countryid = "xts_countryid Value"
				,xts_provinceidname = "xts_provinceidname Value"
				,xts_totalreceipt_base = "xts_totalreceipt_base Value"
				,createdonbehalfbyname = "createdonbehalfbyname Value"
				,createdbyyominame = "createdbyyominame Value"
				,xts_handling = "xts_handling Value"
				,xts_cityid = "xts_cityid Value"
				,ktb_handlinginterfacename = "ktb_handlinginterfacename Value"
				,utcconversiontimezonecode = "utcconversiontimezonecode Value"
				,xts_businessunitid = "xts_businessunitid Value"
				,xts_deliveryordernumber = "xts_deliveryordernumber Value"
				,xts_statusname = "xts_statusname Value"
				,xts_customeridyominame = "xts_customeridyominame Value"
				,ownerid = "ownerid Value"
				,modifiedon = "modifiedon Value"
				,importsequencenumber = "importsequencenumber Value"
				,owneridyominame = "owneridyominame Value"
				,xts_countryidname = "xts_countryidname Value"
				,xts_businessphone = "xts_businessphone Value"
				,xts_customeridname = "xts_customeridname Value"
				,xts_termofpaymentid = "xts_termofpaymentid Value"
				,xts_customerlookuptype = "xts_customerlookuptype Value"
				,xts_address2 = "xts_address2 Value"
				,xts_customercontactidyominame = "xts_customercontactidyominame Value"
				,xts_totalmiscchargetaxamount = "xts_totalmiscchargetaxamount Value"
				,xts_ordertypeidname = "xts_ordertypeidname Value"
				,createdbyname = "createdbyname Value"
				,xts_methodofpaymentid = "xts_methodofpaymentid Value"
				,xts_referencenumberdeliveryorderidname = "xts_referencenumberdeliveryorderidname Value"
				,modifiedonbehalfbyname = "modifiedonbehalfbyname Value"
				,xts_deliverytype = "xts_deliverytype Value"
				,xts_address3 = "xts_address3 Value"
				,xts_totalmiscchargetaxamount_base = "xts_totalmiscchargetaxamount_base Value"
				,xts_cityidname = "xts_cityidname Value"
				,xts_transactiondate = "xts_transactiondate Value"
				,ktb_say = "ktb_say Value"
				,xts_handlingname = "xts_handlingname Value"
				,xts_grandtotal = "xts_grandtotal Value"
				,xts_grandtotal_base = "xts_grandtotal_base Value"
				,xts_postalcode = "xts_postalcode Value"
				,xts_customerlookupname = "xts_customerlookupname Value"
				,ktb_customerdescription = "ktb_customerdescription Value"
				,xts_cancellationdate = "xts_cancellationdate Value"
				,createdby = "createdby Value"
				,modifiedby = "modifiedby Value"
				,xts_address1 = "xts_address1 Value"
				,ktb_saywithouttax = "ktb_saywithouttax Value"
				,xts_externalreferencenumber = "xts_externalreferencenumber Value"
				,owninguser = "owninguser Value"
				,transactioncurrencyidname = "transactioncurrencyidname Value"
				,createdonbehalfbyyominame = "createdonbehalfbyyominame Value"
				,owningbusinessunit = "owningbusinessunit Value"
				,xts_totaldiscountamount = "xts_totaldiscountamount Value"
				,transactioncurrencyid = "transactioncurrencyid Value"
				,ktb_modelcode = "ktb_modelcode Value"
				,xts_parentbusinessunitidname = "xts_parentbusinessunitidname Value"
				,ktb_arinvoiceno = "ktb_arinvoiceno Value"
				,ktb_cogsupdatedname = "ktb_cogsupdatedname Value"
				,statuscode = "statuscode Value"
				,modifiedonbehalfbyyominame = "modifiedonbehalfbyyominame Value"
				,xts_eventdatantext = "xts_eventdatantext Value"
				,xts_totalamountbeforediscount_base = "xts_totalamountbeforediscount_base Value"
				,statecodename = "statecodename Value"
				,xts_businessunitidname = "xts_businessunitidname Value"
				,xts_customercontactidname = "xts_customercontactidname Value"
				,ktb_ordervehiclename = "ktb_ordervehiclename Value"
				,ktb_ordervehicle = "ktb_ordervehicle Value"
				,xts_totalmiscchargeamount_base = "xts_totalmiscchargeamount_base Value"
				,xts_totalmiscchargeamount = "xts_totalmiscchargeamount Value"
				,msdyn_companycode = "msdyn_companycode Value"
            };

            return obj;
        }
    }
}