#region Summary
// ===========================================================================
// AUTHOR        : BSI Code Generator 
// SPECIAL NOTES : DNet WebApi Project
// ---------------------
// Copyright  (c) 2019 
// ---------------------
// $History      : $
// Created on 1/9/2020 1:13:11 PM]
//
// ===========================================================================	
#endregion

using Swashbuckle.Examples;

namespace KTB.DNet.Interface.WebApi.Models.Examples
{
    public class APIUpdateVWI_CRM_xts_purchaseorderExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var obj = new
            {
                UpdatedBy = "DealerUser"
				,company = "company Value"
				,businessunitcode = "businessunitcode Value"
				,ktb_dealerpknumber = "ktb_dealerpknumber Value"
				,xts_prpotypeidname = "xts_prpotypeidname Value"
				,xts_taxablename = "xts_taxablename Value"
				,xts_totalwithholdingtaxamount_base = "xts_totalwithholdingtaxamount_base Value"
				,ktb_documenttype = "ktb_documenttype Value"
				,ktb_purchaseorderno = "ktb_purchaseorderno Value"
				,ktb_redeemamount = "ktb_redeemamount Value"
				,modifiedon = "modifiedon Value"
				,overriddencreatedon = "overriddencreatedon Value"
				,xts_downpaymentispaid = "xts_downpaymentispaid Value"
				,statuscodename = "statuscodename Value"
				,xts_status = "xts_status Value"
				,xts_partsforecastid = "xts_partsforecastid Value"
				,xts_totaltitleregistrationfee_base = "xts_totaltitleregistrationfee_base Value"
				,xts_handling = "xts_handling Value"
				,xts_workorderidname = "xts_workorderidname Value"
				,xts_downpaymentamountpaid_base = "xts_downpaymentamountpaid_base Value"
				,ktb_methodofpaymentid = "ktb_methodofpaymentid Value"
				,ktb_salesorderdate = "ktb_salesorderdate Value"
				,transactioncurrencyidname = "transactioncurrencyidname Value"
				,xts_vendordescription = "xts_vendordescription Value"
				,xts_postalcode = "xts_postalcode Value"
				,ktb_salesorderno = "ktb_salesorderno Value"
				,xts_balance_base = "xts_balance_base Value"
				,xts_termsofpaymentdescription = "xts_termsofpaymentdescription Value"
				,xts_workorderid = "xts_workorderid Value"
				,xts_personinchargeid = "xts_personinchargeid Value"
				,owningbusinessunit = "owningbusinessunit Value"
				,xts_totalamountbeforediscount = "xts_totalamountbeforediscount Value"
				,ktb_salesordertype = "ktb_salesordertype Value"
				,ktb_isbodypaint = "ktb_isbodypaint Value"
				,ktb_isinterfaced = "ktb_isinterfaced Value"
				,xts_salesorderid = "xts_salesorderid Value"
				,xts_totalpaymentamount = "xts_totalpaymentamount Value"
				,ktb_numberofinstallment = "ktb_numberofinstallment Value"
				,xts_formsourcename = "xts_formsourcename Value"
				,modifiedonbehalfby = "modifiedonbehalfby Value"
				,xts_totalpaymentamount_base = "xts_totalpaymentamount_base Value"
				,statuscode = "statuscode Value"
				,ktb_ordertypename = "ktb_ordertypename Value"
				,ktb_purchasetypename = "ktb_purchasetypename Value"
				,xts_warehouseidname = "xts_warehouseidname Value"
				,ktb_orderno = "ktb_orderno Value"
				,ktb_pph22amount = "ktb_pph22amount Value"
				,xts_totaldiscountamount_base = "xts_totaldiscountamount_base Value"
				,xts_vendorcountryid = "xts_vendorcountryid Value"
				,ktb_purchasepriorityname = "ktb_purchasepriorityname Value"
				,xts_stockreferencenumber = "xts_stockreferencenumber Value"
				,ktb_dnetsalesordertype = "ktb_dnetsalesordertype Value"
				,ktb_identificationtype = "ktb_identificationtype Value"
				,statecodename = "statecodename Value"
				,bsi_isfactoringname = "bsi_isfactoringname Value"
				,xts_closereason = "xts_closereason Value"
				,ktb_documenttypename = "ktb_documenttypename Value"
				,xts_newvehiclesalesorderidname = "xts_newvehiclesalesorderidname Value"
				,exchangerate = "exchangerate Value"
				,xts_includetax = "xts_includetax Value"
				,ktb_salespersonid = "ktb_salespersonid Value"
				,ktb_duedate = "ktb_duedate Value"
				,ktb_pph22amount_base = "ktb_pph22amount_base Value"
				,xts_termsofpaymentidname = "xts_termsofpaymentidname Value"
				,createdon = "createdon Value"
				,ktb_orderconfirmationno = "ktb_orderconfirmationno Value"
				,ktb_purchasepriority = "ktb_purchasepriority Value"
				,xts_purchaseordernumber = "xts_purchaseordernumber Value"
				,xts_statusname = "xts_statusname Value"
				,ktb_landedcost_base = "ktb_landedcost_base Value"
				,xts_totalbaseamount_base = "xts_totalbaseamount_base Value"
				,xts_totalconsumptiontaxamount = "xts_totalconsumptiontaxamount Value"
				,xts_externaldocumentnumber = "xts_externaldocumentnumber Value"
				,processid = "processid Value"
				,owneridyominame = "owneridyominame Value"
				,xts_countryid = "xts_countryid Value"
				,xts_eventdata2 = "xts_eventdata2 Value"
				,modifiedby = "modifiedby Value"
				,timezoneruleversionnumber = "timezoneruleversionnumber Value"
				,createdbyname = "createdbyname Value"
				,xts_address1 = "xts_address1 Value"
				,xts_includetaxname = "xts_includetaxname Value"
				,xts_personinchargeidname = "xts_personinchargeidname Value"
				,xts_totalamountbeforediscount_base = "xts_totalamountbeforediscount_base Value"
				,xts_totalwithholdingtaxamount = "xts_totalwithholdingtaxamount Value"
				,xts_priority = "xts_priority Value"
				,traversedpath = "traversedpath Value"
				,xts_grandtotal = "xts_grandtotal Value"
				,owninguser = "owninguser Value"
				,xts_taxable = "xts_taxable Value"
				,owneridtype = "owneridtype Value"
				,ktb_interfacestatusname = "ktb_interfacestatusname Value"
				,xts_transactiondate = "xts_transactiondate Value"
				,xts_termsofpaymentid = "xts_termsofpaymentid Value"
				,xts_partsforecastidname = "xts_partsforecastidname Value"
				,owneridname = "owneridname Value"
				,ktb_salesorderidname = "ktb_salesorderidname Value"
				,ktb_isinterfacedname = "ktb_isinterfacedname Value"
				,createdonbehalfbyyominame = "createdonbehalfbyyominame Value"
				,ktb_dnetsalesordertypename = "ktb_dnetsalesordertypename Value"
				,xts_totalconsumptiontaxamount_base = "xts_totalconsumptiontaxamount_base Value"
				,owningteam = "owningteam Value"
				,xts_vendoraddress2 = "xts_vendoraddress2 Value"
				,ktb_salesorderid = "ktb_salesorderid Value"
				,xts_grandtotal_base = "xts_grandtotal_base Value"
				,xts_prpotypeid = "xts_prpotypeid Value"
				,xts_parentbusinessunitidname = "xts_parentbusinessunitidname Value"
				,xts_siteid = "xts_siteid Value"
				,xts_downpayment_base = "xts_downpayment_base Value"
				,xts_totalbaseamount = "xts_totalbaseamount Value"
				,createdonbehalfby = "createdonbehalfby Value"
				,ktb_ordertype = "ktb_ordertype Value"
				,xts_countryidname = "xts_countryidname Value"
				,xts_parentbusinessunitid = "xts_parentbusinessunitid Value"
				,transactioncurrencyid = "transactioncurrencyid Value"
				,xts_eventdata = "xts_eventdata Value"
				,xts_cityid = "xts_cityid Value"
				,xts_downpayment = "xts_downpayment Value"
				,modifiedonbehalfbyname = "modifiedonbehalfbyname Value"
				,xts_vendorprovinceidname = "xts_vendorprovinceidname Value"
				,xts_vendoraddress3 = "xts_vendoraddress3 Value"
				,bsi_isfactoring = "bsi_isfactoring Value"
				,ktb_vehicletotalamount = "ktb_vehicletotalamount Value"
				,xts_warehouseid = "xts_warehouseid Value"
				,xts_priorityname = "xts_priorityname Value"
				,modifiedbyyominame = "modifiedbyyominame Value"
				,ownerid = "ownerid Value"
				,ktb_identificationtypename = "ktb_identificationtypename Value"
				,ktb_interesttotalamount_base = "ktb_interesttotalamount_base Value"
				,ktb_interesttotalamount = "ktb_interesttotalamount Value"
				,createdonbehalfbyname = "createdonbehalfbyname Value"
				,xts_provinceidname = "xts_provinceidname Value"
				,ktb_say = "ktb_say Value"
				,xts_vendoridname = "xts_vendoridname Value"
				,xts_deliverymethodname = "xts_deliverymethodname Value"
				,ktb_isbodypaintname = "ktb_isbodypaintname Value"
				,xts_businessunitidname = "xts_businessunitidname Value"
				,xts_description = "xts_description Value"
				,xts_totaltitleregistrationfee = "xts_totaltitleregistrationfee Value"
				,xts_siteidname = "xts_siteidname Value"
				,ktb_landedcost = "ktb_landedcost Value"
				,modifiedonbehalfbyyominame = "modifiedonbehalfbyyominame Value"
				,createdby = "createdby Value"
				,xts_vendorcityidname = "xts_vendorcityidname Value"
				,xts_downpaymentamountpaid = "xts_downpaymentamountpaid Value"
				,ktb_vehicletotalamount_base = "ktb_vehicletotalamount_base Value"
				,xts_purchaseorderid = "xts_purchaseorderid Value"
				,xts_balance = "xts_balance Value"
				,ktb_redeemamount_base = "ktb_redeemamount_base Value"
				,xjp_idempotentmessage = "xjp_idempotentmessage Value"
				,xts_totaldiscountamount = "xts_totaldiscountamount Value"
				,stageid = "stageid Value"
				,utcconversiontimezonecode = "utcconversiontimezonecode Value"
				,xts_vendorid = "xts_vendorid Value"
				,xts_vendorcityid = "xts_vendorcityid Value"
				,xts_provinceid = "xts_provinceid Value"
				,ktb_interfacestatus = "ktb_interfacestatus Value"
				,xts_vendorpostalcode = "xts_vendorpostalcode Value"
				,importsequencenumber = "importsequencenumber Value"
				,xts_locking = "xts_locking Value"
				,xts_vendoraddress1 = "xts_vendoraddress1 Value"
				,xts_vendorcountryidname = "xts_vendorcountryidname Value"
				,xts_downpaymentispaidname = "xts_downpaymentispaidname Value"
				,ktb_methodofpaymentidname = "ktb_methodofpaymentidname Value"
				,xts_paymentgroupname = "xts_paymentgroupname Value"
				,xts_address2 = "xts_address2 Value"
				,xts_businessunitid = "xts_businessunitid Value"
				,xts_vendorprovinceid = "xts_vendorprovinceid Value"
				,xts_allocationperiod = "xts_allocationperiod Value"
				,ktb_purchasetype = "ktb_purchasetype Value"
				,xts_vendoraddress4 = "xts_vendoraddress4 Value"
				,xts_salesorderidname = "xts_salesorderidname Value"
				,xts_handlingname = "xts_handlingname Value"
				,xts_deliverymethod = "xts_deliverymethod Value"
				,xts_paymentgroup = "xts_paymentgroup Value"
				,modifiedbyname = "modifiedbyname Value"
				,createdbyyominame = "createdbyyominame Value"
				,xts_newvehiclesalesorderid = "xts_newvehiclesalesorderid Value"
				,xts_address4 = "xts_address4 Value"
				,xts_cityidname = "xts_cityidname Value"
				,xts_address3 = "xts_address3 Value"
				,xts_formsource = "xts_formsource Value"
				,ktb_salespersonidname = "ktb_salespersonidname Value"
				,versionnumber = "versionnumber Value"
				,statecode = "statecode Value"
				,ktb_etd = "ktb_etd Value"
				,msdyn_companycode = "msdyn_companycode Value"
            };

            return obj;
        }
    }
}