#region Summary
// ===========================================================================
// AUTHOR        : BSI Code Generator 
// SPECIAL NOTES : DNet WebApi Project
// ---------------------
// Copyright  (c) 2019 
// ---------------------
// $History      : $
// Created on 15/01/2020 8:22:46]
//
// ===========================================================================	
#endregion

using Swashbuckle.Examples;

namespace KTB.DNet.Interface.WebApi.Models.Examples
{
    public class APIUpdateVWI_CRM_xts_employeeExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var obj = new
            {
                UpdatedBy = "DealerUser"
				,company = "company Value"
				,businessunitcode = "businessunitcode Value"
				,ktb_salesmanarea = "ktb_salesmanarea Value"
				,xts_salutation = "xts_salutation Value"
				,xts_pkcombinationkey = "xts_pkcombinationkey Value"
				,ktb_salespersoncode = "ktb_salespersoncode Value"
				,modifiedon = "modifiedon Value"
				,ktb_ukuranbaju = "ktb_ukuranbaju Value"
				,overriddencreatedon = "overriddencreatedon Value"
				,statuscodename = "statuscodename Value"
				,ktb_salesmanlevelname = "ktb_salesmanlevelname Value"
				,entityimage_timestamp = "entityimage_timestamp Value"
				,modifiedbyyominame = "modifiedbyyominame Value"
				,ktb_superiorsname = "ktb_superiorsname Value"
				,xts_resigndate = "xts_resigndate Value"
				,xts_mobilephone = "xts_mobilephone Value"
				,xts_regardinguseridyominame = "xts_regardinguseridyominame Value"
				,ktb_positionname = "ktb_positionname Value"
				,ktb_interfacehandling = "ktb_interfacehandling Value"
				,bsi_resigntype = "bsi_resigntype Value"
				,bsi_resigntypename = "bsi_resigntypename Value"
				,xts_employeeclassidname = "xts_employeeclassidname Value"
				,xts_regardinguseridname = "xts_regardinguseridname Value"
				,xts_lastname = "xts_lastname Value"
				,owningbusinessunit = "owningbusinessunit Value"
				,modifiedbyname = "modifiedbyname Value"
				,bsi_resignstatusdnet = "bsi_resignstatusdnet Value"
				,ktb_educationname = "ktb_educationname Value"
				,ktb_kategoriteamname = "ktb_kategoriteamname Value"
				,ktb_isinterfaced = "ktb_isinterfaced Value"
				,xts_employeeclasstypename = "xts_employeeclasstypename Value"
				,xts_employeeclassid = "xts_employeeclassid Value"
				,ktb_interfaceexceptionmessage = "ktb_interfaceexceptionmessage Value"
				,ktb_education = "ktb_education Value"
				,statuscode = "statuscode Value"
				,bsi_resignreason = "bsi_resignreason Value"
				,ktb_religion = "ktb_religion Value"
				,versionnumber = "versionnumber Value"
				,statecodename = "statecodename Value"
				,xts_joindate = "xts_joindate Value"
				,xts_departmentidname = "xts_departmentidname Value"
				,xts_taxregistrationnumber = "xts_taxregistrationnumber Value"
				,ktb_jobpositionid = "ktb_jobpositionid Value"
				,xts_birthdate = "xts_birthdate Value"
				,createdon = "createdon Value"
				,ktb_maritalstatusname = "ktb_maritalstatusname Value"
				,xts_workingstatus = "xts_workingstatus Value"
				,xts_employeeid = "xts_employeeid Value"
				,bsi_nomorsepatu = "bsi_nomorsepatu Value"
				,ktb_shirtsize = "ktb_shirtsize Value"
				,ktb_salesmanareaname = "ktb_salesmanareaname Value"
				,bsi_resignreasonname = "bsi_resignreasonname Value"
				,owneridyominame = "owneridyominame Value"
				,entityimage_url = "entityimage_url Value"
				,xts_countryid = "xts_countryid Value"
				,modifiedby = "modifiedby Value"
				,timezoneruleversionnumber = "timezoneruleversionnumber Value"
				,xts_address1 = "xts_address1 Value"
				,modifiedonbehalfby = "modifiedonbehalfby Value"
				,ktb_superiors = "ktb_superiors Value"
				,ktb_resignreason = "ktb_resignreason Value"
				,ktb_outsourcename = "ktb_outsourcename Value"
				,ktb_jobpositionidname = "ktb_jobpositionidname Value"
				,ktb_kategoriteam = "ktb_kategoriteam Value"
				,ktb_position = "ktb_position Value"
				,xts_workingstatusname = "xts_workingstatusname Value"
				,ktb_outsource = "ktb_outsource Value"
				,ktb_salesmanlevel = "ktb_salesmanlevel Value"
				,ktb_categoryname = "ktb_categoryname Value"
				,xts_aliasname = "xts_aliasname Value"
				,createdonbehalfbyname = "createdonbehalfbyname Value"
				,owninguser = "owninguser Value"
				,xts_departmentid = "xts_departmentid Value"
				,ktb_interfacehandlingname = "ktb_interfacehandlingname Value"
				,owneridtype = "owneridtype Value"
				,xts_employee = "xts_employee Value"
				,ktb_interfacestatusname = "ktb_interfacestatusname Value"
				,entityimageid = "entityimageid Value"
				,ktb_birthplacename = "ktb_birthplacename Value"
				,ktb_resigntype = "ktb_resigntype Value"
				,owneridname = "owneridname Value"
				,entityimage = "entityimage Value"
				,modifiedonbehalfbyname = "modifiedonbehalfbyname Value"
				,createdonbehalfbyyominame = "createdonbehalfbyyominame Value"
				,xts_fax = "xts_fax Value"
				,ktb_maritalstatus = "ktb_maritalstatus Value"
				,owningteam = "owningteam Value"
				,xts_firstname = "xts_firstname Value"
				,xts_address3 = "xts_address3 Value"
				,xts_parentemployeeidname = "xts_parentemployeeidname Value"
				,xts_businessphone = "xts_businessphone Value"
				,createdonbehalfby = "createdonbehalfby Value"
				,ktb_resigntypename = "ktb_resigntypename Value"
				,xts_postalcode = "xts_postalcode Value"
				,bsi_nomorsepatukoma = "bsi_nomorsepatukoma Value"
				,ktb_category = "ktb_category Value"
				,xts_cityid = "xts_cityid Value"
				,xts_description = "xts_description Value"
				,bsi_rejectedreason = "bsi_rejectedreason Value"
				,ktb_isinterfacedname = "ktb_isinterfacedname Value"
				,xts_position = "xts_position Value"
				,ownerid = "ownerid Value"
				,ktb_identificationtypename = "ktb_identificationtypename Value"
				,xts_permanentname = "xts_permanentname Value"
				,xts_provinceidname = "xts_provinceidname Value"
				,ktb_birthplace = "ktb_birthplace Value"
				,createdbyname = "createdbyname Value"
				,ktb_identificationno = "ktb_identificationno Value"
				,xts_newvehiclereservationbalance = "xts_newvehiclereservationbalance Value"
				,xts_businessunitidname = "xts_businessunitidname Value"
				,statecode = "statecode Value"
				,modifiedonbehalfbyyominame = "modifiedonbehalfbyyominame Value"
				,createdby = "createdby Value"
				,xts_villageandstreetidname = "xts_villageandstreetidname Value"
				,ktb_id = "ktb_id Value"
				,bsi_resignstatusdnetname = "bsi_resignstatusdnetname Value"
				,xts_permanent = "xts_permanent Value"
				,xts_homephone = "xts_homephone Value"
				,xts_countryidname = "xts_countryidname Value"
				,utcconversiontimezonecode = "utcconversiontimezonecode Value"
				,xts_shortname = "xts_shortname Value"
				,xts_provinceid = "xts_provinceid Value"
				,ktb_salary = "ktb_salary Value"
				,xts_regardinguserid = "xts_regardinguserid Value"
				,importsequencenumber = "importsequencenumber Value"
				,xts_locking = "xts_locking Value"
				,ktb_interfacestatus = "ktb_interfacestatus Value"
				,xts_email = "xts_email Value"
				,xts_gendername = "xts_gendername Value"
				,xts_address2 = "xts_address2 Value"
				,xts_businessunitid = "xts_businessunitid Value"
				,xts_parentemployeeid = "xts_parentemployeeid Value"
				,xts_employeeclasstype = "xts_employeeclasstype Value"
				,xts_gender = "xts_gender Value"
				,ktb_ukuranbajuname = "ktb_ukuranbajuname Value"
				,createdbyyominame = "createdbyyominame Value"
				,ktb_salesmancodereff = "ktb_salesmancodereff Value"
				,xts_positionname = "xts_positionname Value"
				,xts_address4 = "xts_address4 Value"
				,xts_cityidname = "xts_cityidname Value"
				,ktb_identificationtype = "ktb_identificationtype Value"
				,ktb_employeecode = "ktb_employeecode Value"
				,ktb_religionname = "ktb_religionname Value"
				,ktb_superiorscode = "ktb_superiorscode Value"
				,xts_villageandstreetid = "xts_villageandstreetid Value"
				,xts_otherphone = "xts_otherphone Value"
				,msdyn_companycode = "msdyn_companycode Value"
            };

            return obj;
        }
    }
}