#region Summary
// ===========================================================================
// AUTHOR        : BSI Code Generator 
// SPECIAL NOTES : DNet WebApi Project
// ---------------------
// Copyright  (c) 2019 
// ---------------------
// $History      : $
// Created on 24/02/2020 18:15:44]
//
// ===========================================================================	
#endregion

using Swashbuckle.Examples;

namespace KTB.DNet.Interface.WebApi.Models.Examples
{
    public class APIUpdateVWI_CRM_campaignExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var obj = new
            {
                UpdatedBy = "DealerUser"
				,company = "company Value"
				,businessunitcode = "businessunitcode Value"
				,ktb_luaspameran = "ktb_luaspameran Value"
				,xts_parentbusinessunitid = "xts_parentbusinessunitid Value"
				,versionnumber = "versionnumber Value"
				,entityimage_timestamp = "entityimage_timestamp Value"
				,createdon = "createdon Value"
				,objective = "objective Value"
				,modifiedonbehalfbyyominame = "modifiedonbehalfbyyominame Value"
				,tmpregardingobjectid = "tmpregardingobjectid Value"
				,xts_totalwonopportunities = "xts_totalwonopportunities Value"
				,xts_totalwonopportunities_state = "xts_totalwonopportunities_state Value"
				,entityimage_url = "entityimage_url Value"
				,statuscodename = "statuscodename Value"
				,modifiedbyyominame = "modifiedbyyominame Value"
				,xts_salesobjective = "xts_salesobjective Value"
				,owneridtype = "owneridtype Value"
				,ktb_approvalsewatempat_base = "ktb_approvalsewatempat_base Value"
				,createdonbehalfby = "createdonbehalfby Value"
				,promotioncodename = "promotioncodename Value"
				,ktb_statuscampaign = "ktb_statuscampaign Value"
				,message = "message Value"
				,ktb_kategoriprodukname = "ktb_kategoriprodukname Value"
				,totalactualcost_base = "totalactualcost_base Value"
				,owneridname = "owneridname Value"
				,ktb_approvalbabit_base = "ktb_approvalbabit_base Value"
				,xts_totalwonopportunities_date = "xts_totalwonopportunities_date Value"
				,overriddencreatedon = "overriddencreatedon Value"
				,xts_totalwonopportunities_base = "xts_totalwonopportunities_base Value"
				,xts_totalcampaignactivities_state = "xts_totalcampaignactivities_state Value"
				,xts_totalvalueopportunities_base = "xts_totalvalueopportunities_base Value"
				,xts_totalcampaignactivities = "xts_totalcampaignactivities Value"
				,createdonbehalfbyyominame = "createdonbehalfbyyominame Value"
				,ktb_biayaoperasional_base = "ktb_biayaoperasional_base Value"
				,modifiedonbehalfby = "modifiedonbehalfby Value"
				,exchangerate = "exchangerate Value"
				,ktb_biayasewa_base = "ktb_biayasewa_base Value"
				,expectedrevenue_base = "expectedrevenue_base Value"
				,xts_totalcampaignresponse_date = "xts_totalcampaignresponse_date Value"
				,budgetedcost_base = "budgetedcost_base Value"
				,owningteam = "owningteam Value"
				,ktb_biayasewa = "ktb_biayasewa Value"
				,xts_totalopportunities_state = "xts_totalopportunities_state Value"
				,xts_convertedleads_date = "xts_convertedleads_date Value"
				,statecode = "statecode Value"
				,ktb_approvalnonbabit_base = "ktb_approvalnonbabit_base Value"
				,expectedrevenue = "expectedrevenue Value"
				,xts_totalcampaignresponse_state = "xts_totalcampaignresponse_state Value"
				,timezoneruleversionnumber = "timezoneruleversionnumber Value"
				,xts_totalmembers = "xts_totalmembers Value"
				,pricelistname = "pricelistname Value"
				,xts_totalcampaignactivities_date = "xts_totalcampaignactivities_date Value"
				,xts_totalvalueopportunities_date = "xts_totalvalueopportunities_date Value"
				,ktb_approvalbabit = "ktb_approvalbabit Value"
				,xts_locking = "xts_locking Value"
				,othercost = "othercost Value"
				,emailaddress = "emailaddress Value"
				,typecodename = "typecodename Value"
				,expectedresponse = "expectedresponse Value"
				,ktb_approvalsewatempat = "ktb_approvalsewatempat Value"
				,traversedpath = "traversedpath Value"
				,createdonbehalfbyname = "createdonbehalfbyname Value"
				,createdbyyominame = "createdbyyominame Value"
				,actualstart = "actualstart Value"
				,ktb_proposalclaimdealer = "ktb_proposalclaimdealer Value"
				,xts_convertedleads = "xts_convertedleads Value"
				,createdby = "createdby Value"
				,utcconversiontimezonecode = "utcconversiontimezonecode Value"
				,xts_convertedleads_state = "xts_convertedleads_state Value"
				,xts_totalmembers_date = "xts_totalmembers_date Value"
				,ktb_statusreason = "ktb_statusreason Value"
				,istemplatename = "istemplatename Value"
				,ownerid = "ownerid Value"
				,modifiedon = "modifiedon Value"
				,importsequencenumber = "importsequencenumber Value"
				,owneridyominame = "owneridyominame Value"
				,ktb_statuscampaignname = "ktb_statuscampaignname Value"
				,xts_totalvalueopportunities_state = "xts_totalvalueopportunities_state Value"
				,processid = "processid Value"
				,description = "description Value"
				,ktb_targetspk = "ktb_targetspk Value"
				,proposedstart = "proposedstart Value"
				,createdbyname = "createdbyname Value"
				,xts_totalcampaignresponse = "xts_totalcampaignresponse Value"
				,xts_businessunitid = "xts_businessunitid Value"
				,xts_salesobjectivename = "xts_salesobjectivename Value"
				,modifiedonbehalfbyname = "modifiedonbehalfbyname Value"
				,pricelistid = "pricelistid Value"
				,entityimage = "entityimage Value"
				,xts_purposeid = "xts_purposeid Value"
				,stageid = "stageid Value"
				,xts_totalvalueopportunities = "xts_totalvalueopportunities Value"
				,codename = "codename Value"
				,proposedend = "proposedend Value"
				,ktb_transactiondate = "ktb_transactiondate Value"
				,transactioncurrencyid = "transactioncurrencyid Value"
				,totalcampaignactivityactualcost = "totalcampaignactivityactualcost Value"
				,campaignid = "campaignid Value"
				,modifiedby = "modifiedby Value"
				,xts_totalopportunities = "xts_totalopportunities Value"
				,xts_website = "xts_website Value"
				,totalactualcost = "totalactualcost Value"
				,owninguser = "owninguser Value"
				,transactioncurrencyidname = "transactioncurrencyidname Value"
				,xts_totalopportunities_date = "xts_totalopportunities_date Value"
				,actualend = "actualend Value"
				,istemplate = "istemplate Value"
				,xts_purposeidname = "xts_purposeidname Value"
				,ktb_statusreasonname = "ktb_statusreasonname Value"
				,ktb_approvalnonbabit = "ktb_approvalnonbabit Value"
				,xts_totalmembers_state = "xts_totalmembers_state Value"
				,ktb_kategoriproduk = "ktb_kategoriproduk Value"
				,xts_parentbusinessunitidname = "xts_parentbusinessunitidname Value"
				,ktb_venuepameran = "ktb_venuepameran Value"
				,name = "name Value"
				,totalcampaignactivityactualcost_base = "totalcampaignactivityactualcost_base Value"
				,ktb_biayaoperasional = "ktb_biayaoperasional Value"
				,statuscode = "statuscode Value"
				,modifiedbyname = "modifiedbyname Value"
				,budgetedcost = "budgetedcost Value"
				,othercost_base = "othercost_base Value"
				,ktb_proposalclaimdealer_base = "ktb_proposalclaimdealer_base Value"
				,entityimageid = "entityimageid Value"
				,xts_categoryid = "xts_categoryid Value"
				,typecode = "typecode Value"
				,ktb_targetprospek = "ktb_targetprospek Value"
				,statecodename = "statecodename Value"
				,xts_businessunitidname = "xts_businessunitidname Value"
				,owningbusinessunit = "owningbusinessunit Value"
				,xts_categoryidname = "xts_categoryidname Value"
				,msdyn_companycode = "msdyn_companycode Value"
            };

            return obj;
        }
    }
}