#region Summary
// ===========================================================================
// AUTHOR        : BSI Code Generator 
// SPECIAL NOTES : DNet WebApi Project
// ---------------------
// Copyright  (c) 2019 
// ---------------------
// $History      : $
// Created on 24/02/2020 18:15:44]
//
// ===========================================================================	
#endregion

using Swashbuckle.Examples;

namespace KTB.DNet.Interface.WebApi.Models.Examples
{
    public class APIUpdateVWI_CRM_xts_salesorderdetailExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var obj = new
            {
                UpdatedBy = "DealerUser"
				,company = "company Value"
				,businessunitcode = "businessunitcode Value"
				,xts_discountpercentage = "xts_discountpercentage Value"
				,xts_exteriorcolorid = "xts_exteriorcolorid Value"
				,xts_consumptiontax2id = "xts_consumptiontax2id Value"
				,xts_consumptiontax1id = "xts_consumptiontax1id Value"
				,xts_quantityreturnedbaseunit = "xts_quantityreturnedbaseunit Value"
				,xts_originalproductid = "xts_originalproductid Value"
				,ktb_isinterfacename = "ktb_isinterfacename Value"
				,overriddencreatedon = "overriddencreatedon Value"
				,xts_salesunitid = "xts_salesunitid Value"
				,xts_totalamount = "xts_totalamount Value"
				,statuscodename = "statuscodename Value"
				,xts_status = "xts_status Value"
				,xts_unitprice_base = "xts_unitprice_base Value"
				,ktb_isinterface = "ktb_isinterface Value"
				,xts_totalamount_base = "xts_totalamount_base Value"
				,modifiedbyyominame = "modifiedbyyominame Value"
				,bsi_maximumprice = "bsi_maximumprice Value"
				,transactioncurrencyidname = "transactioncurrencyidname Value"
				,xts_transactionamount_base = "xts_transactionamount_base Value"
				,xts_discountamount_base = "xts_discountamount_base Value"
				,owningbusinessunit = "owningbusinessunit Value"
				,xts_warehouseavailabilityid = "xts_warehouseavailabilityid Value"
				,xts_productcrossreferenceidname = "xts_productcrossreferenceidname Value"
				,xts_amountbeforediscount_base = "xts_amountbeforediscount_base Value"
				,xts_quantitydeliveredbaseunit = "xts_quantitydeliveredbaseunit Value"
				,xts_locationid = "xts_locationid Value"
				,statuscode = "statuscode Value"
				,xts_consumptiontax1amount = "xts_consumptiontax1amount Value"
				,xts_productdescription = "xts_productdescription Value"
				,xts_warehouseidname = "xts_warehouseidname Value"
				,xts_quantityorderbaseunit = "xts_quantityorderbaseunit Value"
				,xts_salesorderid = "xts_salesorderid Value"
				,xts_interiorcolorid = "xts_interiorcolorid Value"
				,xts_configurationidname = "xts_configurationidname Value"
				,xts_consumptiontax1idname = "xts_consumptiontax1idname Value"
				,versionnumber = "versionnumber Value"
				,xts_warehouseavailabilityidname = "xts_warehouseavailabilityidname Value"
				,statecodename = "statecodename Value"
				,xts_closereason = "xts_closereason Value"
				,exchangerate = "exchangerate Value"
				,modifiedon = "modifiedon Value"
				,xts_requestdate = "xts_requestdate Value"
				,xts_withholdingtax2id = "xts_withholdingtax2id Value"
				,xts_businessunitidname = "xts_businessunitidname Value"
				,xts_promisedate = "xts_promisedate Value"
				,createdon = "createdon Value"
				,xts_withholdingtaxidname = "xts_withholdingtaxidname Value"
				,ktb_cogs = "ktb_cogs Value"
				,ktb_baseamountimp = "ktb_baseamountimp Value"
				,ktb_sotype = "ktb_sotype Value"
				,xts_statusname = "xts_statusname Value"
				,xts_withholdingtax2amount_base = "xts_withholdingtax2amount_base Value"
				,xts_inventoryunitidname = "xts_inventoryunitidname Value"
				,bsi_category = "bsi_category Value"
				,xts_totalconsumptiontaxamount = "xts_totalconsumptiontaxamount Value"
				,ktb_latestpurchasepricedate = "ktb_latestpurchasepricedate Value"
				,xts_quantityorder = "xts_quantityorder Value"
				,xts_productid = "xts_productid Value"
				,owneridyominame = "owneridyominame Value"
				,xts_interiorcoloridname = "xts_interiorcoloridname Value"
				,xts_baseamount = "xts_baseamount Value"
				,modifiedby = "modifiedby Value"
				,xts_salesorderidname = "xts_salesorderidname Value"
				,modifiedonbehalfby = "modifiedonbehalfby Value"
				,xts_consumptiontax1amount_base = "xts_consumptiontax1amount_base Value"
				,xts_withholdingtaxid = "xts_withholdingtaxid Value"
				,xts_stockavail = "xts_stockavail Value"
				,ktb_sotypename = "ktb_sotypename Value"
				,owningteam = "owningteam Value"
				,xts_discountamount = "xts_discountamount Value"
				,createdonbehalfbyname = "createdonbehalfbyname Value"
				,owninguser = "owninguser Value"
				,owneridtype = "owneridtype Value"
				,xts_salesorderdetailnumber = "xts_salesorderdetailnumber Value"
				,xts_salesunitidname = "xts_salesunitidname Value"
				,bsi_maximumprice_base = "bsi_maximumprice_base Value"
				,owneridname = "owneridname Value"
				,modifiedonbehalfbyname = "modifiedonbehalfbyname Value"
				,createdonbehalfbyyominame = "createdonbehalfbyyominame Value"
				,xts_totalconsumptiontaxamount_base = "xts_totalconsumptiontaxamount_base Value"
				,xts_amountbeforediscount = "xts_amountbeforediscount Value"
				,xts_qtyrequest = "xts_qtyrequest Value"
				,xts_withholdingtax2amount = "xts_withholdingtax2amount Value"
				,timezoneruleversionnumber = "timezoneruleversionnumber Value"
				,xts_quantitydelivered = "xts_quantitydelivered Value"
				,xts_parentbusinessunitidname = "xts_parentbusinessunitidname Value"
				,xts_siteid = "xts_siteid Value"
				,xts_withholdingtax2idname = "xts_withholdingtax2idname Value"
				,createdonbehalfby = "createdonbehalfby Value"
				,xts_parentbusinessunitid = "xts_parentbusinessunitid Value"
				,transactioncurrencyid = "transactioncurrencyid Value"
				,xts_eventdata = "xts_eventdata Value"
				,xts_baseqtyrequest = "xts_baseqtyrequest Value"
				,xts_styleid = "xts_styleid Value"
				,xts_productidname = "xts_productidname Value"
				,xts_stockavailname = "xts_stockavailname Value"
				,xts_configurationid = "xts_configurationid Value"
				,xts_consumptiontax2amount = "xts_consumptiontax2amount Value"
				,xts_warehouseid = "xts_warehouseid Value"
				,xts_originalproductidname = "xts_originalproductidname Value"
				,xts_discountbaseamount_base = "xts_discountbaseamount_base Value"
				,ownerid = "ownerid Value"
				,xts_exteriorcoloridname = "xts_exteriorcoloridname Value"
				,xts_salesorderdetailid = "xts_salesorderdetailid Value"
				,bsi_iseditname = "bsi_iseditname Value"
				,createdbyname = "createdbyname Value"
				,xts_quantityreturned = "xts_quantityreturned Value"
				,statecode = "statecode Value"
				,xts_siteidname = "xts_siteidname Value"
				,xts_locationidname = "xts_locationidname Value"
				,modifiedonbehalfbyyominame = "modifiedonbehalfbyyominame Value"
				,createdby = "createdby Value"
				,bsi_isedit = "bsi_isedit Value"
				,bsi_categoryname = "bsi_categoryname Value"
				,ktb_markuppercentage = "ktb_markuppercentage Value"
				,xts_inventoryunitid = "xts_inventoryunitid Value"
				,xts_unitprice = "xts_unitprice Value"
				,xts_discountbaseamount = "xts_discountbaseamount Value"
				,utcconversiontimezonecode = "utcconversiontimezonecode Value"
				,xts_completedname = "xts_completedname Value"
				,bsi_originalprice = "bsi_originalprice Value"
				,xts_completed = "xts_completed Value"
				,bsi_originalprice_base = "bsi_originalprice_base Value"
				,importsequencenumber = "importsequencenumber Value"
				,xts_locking = "xts_locking Value"
				,xts_styleidname = "xts_styleidname Value"
				,xts_consumptiontax2idname = "xts_consumptiontax2idname Value"
				,xts_productcrossreferenceid = "xts_productcrossreferenceid Value"
				,xts_consumptiontax2amount_base = "xts_consumptiontax2amount_base Value"
				,ktb_modelcode = "ktb_modelcode Value"
				,ktb_baseamountimp_base = "ktb_baseamountimp_base Value"
				,xts_businessunitid = "xts_businessunitid Value"
				,ktb_cogs_base = "ktb_cogs_base Value"
				,xts_closeline = "xts_closeline Value"
				,modifiedbyname = "modifiedbyname Value"
				,createdbyyominame = "createdbyyominame Value"
				,xts_closelinename = "xts_closelinename Value"
				,xts_transactionamount = "xts_transactionamount Value"
				,xts_baseamount_base = "xts_baseamount_base Value"
				,xts_withholdingtaxamount_base = "xts_withholdingtaxamount_base Value"
				,xts_withholdingtaxamount = "xts_withholdingtaxamount Value"
				,xts_runningnumber = "xts_runningnumber Value"
				,msdyn_companycode = "msdyn_companycode Value"
            };

            return obj;
        }
    }
}