#region Summary
// ===========================================================================
// AUTHOR        : BSI Code Generator 
// SPECIAL NOTES : DNet WebApi Project
// ---------------------
// Copyright  (c) 2019 
// ---------------------
// $History      : $
// Created on 24/02/2020 18:15:44]
//
// ===========================================================================	
#endregion

using Swashbuckle.Examples;

namespace KTB.DNet.Interface.WebApi.Models.Examples
{
    public class APIUpdateVWI_CRM_xts_inventorynewvehicleExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var obj = new
            {
                UpdatedBy = "DealerUser"
				,company = "company Value"
				,businessunitcode = "businessunitcode Value"
				,xts_lastvehicleorderidname = "xts_lastvehicleorderidname Value"
				,xts_lastvehicleorderid = "xts_lastvehicleorderid Value"
				,xjp_nitrogenoxidesunit = "xjp_nitrogenoxidesunit Value"
				,xts_vehicleexteriorcoloridname = "xts_vehicleexteriorcoloridname Value"
				,xts_installedaccessories = "xts_installedaccessories Value"
				,xjp_lightvehiclecategoryname = "xjp_lightvehiclecategoryname Value"
				,modifiedon = "modifiedon Value"
				,xjp_completeinspectionissuedate1 = "xjp_completeinspectionissuedate1 Value"
				,overriddencreatedon = "overriddencreatedon Value"
				,xts_receivingdate = "xts_receivingdate Value"
				,xjp_stocknumberreferenceid = "xjp_stocknumberreferenceid Value"
				,statuscodename = "statuscodename Value"
				,xts_width = "xts_width Value"
				,xts_receivingprocess = "xts_receivingprocess Value"
				,transactioncurrencyid = "transactioncurrencyid Value"
				,modifiedbyyominame = "modifiedbyyominame Value"
				,xjp_lastrecyclingissuecategoryname = "xjp_lastrecyclingissuecategoryname Value"
				,xjp_bodyshapeid = "xjp_bodyshapeid Value"
				,xjp_shipmentdestination = "xjp_shipmentdestination Value"
				,xjp_scheduledarrivaldate = "xjp_scheduledarrivaldate Value"
				,xts_purchasediscount = "xts_purchasediscount Value"
				,xts_vehicleinteriorcolorid = "xts_vehicleinteriorcolorid Value"
				,xts_mainfueltypeidname = "xts_mainfueltypeidname Value"
				,transactioncurrencyidname = "transactioncurrencyidname Value"
				,xjp_recyclingticketnumber = "xjp_recyclingticketnumber Value"
				,xts_chassismodel = "xts_chassismodel Value"
				,xts_departmentidname = "xts_departmentidname Value"
				,ktb_iskaroseriname = "ktb_iskaroseriname Value"
				,xjp_nitrogenoxides = "xjp_nitrogenoxides Value"
				,xts_totallandedcost = "xts_totallandedcost Value"
				,ktb_beginingbalance = "ktb_beginingbalance Value"
				,xts_totalvalue = "xts_totalvalue Value"
				,ktb_caroseriesamount_base = "ktb_caroseriesamount_base Value"
				,owningbusinessunit = "owningbusinessunit Value"
				,modifiedbyname = "modifiedbyname Value"
				,xjp_lastrecyclingdepositdate = "xjp_lastrecyclingdepositdate Value"
				,xts_inventorynewvehicleid = "xts_inventorynewvehicleid Value"
				,xts_locationid = "xts_locationid Value"
				,xts_keynumber = "xts_keynumber Value"
				,statuscode = "statuscode Value"
				,xts_productdescription = "xts_productdescription Value"
				,xts_warehouseidname = "xts_warehouseidname Value"
				,xjp_completeinspectionexpirydate2 = "xjp_completeinspectionexpirydate2 Value"
				,ktb_vehiclecategoryidname = "ktb_vehiclecategoryidname Value"
				,xjp_particulatematerialunit = "xjp_particulatematerialunit Value"
				,xjp_suitabilityforabusiness = "xjp_suitabilityforabusiness Value"
				,xts_remarks = "xts_remarks Value"
				,xts_configurationidname = "xts_configurationidname Value"
				,xts_totallandedcost_base = "xts_totallandedcost_base Value"
				,xjp_vehicleconsumptiontaxamount_base = "xjp_vehicleconsumptiontaxamount_base Value"
				,xts_vehicleexteriorcolorid = "xts_vehicleexteriorcolorid Value"
				,xts_frontfrontaxleweight = "xts_frontfrontaxleweight Value"
				,xts_styleid = "xts_styleid Value"
				,statecodename = "statecodename Value"
				,xts_enginevolume = "xts_enginevolume Value"
				,xts_secondfueltypeidname = "xts_secondfueltypeidname Value"
				,xjp_registrationdatejapan = "xjp_registrationdatejapan Value"
				,xts_installedaccessories_base = "xts_installedaccessories_base Value"
				,ktb_beginingbalancename = "ktb_beginingbalancename Value"
				,xts_vehicleidentificationid = "xts_vehicleidentificationid Value"
				,xts_purchasediscount_base = "xts_purchasediscount_base Value"
				,xts_reasoncodeid = "xts_reasoncodeid Value"
				,createdon = "createdon Value"
				,xts_classificationnumber = "xts_classificationnumber Value"
				,xjp_confirmedarrivalscheduledate = "xjp_confirmedarrivalscheduledate Value"
				,xjp_lastrecyclingissuecategory = "xjp_lastrecyclingissuecategory Value"
				,xjp_grossweight2 = "xjp_grossweight2 Value"
				,ktb_vehiclecategoryid = "ktb_vehiclecategoryid Value"
				,xjp_completeinspectioncertificatenumber2 = "xjp_completeinspectioncertificatenumber2 Value"
				,ktb_purchaseorderdate = "ktb_purchaseorderdate Value"
				,ktb_dealeralokasiidname = "ktb_dealeralokasiidname Value"
				,createdonbehalfby = "createdonbehalfby Value"
				,ktb_caroseriesamount = "ktb_caroseriesamount Value"
				,xjp_registrationmodel = "xjp_registrationmodel Value"
				,xts_vehiclespecificationidname = "xts_vehiclespecificationidname Value"
				,xts_vehicleidentificationidname = "xts_vehicleidentificationidname Value"
				,xts_serialid = "xts_serialid Value"
				,xts_productid = "xts_productid Value"
				,owneridyominame = "owneridyominame Value"
				,modifiedby = "modifiedby Value"
				,timezoneruleversionnumber = "timezoneruleversionnumber Value"
				,xjp_maximumload1 = "xjp_maximumload1 Value"
				,ktb_vehiclecolorname = "ktb_vehiclecolorname Value"
				,xjp_variousconsumptiontaxamount = "xjp_variousconsumptiontaxamount Value"
				,xts_mainfueltypeid = "xts_mainfueltypeid Value"
				,modifiedonbehalfby = "modifiedonbehalfby Value"
				,xts_madeinid = "xts_madeinid Value"
				,xjp_suitabilityforbusiness = "xjp_suitabilityforbusiness Value"
				,xjp_purchasecategoryname = "xjp_purchasecategoryname Value"
				,ktb_vehicledescription = "ktb_vehicledescription Value"
				,owningteam = "owningteam Value"
				,xts_totalvalue_base = "xts_totalvalue_base Value"
				,xts_scheduledshipmentdate = "xts_scheduledshipmentdate Value"
				,xts_serviceandcostinspection_base = "xts_serviceandcostinspection_base Value"
				,xts_rearrearaxleweight = "xts_rearrearaxleweight Value"
				,ktb_accessoriesid = "ktb_accessoriesid Value"
				,xjp_actualreceivedate = "xjp_actualreceivedate Value"
				,owninguser = "owninguser Value"
				,xts_departmentid = "xts_departmentid Value"
				,xjp_bodyworkclassificationcategoryname = "xjp_bodyworkclassificationcategoryname Value"
				,xjp_purchaseconsumptiontaxid = "xjp_purchaseconsumptiontaxid Value"
				,xts_height = "xts_height Value"
				,xjp_stockaddress = "xjp_stockaddress Value"
				,xts_visibility = "xts_visibility Value"
				,owneridtype = "owneridtype Value"
				,xts_enginenumber = "xts_enginenumber Value"
				,xjp_preliminaryinspectiondate = "xjp_preliminaryinspectiondate Value"
				,ktb_dealeralokasiid = "ktb_dealeralokasiid Value"
				,xjp_pocancellationdatelimit = "xjp_pocancellationdatelimit Value"
				,xts_chassisnumber = "xts_chassisnumber Value"
				,xts_productionyear = "xts_productionyear Value"
				,xjp_lastinitialassessmentid = "xjp_lastinitialassessmentid Value"
				,owneridname = "owneridname Value"
				,ktb_iskaroseri = "ktb_iskaroseri Value"
				,modifiedonbehalfbyname = "modifiedonbehalfbyname Value"
				,createdonbehalfbyyominame = "createdonbehalfbyyominame Value"
				,xjp_enginemodel = "xjp_enginemodel Value"
				,ktb_vehiclemodelid = "ktb_vehiclemodelid Value"
				,xts_generation = "xts_generation Value"
				,xjp_lastinitialassessmentidname = "xjp_lastinitialassessmentidname Value"
				,xts_stocknumber = "xts_stocknumber Value"
				,xjp_emissionpreventiondevice = "xjp_emissionpreventiondevice Value"
				,xts_purchaseprice_base = "xts_purchaseprice_base Value"
				,ktb_vendoridname = "ktb_vendoridname Value"
				,xts_siteid = "xts_siteid Value"
				,exchangerate = "exchangerate Value"
				,xts_vehiclespecificationid = "xts_vehiclespecificationid Value"
				,xts_productfamily = "xts_productfamily Value"
				,xjp_capacity2 = "xjp_capacity2 Value"
				,xjp_capacity1 = "xjp_capacity1 Value"
				,xjp_completeinspectionissuedate2 = "xjp_completeinspectionissuedate2 Value"
				,xts_weight = "xts_weight Value"
				,xjp_idempotentmessage = "xjp_idempotentmessage Value"
				,xts_length = "xts_length Value"
				,xts_frontrearaxleweight = "xts_frontrearaxleweight Value"
				,xts_productidname = "xts_productidname Value"
				,xjp_maximumload2 = "xjp_maximumload2 Value"
				,xts_configurationid = "xts_configurationid Value"
				,xts_dmsreferencenumber = "xts_dmsreferencenumber Value"
				,xts_warehouseid = "xts_warehouseid Value"
				,ktb_accessoriesidname = "ktb_accessoriesidname Value"
				,ownerid = "ownerid Value"
				,xts_serviceandcostinspection = "xts_serviceandcostinspection Value"
				,xjp_cartype = "xjp_cartype Value"
				,ktb_vendorid = "ktb_vendorid Value"
				,createdonbehalfbyname = "createdonbehalfbyname Value"
				,xts_frombusinessunitid = "xts_frombusinessunitid Value"
				,xjp_particulatematerial = "xjp_particulatematerial Value"
				,xts_ribbondata = "xts_ribbondata Value"
				,xts_rearfrontaxleweight = "xts_rearfrontaxleweight Value"
				,xts_tobusinessunitid = "xts_tobusinessunitid Value"
				,createdbyname = "createdbyname Value"
				,xjp_purchasecategory = "xjp_purchasecategory Value"
				,xts_businessunitidname = "xts_businessunitidname Value"
				,statecode = "statecode Value"
				,xts_siteidname = "xts_siteidname Value"
				,xts_locationidname = "xts_locationidname Value"
				,modifiedonbehalfbyyominame = "modifiedonbehalfbyyominame Value"
				,createdby = "createdby Value"
				,xts_serialidname = "xts_serialidname Value"
				,xjp_numberofsideairbag = "xjp_numberofsideairbag Value"
				,xjp_bodyworkclassificationcategory = "xjp_bodyworkclassificationcategory Value"
				,xjp_enginetype = "xjp_enginetype Value"
				,xjp_suitabilityforabusinessname = "xjp_suitabilityforabusinessname Value"
				,xjp_preliminaryinspectionexpense_base = "xjp_preliminaryinspectionexpense_base Value"
				,xts_referencenumber = "xts_referencenumber Value"
				,xjp_bodyshapeidname = "xjp_bodyshapeidname Value"
				,xts_vehicleinteriorcoloridname = "xts_vehicleinteriorcoloridname Value"
				,xjp_newvehiclesalesorderidname = "xjp_newvehiclesalesorderidname Value"
				,xjp_enginetypename = "xjp_enginetypename Value"
				,utcconversiontimezonecode = "utcconversiontimezonecode Value"
				,xjp_preliminaryinspectionexpense = "xjp_preliminaryinspectionexpense Value"
				,xts_secondfueltypeid = "xts_secondfueltypeid Value"
				,xts_receivingprocessname = "xts_receivingprocessname Value"
				,xjp_newvehiclesalesorderid = "xjp_newvehiclesalesorderid Value"
				,ktb_applicationno = "ktb_applicationno Value"
				,xts_visibilityname = "xts_visibilityname Value"
				,xts_frombusinessunitidname = "xts_frombusinessunitidname Value"
				,importsequencenumber = "importsequencenumber Value"
				,xts_locking = "xts_locking Value"
				,xts_styleidname = "xts_styleidname Value"
				,xjp_purchaseconsumptiontaxidname = "xjp_purchaseconsumptiontaxidname Value"
				,xjp_shipmentdate = "xjp_shipmentdate Value"
				,xjp_totalconsumptiontaxamount_base = "xjp_totalconsumptiontaxamount_base Value"
				,xjp_shipmentplace = "xjp_shipmentplace Value"
				,xjp_vehicleconsumptiontaxamount = "xjp_vehicleconsumptiontaxamount Value"
				,versionnumber = "versionnumber Value"
				,ktb_vehiclemodelidname = "ktb_vehiclemodelidname Value"
				,xts_businessunitid = "xts_businessunitid Value"
				,xts_modelspecificationnumber = "xts_modelspecificationnumber Value"
				,xjp_variousconsumptiontaxamount_base = "xjp_variousconsumptiontaxamount_base Value"
				,xts_issueddate = "xts_issueddate Value"
				,xjp_totalconsumptiontaxamount = "xjp_totalconsumptiontaxamount Value"
				,xjp_grossweight1 = "xjp_grossweight1 Value"
				,xjp_completeinspectionexpirydate = "xjp_completeinspectionexpirydate Value"
				,xjp_completeinspectioncertificatenumber1 = "xjp_completeinspectioncertificatenumber1 Value"
				,xts_tobusinessunitidname = "xts_tobusinessunitidname Value"
				,xjp_completeinspectiondate = "xjp_completeinspectiondate Value"
				,xts_madeinidname = "xts_madeinidname Value"
				,createdbyyominame = "createdbyyominame Value"
				,xjp_usageid = "xjp_usageid Value"
				,xjp_lightvehiclecategory = "xjp_lightvehiclecategory Value"
				,xjp_suitabilityforbusinessname = "xjp_suitabilityforbusinessname Value"
				,xts_purchaseprice = "xts_purchaseprice Value"
				,xjp_stocknumberreferenceidname = "xjp_stocknumberreferenceidname Value"
				,xjp_usageidname = "xjp_usageidname Value"
				,xjp_productionplant = "xjp_productionplant Value"
				,xts_reasoncodeidname = "xts_reasoncodeidname Value"
				,ktb_description = "ktb_description Value"
				,ktb_atd = "ktb_atd Value"
				,ktb_etd = "ktb_etd Value"
				,ktb_eta = "ktb_eta Value"
				,ktb_statusinterfacednetname = "ktb_statusinterfacednetname Value"
				,ktb_statusinterfacednet = "ktb_statusinterfacednet Value"
				,ktb_chassisexternalname = "ktb_chassisexternalname Value"
				,ktb_interfaceexceptionmessage = "ktb_interfaceexceptionmessage Value"
				,ktb_chassisexternal = "ktb_chassisexternal Value"
				,ktb_fakturdate = "ktb_fakturdate Value"
				,ktb_revisionstatusname = "ktb_revisionstatusname Value"
				,ktb_validationdate = "ktb_validationdate Value"
				,ktb_printeddate = "ktb_printeddate Value"
				,ktb_revisionstatus = "ktb_revisionstatus Value"
				,ktb_fakturnumber = "ktb_fakturnumber Value"
				,ktb_confirmdate = "ktb_confirmdate Value"
				,ktb_fakturstatusname = "ktb_fakturstatusname Value"
				,ktb_fakturstatus = "ktb_fakturstatus Value"
				,ktb_kondisikendaraan = "ktb_kondisikendaraan Value"
				,msdyn_companycode = "msdyn_companycode Value"
            };

            return obj;
        }
    }
}