#region Summary
// ===========================================================================
// AUTHOR        : BSI Code Generator 
// SPECIAL NOTES : DNet WebApi Project
// ---------------------
// Copyright  (c) 2019 
// ---------------------
// $History      : $
// Created on 24/02/2020 18:15:44]
//
// ===========================================================================	
#endregion

using Swashbuckle.Examples;

namespace KTB.DNet.Interface.WebApi.Models.Examples
{
    public class APIUpdateVWI_CRM_xts_salesorderExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var obj = new
            {
                UpdatedBy = "DealerUser"
				,company = "company Value"
				,businessunitcode = "businessunitcode Value"
				,xts_parentbusinessunitid = "xts_parentbusinessunitid Value"
				,versionnumber = "versionnumber Value"
				,createdon = "createdon Value"
				,xts_methodofpaymentidname = "xts_methodofpaymentidname Value"
				,xts_salesordernumber = "xts_salesordernumber Value"
				,xjp_idempotentmessage = "xjp_idempotentmessage Value"
				,xts_referencenumberlookuptype = "xts_referencenumberlookuptype Value"
				,xts_eventdata = "xts_eventdata Value"
				,statuscodename = "statuscodename Value"
				,xts_status = "xts_status Value"
				,xts_customerid = "xts_customerid Value"
				,xts_description = "xts_description Value"
				,modifiedbyyominame = "modifiedbyyominame Value"
				,owneridtype = "owneridtype Value"
				,ktb_saleschannel = "ktb_saleschannel Value"
				,xts_totalbaseamount_base = "xts_totalbaseamount_base Value"
				,xts_checkstockagainst = "xts_checkstockagainst Value"
				,createdonbehalfby = "createdonbehalfby Value"
				,xts_referencenumberusedvehiclesalesorderid = "xts_referencenumberusedvehiclesalesorderid Value"
				,modifiedbyname = "modifiedbyname Value"
				,xts_salesorderid = "xts_salesorderid Value"
				,xts_newvehiclesalesorderid = "xts_newvehiclesalesorderid Value"
				,xts_behaviorname = "xts_behaviorname Value"
				,xts_totalbaseamount = "xts_totalbaseamount Value"
				,xts_overcreditlimitonhold = "xts_overcreditlimitonhold Value"
				,xts_billtocustomeridname = "xts_billtocustomeridname Value"
				,owneridname = "owneridname Value"
				,xts_downpaymentispaidname = "xts_downpaymentispaidname Value"
				,overriddencreatedon = "overriddencreatedon Value"
				,xts_billtocustomerid = "xts_billtocustomerid Value"
				,xts_ordertypeid = "xts_ordertypeid Value"
				,ktb_purchaseorderid = "ktb_purchaseorderid Value"
				,xts_downpaymentamount = "xts_downpaymentamount Value"
				,createdonbehalfbyyominame = "createdonbehalfbyyominame Value"
				,modifiedonbehalfby = "modifiedonbehalfby Value"
				,exchangerate = "exchangerate Value"
				,xts_totalconsumptiontaxamount_base = "xts_totalconsumptiontaxamount_base Value"
				,ktb_saleschannelid = "ktb_saleschannelid Value"
				,xts_downpaymentamount_base = "xts_downpaymentamount_base Value"
				,ktb_ribbondata = "ktb_ribbondata Value"
				,owningteam = "owningteam Value"
				,xts_referencenumberusedvehiclesalesorderidname = "xts_referencenumberusedvehiclesalesorderidname Value"
				,xts_balance = "xts_balance Value"
				,xts_billtocustomeridyominame = "xts_billtocustomeridyominame Value"
				,xts_checkstockagainstname = "xts_checkstockagainstname Value"
				,xts_totalreceipt = "xts_totalreceipt Value"
				,xts_exchangeratedate = "xts_exchangeratedate Value"
				,xts_totaldiscountamount_base = "xts_totaldiscountamount_base Value"
				,statecode = "statecode Value"
				,xts_salespersonid = "xts_salespersonid Value"
				,timezoneruleversionnumber = "timezoneruleversionnumber Value"
				,xts_termofpaymentid = "xts_termofpaymentid Value"
				,xts_totalwithholdingtaxamount_base = "xts_totalwithholdingtaxamount_base Value"
				,ktb_purchaserequisitionid = "ktb_purchaserequisitionid Value"
				,ktb_purchaserequisitionidname = "ktb_purchaserequisitionidname Value"
				,xts_exchangerateamount = "xts_exchangerateamount Value"
				,ktb_latestpurchasepricedate = "ktb_latestpurchasepricedate Value"
				,xts_totalconsumptiontaxamount = "xts_totalconsumptiontaxamount Value"
				,xts_referencenumberlookupname = "xts_referencenumberlookupname Value"
				,xts_locking = "xts_locking Value"
				,xts_handling = "xts_handling Value"
				,xts_termofpaymentidname = "xts_termofpaymentidname Value"
				,xts_totalamountbeforediscount = "xts_totalamountbeforediscount Value"
				,xts_customernumber = "xts_customernumber Value"
				,xts_referencenumbernewvehiclesalesorderid = "xts_referencenumbernewvehiclesalesorderid Value"
				,xts_totalreceipt_base = "xts_totalreceipt_base Value"
				,createdonbehalfbyname = "createdonbehalfbyname Value"
				,xts_exchangeratetypeidname = "xts_exchangeratetypeidname Value"
				,xts_newvehiclesalesorderidname = "xts_newvehiclesalesorderidname Value"
				,ktb_saleschannelidname = "ktb_saleschannelidname Value"
				,xts_totaldiscountamount = "xts_totaldiscountamount Value"
				,utcconversiontimezonecode = "utcconversiontimezonecode Value"
				,xts_businessunitid = "xts_businessunitid Value"
				,xts_referencenumberworkorderid = "xts_referencenumberworkorderid Value"
				,xts_statusname = "xts_statusname Value"
				,xts_customeridyominame = "xts_customeridyominame Value"
				,ownerid = "ownerid Value"
				,modifiedon = "modifiedon Value"
				,importsequencenumber = "importsequencenumber Value"
				,owneridyominame = "owneridyominame Value"
				,ktb_modelcode = "ktb_modelcode Value"
				,ktb_campaignid = "ktb_campaignid Value"
				,xts_shipmenttypename = "xts_shipmenttypename Value"
				,xts_transactiondate = "xts_transactiondate Value"
				,xts_downpaymentispaid = "xts_downpaymentispaid Value"
				,xts_referencenumbernewvehiclesalesorderidname = "xts_referencenumbernewvehiclesalesorderidname Value"
				,xts_ordertypeidname = "xts_ordertypeidname Value"
				,createdbyname = "createdbyname Value"
				,xts_totalwithholdingtaxamount = "xts_totalwithholdingtaxamount Value"
				,xts_methodofpaymentid = "xts_methodofpaymentid Value"
				,xts_exchangerateamount_base = "xts_exchangerateamount_base Value"
				,xts_exchangeratetypeid = "xts_exchangeratetypeid Value"
				,ktb_campaignidname = "ktb_campaignidname Value"
				,xts_overcreditlimitonholdname = "xts_overcreditlimitonholdname Value"
				,xts_balance_base = "xts_balance_base Value"
				,xts_bigdata = "xts_bigdata Value"
				,xts_handlingname = "xts_handlingname Value"
				,xts_grandtotal = "xts_grandtotal Value"
				,xts_grandtotal_base = "xts_grandtotal_base Value"
				,xts_salespersonidname = "xts_salespersonidname Value"
				,transactioncurrencyid = "transactioncurrencyid Value"
				,ktb_customerdescription = "ktb_customerdescription Value"
				,xts_cancellationdate = "xts_cancellationdate Value"
				,createdby = "createdby Value"
				,modifiedby = "modifiedby Value"
				,ktb_overdueonholdname = "ktb_overdueonholdname Value"
				,xts_shipmenttype = "xts_shipmenttype Value"
				,createdbyyominame = "createdbyyominame Value"
				,owninguser = "owninguser Value"
				,transactioncurrencyidname = "transactioncurrencyidname Value"
				,xts_customeridname = "xts_customeridname Value"
				,owningbusinessunit = "owningbusinessunit Value"
				,xts_downpaymentamountreceived = "xts_downpaymentamountreceived Value"
				,xts_parentbusinessunitidname = "xts_parentbusinessunitidname Value"
				,modifiedonbehalfbyname = "modifiedonbehalfbyname Value"
				,xts_bigdataname = "xts_bigdataname Value"
				,ktb_purchaseorderidname = "ktb_purchaseorderidname Value"
				,xts_externalreferencenumber = "xts_externalreferencenumber Value"
				,statuscode = "statuscode Value"
				,modifiedonbehalfbyyominame = "modifiedonbehalfbyyominame Value"
				,xts_behavior = "xts_behavior Value"
				,ktb_say = "ktb_say Value"
				,xts_totalamountbeforediscount_base = "xts_totalamountbeforediscount_base Value"
				,ktb_overdueonhold = "ktb_overdueonhold Value"
				,xts_downpaymentamountreceived_base = "xts_downpaymentamountreceived_base Value"
				,xts_referencenumberworkorderidname = "xts_referencenumberworkorderidname Value"
				,statecodename = "statecodename Value"
				,xts_businessunitidname = "xts_businessunitidname Value"
				,ktb_saleschannelname = "ktb_saleschannelname Value"
				,xts_totalmiscchargetaxamount_base = "xts_totalmiscchargetaxamount_base Value"
				,xts_totalmiscchargebaseamount_base = "xts_totalmiscchargebaseamount_base Value"
				,xts_totalmiscchargeamount_base = "xts_totalmiscchargeamount_base Value"
				,xts_totalmiscchargetaxamount = "xts_totalmiscchargetaxamount Value"
				,xts_totalmiscchargeamount = "xts_totalmiscchargeamount Value"
				,xts_totalmiscchargebaseamount = "xts_totalmiscchargebaseamount Value"
				,msdyn_companycode = "msdyn_companycode Value"
            };

            return obj;
        }
    }
}