#region Summary
// ===========================================================================
// AUTHOR        : BSI Code Generator 
// SPECIAL NOTES : DNet WebApi Project
// ---------------------
// Copyright  (c) 2019 
// ---------------------
// $History      : $
// Created on 24/02/2020 18:15:44]
//
// ===========================================================================	
#endregion

using Swashbuckle.Examples;

namespace KTB.DNet.Interface.WebApi.Models.Examples
{
    public class APIUpdateVWI_CRM_xts_incomingoutsourceworkorderExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var obj = new
            {
                UpdatedBy = "DealerUser"
				,company = "company Value"
				,businessunitcode = "businessunitcode Value"
				,xjp_requeststampfeeadvancedpaymentname = "xjp_requeststampfeeadvancedpaymentname Value"
				,xts_totaltaxamount_base = "xts_totaltaxamount_base Value"
				,xts_outsourceworkorderreferencedate = "xts_outsourceworkorderreferencedate Value"
				,versionnumber = "versionnumber Value"
				,xts_outsrcworefnumberlookupname = "xts_outsrcworefnumberlookupname Value"
				,createdon = "createdon Value"
				,xts_totalbillingamountaftertax = "xts_totalbillingamountaftertax Value"
				,statuscodename = "statuscodename Value"
				,xts_scheduledarrivaldateandtime = "xts_scheduledarrivaldateandtime Value"
				,xts_totaltaxamount = "xts_totaltaxamount Value"
				,xjp_requestcaliadvancedpayment = "xjp_requestcaliadvancedpayment Value"
				,xts_outsrcworefnumberserviceinstructionid = "xts_outsrcworefnumberserviceinstructionid Value"
				,xts_finishpatternname = "xts_finishpatternname Value"
				,xts_status = "xts_status Value"
				,xts_customerid = "xts_customerid Value"
				,xts_manufacturerdescription = "xts_manufacturerdescription Value"
				,xts_incomingoutsourceworkorderid = "xts_incomingoutsourceworkorderid Value"
				,xts_scheduledfinishdateandtime = "xts_scheduledfinishdateandtime Value"
				,owneridtype = "owneridtype Value"
				,xts_schledoutsourceservicefinishdateandtime = "xts_schledoutsourceservicefinishdateandtime Value"
				,xts_incomingoutsourceworkordermemo = "xts_incomingoutsourceworkordermemo Value"
				,createdonbehalfby = "createdonbehalfby Value"
				,xjp_requestcaliadvancedpaymentname = "xjp_requestcaliadvancedpaymentname Value"
				,xts_chassisnumber = "xts_chassisnumber Value"
				,xts_platenumber = "xts_platenumber Value"
				,xts_outsrcworkorderreferencepersoninchargeid = "xts_outsrcworkorderreferencepersoninchargeid Value"
				,xts_vehiclemodelname = "xts_vehiclemodelname Value"
				,owneridname = "owneridname Value"
				,xts_totalbillingamountbeforetax_base = "xts_totalbillingamountbeforetax_base Value"
				,xts_totalbillingamountbeforetax = "xts_totalbillingamountbeforetax Value"
				,overriddencreatedon = "overriddencreatedon Value"
				,xts_deliverymemo = "xts_deliverymemo Value"
				,xts_originalbusinessunitidname = "xts_originalbusinessunitidname Value"
				,xts_originalworkorderreferenceidname = "xts_originalworkorderreferenceidname Value"
				,createdonbehalfbyyominame = "createdonbehalfbyyominame Value"
				,transactioncurrencyidname = "transactioncurrencyidname Value"
				,modifiedonbehalfby = "modifiedonbehalfby Value"
				,xts_outsrcworefnumberlookuptype = "xts_outsrcworefnumberlookuptype Value"
				,xts_manufactureridname = "xts_manufactureridname Value"
				,xts_customeridyominame = "xts_customeridyominame Value"
				,xjp_requeststampfeeadvancedpayment = "xjp_requeststampfeeadvancedpayment Value"
				,owningteam = "owningteam Value"
				,xts_arrivalmemo = "xts_arrivalmemo Value"
				,xjp_weighttax = "xjp_weighttax Value"
				,xts_arrivalpatternname = "xts_arrivalpatternname Value"
				,statecode = "statecode Value"
				,timezoneruleversionnumber = "timezoneruleversionnumber Value"
				,xjp_requestweighttaxadvancedpaymentname = "xjp_requestweighttaxadvancedpaymentname Value"
				,exchangerate = "exchangerate Value"
				,modifiedbyname = "modifiedbyname Value"
				,xjp_outsourceworefnbrpdiidname = "xjp_outsourceworefnbrpdiidname Value"
				,xts_parentbusinessunitid = "xts_parentbusinessunitid Value"
				,xjp_taxpaymentdocumentname = "xjp_taxpaymentdocumentname Value"
				,xts_locking = "xts_locking Value"
				,xts_handling = "xts_handling Value"
				,xts_customernumber = "xts_customernumber Value"
				,xjp_opticalcharacterreadername = "xjp_opticalcharacterreadername Value"
				,xjp_requestweighttaxadvancedpayment = "xjp_requestweighttaxadvancedpayment Value"
				,xts_modelspecificationnumber = "xts_modelspecificationnumber Value"
				,xjp_taxpaymentdocument = "xjp_taxpaymentdocument Value"
				,traversedpath = "traversedpath Value"
				,createdonbehalfbyname = "createdonbehalfbyname Value"
				,xts_chassismodel = "xts_chassismodel Value"
				,xjp_outsourceworefnbrpdiid = "xjp_outsourceworefnbrpdiid Value"
				,xjp_opticalcharacterreader = "xjp_opticalcharacterreader Value"
				,xts_incomingreservationreferenceidname = "xts_incomingreservationreferenceidname Value"
				,xts_classificationnumber = "xts_classificationnumber Value"
				,utcconversiontimezonecode = "utcconversiontimezonecode Value"
				,xts_vehicleidentificationid = "xts_vehicleidentificationid Value"
				,xts_outsrcworkorderreferencepersoninchargeidname = "xts_outsrcworkorderreferencepersoninchargeidname Value"
				,xts_statusname = "xts_statusname Value"
				,ownerid = "ownerid Value"
				,modifiedon = "modifiedon Value"
				,importsequencenumber = "importsequencenumber Value"
				,owneridyominame = "owneridyominame Value"
				,xjp_weighttaxname = "xjp_weighttaxname Value"
				,xjp_compulsoryautomobileliabilityinsurancename = "xjp_compulsoryautomobileliabilityinsurancename Value"
				,xts_originalworkorderreferenceid = "xts_originalworkorderreferenceid Value"
				,xts_category = "xts_category Value"
				,xts_servicecategoryid = "xts_servicecategoryid Value"
				,xts_transactiondate = "xts_transactiondate Value"
				,xts_outsrcworefnumberserviceinstructionidname = "xts_outsrcworefnumberserviceinstructionidname Value"
				,processid = "processid Value"
				,createdbyname = "createdbyname Value"
				,xts_businessunitid = "xts_businessunitid Value"
				,modifiedonbehalfbyname = "modifiedonbehalfbyname Value"
				,xts_schledarrivalinoriginworkshopdateandtime = "xts_schledarrivalinoriginworkshopdateandtime Value"
				,xts_originalbusinessunitid = "xts_originalbusinessunitid Value"
				,xts_vehicleidentificationidname = "xts_vehicleidentificationidname Value"
				,stageid = "stageid Value"
				,xts_categoryname = "xts_categoryname Value"
				,xts_handlingname = "xts_handlingname Value"
				,transactioncurrencyid = "transactioncurrencyid Value"
				,xjp_compulsoryautomobileliabilityinsurance = "xjp_compulsoryautomobileliabilityinsurance Value"
				,xts_businessunitidname = "xts_businessunitidname Value"
				,createdby = "createdby Value"
				,modifiedby = "modifiedby Value"
				,xts_outsrcworefnumberoutsourceworkorderid = "xts_outsrcworefnumberoutsourceworkorderid Value"
				,createdbyyominame = "createdbyyominame Value"
				,owninguser = "owninguser Value"
				,xts_incomingoutsourceworkorder = "xts_incomingoutsourceworkorder Value"
				,xts_customeridname = "xts_customeridname Value"
				,owningbusinessunit = "owningbusinessunit Value"
				,modifiedbyyominame = "modifiedbyyominame Value"
				,xts_parentbusinessunitidname = "xts_parentbusinessunitidname Value"
				,xts_manufacturerid = "xts_manufacturerid Value"
				,xts_finishpattern = "xts_finishpattern Value"
				,statuscode = "statuscode Value"
				,modifiedonbehalfbyyominame = "modifiedonbehalfbyyominame Value"
				,xts_scheduledoutsourcearrivaldateandtime = "xts_scheduledoutsourcearrivaldateandtime Value"
				,xts_arrivalpattern = "xts_arrivalpattern Value"
				,xts_incomingreservationreferenceid = "xts_incomingreservationreferenceid Value"
				,xts_scheduledoutsourcefinishdateandtime = "xts_scheduledoutsourcefinishdateandtime Value"
				,xts_servicecategoryidname = "xts_servicecategoryidname Value"
				,statecodename = "statecodename Value"
				,xts_totalbillingamountaftertax_base = "xts_totalbillingamountaftertax_base Value"
				,xts_outsrcworefnumberoutsourceworkorderidname = "xts_outsrcworefnumberoutsourceworkorderidname Value"
				,msdyn_companycode = "msdyn_companycode Value"
            };

            return obj;
        }
    }
}