#region Summary
// ===========================================================================
// AUTHOR        : BSI Code Generator 
// SPECIAL NOTES : DNet WebApi Project
// ---------------------
// Copyright  (c) 2019 
// ---------------------
// $History      : $
// Created on 12/18/2019 10:09:30 AM]
//
// ===========================================================================	
#endregion

using Swashbuckle.Examples;

namespace KTB.DNet.Interface.WebApi.Models.Examples
{
    public class APIUpdateVWI_CRM_xts_vendorclassExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var obj = new
            {
                UpdatedBy = "DealerUser"
				,versionnumber = "versionnumber Value"
				,xts_pricevariancedimension6id = "xts_pricevariancedimension6id Value"
				,createdon = "createdon Value"
				,xts_pricevariancedimension5idname = "xts_pricevariancedimension5idname Value"
				,statuscodename = "statuscodename Value"
				,xts_dimension8id = "xts_dimension8id Value"
				,xts_pricevariancedimension2fromname = "xts_pricevariancedimension2fromname Value"
				,xts_downpaymentdimension3fromname = "xts_downpaymentdimension3fromname Value"
				,xts_accountpayableaccruegitaccountid = "xts_accountpayableaccruegitaccountid Value"
				,xts_downpaymentaccountidname = "xts_downpaymentaccountidname Value"
				,xts_pricevariancedimension1id = "xts_pricevariancedimension1id Value"
				,xts_description = "xts_description Value"
				,modifiedon = "modifiedon Value"
				,xts_downpaymentdimension2id = "xts_downpaymentdimension2id Value"
				,xts_dimension5id = "xts_dimension5id Value"
				,xts_accountpayabledimension6from = "xts_accountpayabledimension6from Value"
				,xts_accountpayabledimension5from = "xts_accountpayabledimension5from Value"
				,xts_advtitleregfeedimension6id = "xts_advtitleregfeedimension6id Value"
				,xts_downpaymentdimension5fromname = "xts_downpaymentdimension5fromname Value"
				,createdonbehalfby = "createdonbehalfby Value"
				,xts_downpaymentdimension3idname = "xts_downpaymentdimension3idname Value"
				,xts_pricevariancedimension5id = "xts_pricevariancedimension5id Value"
				,modifiedbyname = "modifiedbyname Value"
				,xts_downpaymentdimension6idname = "xts_downpaymentdimension6idname Value"
				,xts_accountpayabledimension3from = "xts_accountpayabledimension3from Value"
				,xts_dimension7id = "xts_dimension7id Value"
				,xts_dimension2id = "xts_dimension2id Value"
				,xts_dimension7idname = "xts_dimension7idname Value"
				,overriddencreatedon = "overriddencreatedon Value"
				,xts_dimension4id = "xts_dimension4id Value"
				,xts_downpaymentdimension1idname = "xts_downpaymentdimension1idname Value"
				,xts_downpaymentdimension3id = "xts_downpaymentdimension3id Value"
				,xts_accountpayableaccruegitaccountidname = "xts_accountpayableaccruegitaccountidname Value"
				,xts_downpaymentaccountid = "xts_downpaymentaccountid Value"
				,xts_pricevariancedimension2id = "xts_pricevariancedimension2id Value"
				,modifiedonbehalfby = "modifiedonbehalfby Value"
				,xts_accountpayableaccountidname = "xts_accountpayableaccountidname Value"
				,xts_pricevariancedimension2from = "xts_pricevariancedimension2from Value"
				,xts_pricevariancedimension5from = "xts_pricevariancedimension5from Value"
				,xts_writeoffaccountidname = "xts_writeoffaccountidname Value"
				,xts_pricevariancedimension4id = "xts_pricevariancedimension4id Value"
				,xts_advtitleregfeedimension4id = "xts_advtitleregfeedimension4id Value"
				,xts_accountpayabledimension2from = "xts_accountpayabledimension2from Value"
				,xts_accountpayabledimension4fromname = "xts_accountpayabledimension4fromname Value"
				,statecode = "statecode Value"
				,xts_pricevariancedimension1from = "xts_pricevariancedimension1from Value"
				,xts_accountpayabledimension5fromname = "xts_accountpayabledimension5fromname Value"
				,xts_company = "xts_company Value"
				,xts_advtitleregfeedimension1id = "xts_advtitleregfeedimension1id Value"
				,timezoneruleversionnumber = "timezoneruleversionnumber Value"
				,xts_vendorclass = "xts_vendorclass Value"
				,xts_pricevariancedimension6idname = "xts_pricevariancedimension6idname Value"
				,xts_accountpayabledimension2fromname = "xts_accountpayabledimension2fromname Value"
				,xts_downpaymentdimension6from = "xts_downpaymentdimension6from Value"
				,xts_accountpayableaccrueaccountidname = "xts_accountpayableaccrueaccountidname Value"
				,xts_accountpayabledimension3fromname = "xts_accountpayabledimension3fromname Value"
				,xts_writeoffaccountid = "xts_writeoffaccountid Value"
				,xts_pricevariancedimension2idname = "xts_pricevariancedimension2idname Value"
				,xts_downpaymentdimension1from = "xts_downpaymentdimension1from Value"
				,xts_advtitleregfeedimension4idname = "xts_advtitleregfeedimension4idname Value"
				,xts_pricevariancedimension3fromname = "xts_pricevariancedimension3fromname Value"
				,xts_accountpayabledimension4from = "xts_accountpayabledimension4from Value"
				,xts_pricevariancedimension4fromname = "xts_pricevariancedimension4fromname Value"
				,xts_vendortypename = "xts_vendortypename Value"
				,xts_accountpayabledimension1fromname = "xts_accountpayabledimension1fromname Value"
				,xts_downpaymentdimension3from = "xts_downpaymentdimension3from Value"
				,createdonbehalfbyname = "createdonbehalfbyname Value"
				,xts_accountpayabledimension6fromname = "xts_accountpayabledimension6fromname Value"
				,xts_dimension1id = "xts_dimension1id Value"
				,xts_downpaymentdimension2from = "xts_downpaymentdimension2from Value"
				,xts_pricevariancedimension5fromname = "xts_pricevariancedimension5fromname Value"
				,utcconversiontimezonecode = "utcconversiontimezonecode Value"
				,xts_pricevariancedimension1idname = "xts_pricevariancedimension1idname Value"
				,xts_dimension5idname = "xts_dimension5idname Value"
				,xts_downpaymentdimension5from = "xts_downpaymentdimension5from Value"
				,xts_pricevariancedimension4idname = "xts_pricevariancedimension4idname Value"
				,xts_downpaymentdimension4fromname = "xts_downpaymentdimension4fromname Value"
				,xts_downpaymentdimension5id = "xts_downpaymentdimension5id Value"
				,xts_downpaymentdimension5idname = "xts_downpaymentdimension5idname Value"
				,xts_vendorclassid = "xts_vendorclassid Value"
				,importsequencenumber = "importsequencenumber Value"
				,xts_dimension6id = "xts_dimension6id Value"
				,xts_advtitleregfeedimension5id = "xts_advtitleregfeedimension5id Value"
				,xts_accountpayabledimension1from = "xts_accountpayabledimension1from Value"
				,xts_dimension2idname = "xts_dimension2idname Value"
				,xts_dimension10idname = "xts_dimension10idname Value"
				,xts_pricevarianceaccountid = "xts_pricevarianceaccountid Value"
				,xts_pricevariancedimension6fromname = "xts_pricevariancedimension6fromname Value"
				,xts_advtitleregfeedimension6idname = "xts_advtitleregfeedimension6idname Value"
				,xts_pricevariancedimension6from = "xts_pricevariancedimension6from Value"
				,createdbyname = "createdbyname Value"
				,xts_advancetitleregistrationfeeaccountid = "xts_advancetitleregistrationfeeaccountid Value"
				,xts_pricevarianceaccountidname = "xts_pricevarianceaccountidname Value"
				,xts_dimension6idname = "xts_dimension6idname Value"
				,modifiedonbehalfbyname = "modifiedonbehalfbyname Value"
				,xts_locking = "xts_locking Value"
				,xts_advtitleregfeedimension2idname = "xts_advtitleregfeedimension2idname Value"
				,xts_downpaymentdimension1fromname = "xts_downpaymentdimension1fromname Value"
				,xts_downpaymentdimension4id = "xts_downpaymentdimension4id Value"
				,xts_pricevariancedimension3id = "xts_pricevariancedimension3id Value"
				,xts_advtitleregfeedimension3id = "xts_advtitleregfeedimension3id Value"
				,xts_downpaymentdimension6id = "xts_downpaymentdimension6id Value"
				,xts_dimension8idname = "xts_dimension8idname Value"
				,xts_advtitleregfeedimension2id = "xts_advtitleregfeedimension2id Value"
				,xts_accountpayableaccrueaccountid = "xts_accountpayableaccrueaccountid Value"
				,createdby = "createdby Value"
				,xts_pricevariancedimension3idname = "xts_pricevariancedimension3idname Value"
				,modifiedby = "modifiedby Value"
				,xts_advtitleregfeedimension1idname = "xts_advtitleregfeedimension1idname Value"
				,xts_dimension10id = "xts_dimension10id Value"
				,createdbyyominame = "createdbyyominame Value"
				,xts_dimension4idname = "xts_dimension4idname Value"
				,xts_dimension3idname = "xts_dimension3idname Value"
				,xts_dimension9idname = "xts_dimension9idname Value"
				,createdonbehalfbyyominame = "createdonbehalfbyyominame Value"
				,xts_dimension3id = "xts_dimension3id Value"
				,xts_vendortype = "xts_vendortype Value"
				,xts_dimension1idname = "xts_dimension1idname Value"
				,xts_dimension9id = "xts_dimension9id Value"
				,modifiedbyyominame = "modifiedbyyominame Value"
				,xts_downpaymentdimension2idname = "xts_downpaymentdimension2idname Value"
				,xts_accountpayableaccountid = "xts_accountpayableaccountid Value"
				,xts_pricevariancedimension3from = "xts_pricevariancedimension3from Value"
				,xts_advtitleregfeedimension5idname = "xts_advtitleregfeedimension5idname Value"
				,xts_downpaymentdimension2fromname = "xts_downpaymentdimension2fromname Value"
				,statuscode = "statuscode Value"
				,modifiedonbehalfbyyominame = "modifiedonbehalfbyyominame Value"
				,xts_pricevariancedimension4from = "xts_pricevariancedimension4from Value"
				,organizationid = "organizationid Value"
				,xts_downpaymentdimension1id = "xts_downpaymentdimension1id Value"
				,xts_downpaymentdimension4from = "xts_downpaymentdimension4from Value"
				,xts_advtitleregfeedimension3idname = "xts_advtitleregfeedimension3idname Value"
				,xts_downpaymentdimension6fromname = "xts_downpaymentdimension6fromname Value"
				,xts_pricevariancedimension1fromname = "xts_pricevariancedimension1fromname Value"
				,organizationidname = "organizationidname Value"
				,xts_downpaymentdimension4idname = "xts_downpaymentdimension4idname Value"
				,statecodename = "statecodename Value"
				,xts_advancetitleregistrationfeeaccountidname = "xts_advancetitleregistrationfeeaccountidname Value"
            };

            return obj;
        }
    }
}