#region Summary
// ===========================================================================
// AUTHOR        : BSI Code Generator 
// SPECIAL NOTES : DNet WebApi Project
// ---------------------
// Copyright  (c) 2019 
// ---------------------
// $History      : $
// Created on 12/18/2019 10:09:30 AM]
//
// ===========================================================================	
#endregion

using Swashbuckle.Examples;

namespace KTB.DNet.Interface.WebApi.Models.Examples
{
    public class APIUpdateVWI_CRM_xts_productclassExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var obj = new
            {
                UpdatedBy = "DealerUser"
				,xts_cogsdimension7id = "xts_cogsdimension7id Value"
				,xts_goodsintransitdimension2id = "xts_goodsintransitdimension2id Value"
				,xts_cogsdimension4id = "xts_cogsdimension4id Value"
				,xts_defaultunitid = "xts_defaultunitid Value"
				,modifiedon = "modifiedon Value"
				,overriddencreatedon = "overriddencreatedon Value"
				,statuscodename = "statuscodename Value"
				,xts_inventorydimension4id = "xts_inventorydimension4id Value"
				,xts_discountdimension6id = "xts_discountdimension6id Value"
				,xts_salesdimension3id = "xts_salesdimension3id Value"
				,xts_salesdimension10idname = "xts_salesdimension10idname Value"
				,xts_discountdimension10id = "xts_discountdimension10id Value"
				,xts_goodsintransitdimension7idname = "xts_goodsintransitdimension7idname Value"
				,xts_includetransferorder = "xts_includetransferorder Value"
				,xts_goodsintransitdimension4id = "xts_goodsintransitdimension4id Value"
				,xts_goodsintransitdimension5id = "xts_goodsintransitdimension5id Value"
				,xts_defaultsalesunitidname = "xts_defaultsalesunitidname Value"
				,xts_discountdimension4idname = "xts_discountdimension4idname Value"
				,xts_cogsdimension6idname = "xts_cogsdimension6idname Value"
				,xts_discountdimension7idname = "xts_discountdimension7idname Value"
				,xts_cogsdimension5idname = "xts_cogsdimension5idname Value"
				,xts_inventorydimension7idname = "xts_inventorydimension7idname Value"
				,xts_salesdimension4idname = "xts_salesdimension4idname Value"
				,xts_goodsintransitdimension10id = "xts_goodsintransitdimension10id Value"
				,xts_type = "xts_type Value"
				,xts_inventorydimension3id = "xts_inventorydimension3id Value"
				,xts_goodsintransitdimension1idname = "xts_goodsintransitdimension1idname Value"
				,xts_trackingdimensiongroupid = "xts_trackingdimensiongroupid Value"
				,xts_defaultunitidname = "xts_defaultunitidname Value"
				,xts_cogsdimension10id = "xts_cogsdimension10id Value"
				,xts_discountdimension1id = "xts_discountdimension1id Value"
				,xts_discountdimension8idname = "xts_discountdimension8idname Value"
				,xts_inventorydimension6idname = "xts_inventorydimension6idname Value"
				,xts_inventorydimension9id = "xts_inventorydimension9id Value"
				,xts_inventorydimension2id = "xts_inventorydimension2id Value"
				,statuscode = "statuscode Value"
				,xts_discountdimension8id = "xts_discountdimension8id Value"
				,xts_salesdimension8idname = "xts_salesdimension8idname Value"
				,xts_salesdimension3idname = "xts_salesdimension3idname Value"
				,xts_cogsdimension9id = "xts_cogsdimension9id Value"
				,xts_salesdimension4id = "xts_salesdimension4id Value"
				,xts_goodsintransitdimension6idname = "xts_goodsintransitdimension6idname Value"
				,xts_discountdimension7id = "xts_discountdimension7id Value"
				,xts_inventorydimension8id = "xts_inventorydimension8id Value"
				,statecodename = "statecodename Value"
				,xts_defaultsalesunitid = "xts_defaultsalesunitid Value"
				,xts_cogsdimension1idname = "xts_cogsdimension1idname Value"
				,xts_includepurchaseordername = "xts_includepurchaseordername Value"
				,xts_inventorydimension5id = "xts_inventorydimension5id Value"
				,xts_salesdimension5id = "xts_salesdimension5id Value"
				,xts_entitytag = "xts_entitytag Value"
				,bsi_roundingname = "bsi_roundingname Value"
				,xts_cogsdimension6id = "xts_cogsdimension6id Value"
				,xts_goodsintransitdimension8id = "xts_goodsintransitdimension8id Value"
				,xts_storagedimensiongroupidname = "xts_storagedimensiongroupidname Value"
				,createdon = "createdon Value"
				,xts_goodsintransitdimension9id = "xts_goodsintransitdimension9id Value"
				,xts_discountdimension2id = "xts_discountdimension2id Value"
				,xts_discountdimension6idname = "xts_discountdimension6idname Value"
				,xts_deductworkordername = "xts_deductworkordername Value"
				,xts_salesdimension10id = "xts_salesdimension10id Value"
				,xts_goodsintransitdimension7id = "xts_goodsintransitdimension7id Value"
				,xts_goodsintransitdimension6id = "xts_goodsintransitdimension6id Value"
				,xts_cogsdimension9idname = "xts_cogsdimension9idname Value"
				,xts_includetransferordername = "xts_includetransferordername Value"
				,xts_deductsalesordername = "xts_deductsalesordername Value"
				,xts_goodsintransitdimension9idname = "xts_goodsintransitdimension9idname Value"
				,xts_goodsintransitdimension2idname = "xts_goodsintransitdimension2idname Value"
				,xts_deductsalesorder = "xts_deductsalesorder Value"
				,modifiedbyyominame = "modifiedbyyominame Value"
				,xts_discountdimension5idname = "xts_discountdimension5idname Value"
				,xts_goodsintransitdimension4idname = "xts_goodsintransitdimension4idname Value"
				,modifiedby = "modifiedby Value"
				,xts_salesdimension5idname = "xts_salesdimension5idname Value"
				,timezoneruleversionnumber = "timezoneruleversionnumber Value"
				,xts_productdimensiongroupidname = "xts_productdimensiongroupidname Value"
				,xts_trackingdimensiongroupidname = "xts_trackingdimensiongroupidname Value"
				,modifiedonbehalfby = "modifiedonbehalfby Value"
				,xts_inventorydimension10idname = "xts_inventorydimension10idname Value"
				,xts_salesdimension2idname = "xts_salesdimension2idname Value"
				,xts_cogsdimension7idname = "xts_cogsdimension7idname Value"
				,xts_cogsdimension4idname = "xts_cogsdimension4idname Value"
				,xts_cogsdimension5id = "xts_cogsdimension5id Value"
				,xts_goodsintransitdimension3idname = "xts_goodsintransitdimension3idname Value"
				,xts_inventorydimension2idname = "xts_inventorydimension2idname Value"
				,createdonbehalfbyname = "createdonbehalfbyname Value"
				,xts_discountdimension9id = "xts_discountdimension9id Value"
				,xts_inventorydimension1idname = "xts_inventorydimension1idname Value"
				,xts_discountdimension4id = "xts_discountdimension4id Value"
				,modifiedonbehalfbyname = "modifiedonbehalfbyname Value"
				,createdonbehalfbyyominame = "createdonbehalfbyyominame Value"
				,xts_cogsdimension2idname = "xts_cogsdimension2idname Value"
				,xts_salesdimension6idname = "xts_salesdimension6idname Value"
				,xts_inventorydimension1id = "xts_inventorydimension1id Value"
				,xts_inventorydimension5idname = "xts_inventorydimension5idname Value"
				,xts_goodsintransitdimension8idname = "xts_goodsintransitdimension8idname Value"
				,xts_salesdimension1id = "xts_salesdimension1id Value"
				,xts_defaultpurchaseunitid = "xts_defaultpurchaseunitid Value"
				,xts_description = "xts_description Value"
				,createdonbehalfby = "createdonbehalfby Value"
				,xts_deductreservationname = "xts_deductreservationname Value"
				,xts_inventorydimension4idname = "xts_inventorydimension4idname Value"
				,xts_storagedimensiongroupid = "xts_storagedimensiongroupid Value"
				,organizationid = "organizationid Value"
				,xts_cogsdimension3idname = "xts_cogsdimension3idname Value"
				,bsi_rounding = "bsi_rounding Value"
				,xts_goodsintransitdimension3id = "xts_goodsintransitdimension3id Value"
				,xts_defaultpurchaseunitidname = "xts_defaultpurchaseunitidname Value"
				,xts_salesdimension6id = "xts_salesdimension6id Value"
				,xts_cogsdimension2id = "xts_cogsdimension2id Value"
				,xts_goodsintransitdimension1id = "xts_goodsintransitdimension1id Value"
				,xts_cogsdimension3id = "xts_cogsdimension3id Value"
				,xts_salesdimension9idname = "xts_salesdimension9idname Value"
				,xts_includepurchaseorder = "xts_includepurchaseorder Value"
				,xts_inventorydimension9idname = "xts_inventorydimension9idname Value"
				,xts_inventorymodelgroupidname = "xts_inventorymodelgroupidname Value"
				,xts_cogsdimension8id = "xts_cogsdimension8id Value"
				,createdbyname = "createdbyname Value"
				,xts_salesdimension1idname = "xts_salesdimension1idname Value"
				,xts_salesdimension7id = "xts_salesdimension7id Value"
				,statecode = "statecode Value"
				,modifiedonbehalfbyyominame = "modifiedonbehalfbyyominame Value"
				,createdby = "createdby Value"
				,xts_cogsdimension8idname = "xts_cogsdimension8idname Value"
				,xts_virtualcompany = "xts_virtualcompany Value"
				,xts_discountdimension1idname = "xts_discountdimension1idname Value"
				,xts_deductworkorder = "xts_deductworkorder Value"
				,xts_inventorymodelgroupid = "xts_inventorymodelgroupid Value"
				,xts_discountdimension10idname = "xts_discountdimension10idname Value"
				,utcconversiontimezonecode = "utcconversiontimezonecode Value"
				,xts_discountdimension2idname = "xts_discountdimension2idname Value"
				,xts_postingclassidname = "xts_postingclassidname Value"
				,xts_inventorydimension7id = "xts_inventorydimension7id Value"
				,xts_postingclassid = "xts_postingclassid Value"
				,xts_goodsintransitdimension10idname = "xts_goodsintransitdimension10idname Value"
				,xts_discountdimension3id = "xts_discountdimension3id Value"
				,xts_productclassid = "xts_productclassid Value"
				,importsequencenumber = "importsequencenumber Value"
				,xts_cogsdimension1id = "xts_cogsdimension1id Value"
				,xts_discountdimension5id = "xts_discountdimension5id Value"
				,organizationidname = "organizationidname Value"
				,xts_deductreservation = "xts_deductreservation Value"
				,xts_productclass = "xts_productclass Value"
				,versionnumber = "versionnumber Value"
				,xts_salesdimension7idname = "xts_salesdimension7idname Value"
				,xts_discountdimension3idname = "xts_discountdimension3idname Value"
				,xts_inventorydimension6id = "xts_inventorydimension6id Value"
				,xts_salesdimension8id = "xts_salesdimension8id Value"
				,xts_typename = "xts_typename Value"
				,modifiedbyname = "modifiedbyname Value"
				,createdbyyominame = "createdbyyominame Value"
				,xts_inventorydimension3idname = "xts_inventorydimension3idname Value"
				,xts_productdimensiongroupid = "xts_productdimensiongroupid Value"
				,xts_inventorydimension8idname = "xts_inventorydimension8idname Value"
				,xts_discountdimension9idname = "xts_discountdimension9idname Value"
				,xts_salesdimension2id = "xts_salesdimension2id Value"
				,xts_inventorydimension10id = "xts_inventorydimension10id Value"
				,xts_goodsintransitdimension5idname = "xts_goodsintransitdimension5idname Value"
				,xts_cogsdimension10idname = "xts_cogsdimension10idname Value"
				,xts_salesdimension9id = "xts_salesdimension9id Value"
            };

            return obj;
        }
    }
}