#region Summary
// ===========================================================================
// AUTHOR        : BSI Code Generator 
// SPECIAL NOTES : DNet WebApi Project
// ---------------------
// Copyright  (c) 2019 
// ---------------------
// $History      : $
// Created on 24/02/2020 18:15:44]
//
// ===========================================================================	
#endregion

using Swashbuckle.Examples;

namespace KTB.DNet.Interface.WebApi.Models.Examples
{
    public class APIUpdateVWI_CRM_xts_reservationtransactionExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var obj = new
            {
                UpdatedBy = "DealerUser"
				,company = "company Value"
				,businessunitcode = "businessunitcode Value"
				,xts_reservationtransaction = "xts_reservationtransaction Value"
				,ktb_esttotalworktaxamount = "ktb_esttotalworktaxamount Value"
				,modifiedon = "modifiedon Value"
				,overriddencreatedon = "overriddencreatedon Value"
				,xts_finishpattern = "xts_finishpattern Value"
				,ktb_esttotalmiscchargebaseamount_base = "ktb_esttotalmiscchargebaseamount_base Value"
				,statuscodename = "statuscodename Value"
				,xts_status = "xts_status Value"
				,xts_scheduledarrivaldateandtime = "xts_scheduledarrivaldateandtime Value"
				,xts_deliveryaddress2 = "xts_deliveryaddress2 Value"
				,xts_workorderidname = "xts_workorderidname Value"
				,xts_estimatebayidname = "xts_estimatebayidname Value"
				,ktb_esttotalbaseamount_base = "ktb_esttotalbaseamount_base Value"
				,ktb_esttotalothersalestaxamount_base = "ktb_esttotalothersalestaxamount_base Value"
				,ktb_esttotalothersalestaxamount = "ktb_esttotalothersalestaxamount Value"
				,xts_pickupaddress1 = "xts_pickupaddress1 Value"
				,ktb_estgrandtotalamount = "ktb_estgrandtotalamount Value"
				,transactioncurrencyidname = "transactioncurrencyidname Value"
				,xts_customeridyominame = "xts_customeridyominame Value"
				,xts_chassismodel = "xts_chassismodel Value"
				,xts_vehicleincludedintherecall = "xts_vehicleincludedintherecall Value"
				,createdonbehalfby = "createdonbehalfby Value"
				,xts_scheduledservicestartdate = "xts_scheduledservicestartdate Value"
				,xts_pickupaddress2 = "xts_pickupaddress2 Value"
				,ktb_productsegment2id = "ktb_productsegment2id Value"
				,ktb_productsegment4idname = "ktb_productsegment4idname Value"
				,ktb_esttotalworkamount_base = "ktb_esttotalworkamount_base Value"
				,owningbusinessunit = "owningbusinessunit Value"
				,ktb_productidname = "ktb_productidname Value"
				,xts_deliverypostalcode = "xts_deliverypostalcode Value"
				,xts_customernumber = "xts_customernumber Value"
				,ktb_productsegment3idname = "ktb_productsegment3idname Value"
				,ktb_exchangerateamount = "ktb_exchangerateamount Value"
				,modifiedonbehalfby = "modifiedonbehalfby Value"
				,xts_customeridname = "xts_customeridname Value"
				,owneridyominame = "owneridyominame Value"
				,statuscode = "statuscode Value"
				,xts_estimatebayid = "xts_estimatebayid Value"
				,ktb_esttotalmiscchargeamount_base = "ktb_esttotalmiscchargeamount_base Value"
				,ktb_esttotalothersalesbaseamount = "ktb_esttotalothersalesbaseamount Value"
				,xts_defaultoutsourceworkshopidname = "xts_defaultoutsourceworkshopidname Value"
				,xts_maintenancepackageinformation = "xts_maintenancepackageinformation Value"
				,ktb_esttotalworkamount = "ktb_esttotalworkamount Value"
				,statecodename = "statecodename Value"
				,xts_deliveryaddress1 = "xts_deliveryaddress1 Value"
				,xts_scheduledfinishdateandtime = "xts_scheduledfinishdateandtime Value"
				,ktb_esttotalmiscchargetaxamount = "ktb_esttotalmiscchargetaxamount Value"
				,ktb_productsegment1idname = "ktb_productsegment1idname Value"
				,xts_contactpersonidname = "xts_contactpersonidname Value"
				,xts_vehicleidentificationid = "xts_vehicleidentificationid Value"
				,xts_contactpersonid = "xts_contactpersonid Value"
				,xts_reservationpersoninchargeid = "xts_reservationpersoninchargeid Value"
				,xts_defaultoutsourceworkshopid = "xts_defaultoutsourceworkshopid Value"
				,xts_servicecategoryid = "xts_servicecategoryid Value"
				,createdon = "createdon Value"
				,ktb_productsegment2idname = "ktb_productsegment2idname Value"
				,xts_handling = "xts_handling Value"
				,xts_customerid = "xts_customerid Value"
				,xts_statusname = "xts_statusname Value"
				,ktb_esttotalmiscchargeamount = "ktb_esttotalmiscchargeamount Value"
				,xts_contactpersonidyominame = "xts_contactpersonidyominame Value"
				,xts_previousreservationid = "xts_previousreservationid Value"
				,ktb_esttotalworkbaseamount_base = "ktb_esttotalworkbaseamount_base Value"
				,ktb_productdescription = "ktb_productdescription Value"
				,xts_vehicleidentificationidname = "xts_vehicleidentificationidname Value"
				,ktb_esttotaltaxamount_base = "ktb_esttotaltaxamount_base Value"
				,xts_personinchargefordeliveryidname = "xts_personinchargefordeliveryidname Value"
				,modifiedby = "modifiedby Value"
				,timezoneruleversionnumber = "timezoneruleversionnumber Value"
				,ktb_esttotalothersalesbaseamount_base = "ktb_esttotalothersalesbaseamount_base Value"
				,owninguser = "owninguser Value"
				,xts_incomingoutsourcebusinessunitid = "xts_incomingoutsourcebusinessunitid Value"
				,xts_vehicleplatenumber = "xts_vehicleplatenumber Value"
				,xts_vehiclemodelname = "xts_vehiclemodelname Value"
				,ktb_esttotalworkbaseamount = "ktb_esttotalworkbaseamount Value"
				,ktb_exchangerate = "ktb_exchangerate Value"
				,ktb_exchangeratedate = "ktb_exchangeratedate Value"
				,xts_globalserviceidname = "xts_globalserviceidname Value"
				,traversedpath = "traversedpath Value"
				,xts_aliasname = "xts_aliasname Value"
				,ktb_esttotalpartstaxamount = "ktb_esttotalpartstaxamount Value"
				,createdonbehalfbyname = "createdonbehalfbyname Value"
				,xts_reservationclassidname = "xts_reservationclassidname Value"
				,ktb_esttotaltaxamount = "ktb_esttotaltaxamount Value"
				,xts_servicecategoryidname = "xts_servicecategoryidname Value"
				,xts_reservationclassid = "xts_reservationclassid Value"
				,xts_salespersonid = "xts_salespersonid Value"
				,owneridtype = "owneridtype Value"
				,ktb_esttotalpartsamount_base = "ktb_esttotalpartsamount_base Value"
				,xts_transactiondate = "xts_transactiondate Value"
				,ktb_esttotalpartstaxamount_base = "ktb_esttotalpartstaxamount_base Value"
				,xts_personinchargeforarrivalidname = "xts_personinchargeforarrivalidname Value"
				,xts_reservationtransactionid = "xts_reservationtransactionid Value"
				,xts_chassisnumber = "xts_chassisnumber Value"
				,owneridname = "owneridname Value"
				,xts_vehicleincludedintherecallname = "xts_vehicleincludedintherecallname Value"
				,modifiedonbehalfbyname = "modifiedonbehalfbyname Value"
				,createdonbehalfbyyominame = "createdonbehalfbyyominame Value"
				,xts_personinchargeforarrivalid = "xts_personinchargeforarrivalid Value"
				,xts_loadinggroupidname = "xts_loadinggroupidname Value"
				,ktb_dnetticketno = "ktb_dnetticketno Value"
				,xts_globalserviceid = "xts_globalserviceid Value"
				,owningteam = "owningteam Value"
				,xts_reservationmemo = "xts_reservationmemo Value"
				,ktb_productsegment4id = "ktb_productsegment4id Value"
				,xts_arrivalpatternname = "xts_arrivalpatternname Value"
				,xts_parentbusinessunitidname = "xts_parentbusinessunitidname Value"
				,processid = "processid Value"
				,exchangerate = "exchangerate Value"
				,xts_insurancecontract = "xts_insurancecontract Value"
				,xts_parentbusinessunitid = "xts_parentbusinessunitid Value"
				,transactioncurrencyid = "transactioncurrencyid Value"
				,xts_reservationpersoninchargeidname = "xts_reservationpersoninchargeidname Value"
				,xts_finishpatternname = "xts_finishpatternname Value"
				,modifiedbyyominame = "modifiedbyyominame Value"
				,ownerid = "ownerid Value"
				,ktb_esttotalpartsamount = "ktb_esttotalpartsamount Value"
				,xts_ordertypeidname = "xts_ordertypeidname Value"
				,xts_salespersonidname = "xts_salespersonidname Value"
				,createdbyname = "createdbyname Value"
				,xts_businessunitidname = "xts_businessunitidname Value"
				,statecode = "statecode Value"
				,xts_personinchargefordeliveryid = "xts_personinchargefordeliveryid Value"
				,modifiedonbehalfbyyominame = "modifiedonbehalfbyyominame Value"
				,createdby = "createdby Value"
				,xts_platenumber = "xts_platenumber Value"
				,xts_arrivalpattern = "xts_arrivalpattern Value"
				,ktb_productsegment1id = "ktb_productsegment1id Value"
				,xts_deliveryaddress4 = "xts_deliveryaddress4 Value"
				,xts_ordertypeid = "xts_ordertypeid Value"
				,xts_arrivalpostalcode = "xts_arrivalpostalcode Value"
				,xts_deliveryaddress3 = "xts_deliveryaddress3 Value"
				,stageid = "stageid Value"
				,utcconversiontimezonecode = "utcconversiontimezonecode Value"
				,xts_incomingoutsourcebusinessunitidname = "xts_incomingoutsourcebusinessunitidname Value"
				,ktb_esttotalothersalesamount_base = "ktb_esttotalothersalesamount_base Value"
				,ktb_estgrandtotalamount_base = "ktb_estgrandtotalamount_base Value"
				,importsequencenumber = "importsequencenumber Value"
				,xts_locking = "xts_locking Value"
				,ktb_productid = "ktb_productid Value"
				,xts_reservationmanhour = "xts_reservationmanhour Value"
				,xts_pickupaddress3 = "xts_pickupaddress3 Value"
				,xts_servicepackagecontract = "xts_servicepackagecontract Value"
				,versionnumber = "versionnumber Value"
				,ktb_esttotalothersalesamount = "ktb_esttotalothersalesamount Value"
				,xts_businessunitid = "xts_businessunitid Value"
				,ktb_esttotalbaseamount = "ktb_esttotalbaseamount Value"
				,ktb_esttotalworktaxamount_base = "ktb_esttotalworktaxamount_base Value"
				,ktb_esttotalpartsbaseamount_base = "ktb_esttotalpartsbaseamount_base Value"
				,xts_handlingname = "xts_handlingname Value"
				,ktb_esttotalpartsbaseamount = "ktb_esttotalpartsbaseamount Value"
				,ktb_esttotalmiscchargetaxamount_base = "ktb_esttotalmiscchargetaxamount_base Value"
				,xts_pickupaddress4 = "xts_pickupaddress4 Value"
				,xts_contactpersonphone = "xts_contactpersonphone Value"
				,modifiedbyname = "modifiedbyname Value"
				,ktb_productsegment3id = "ktb_productsegment3id Value"
				,createdbyyominame = "createdbyyominame Value"
				,ktb_esttotalmiscchargebaseamount = "ktb_esttotalmiscchargebaseamount Value"
				,xts_loadinggroupid = "xts_loadinggroupid Value"
				,xts_previousreservationidname = "xts_previousreservationidname Value"
				,xts_workorderid = "xts_workorderid Value"
				,xts_cancelreason = "xts_cancelreason Value"
				,msdyn_companycode = "msdyn_companycode Value"
            };

            return obj;
        }
    }
}