#region Summary
/*
 ===========================================================================
 AUTHOR        : BSI Code Generator Interface 
 PURPOSE       : CRM_xts_writeoffbalancedetail class
 SPECIAL NOTES : Generated from database BSIDMS_MMKSI_IF_ACC_DEV
 GENERATED BY  : Khalil (version : v.1.08)
 ---------------------
 Copyright  (c) 2020 
 ---------------------
 $History      : $
 Created on 03 Sep 2020 13:25:57
 ===========================================================================
*/
#endregion


namespace KTB.DNet.Interface.Model
{
    public class CRM_xts_writeoffbalancedetailFilterDto : FilterDtoBase
    {

    }
}
