//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTB.DNet.Interface.Repository.Dapper.SqlQuery.EndpointSchedule {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EndpointScheduleQuery {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EndpointScheduleQuery() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KTB.DNet.Interface.Repository.Dapper.SqlQuery.EndpointSchedule.EndpointScheduleQu" +
                            "ery", typeof(EndpointScheduleQuery).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [APIEndpointSchedule] 
        ///WHERE [APIEndpointSchedule].Id = @Id
        ///.
        /// </summary>
        internal static string DeleteEndpointSchedule {
            get {
                return ResourceManager.GetString("DeleteEndpointSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    [APIEndpointSchedule].[Id]
        ///    ,[APIEndpointSchedule].[EndpointId]
        ///    ,[APIEndpointSchedule].[CreatedBy]
        ///    ,[APIEndpointSchedule].[CreatedTime]
        ///    ,[APIEndpointSchedule].[UpdatedBy]
        ///    ,[APIEndpointSchedule].[UpdatedTime]
        ///    ,[APIEndpointSchedule].[ScheduleId]
        ///FROM [APIEndpointSchedule]
        ///.
        /// </summary>
        internal static string GetAllEndpointSchedule {
            get {
                return ResourceManager.GetString("GetAllEndpointSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    es.[Id]
        ///    ,es.[EndpointId]
        ///    ,es.[CreatedBy]
        ///    ,es.[CreatedTime]
        ///    ,es.[UpdatedBy]
        ///    ,es.[UpdatedTime]
        ///    ,es.[ScheduleId]
        ///    ,s.[Id]
        ///    ,s.[Name]
        ///    ,s.[ScheduleType]
        ///    ,s.[ScheduleDay]
        ///    ,s.[MonthDay]
        ///    ,s.[ScheduleTime]
        ///    ,s.[Interval]
        ///    ,s.[DealerCode]
        ///FROM [APIEndpointSchedule] es
        ///INNER JOIN [APISchedule] s on s.Id = es.ScheduleId
        ///WHERE (@EndpointId = &apos;&apos; OR lower(es.EndpointId) = lower(@EndpointId))
        ///.
        /// </summary>
        internal static string GetEndpointScheduleByEndpointId {
            get {
                return ResourceManager.GetString("GetEndpointScheduleByEndpointId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  es.[Id]
        ///    ,es.[EndpointId]
        ///    ,es.[CreatedBy]
        ///    ,es.[CreatedTime]
        ///    ,es.[UpdatedBy]
        ///    ,es.[UpdatedTime]
        ///    ,es.[ScheduleId]
        ///	,e.[Id]
        ///      ,e.[Name]
        ///      ,e.[PermissionCode]
        ///      ,e.[URI]
        ///      ,e.[EndpointType]
        ///      ,e.[OperationType]
        ///      ,e.[Description]
        ///      ,e.[IsScheduled]
        ///      ,e.[CreatedBy]
        ///      ,e.[CreatedTime]
        ///      ,e.[UpdatedBy]
        ///      ,e.[UpdatedTime]
        ///  FROM [dbo].[APIEndpointSchedule] es
        ///  INNER JOIN [APIEndpointPermission] e on e.Id = es.EndpointId        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEndpointScheduleByEndpointUrl {
            get {
                return ResourceManager.GetString("GetEndpointScheduleByEndpointUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    [APIEndpointSchedule].[Id]
        ///    ,[APIEndpointSchedule].[EndpointId]
        ///    ,[APIEndpointSchedule].[CreatedBy]
        ///    ,[APIEndpointSchedule].[CreatedTime]
        ///    ,[APIEndpointSchedule].[UpdatedBy]
        ///    ,[APIEndpointSchedule].[UpdatedTime]
        ///    ,[APIEndpointSchedule].[ScheduleId]
        ///FROM [APIEndpointSchedule] 
        ///WHERE [APIEndpointSchedule].Id = @Id
        ///.
        /// </summary>
        internal static string GetEndpointScheduleById {
            get {
                return ResourceManager.GetString("GetEndpointScheduleById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [APIEndpointSchedule]
        ///           ([EndpointId]
        ///           ,[ScheduleId]
        ///           ,[CreatedBy]
        ///           ,[CreatedTime]
        ///           ,[UpdatedBy]
        ///           ,[UpdatedTime])
        ///	OUTPUT Inserted.Id
        ///    VALUES
        ///           (@EndpointId
        ///           ,@ScheduleId
        ///           ,@CreatedBy
        ///           ,@CreatedTime
        ///           ,@UpdatedBy
        ///           ,@UpdatedTime)
        ///
        ///.
        /// </summary>
        internal static string InsertEndpointSchedule {
            get {
                return ResourceManager.GetString("InsertEndpointSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    /**PagingIndexQuery**/
        ///    es.[Id]
        ///    ,es.[EndpointId]
        ///    ,es.[CreatedBy]
        ///    ,es.[CreatedTime]
        ///    ,es.[UpdatedBy]
        ///    ,es.[UpdatedTime]
        ///    ,es.[ScheduleId]
        ///    ,APISchedule.[Name]
        ///    ,APISchedule.[ScheduleType]
        ///    ,APISchedule.[ScheduleDay]
        ///    ,APISchedule.[MonthDay]
        ///    ,APISchedule.[ScheduleTime]
        ///    ,APISchedule.[Interval]
        ///    ,APISchedule.[DealerCode]
        ///    /**EndPagingIndexQuery**/
        ///FROM [APIEndpointSchedule] es
        ///-- INNER JOIN [APIEndpointPermission] ep on ep.Id = es.E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchEndpointSchedule {
            get {
                return ResourceManager.GetString("SearchEndpointSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [APIEndpointSchedule]
        ///   SET [EndpointId] = @EndpointId
        ///      ,[ScheduleId] = @ScheduleId
        ///      ,[CreatedBy] = @CreatedBy
        ///      ,[CreatedTime] = @CreatedTime
        ///      ,[UpdatedBy] = @UpdatedBy
        ///      ,[UpdatedTime] = @UpdatedTime
        /// WHERE Id = @Id
        ///
        ///.
        /// </summary>
        internal static string UpdateEndpointSchedule {
            get {
                return ResourceManager.GetString("UpdateEndpointSchedule", resourceCulture);
            }
        }
    }
}
