#region Summary
/*
 ===========================================================================
 AUTHOR        : BSI Code Generator Interface 
 PURPOSE       : CRM_appointment class
 SPECIAL NOTES : Generated from database BSIDMS_MMKSI_IF_ACC_DEV 
 GENERATED BY  : Ivan
 ---------------------
 Copyright  (c) 2020 
 ---------------------
 $History      : $
 Created on 19 Jan 2021 09:14:36
 ===========================================================================
*/
#endregion


#region Namespace Imports
using KTB.DNet.DataMapper.Framework;
using KTB.DNet.Domain;
using KTB.DNet.Domain.Search;
using KTB.DNet.Interface.BusinessLogic.Interface;
using KTB.DNet.Interface.BusinessLogic.MapperBL;
using KTB.DNet.Interface.Repository.Interface;
using KTB.DNet.Interface.Model;
using KTB.DNet.Interface.Domain;
using KTB.DNet.Interface.Resources;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using KTB.DNet.Interface.Framework;
using AutoMapper;
using System.Reflection;
#endregion

namespace KTB.DNet.Interface.BusinessLogic
{
    public class CRM_appointmentBL : AbstractBusinessLogic, ICRM_appointmentBL
    {
        #region Variables
        private ICRM_appointmentRepository<CRM_appointment, int> _CRM_appointmentRepo;
        #endregion

        #region Constructor
        public CRM_appointmentBL(ICRM_appointmentRepository<CRM_appointment, int> CRM_appointmentRepo)
        {
            _CRM_appointmentRepo = CRM_appointmentRepo;
        }

        #endregion

        #region Public Methods
        /// <summary>
        /// Get CRM_appointment by certain criteria
        /// </summary>
        /// <param name="filterDto"></param>
        /// <param name="pageSize"></param>
        /// <returns></returns>
        public ResponseBase<List<CRM_appointmentDto>> Read(CRM_appointmentFilterDto filterDto, int pageSize)
        {
            return null;
        }

        public ResponseBase<List<CRM_appointmentDto>> ReadList(CRM_appointmentFilterDto filterDto, int pageSize)
        {

            var result = new ResponseBase<List<CRM_appointmentDto>>();
            var sortColl = string.Empty;
            int totalRow = 0;
            int filteredTotalRow = 0;
            string rawSql = string.Empty;

            try
            {
                var innerQueryCriteria = string.Empty;
                var dc = DealerCode;
                var criterias = Helper.InitialStrCriteria(typeof(CRM_appointment), filterDto);

                criterias = Helper.UpdateStrCriteria(typeof(CRM_appointment), new MatchTypeFilter { SqlOperation = SQLOperation.And }, MatchType.Exact.GetHashCode(), "DealerCode", DealerCode, false, criterias);
                criterias = Helper.UpdateStrCriteria(typeof(CRM_appointment), new MatchTypeFilter { SqlOperation = SQLOperation.And }, MatchType.Exact.GetHashCode(), "SourceType", "NON DMS", false, criterias);
                criterias = Helper.UpdateStrCriteria(typeof(CRM_appointment), new MatchTypeFilter { SqlOperation = SQLOperation.And }, MatchType.Exact.GetHashCode(), "RowStatus", "0", false, criterias);

                sortColl = Helper.UpdateSortColumnDapper(typeof(CRM_appointment), filterDto, "CRM_appointment");

                List<CRM_appointment> data = _CRM_appointmentRepo.Search(
                                    criterias, innerQueryCriteria, sortColl, filterDto.pages, pageSize, out filteredTotalRow, out totalRow);

                if (data != null && data.Count > 0)
                {
                    CRM_appointment x = new CRM_appointment();
                    result.lst = data.ConvertList<CRM_appointment, CRM_appointmentDto>();
                    result.total = filteredTotalRow;
                }
                else
                {
                    ErrorMsgHelper.DataNotFound(result.messages, typeof(CRM_appointment), filterDto);
                }

                result.success = true;

            }
            catch (SqlException ex)
            {
                ErrorMsgHelper.SqlExceptionRead(result.messages, ex.Message);
            }
            catch (Exception ex)
            {
                ErrorMsgHelper.Exception(result.messages, ex.Message);
            }
            return result;

        }

        /// <summary>
        /// Create a new CRM_appointment
        /// </summary>
        /// <param name="objCreate"></param>
        /// <returns></returns>
        public ResponseBase<CRM_appointmentDto> Create(CRM_appointmentParameterDto objCreate)
        {
            return null;
        }


        public ResponseBaseCustom<CRM_appointmentDto> Create(CRM_appointmentCreateParameterDto paramCreate)
        {
            var result = new ResponseBaseCustom<CRM_appointmentDto>();
            var sortColl = string.Empty;
            int totalRow = 0;
            int filteredTotalRow = 0;
            string rawSql = string.Empty;
            var innerQueryCriteria = string.Empty;
            var page = 1;
            var size = 20;
            var validationResults = new List<DNetValidationResult>();

            try
            {
                #region old code Check Duplicate Data
                //            var criterias = "";
                //            criterias = Helper.UpdateStrCriteria(typeof(CRM_appointment), new MatchTypeFilter { SqlOperation = SQLOperation.And }, MatchType.Exact.GetHashCode(), "DealerCode", DealerCode, false, criterias);
                //            criterias = Helper.UpdateStrCriteria(typeof(CRM_appointment), new MatchTypeFilter { SqlOperation = SQLOperation.And }, MatchType.Exact.GetHashCode(), "SourceType", "NON DMS", false, criterias);
                //            criterias = Helper.UpdateStrCriteria(typeof(CRM_appointment), new MatchTypeFilter { SqlOperation = SQLOperation.And }, MatchType.Exact.GetHashCode(), "RowStatus", 0, false, criterias);
                //criterias = Helper.UpdateStrCriteria(typeof(CRM_appointment), new MatchTypeFilter { SqlOperation = SQLOperation.And }, MatchType.Exact.GetHashCode(), "xts_appointmenttype", paramCreate.xts_appointmenttype.ToString(), false, criterias);
                //criterias = Helper.UpdateStrCriteria(typeof(CRM_appointment), new MatchTypeFilter { SqlOperation = SQLOperation.And }, MatchType.Exact.GetHashCode(), "xts_businessunitid", paramCreate.xts_businessunitid.ToString(), false, criterias);

                //            List<CRM_appointment> data = _CRM_appointmentRepo.Search(
                //                                criterias, innerQueryCriteria, sortColl, page, size, out filteredTotalRow, out totalRow);

                //            if (data != null && data.Count == 0)
                //            {
                #endregion

                PropertyInfo[] properties = typeof(CRM_appointmentCreateParameterDto).GetProperties();
                foreach (PropertyInfo property in properties)
                {
                    if (property.PropertyType.FullName.Contains("DateTime"))
                    {
                        if (property.GetValue(paramCreate) != null && (property.GetValue(paramCreate).ToString() == "01/01/0001 0:00:00" || property.GetValue(paramCreate).ToString() == "01/01/1753 0:00:00"))
                        {
                            property.SetValue(paramCreate, null);
                        }

                        if (property.GetValue(paramCreate) != null && property.GetValue(paramCreate).ToString() != "01/01/0001 0:00:00")
                        {
                            DateTime datetimeUTCzero = Convert.ToDateTime(property.GetValue(paramCreate)).AddHours(-7);
                            property.SetValue(paramCreate, datetimeUTCzero);
                        }
                    }
                }

                CRM_appointment createRow = paramCreate.ConvertObject<CRM_appointment>();
                Guid newId = Guid.NewGuid();
                createRow.activityid = newId;
                createRow.DealerCode = DealerCode;
                createRow.SourceType = "NON DMS"; createRow.createdby = (createRow.createdby == null || createRow.createdby.ToString() == "00000000-0000-0000-0000-000000000000") ? createRow.modifiedby : createRow.createdby;
                createRow.RowStatus = 0; createRow.statecode = 0;

                //Add Validation Data Input
                ValidationParameterDto paramCheck = new ValidationParameterDto();
                paramCheck.dealerCode = DealerCode;
                paramCheck.xts_businessunitid = paramCreate.xts_businessunitid;
                paramCheck.xto_salespersonid = paramCreate.xto_salespersonid;
                paramCheck.ownerid = paramCreate.ownerid;
                #region PickList
                List<ParamPick> param = new List<ParamPick>();
                param.Add(new ParamPick { Category = "appointment.xts_appointmenttype", ValueId = paramCreate.xts_appointmenttype });
                paramCheck.pickList = param;
                #endregion


                if (!ValidationHelper.ValidateDataInput(paramCheck, validationResults))
                {
                    ValidationDapper dapper = new ValidationDapper();
                    List<MessageBase> errMsg = dapper.messageList(validationResults);
                    result.messages = errMsg;
                }
                else
                {
                    var nResult = _CRM_appointmentRepo.Create(createRow);
                    if (nResult.Success == true)
                    {
                        result.success = true;
                        result._idGuid = newId;
                        result.total = 1;
                    }
                    else
                    {
                        ErrorMsgHelper.ErrorMsgDBSave(result.messages);
                    }
                }

                #region old code Check Duplicate Data
                //}
                //else
                //{
                //    ErrorMsgHelper.Exception(result.messages, String.Concat("Data already exist | " + data[0].activityid.ToString()));
                //}
                #endregion

            }
            catch (SqlException ex)
            {
                ErrorMsgHelper.SqlException(result.messages, ex.Message);
            }
            catch (Exception ex)
            {
                ErrorMsgHelper.Exception(result.messages, ex.Message);
            }

            return result;
        }



        public ResponseBase<List<CRM_appointmentDto>> BulkCreate(List<CRM_appointmentCreateParameterDto> lstObjCreate)
        {
            var result = new ResponseBase<List<CRM_appointmentDto>>();
            var listOfExistingData = new List<CRM_appointmentDto>();
            var validationResults = new List<DNetValidationResult>();

            try
            {

                if (lstObjCreate.Count > 0)
                {

                    #region old code Check Duplicate Data
                    //if (ValidateDuplicateParamData(lstObjCreate, validationResults) == true)
                    //{
                    //    // validate any duplicate data in database
                    //    ValidateDuplicateDataInDB(lstObjCreate, validationResults, ref listOfExistingData);
                    //}
                    #endregion
                }

                // if any error found
                if (validationResults.Any())
                {
                    return PopulateValidationError<List<CRM_appointmentDto>>(validationResults.Distinct().ToList(), null);
                }
                else
                {
                    // insert into db
                    var CRM_appointmentList = lstObjCreate.ConvertList<CRM_appointmentCreateParameterDto, CRM_appointment>();
                    foreach (var item in CRM_appointmentList.Select((value, index) => new { value, index }))
                    {
                        PropertyInfo[] properties = typeof(CRM_appointment).GetProperties();
                        foreach (PropertyInfo property in properties)
                        {
                            if (property.PropertyType.FullName.Contains("DateTime"))
                            {
                                if (property.GetValue(item.value) != null && (property.GetValue(item.value).ToString() == "01/01/0001 0:00:00" || property.GetValue(item.value).ToString() == "01/01/1753 0:00:00"))
                                {
                                    property.SetValue(item.value, null);
                                }

                                if (property.GetValue(item.value) != null && property.GetValue(item.value).ToString() != "01/01/0001 0:00:00")
                                {
                                    DateTime datetimeUTCzero = Convert.ToDateTime(property.GetValue(item.value)).AddHours(-7);
                                    property.SetValue(item.value, datetimeUTCzero);
                                }
                            }
                        }

                        Guid newId = Guid.NewGuid();
                        item.value.activityid = newId;
                        item.value.DealerCode = DealerCode;
                        item.value.SourceType = "NON DMS"; item.value.createdby = (item.value.createdby == null || item.value.createdby.ToString() == "00000000-0000-0000-0000-000000000000") ? item.value.modifiedby : item.value.createdby;
                        item.value.RowStatus = 0; 
                        item.value.statecode = item.value.statecode == null ? 0 : item.value.statecode;

                        //Add Validation Data Input
                        ValidationParameterDto paramCheck = new ValidationParameterDto();
                        paramCheck.dealerCode = DealerCode;
                        paramCheck.xts_businessunitid = item.value.xts_businessunitid;
                        paramCheck.xto_salespersonid = item.value.xto_salespersonid;
                        paramCheck.ownerid = item.value.ownerid;
                        #region PickList
                        List<ParamPick> param = new List<ParamPick>();
                        param.Add(new ParamPick { Category = "appointment.xts_appointmenttype", ValueId = Convert.ToInt32(item.value.xts_appointmenttype) });
                        paramCheck.pickList = param;
                        #endregion

                        if (ValidationHelper.ValidateDataInput(paramCheck, validationResults, item.index, true))
                        {
                            //_CRM_appointmentRepo.SetCreatedLog(item.value);
                        }
                    }

                    if (validationResults.Any())
                    {
                        return PopulateValidationError<List<CRM_appointmentDto>>(validationResults.Distinct().ToList(), null);
                    }
                    else
                    {
                        var isSuccess = _CRM_appointmentRepo.BulkInsert(CRM_appointmentList);
                        result.success = isSuccess;
                        if (result.success)
                            result.total = CRM_appointmentList.Count;
                        result.lst = CRM_appointmentList.ConvertList<CRM_appointment, CRM_appointmentDto>();
                    }
                }
            }
            catch (SqlException ex)
            {
                ErrorMsgHelper.SqlException(result.messages, ex.Message);
            }
            catch (Exception ex)
            {
                ErrorMsgHelper.Exception(result.messages, ex.Message);
            }

            return result;
        }


        /// <summary>
        /// Update CRM_appointment
        /// </summary>
        /// <param name="objUpdate"></param>
        /// <returns></returns>
        public ResponseBase<CRM_appointmentDto> Update(CRM_appointmentParameterDto paramUpdate)
        {
            return null;
        }


        public ResponseBaseCustom<CRM_appointmentDto> Update(CRM_appointmentUpdateParameterDto paramUpdate)
        {
            var result = new ResponseBaseCustom<CRM_appointmentDto>();
            var sortColl = string.Empty;
            int totalRow = 0;
            int filteredTotalRow = 0;
            string rawSql = string.Empty;
            var innerQueryCriteria = string.Empty;
            var page = 1;
            var size = 20;
            var validationResults = new List<DNetValidationResult>();

            try
            {
                var criterias = "";
                criterias = Helper.UpdateStrCriteria(typeof(CRM_appointment), new MatchTypeFilter { SqlOperation = SQLOperation.And }, MatchType.Exact.GetHashCode(), "DealerCode", DealerCode, false, criterias);
                criterias = Helper.UpdateStrCriteria(typeof(CRM_appointment), new MatchTypeFilter { SqlOperation = SQLOperation.And }, MatchType.Exact.GetHashCode(), "SourceType", "NON DMS", false, criterias);
                criterias = Helper.UpdateStrCriteria(typeof(CRM_appointment), new MatchTypeFilter { SqlOperation = SQLOperation.And }, MatchType.Exact.GetHashCode(), "RowStatus", "0", false, criterias);
                criterias = Helper.UpdateStrCriteria(typeof(CRM_appointment), new MatchTypeFilter { SqlOperation = SQLOperation.And }, MatchType.Exact.GetHashCode(), "activityid", paramUpdate.activityid.ToString(), false, criterias);
                List<CRM_appointment> data = _CRM_appointmentRepo.Search(
                                    criterias, innerQueryCriteria, sortColl, page, size, out filteredTotalRow, out totalRow);

                if (data != null && data.Count > 0)
                {
                    PropertyInfo[] properties = typeof(CRM_appointmentUpdateParameterDto).GetProperties();
                    foreach (PropertyInfo property in properties)
                    {
                        if (property.PropertyType.FullName.Contains("DateTime"))
                        {
                            if (property.GetValue(paramUpdate) != null && (property.GetValue(paramUpdate).ToString() == "01/01/0001 0:00:00" || property.GetValue(paramUpdate).ToString() == "01/01/1753 0:00:00"))
                            {
                                property.SetValue(paramUpdate, null);
                            }

                            if (property.GetValue(paramUpdate) != null && property.GetValue(paramUpdate).ToString() != "01/01/0001 0:00:00")
                            {
                                DateTime datetimeUTCzero = Convert.ToDateTime(property.GetValue(paramUpdate)).AddHours(-7);
                                property.SetValue(paramUpdate, datetimeUTCzero);
                            }
                        }
                    }

                    //Add Validation Data Input
                    ValidationParameterDto paramCheck = new ValidationParameterDto();
                    paramCheck.dealerCode = DealerCode;
                    paramCheck.xts_businessunitid = paramUpdate.xts_businessunitid;
                    paramCheck.xto_salespersonid = paramUpdate.xto_salespersonid;
                    paramCheck.ownerid = paramUpdate.ownerid;
                    #region PickList
                    List<ParamPick> param = new List<ParamPick>();
                    param.Add(new ParamPick { Category = "appointment.xts_appointmenttype", ValueId = paramUpdate.xts_appointmenttype });
                    paramCheck.pickList = param;
                    #endregion

                    if (!ValidationHelper.ValidateDataInput(paramCheck, validationResults))
                    {
                        ValidationDapper dapper = new ValidationDapper();
                        List<MessageBase> errMsg = dapper.messageList(validationResults);
                        result.messages = errMsg;
                    }
                    else
                    {
                        CRM_appointment updateRow = paramUpdate.ConvertObject<CRM_appointment>();
                        updateRow.DealerCode = DealerCode;
                        updateRow.SourceType = "NON DMS";
                        updateRow.RowStatus = updateRow.RowStatus == null? 0 : updateRow.RowStatus;

                        var nResult = _CRM_appointmentRepo.Update(updateRow);
                        if (nResult.Success == true)
                        {
                            result.success = true;
                            result._idGuid = nResult.Data.ConvertObject<CRM_appointment>().activityid;
                            result.total = 1;
                        }
                        else
                        {
                            ErrorMsgHelper.ErrorMsgDBSave(result.messages);
                        }
                    }
                }
                else
                {
                    ErrorMsgHelper.UpdateNotAvailable(result.messages);
                }
            }
            catch (SqlException ex)
            {
                ErrorMsgHelper.SqlException(result.messages, ex.Message);
            }
            catch (Exception ex)
            {
                ErrorMsgHelper.Exception(result.messages, ex.Message);
            }

            return result;
        }


        /// <summary>
        /// Delete CRM_appointment by its id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ResponseBase<CRM_appointmentDto> Delete(int ID)
        {
            return null;
        }


        public ResponseBaseCustom<CRM_appointmentDto> Delete(CRM_appointmentDeleteParameterDto paramDelete)
        {
            var result = new ResponseBaseCustom<CRM_appointmentDto>();
            var sortColl = string.Empty;
            int totalRow = 0;
            int filteredTotalRow = 0;
            string rawSql = string.Empty;
            var innerQueryCriteria = string.Empty;
            var page = 1;
            var size = 20;
            try
            {
                var criterias = "";
                criterias = Helper.UpdateStrCriteria(typeof(CRM_appointment), new MatchTypeFilter { SqlOperation = SQLOperation.And }, MatchType.Exact.GetHashCode(), "DealerCode", DealerCode, false, criterias);
                criterias = Helper.UpdateStrCriteria(typeof(CRM_appointment), new MatchTypeFilter { SqlOperation = SQLOperation.And }, MatchType.Exact.GetHashCode(), "SourceType", "NON DMS", false, criterias);
                criterias = Helper.UpdateStrCriteria(typeof(CRM_appointment), new MatchTypeFilter { SqlOperation = SQLOperation.And }, MatchType.Exact.GetHashCode(), "RowStatus", "0", false, criterias);
                criterias = Helper.UpdateStrCriteria(typeof(CRM_appointment), new MatchTypeFilter { SqlOperation = SQLOperation.And }, MatchType.Exact.GetHashCode(), "activityid", paramDelete.activityid.ToString(), false, criterias);

                List<CRM_appointment> data = _CRM_appointmentRepo.Search(
                                    criterias, innerQueryCriteria, sortColl, page, size, out filteredTotalRow, out totalRow);
                if (data != null && data.Count > 0)
                {
                    CRM_appointment deleteRow = data[0];
                    deleteRow.RowStatus = -1; deleteRow.modifiedby = paramDelete.modifiedby; deleteRow.modifiedon = Convert.ToDateTime(paramDelete.modifiedon).AddHours(-7);
                    var nResult = _CRM_appointmentRepo.Update(deleteRow);
                    if (nResult.Success == true)
                    {
                        result.success = true;
                        result._idGuid = nResult.Data.ConvertObject<CRM_appointment>().activityid;
                        result.total = 1;
                    }
                    else
                    {
                        ErrorMsgHelper.ErrorMsgDBSave(result.messages);
                    }
                }
                else
                {
                    ErrorMsgHelper.DeleteNotAvailable(result.messages);
                }
            }
            catch (SqlException ex)
            {
                ErrorMsgHelper.SqlException(result.messages, ex.Message);
            }
            catch (Exception ex)
            {
                ErrorMsgHelper.Exception(result.messages, ex.Message);
            }

            return result;
        }

        #endregion


        #region Private Methods
        private bool ValidateDuplicateParamData(List<CRM_appointmentCreateParameterDto> lstObjCreate, List<DNetValidationResult> validationResults)
        {
            foreach (var item in lstObjCreate)
            {
                var lst = lstObjCreate.Where(x => x.xts_appointmenttype.ToString().Trim() == item.xts_appointmenttype.ToString().Trim() &&
                                                x.xts_businessunitid.ToString().Trim() == item.xts_businessunitid.ToString().Trim());
                if (lst.Count() > 1)
                {
                    String errorMessage = string.Format(string.Format(MessageResource.ErrorMsgDuplicateData) + string.Format(" ({0},{1})", "xts_appointmenttype = " + item.xts_appointmenttype.ToString(), "xts_businessunitid = " + item.xts_businessunitid.ToString()));
                    bool isErrorExist = validationResults.Any(q => q.ErrorMessage == errorMessage);
                    if (isErrorExist == false)
                    {
                        validationResults.Add(new DNetValidationResult(errorMessage));
                    }
                }
            }
            return validationResults.Count == 0;
        }

        private bool ValidateDuplicateDataInDB(List<CRM_appointmentCreateParameterDto> CRM_appointmentList, List<DNetValidationResult> validationResults, ref List<CRM_appointmentDto> listOfExistingData)
        {
            listOfExistingData = new List<CRM_appointmentDto>();

            foreach (CRM_appointmentCreateParameterDto item in CRM_appointmentList)
            {
                //check duplicate
                List<CRM_appointment> duplicateinDBlist = GetExistingCRM_appointment(item);
                if (duplicateinDBlist != null)
                {
                    CRM_appointment duplicateinDB = duplicateinDBlist.FirstOrDefault();
                    String errorMessage = string.Format(string.Format(MessageResource.ErrorMsgDataDBExist) + string.Format(" ({0},{1},{2})", "xts_appointmenttype = " + item.xts_appointmenttype.ToString(), "xts_businessunitid = " + item.xts_businessunitid.ToString(), "statecode=0" + " | " + duplicateinDB.activityid.ToString()));
                    bool isErrorExist = validationResults.Any(q => q.ErrorMessage == errorMessage);
                    if (isErrorExist == false)
                    {
                        validationResults.Add(new DNetValidationResult(errorMessage));
                    }
                }
            }

            return validationResults.Count == 0;
        }

        private List<CRM_appointment> GetExistingCRM_appointment(CRM_appointmentCreateParameterDto param)
        {
            try
            {
                String criterias = "";
                var sortColl = string.Empty;
                int totalRow = 0;
                int filteredTotalRow = 0;
                string rawSql = string.Empty;
                var innerQueryCriteria = string.Empty;
                var page = 1;
                var size = 20;
                criterias = Helper.UpdateStrCriteria(typeof(CRM_appointment), new MatchTypeFilter { SqlOperation = SQLOperation.And }, MatchType.Exact.GetHashCode(), "DealerCode", DealerCode, false, criterias);
                criterias = Helper.UpdateStrCriteria(typeof(CRM_appointment), new MatchTypeFilter { SqlOperation = SQLOperation.And }, MatchType.Exact.GetHashCode(), "SourceType", "NON DMS", false, criterias);
                criterias = Helper.UpdateStrCriteria(typeof(CRM_appointment), new MatchTypeFilter { SqlOperation = SQLOperation.And }, MatchType.Exact.GetHashCode(), "RowStatus", "0", false, criterias);
                criterias = Helper.UpdateStrCriteria(typeof(CRM_appointment), new MatchTypeFilter { SqlOperation = SQLOperation.And }, MatchType.Exact.GetHashCode(), "xts_appointmenttype", param.xts_appointmenttype.ToString(), false, criterias);
                criterias = Helper.UpdateStrCriteria(typeof(CRM_appointment), new MatchTypeFilter { SqlOperation = SQLOperation.And }, MatchType.Exact.GetHashCode(), "xts_businessunitid", param.xts_businessunitid.ToString(), false, criterias);
                criterias = Helper.UpdateStrCriteria(typeof(CRM_appointment), new MatchTypeFilter { SqlOperation = SQLOperation.And }, MatchType.Exact.GetHashCode(), "statecode", "0", false, criterias);

                List<CRM_appointment> data = _CRM_appointmentRepo.Search(
                                    criterias, innerQueryCriteria, sortColl, page, size, out filteredTotalRow, out totalRow);

                if (data.Count > 0)
                {
                    return data.Cast<CRM_appointment>().ToList();
                }

                return null;
            }
            catch (Exception e)
            {
                return null;
            }
        }

        #endregion


    }
}
