#region Summary
/*
 ===========================================================================
 AUTHOR        : BSI Code Generator Interface 
 PURPOSE       : APIReadIPAddressRestrictionExample class
 GENERATED BY  : Admin
 ---------------------
 Copyright  (c) 2020 
 ---------------------
 $History      : $
 Created on 11 Okt 2021
 ===========================================================================
*/
#endregion

using Swashbuckle.Examples;
using System;

namespace KTB.DNet.Interface.WebApi.Models
{
    public class APIReadIPAddressRestrictionExample : IExamplesProvider
    {
        public object GetExamples()
        {
            var obj = new
            {
                IP_Address = "129.250.114.17",
                UserName = "admin@mmksi.co.id"
            };

            return obj;
        }
    }
}